### ISSUE TITLE
Failure to set Git username in Git Bash

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#1]
I followed the instruction on the course website, but failed to set a Git username. According to https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git, there should be a confirmation. However, the username for me seems to remain the same.

```
MY_INITIAL_USERNAME@LAPTOP-8ES9LBQ3 MINGW64 ~
$ git config --global user.name MY_ACTUAL_NAME

MY_INITIAL_USERNAME@LAPTOP-8ES9LBQ3 MINGW64 ~
```

**Comment by KamJiaYue** [comment]
have u tried putting quotation symbols("<YOUR_NAME>") to your MY_ACTUAL_NAME ?

**Comment by ChangruHenryQian** [comment]
> have u tried putting quotation symbols("<YOUR_NAME>") to your MY_ACTUAL_NAME ?

It still doesn't work.

**Comment by damithc** [comment]
@ChangruHenryQian How did you verify that the `user.name` did not change?

**Comment by ChangruHenryQian** [comment]
> @ChangruHenryQian How did you verify that the `user.name` did not change?

Because according to https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git, there should be a confirmation like `> Mona Lisa`, but Git Bash doesn't return anything when I try to set the Git username.

**Comment by ChangruHenryQian** [comment]
Sorry for accidentally closing the post.

**Comment by damithc** [comment]
```
MY_INITIAL_USERNAME@LAPTOP-8ES9LBQ3 MINGW64 ~
$ git config --global user.name MY_ACTUAL_NAME

MY_INITIAL_USERNAME@LAPTOP-8ES9LBQ3 MINGW64 ~
```
@ChangruHenryQian is this your full interaction in GitBash?

If yes, I think you missed the fact that step 2 and 3 in [https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-gi](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git) are not the same command.

**Comment by ChangruHenryQian** [comment]
> ```
> MY_INITIAL_USERNAME@LAPTOP-8ES9LBQ3 MINGW64 ~
> $ git config --global user.name MY_ACTUAL_NAME
> 
> MY_INITIAL_USERNAME@LAPTOP-8ES9LBQ3 MINGW64 ~
> ```
> 
> @ChangruHenryQian is this your full interaction in GitBash?
> 
> If yes, I think you missed the fact that step 2 and 3 in [https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-gi](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git) are not the same command.

Thank you for helping Professor. May I confirm if this setting Git username process is a one time step or we have to do it every time?

**Comment by damithc** [comment]
> Thank you for helping Professor. May I confirm if this setting Git username process is a one time step or we have to do it every time?

@ChangruHenryQian One time only, for each computer you use for coding course projects.
