### ISSUE TITLE
Is this hierarchy good practise?  

### ISSUE THREAD

**Issue by MagnificentCreature** [nus-cs2103-AY2324S1/forum#10]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/61371541/2af91453-00a3-4ccf-abe3-a710eeb635bf)

Because now, if I try and run Duke.java directly, it will say "package Tasks does not exist", which makes sense. They are not in the same folder, instead I have to compile and run.

**Comment by woojiahao** [comment]
Usually you would create packages under `src/main/java` instead, not as separate packages under `src`. Inspired by the Maven repository structure which I believe Gradle follows as well: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

Both Maven and Gradle are package management tools for Java, similar to `npm` in Javascript or Cargo in Rust

**Comment by MagnificentCreature** [comment]
Great answer! It aligns with what I saw here too 
https://youtu.be/DoK3-9V5HRE?feature=shared
Leaving this youtube link for anyone who comes by and is curious
With that I will close this question
