### ISSUE TITLE
How to configure IDE IntelliJ to follow Coding Standard for things like indent on Case: and others

### ISSUE THREAD

**Issue by eyelessrhyme7** [nus-cs2103-AY2324S1/forum#100]
I am using IntelliJ Windows10 Java 11. 

How to use configurations and edit them. I can't seem to even hardcodedly follow the Java Coding Standard, when I try to delete 4 spaces to paste my case: arguments within a switch block, it automatically skips to the switch {.

<img width="721" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/59199841/b7ff7f5b-d2c6-47e6-bbd9-96ddb08944a1">
AFTER CLICKING BACKSPACE, the cursor automatically skips to the curly brace.
<img width="452" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/59199841/20893dc6-48c4-42a8-b76e-ad55e63c3a1e">

**Comment by joeng03** [comment]
Open the settings in Intellij (Ctrl+alt+S if you are using Windows), go to Editor>CodeStyle>Java>Wrapping and Braces, at 'switch' statement, untick the box 'Indent case branches'

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/51855281/28da52d2-864d-461a-abb7-1ba0f023b066)

**Comment by joeng03** [comment]
[Open settings in Intellij](https://www.jetbrains.com/help/idea/configure-project-settings.html), go to Editor>CodeStyle>Java>Wrapping and Braces, at 'switch' statement, untick the box 'Indent case branches'

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/51855281/28da52d2-864d-461a-abb7-1ba0f023b066)

To reformat a section of code in Intellij, [refer to](https://www.jetbrains.com/idea/guide/tips/reformat-file/#:~:text=Sometimes%20code%20formatting%20can%20get,L%20(Windows%2FLinux))

**Comment by damithc** [comment]
Also see https://se-education.org/guides/tutorials/intellijCodeStyle.html
