### ISSUE TITLE
Inquiry on coding standards for mutable constants and variable aggregators

### ISSUE THREAD

**Issue by ruiyangzh** [nus-cs2103-AY2324S1/forum#102]
Hi, just a quick question on these two types of variables and how we should declare them in naming. I'm aware that coding standards are just a standard, and they can be changed, just wondering which of the two options we should adhere to or if both are OK.

1. for e.g. a storage class linked to a bot, that is intended to be paired permanently with the bot:
```java
private final Storage ______ = new Storage();
```
what should we put in the space? uppercase STORAGE_FILE (Since it's declared as final) or camelcase storageFile (Since it's mutable)?

2. next, for a variable aggregator such as an arraylist holding multiple objects:
```java
private ArrayList<Task> ______ = new ArrayList<>();
```
I'm aware that the convention recommends a name like listOfTasks; but what if we refer to the arraylist as a single object, like taskHolder or taskList? is that acceptable within the standard of this course?

thanks for the clarification!

**Comment by woojiahao** [comment]
My name for first is `STORAGE` but `FILE_STORAGE` works too.

For the second, I named it as `tasks`, the type of the variable is self-explanatory so I believe it's not needed to include `listOfX`

**Comment by damithc** [comment]
@ruiyangzh Good points for discussion. Let's see what others think.

**Comment by rocketninja7** [comment]
For the first, the coding standard states:
```
Constant names must be all uppercase using underscore to separate words.
```
I believe that constant means it has to be a static variable. Otherwise, for every instance of the class, I can have a different value of that variable. Hence, we use camelCase in this case.
For the second, it states:
```
Plural form should be used on names representing a collection of objects.
```
Hence, I think we should use ```tasks``` as the name instead. However, if there is a case where ```taskList``` is needed for some reason, we notice the following below the standard:
```
Rationale: Enhances readability since the name gives the user an immediate clue of the type of the variable and the operations that can be performed on its elements. One space character after the variable type is enough to obtain clarity.
```
Hence, I think it is okay to leave it in singular form as it hints to people that it is only one list.

**Comment by ruiyangzh** [comment]
Hi guys, update: I found a google style guide [here](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) that states mutable static final objects should **NOT** be written in uppercase, since they don't adhere to what a constant is. Should we adhere to this standard?

**Comment by damithc** [comment]
> Hi guys, update: I found a google style guide [here](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) that states mutable static final objects should **NOT** be written in uppercase, since they don't adhere to what a constant is. Should we adhere to this standard?

@ruiyangzh good find. Yes, as per the below:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/2446a689-cba1-4bde-a585-6049ad6e0f67)

**Comment by damithc** [comment]
> I'm aware that the convention recommends a name like listOfTasks; but what if we refer to the arraylist as a single object, like taskHolder or taskList?

@ruiyangzh `taskList` (or `tasksList`) is acceptable. But `listOfTasks` adheres to both the spirit and the letter of the rule. As some mentioned, `tasks` works well too, if there is no need to mention the type of collection being used.

**Comment by ruiyangzh** [comment]
Ok thanks everyone for the input, will keep all this in mind!
