### ISSUE TITLE
iP tags in github but iP Dashboard not recognising them

### ISSUE THREAD

**Issue by sushiyade** [nus-cs2103-AY2324S1/forum#104]
In Github,
<img width="1296" alt="スクリーンショット 2023-09-05 午後3 26 58" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/68842066/8cfbb588-63fb-4c70-b9be-aeb482c6753a">

In iP dashboard,
![スクリーンショット 2023-09-05 午後3 27 55](https://github.com/nus-cs2103-AY2324S1/forum/assets/68842066/2cdf3716-6dc4-43b8-8c8a-cce70df8d382)

I'm not sure what to do next, please advise, much appreciated!

**Comment by larrywang0701** [comment]
Try "Level-x" with uppercase "L" instead of lowercase in your tag name? (I'm not sure whether the dashboard system is case sensitive or not)  (update: I see your level-8 can be detacted from your screenshot, so this may not be the main reason for your problem)
Also, go to check that whether you really **created the branch** for level 8, javadoc, coding standard and level 9 and then merge and then tag the merged comment in master branch as required?

**Comment by AlagappanRa** [comment]
On top of what @larrywang0701 has said, the iP dashboard is updated daily. So you might need to come back tommorow to see if the script has detected your tag. 

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/cbc975be-e9f1-4e4b-a539-f3a8e3a6535a)

**Comment by larrywang0701** [comment]
No from his screenshot he tagged his commit 5 days ago already @AlagappanRa 
As his branches are also not detacted, I guess he may failed to follow the branch requirements in iP, thus causing the problem (just guessing)

**Comment by AlagappanRa** [comment]
oh right ok that could not be the problem, thanks for pointing that out. The issue is likely due to the naming and also not tagging the branch to the correct commit

**Comment by sushiyade** [comment]
> Try "Level-x" with uppercase "L" instead of lowercase in your tag name? (I'm not sure whether the dashboard system is case sensitive or not) Also, go to check that whether you really **created the branch** for level 8, javadoc, coding standard and level 9 and then merge and then tag the merged comment in master branch as required?

I 
<img width="144" alt="スクリーンショット 2023-09-05 午後4 51 30" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/68842066/eeef4686-7d3b-4140-92cd-e586350ea42a">


![Uploading スクリーンショット 2023-09-05 午後4.53.50.png…]()

**Comment by sushiyade** [comment]
> Try "Level-x" with uppercase "L" instead of lowercase in your tag name? (I'm not sure whether the dashboard system is case sensitive or not) Also, go to check that whether you really **created the branch** for level 8, javadoc, coding standard and level 9 and then merge and then tag the merged comment in master branch as required?


These were my previous tag names (all lowercase) and they were recognised by the dashboard so I don't think the issue lies there.
<img width="144" alt="スクリーンショット 2023-09-05 午後4 51 30" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/68842066/d2bf471a-34de-4016-bd6f-514057b495b7">


Sorry I am not sure about how to tag a merge commit but this is what my branches look like right now.
<img width="947" alt="スクリーンショット 2023-09-05 午後4 53 50" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/68842066/c8676240-287d-493c-87ff-262ed3894241">

**Comment by AlagappanRa** [comment]
If you are still facing issues, you can use these following commands. 

1. Open up your terminal and navigate to your iP folder
2. Type command `git log` to list all the recent commits

For example, mine looks like this:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/c80d85d6-a39a-47cb-a104-7a180a7fba6e)

^My tag above is listed with the merge commit, so I know the merge commit has been tagged correctly. 

From your screenshot, it seems to me that your tag is not attached to the merge commit, which might be what is causing the issue.

1. Run `git log` and make sure all your commits are synced with your local repositiory
2. Delete the old tag from your local repository using `git tag -d <tag-name>`
3. Create the tag on the new commit using `git tag <tag-name> <hash-of-the-merge-commit>`
4. Delete the old tag from the remote repositiory `git push origin --delete <tag-name>`
5. Push the new tag to the remote repository `git push origin <tag-name>`

This method has worked for me before, and it should for you as well 😊

**Comment by larrywang0701** [comment]
I can not see your branch names from your screenshot, so it's hard for me to give you more helpful information. But instead of just correcting your correct commits, why not try deleting all of your current tags that can not be correctly detacted, **then follow the iP requirements last week starting from A-Packages again all over again?**
Since from my experience, Github commits is really easy to messed up if you are not sure what you are doing (**you may make more mistakes and make your repo more messy during fixing**), so just redo everything may be better than try to fix the current wrong one.

**Comment by damithc** [comment]
> No from his screenshot he tagged his commit 5 days ago already

This is based on the time the tag/commit was created, not the time it was pushed to the fork.

**Comment by larrywang0701** [comment]
@damithc Yes I know this, professor, so what I mean is this his problem is not caused by the daily update basis of the dashboard system as the other classmate mentioned, as his tag already exists 5 days ago.

**Comment by damithc** [comment]
> @damithc Yes I know this, professor, so what I mean is this his problem is not caused by the daily update basis of the dashboard system, as his tag already exists 5 days ago.

@larrywang0701 Actually, it can be. The dashboard cannot detect things that are not in the fork. So, if the tag was created 5 days ago but was pushed to the fork _after_ the most recent dashboard, it will not be reflected in the dashborad.

@sushiyade The above appears to be the problem. The last time the dashboard checked your fork, those red tags were not in the fork. But now that they are in the fork, they should turn green at the next dashboard update.

**Comment by larrywang0701** [comment]
@damithc Thanks for correcting me on this. I don't know how CS2103T's dashboard detactor actually works, so my above answers may be not correct. Sorry about any inconvenience my answer caused.

**Comment by damithc** [comment]
> @damithc Thanks for correcting me on this. I don't know how CS2103T's dashboard detactor actually works, so my above answers may be not correct. Sorry about any inconvenience my answer caused.

No worries @larrywang0701 Our scripts check your forks periodically, and update the dashboard accordingly.

**Comment by sushiyade** [comment]
> > @damithc Yes I know this, professor, so what I mean is this his problem is not caused by the daily update basis of the dashboard system, as his tag already exists 5 days ago.
> 
> @larrywang0701 Actually, it can be. The dashboard cannot detect things that are not in the fork. So, if the tag was created 5 days ago but was pushed to the fork _after_ the most recent dashboard, it will not be reflected in the dashborad.
> 
> @sushiyade The above appears to be the problem. The last time the dashboard checked your fork, those red tags were not in the fork. But now that they are in the fork, they should turn green at the next dashboard update.


Alright, I may or may not have pushed the tags onto the fork 5 days ago, I have just pushed the tags today and I'll check in again tomorrow morning to see if the issue persists.

Thank you all for your help, if everything goes well by the time the detector checks for my tags, I will close the issue. 

Thanks all once again!

**Comment by larrywang0701** [comment]
But still weird, though your tags may not be pushed, why your branches on the right is also red?
Did you also forget to push your branches to the remote repo?
I push everytime I make a commit or tag a commit so I never encounter a problem like yours.
Tomorrow if the dashboard is updated but your detaction is still red, then you may need to come back again.

**Comment by nixonwidjaja** [comment]
@damithc do we need to tag anything for GFMD? Dashboard also doesn't recognize my updated MD file.

**Comment by damithc** [comment]
> @damithc do we need to tag anything for GFMD? Dashboard also doesn't recognize my updated MD file.

@nixonwidjaja No. But there is no MD file involved. So, perhaps you missed something when doing the task?

**Comment by sushiyade** [comment]
Thanks all everything is fine now!
