### ISSUE TITLE
Naming requirements for iP and tP tasks

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#105]
The code below was given for the task in week 2 where we have to extract out the classes `Storage`, `TaskList` and `Ui`. 

```java
public class Duke {
    private Storage storage;
    private TaskList tasks;
    private Ui ui;

    public Duke(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.load());
        } catch (DukeException e) {
            ui.showLoadingError();
            tasks = new TaskList();
        }
    }

    public void run() {
        //...
    }

    public static void main(String[] args) {
        new Duke("data/tasks.txt").run();
    }
}
```

Could I ask if exact naming standard are imposed? (in other words, if my `TaskList` class is called `CustomList`, will it still be accepted? Or do I have to rename it due to possible automated script checks?)

**Comment by zhanyang01** [comment]
I think so long as coding standards are hit it is fine, CustomList is also is pascalcase which is fine.

**Comment by damithc** [comment]
@AlagappanRa It's fine to use other suitable names.
