### ISSUE TITLE
Question about Checkstyle

### ISSUE THREAD

**Issue by wj331** [nus-cs2103-AY2324S1/forum#109]
Hi all,

I currently have a field that is 
`private final String SYMBOL = "[T]";` which helps me in representing the symbol that represent the task

However, when I run checkstyle, it says
<img width="932" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122218312/55b80456-25a9-4e2c-b2eb-63303df269fa">

Anyone knows how I can suppress this warning?

**Comment by junhonglow** [comment]
Will need to declare the variable as static if it's meant to be a constant.

**Comment by wj331** [comment]
Alright thanks @junhonglow!
