### ISSUE TITLE
Did enums early

### ISSUE THREAD

**Issue by MagnificentCreature** [nus-cs2103-AY2324S1/forum#11]
My programmer habits made me do enums early on in level 3 before realising they were a requirement later on. The requirements said to "do things in order" does this mean I have to recode?

**Comment by MagnificentCreature** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/61371541/604c6a92-7835-49eb-ba8c-2c167cacfd16)

**Comment by damithc** [comment]
It's OK to miss the order occasionally @MagnificentCreature. Just tag the appropriate commit as `A-Enums`.

**Comment by MagnificentCreature** [comment]
I'm still around level 3, just happened to notice that adding Enums was a thing halfway.

Should I tag A-Enums once I finish level 6? (Just incase there may be more items later that require me to use more enums)

**Comment by damithc** [comment]
@MagnificentCreature either way is fine. Tags are used here as a self-reporting mechanism, to indicate progress (and a way for you to practice tagging). You can add/push the tag whenever you think you are done with the corresponding increment.

**Comment by MagnificentCreature** [comment]
Okay thank you!
