### ISSUE TITLE
Java folder not responding error on MacOS when running launcher

### ISSUE THREAD

**Issue by wjacobw** [nus-cs2103-AY2324S1/forum#110]
When I ran the launcher, a blue folder named java (Application not responding) appeared instead of the Hello World GUI.  There is not any error in the program as far as I know. I am using java 11.0.19.fx-zulu, which is recommended by the CS2103 website. This is the result of the program: 

```
09.17.40: Executing ':Launcher.main()'...
> Configure project :
Project : => no module-info.java found
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :Launcher.main()
```

**Comment by keaganpzh** [comment]
Hi can you push your code to the fork and share the link here so we can reproduce the problem? Thanks.

**Comment by wjacobw** [comment]
> Hi can you push your code to the fork and share the link here so we can reproduce the problem? Thanks.

Yes. This is the link: https://github.com/wjacobw/ip. Thank you!

**Comment by keaganpzh** [comment]
Your `build.gradle` settings should target your `Launcher` class instead of your regular `Duke` class. You can do this by changing the `application` field in `build.gradle` to this:

```java
application {
    mainClass.set("duke.Launcher")
}
``` 

Do also make sure there is only one `application` field in the file because I noticed you specified it twice.

**Comment by wjacobw** [comment]
> Your `build.gradle` settings should target your `Launcher` class instead of your regular `Duke` class. You can do this by changing the `application` field in `build.gradle` to this:
> 
> ```java
> application {
>     mainClass.set("duke.Launcher")
> }
> ```
> 
> Do also make sure there is only one `application` field in the file because I noticed you specified it twice.

Thank you for the advice. I have changed it according to your code. But when I ran the launcher, it still only showed the same blue folder.

**Comment by wjacobw** [comment]
Update: the GUI appeared only when I end the program, that is bye inputting the string "bye" to the program. Anyone knows why it is like that?

**Comment by damithc** [comment]
@wjacobw There are some Mac users posting their GUI is #101 You can compare your code to theirs, to find what you are doing differently.
I also assume you installed the exact JDK we have specified in this advisory for Mac users https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html#programming-language

**Comment by mingyuanc** [comment]
It could be because in your duke constructor your calling a method to wait for user response. Hence the programme is stuck waiting for user response and the javafx cant run its method. This is why when u use the bye command the gui appears. Just comment out the part of the constructor where you poll for user response

**Comment by SPWwj** [comment]
Hi @wjacobw, I'm from your senior batch. @mingyuanc has the correct answer to your issue. Here are some tips for debugging:

1. Always keep a working version to compare with the buggy code.
2. Understand the code and test functions minimally. For example, to show the GUI, comment out the code in the Duke constructor.

Quick question: why do we need to create a Duke object?

**Comment by melissaharijanto** [comment]
Hello @wjacobw, I'm from your senior batch :) just to give further elaboration to the previous two responses, the call to the `Answer()` static method in the `Duke` class is causing the issue (i.e. the `taskList.Answer()`). Try commenting that out and see if the issue still persists (tried it out on my computer and it works!).

**Comment by wjacobw** [comment]
> It could be because in your duke constructor your calling a method to wait for user response. Hence the programme is stuck waiting for user response and the javafx cant run its method. This is why when u use the bye command the gui appears. Just comment out the part of the constructor where you poll for user response

Oh, that appears to be right. I have tried it and it worked. Thank you for the help!

**Comment by wjacobw** [comment]
> Hi @wjacobw, I'm from your senior batch. @mingyuanc has the correct answer to your issue. Here are some tips for debugging:
> 
>     1. Always keep a working version to compare with the buggy code.
> 
>     2. Understand the code and test functions minimally. For example, to show the GUI, comment out the code in the Duke constructor.
> 
> 
> Quick question: why do we need to create a Duke object?

In my code, I created the Duke object so that the taskList.Answer() will be run. And that seems to be the root of the problem. Thank you for the helpful tips!

**Comment by wjacobw** [comment]
> Hello @wjacobw, I'm from your senior batch :) just to give further elaboration to the previous two responses, the call to the `Answer()` static method in the `Duke` class is causing the issue (i.e. the `taskList.Answer()`). Try commenting that out and see if the issue still persists (tried it out on my computer and it works!).

Hi Mellisa, yes, turned out the problem is with my code and not related to me using macOS or javaFTX related problem. Thanks for helping me find the bug! :)
