### ISSUE TITLE
Format of GUI

### ISSUE THREAD

**Issue by JCSnap** [nus-cs2103-AY2324S1/forum#114]
Hello prof and friends, When I see GUI I interpret it as a graphical interface in the sense that users can call the commands by interacting with the UI like how we would do with normal applications, which is why I created my program to be something like this (delete, add, mark, unmark, task type) are all selected through a user interface.

<img width="814" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/111076731/538c28df-bde6-486a-a35a-9e5a71b0fda1">

But after looking through the other people's screenshots, I realized GUI would retain the same functionalities (all the commands are accessed through the command line, in this case the user input field), just that we have a graphical representation of it in the form of a chatbot.

Will mine fulfill the requirement or do I need to redo it?

**Comment by damithc** [comment]
@JCSnap While this route is not typical for the iP, it's not disallowed either. So, no issue. 
Kudos for taking a less beaten path 💯
