### ISSUE TITLE
Facing this error when handling user inputs

### ISSUE THREAD

**Issue by lululwtv** [nus-cs2103-AY2324S1/forum#117]
<img width="526" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/85116693/f7ffe4b3-f138-4753-b8e1-2a888dbdcfb0">

Hi everyone, as shown in the screenshot above, I am getting this error whenever I key in inputs in my chatbot. It seems like the input goes through, because the input disappears from the dialogbox after hitting enter. However, there is no output in the pane, and this error pops up in the terminal instead. My application does not terminate.

Anyone else faced this issue and knows how to fix it?

I have pushed the code into the branch "branch-Level-10" here
https://github.com/lululwtv/ip.git

**Comment by damithc** [comment]
@lululwtv You can push the code to a branch in your fork and share the branch name here so that other can try to replicate the problem (or do a more thorough examination of the code).

**Comment by lululwtv** [comment]
> @lululwtv You can push the code to a branch in your fork and share the branch name here so that other can try to replicate the problem (or do a more thorough examination of the code).

Hi prof, I have pushed the code into a branch already and updated my post description

**Comment by lululwtv** [comment]
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/85116693/266205890-f7ffe4b3-f138-4753-b8e1-2a888dbdcfb0.png">
> Hi everyone, as shown in the screenshot above, I am getting this error whenever I key in inputs in my chatbot. It seems like the input goes through, because the input disappears from the dialogbox after hitting enter. However, there is no output in the pane, and this error pops up in the terminal instead. My application does not terminate.
> 
> Anyone else faced this issue and knows how to fix it?
> 
> I have pushed the code into the branch "branch-Level-10" here https://github.com/lululwtv/ip.git

I have solved it
