### ISSUE TITLE
JavaFX Runtime Components are missing.

### ISSUE THREAD

**Issue by wesho1107** [nus-cs2103-AY2324S1/forum#118]
Currently I have my IntelliJ set as such:
* SDK: 11
* Language level: SDK default (11)

I am running through the setup for GUI with JavaFX and at the Introduction part at the SE-EDU JavaFX tutorial.
I have included the said lines in my build.gradle, and it is now as such:
```java
dependencies {
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'

    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}
```

When trying to run with Gradle, this is the error that I have
![Screenshot 2023-09-07 at 4 30 36 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/99474795/8e2bd9dc-dff4-48b7-a3c5-fbcbc9150607)

![Screenshot 2023-09-07 at 5 06 58 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/99474795/3bf4f4a0-ba2c-4951-9b30-60853ce8f1f5)

This is when I am running using Gradle the following class:
```java
package duke.main;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class Main extends Application {
    @Override
    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }
}
```
```java
package duke.main;

import javafx.application.Application;

/**
 * A launcher class to workaround classpath issues.
 */
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
}

```

My main Duke.java still runs as per normal without any issue.

**Comment by damithc** [comment]
@wesho1107 I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

**Comment by keaganpzh** [comment]
In order to build using Gradle, the project is configured based on your system's version of Java, not the project's. You need to verify that your system is running the correct version of Java too. You can check your system's version of Java using this command:
```shell
java -version
``` 

You should see something like this:
```shell
openjdk version "11.0.20" 2023-07-18 LTS
OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
```

Check the build version of Java, make sure it includes support for JavaFX. You can refer to the course website for more info. https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html

**Comment by Bombbird2001** [comment]
Check that in your build.gradle you have

```groovy
application {
    mainClass.set("duke.main.Launcher")
}
```

I'm not entirely sure, but I'm guessing your mainClass is currently set to `duke.main.Main` or `duke.main.Duke` and some code is calling `new Main()` somewhere causing the error you're seeing.

**Comment by J-hta-n** [comment]
> In order to build using Gradle, the project is configured based on your system's version of Java, not the project's. You need to verify that your system is running the correct version of Java too. You can check your system's version of Java using this command:
> 
> ```shell
> java -version
> ```
> 
> You should see something like this:
> 
> ```shell
> openjdk version "11.0.20" 2023-07-18 LTS
> OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
> OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
> ```
> 
> Check the build version of Java, make sure it includes support for JavaFX. You can refer to the course website for more info. https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html

Yep, following what Keagan said with reference to the course website link he provided, perhaps you could try using the Azul jdk 11.0.20 version from [here](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#zulu) instead of the jdk 11.0.17 version (as configured in your IntelliJ project SDK). Hope this helps!

**Comment by nixonwidjaja** [comment]
To fix the red import statements, you need to use JDK from Zulu that has built in JavaFX, or install JavaFx and put them in the appropriate dependencies.

**Comment by LimJH2002** [comment]
> > In order to build using Gradle, the project is configured based on your system's version of Java, not the project's. You need to verify that your system is running the correct version of Java too. You can check your system's version of Java using this command:
> > ```shell
> > java -version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should see something like this:
> > ```shell
> > openjdk version "11.0.20" 2023-07-18 LTS
> > OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
> > OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Check the build version of Java, make sure it includes support for JavaFX. You can refer to the course website for more info. https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html
> 
> Yep, following what Keagan said with reference to the course website link he provided, perhaps you could try using the Azul jdk 11.0.20 version from [here](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#zulu) instead of the jdk 11.0.17 version (as configured in your IntelliJ project SDK). Hope this helps!

This helped me to solve this issue, changing the JDK to 11.0.20 works! Thanks.
