### ISSUE TITLE
Checkstyle off not working?

### ISSUE THREAD

**Issue by MagnificentCreature** [nus-cs2103-AY2324S1/forum#119]
I used //CHECKSTYLE:OFF LineLength but not only does it not work, the comment itself became a target of the checkstyle.
Has anyone encountered the same issue?
PS Sorry for breaking convention but I am using VSCode...

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/61371541/06cd38db-e231-4545-978d-bfd2ce7445b1)

PS I have also tried //CHECKSTYLE:OFF LineLengthRule

**Comment by MagnificentCreature** [comment]
I also tried // CHECKSTYLE:OFF LineLength (note the space between // and CHECKSTYLE...)

**Comment by damithc** [comment]
@MagnificentCreature Does the error also happen when you run Checkstyle using Gradle?

**Comment by MagnificentCreature** [comment]
Yes

**Comment by howenc** [comment]
Sry bois, I haven't used CHECKSTYLE:OFF befoee

**Comment by MagnificentCreature** [comment]
update: I refreshed the checkstyle extension checkstyle file path to checkstyle.xml again, and suddenly there is no red underline in the edittor. But the gradle still gives the checkstyle error, which makes me unable to build the app.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/61371541/d5f678f4-c2d3-447e-8c81-a8bfaa7a624d)
When I build this, I do not get a tailing whitespace style error in between 
```
     * CHECKSTYLE.OFF: Regexp
     *  
     * CHECKSTYLE.ON: Regexp
```
    
But I still get an error for the line length.

Also, when I change the length in the XML file to 180, it does fix the issue, but the checkstyle off is buggy nonetheless

**Comment by MagnificentCreature** [comment]
UPDATE:

Changing the tool version in the build.gradle to the latest 10.12.3 instead of the 10.2 in the guide fixed it.

```
checkstyle {
    toolVersion = '10.12.3'
}
```

**Comment by damithc** [comment]
> Changing the tool version in the build.gradle to the latest 10.12.3 instead of the 10.2 in the guide fixed it.

Good find. Thanks for sharing it @MagnificentCreature

**Comment by MagnificentCreature** [comment]
So the issue came back, but I fixed it by adding this under checker

  <module name="SuppressWithPlainTextCommentFilter">
    <property name="offCommentFormat" value="// CHECKSTYLE\.OFF\: ([\w\|]+)"/>
    <property name="onCommentFormat" value="// CHECKSTYLE\.ON\: ([\w\|]+)"/>
    <property name="checkFormat" value="$1"/>
  </module>
  
  from https://github.com/checkstyle/checkstyle/issues/7287
