### ISSUE TITLE
iP Progress Dashboard

### ISSUE THREAD

**Issue by inezkok** [nus-cs2103-AY2324S1/forum#12]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/b5a611b7-6921-4ce4-8569-f74ebe5309d5)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/4367334c-7789-44e5-86ea-6fb17dd1a007)

I was checking the iP Progress Dashboard and realised that it shows that I have not completed Level-3 even though I have committed and tagged it as shown in the picture above. Is there a problem with my repo or maybe an issue with the linking between my repo and the iP progress dashboard?

**Comment by inezkok** [comment]
I realised that I forgot to tag Level-3 and just tagged it, do I need to re-commit Level-3 or do I just leave it as is?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/98f67fde-4ef8-4d5b-a4e6-7e6527fe0171)

**Comment by damithc** [comment]
@inezkok If you pushed to tag to your fork, it should get detected at the next dashboard update. No further action needed from you.

**Comment by inezkok** [comment]
> 

Ok thank you
