### ISSUE TITLE
Unable to set up GUI 

### ISSUE THREAD

**Issue by RiyaMehta2211** [nus-cs2103-AY2324S1/forum#120]
I am unable to set up GUI as per the tutorial even though I added the relevant dependencies on the build.gradle file, and made Launcher file but still not able to set up GUI. The import statements are still red for me. I have attached the relevant codes here: currently I am using SDK Default 11.0 and ./gradlew build to rebuild the files. I have tried invalidating cache and restarting multiple times but the import statements are still red.

```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.Launcher")
    mainClassName = 'duke.Launcher'
}```



```public class Duke extends Application{
    @Override
    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }
    public Duke() {
        Storage storage = new Storage();
        Ui ui = new Ui();
        ui.printHello();
        Scanner scanner = new Scanner(System.in);
        String str = scanner.nextLine();
        Parser parser = new Parser();
        TaskList tasks = storage.loadTasks("src/data/Duke.txt");
        while (!str.equals("bye")) {
            parser.chat(str, tasks);
            str = scanner.nextLine();
        } try {
            storage.saveTasks("src/data/Duke.txt", tasks);
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
        scanner.close();
        ui.printBye();
    }
} 
```

Above in my duke class, I have also ensured to remove the main() method but the issue still persists. Right now I am not able to get the desired hello world outcome, and my import statements are still not being recognized.

**Comment by damithc** [comment]
@RiyaMehta2211 
You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

**Comment by RiyaMehta2211** [comment]
Hi Prof yup will format the post accordingly. I have attached the link here to my latest commit with the edited files:
https://github.com/RiyaMehta2211/ip/commit/a57ff803d7009f4d943a39bf46d4c34d1b4e90e2

**Comment by lshaoqin** [comment]
Your `build.gradle` file does not seem to contain `id 'org.openjfx.javafxplugin' version '0.0.13'` under plugins, perhaps that could be the issue? For reference, [here](https://github.com/lshaoqin/ip/blob/master/build.gradle) is my `build.gradle` file.

**Comment by Respirayson** [comment]
Perhaps you might want to try gradlew build, then close IntelliJ and reopen it.

Otherwise, I think a brute force way would be to 
Delete the `.gradle` folder in your project and in your users folder (e.g.,: `C:\users\<username>\.gradle`)
Afterwards rebuild gradle using gradlew build
This will force Gradle to download the packages all over again and could solve the problem
However, don't delete the `gradle` folder in the repo.

**Comment by nixonwidjaja** [comment]
To fix the red import statements, you need to use JDK from Zulu that has built in JavaFX, or install JavaFx and put them in the appropriate dependencies.

**Comment by RiyaMehta2211** [comment]
Hi guys, thank you for the suggestions. When I went to check the list of files using command E, I was unable to see the gradle in the tools tab. I suspect my gradle file has been only partially installed. But I can also see all the gradle folders, libraries and gradlew wrapper files too. How do I fix this issue? Is there a way to reinstall gradle but also keep my latest work?

**Comment by RiyaMehta2211** [comment]
Also @Respirayson when I tried removing the .gradle folder from my project but gradle still does not appear in my tools dropdown list. Are there other methods to reinstall?

**Comment by damithc** [comment]
> I suspect my gradle file has been only partially installed.

@RiyaMehta2211 Just to be clear, there was no need to _install_ Gradle. Gradle support was provided as a separate branch -- you just needed to merge it to master.

**Comment by RiyaMehta2211** [comment]
Hi prof, sorry I merged the branch earlier but currently gradle is not being reflected under tools as compared to others. And I am unsure how I could rectify the issue. As of now, I could see the popup for Hello world as well as the files are able to compile. But the import lines are still being underlined and the packages still don't appear to be recognized

**Comment by SynapseProgramming** [comment]
Hihi, im assuming that you are using Intellij as your IDE. In that case, did you turn off Intellij, delete the hidden .idea folder(maybe make a backup of it just in case)  and then turn it back on again?

**Comment by kiwibang** [comment]
Hey, I would like to suggest trying out the [second method](https://openjfx.io/openjfx-docs/#gradle). 
I could not set up JavaFX properly with the first method too but this one worked for me! I tweaked the steps a little to make it work for my project and the import statements (finally) got recognized :)

Setup steps(some steps are slightly different since the version of JavaFX that the tutorial uses is JavaFX 17.0.7):
1. In your build.gradle file, add the following to your `build.gradle` file on top of your existing plugins:
(this adds the JavaFX plugin for Gradle)
```
plugins {
    id 'org.openjfx.javafxplugin' version '0.0.13'
}
```
2. In your `build.gradle` file, also add the following:
(the snippet below specifies that JavaFX 17.0.7 should be used, and that we need the 'javafx.controls' & 'javafx.fxml' modules, FXML can be omitted if you do not plan to use FXML to develop your chatbot GUI)
```
javafx {
    version = "17.0.7"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```
3. Run your `build.gradle` file:
- Linux/Mac: `./gradlew run`
- Windows: `gradlew run`

Really hope this helps! Jiayous!

**Comment by RiyaMehta2211** [comment]
Hi guys,
I am really grateful for all your help! Turns out deleting the .idea folder helped configure gradle properly and partially solve the issue. Unfortunately I get an Unsupported class file major version 64 and Duke cannot be loaded. I am wondering how I could solve this issue? I have pasted a screenshot here of the errors:

<img width="838" alt="Screenshot 2023-09-08 at 9 36 46 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/77782419/1f688560-49af-4b5e-bb11-6078d083e23f">
<img width="1004" alt="Screenshot 2023-09-08 at 9 37 20 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/77782419/33c752b0-2a9b-4090-949a-eef2c276bf4d">

I also found online that downgrading JDK helps with this issue, may I ask what are your configurations for the project structure (ie exact jdk/sdk files being used) as shown in the screenshot below?

<img width="950" alt="Screenshot 2023-09-08 at 9 40 58 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/77782419/5708aacd-bbc2-48aa-82c1-e66649373b44">
<img width="950" alt="Screenshot 2023-09-08 at 9 41 33 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/77782419/35e16245-30ed-4024-92d5-8392a5300e7b">
<img width="950" alt="Screenshot 2023-09-08 at 9 41 55 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/77782419/4c4637f0-706b-4187-970a-9f8076f8030e">
Thank you all so much once again!

**Comment by RiyaMehta2211** [comment]
Hi guys,
I am really grateful for all your help! Turns out deleting the .idea folder helped configure gradle properly and partially solve the issue. I will now revert back to the newest commit to try out Method 2. Thank you so much for your help guys! Greatly appreciate it!

**Comment by RiyaMehta2211** [comment]
I have also tried restarting, clearing cache and doing gradlew clean to no avail

**Comment by RiyaMehta2211** [comment]
The issue has been resolved by deleting the .idea folder and restarting Intellij a couple times. Thank you so much guys!
