### ISSUE TITLE
[A-Gradle] Could not find/load main class && GradleWrapperMain ClassNotFoundException

### ISSUE THREAD

**Issue by evanyan13** [nus-cs2103-AY2324S1/forum#121]
### Development Environment: 
* OS: Mac M2 13.5.1
* IntelliJ: 17.0.8+7-b1000.8 aarch64
* Java: Zulu OpenJDK 11.0.20
* Gradle: 8.3

### Sample Branch with my gradle wrapper :
https://github.com/evanyan13/ip/tree/update-gradle

### Situation
I have been encountering issues when running gradle for the past 5 days and I couldn't seem to figure out what is the issue even after I consulted my team mates. I sincerely hope for your input and advice on resolving this, please.

### Error:
![Screenshot 2023-09-08 at 12 39 22 AM](https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/50259b83-f207-4377-94c9-0bcfbcf75be6)

### This is my build.gradle as well as Project Structure
![Screenshot 2023-09-08 at 12 39 04 AM](https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/3ffc7ffc-c30b-4b30-abc2-3ebdea7055a7)

### I could initiate gradle properly through gradle clean test & gradle init wrapper
<img width="1358" alt="Screenshot 2023-09-08 at 1 06 16 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/6114ae01-257e-4fad-b4c6-630240409b4e">

I have tried all ways I could find to fix this but I could not seem to get it to work...

### Some actions I have attempted:
1. Revert commit and merge add-gradle-support again
2. Init and rebuild the gradle wrapper file
3. Check my Project structure and whether my main class is set correctly in build.gradle
```
application {
    mainClass.set("jarvis.Jarvis")
}
```

4. Verify my Gradle JVM and Java SDK compatibility
![Screenshot 2023-09-08 at 12 40 27 AM](https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/eb325558-6160-4f87-9132-6a8691b15b0b)

## Issue 2. Could not find or load main class org.gradle.wrapper.GradleWrapperMain when running gradlew
![Screenshot 2023-09-08 at 12 41 32 AM](https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/0ce4d3db-d32e-4163-9793-87d9eef2192e)

I'm not too sure if this might be because of the same issue with gradle as well so I think I will leave it in the same post for now. I could not run my gradlew file via 
`./gradlew`
as the error above. This is my gradle/wrapper package:
<img width="446" alt="Screenshot 2023-09-08 at 1 11 17 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/97fe979e-439f-4b18-b498-5273791ba813">

**Comment by damithc** [comment]
@evanyan13 I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

BTW, it looks like you are not using the exact version of the JDK we advise Mac users to use. See https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html#programming-language

> have been struggling with this for the past 5 days!

Should have asked sooner :-)

**Comment by evanyan13** [comment]
@damithc Hi Prof I have set up the JDK as recommended and I am able to run my JAR file now. Thank you for that!

However, the problem with my gradle still persists. I have pushed a branch to the following link:
### Branch Name: update-gradle
https://github.com/evanyan13/ip/tree/update-gradle

For anyone who sees this, please kindly help me take a look at it :''')

**Comment by damithc** [comment]
@evanyan13 Have you pushed the latest code to your branch? I can't see the build.gradle file in that branch

**Comment by evanyan13** [comment]
@damithc Hi prof my apologises. I have pushed the latest code to the branch now. For your further advice please, thank you!

**Comment by HugeNoob** [comment]
Just to confirm, are you facing issues doing `./gradlew run` in the terminal? I've cloned your repo and tried running on my own machine, seems to be working as shown below.

<img width="1294" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/0b9b84d1-b49d-4ab3-95fa-7f2101eaa0a4">
  
Have you tried doing `./gradlew clean build`, or manually deleting the build folder and rebuilding? Perhaps some old build files are causing problems.

**Comment by KamJiaYue** [comment]
@HugeNoob cool JARVIS, Mr. Stark

**Comment by KamJiaYue** [comment]
No problem from my end too, ./gradlew run can be successfully executed

**Comment by woojiahao** [comment]
Interestingly, it seems like Intellij is not configured properly for the project because your class files should not be generated inside the `src` folder (unless you explicitly compiled). Could you share your project structure? In the new UI, it's the cog at the top right.

**Comment by damithc** [comment]
> Interestingly, it seems like Intellij is not configured properly

Good point @woojiahao Could also be a result of using both Intellij and VSCode at the same time. 
@evanyan13 Perhaps clone the fork again and set up Intellij for it again?

**Comment by craigtonlian** [comment]
I was able to run `./gradlew run` without problems too.

@evanyan13 Has this issue been resolved yet? 😄

**Comment by evanyan13** [comment]
@damithc @craigtonlian @woojiahao @KamJiaYue @HugeNoob 

Hi Prof and friends! Great news I finally got my gradle to work after 1 week. 
### So the solution was to move my entire ip to /user instead of /user/Project/

I'm able to get it running from both Intellij and VSCode so I don't think the problem is with the IDE. I'm not very sure why this is the case so I wish to seek advice on this as well, please. Thank you Prof and everyone for your time and attention on my issue.

<img width="1074" alt="Screenshot 2023-09-09 at 7 35 18 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/103996156/9efe8e09-c89e-4745-b6e8-7f3383086697">
