### ISSUE TITLE
Started another canvas quiz on accident

### ISSUE THREAD

**Issue by MagnificentCreature** [nus-cs2103-AY2324S1/forum#123]
I clicked take quiz again on accident even though I submitted a quiz already, do I have to fill it in and submit again?

Asking because in 2100 they take the marks of the lastest submitted quiz, so if I don't fill up the resubmission, canvas will automatically submit a blank response at the end and I will get 0 marks

**Comment by damithc** [comment]
@MagnificentCreature We take the submission with the highest score.

**Comment by MagnificentCreature** [comment]
Noted with thanks!
