### ISSUE TITLE
Made changes to an implementation

### ISSUE THREAD

**Issue by RiyaMehta2211** [nus-cs2103-AY2324S1/forum#124]
Hi,

If I made changes to a past implementation to fix some errors I am getting now, do I need to push a new commit and shift the tag from a previous commit? Or are previous commits not really taken into account for the grading? 

Thank you.

**Comment by damithc** [comment]
@RiyaMehta2211 It's fine to fix old bugs in new commits. There is no need to move tags on account of that.

**Comment by RiyaMehta2211** [comment]
Thank you Prof
