### ISSUE TITLE
[GUI] JavaFx: cannot access javafx.event.EventTarget & javafx.collections.ObservableList

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#126]
IntelliJ 2022.1.2, Java 11, Windows

<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/155e9cd3-6740-4edf-a929-dbd252c278b5">

<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/bb102522-b3bd-4f35-a111-e4158ce367b8">

However, doing ./gradlew run works fine
<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/fbc34095-210b-43db-92f2-ddb1e1277278">

build.gradle is configured as in the guide. If anyone knows how I can compile the build please advice.

Thank you.

**Comment by s-peiran** [comment]
deleting the .idea file seems to fix the problem

**Comment by KamJiaYue** [comment]
could it be a mismatch between this file and ur fxml files?

**Comment by lamchenghou** [comment]
Maybe your javafx dependencies are not set up correctly?

**Comment by damithc** [comment]
@s-peiran if the problem is resolved, you can close this issue.

**Comment by s-peiran** [comment]
Thanks everyone for your inputs
