### ISSUE TITLE
Set up username wrongly

### ISSUE THREAD

**Issue by ong-wei-hong** [nus-cs2103-AY2324S1/forum#13]
Hi, I ve submitted my github username on canvas wrongly, is there any way to fix it?

**Comment by damithc** [comment]
@ong-wei-hong email the correct username to `cs2103@comp.nus.edu.sg`

**Comment by IsabelChong** [comment]
Hi @ong-wei-hong if you've had a chance to resolve the issue, please do remember to close it afterwards.

**Comment by ong-wei-hong** [comment]
Thanks! I've sent an email to the above email address
