### ISSUE TITLE
Execution failed for task ':Launcher.main()' in JavaFX

### ISSUE THREAD

**Issue by yyyaohhh** [nus-cs2103-AY2324S1/forum#130]
Hi, I faced the error of not able to launch the launcher when following step 1 of the JavaFX tutorial. 
I have read the previous issues on changing Java version to 11.0.20, but that did not seem to work.
<img width="464" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/3a9e6027-9614-448e-956c-58fd75d96cd2">
Adding JavaFX modules from https://openjfx.io/openjfx-docs/#gradle also did not work, and I used 
```
javafx {
    version = '17.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}
```
May I know what else should I do to solve this problem?
<img width="786" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/2924368a-2aa8-4825-b0fd-7630df32c9b3">
<img width="398" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/5d39c39e-d3e8-432f-8d85-3a86822b765a">

**Comment by s-peiran** [comment]
Hi is this part 3 of the JavaFX tutorial? and have you pushed the corresponding code to the remote repo?

**Comment by yyyaohhh** [comment]
Hi this is part 1 of the JavaFX tutorial, and I have just pushed the code to the remote repo under the branch GUI. Thanks :)

**Comment by lamchenghou** [comment]
Hi, I believe this is similar to the tip given by Jeffrey in #111.

**Comment by yyyaohhh** [comment]
Thank you so much this works! :))
