### ISSUE TITLE
iP Dashboard cannot track Use-GFMD

### ISSUE THREAD

**Issue by tiif** [nus-cs2103-AY2324S1/forum#133]
Hi, I already did these thing but iP dashboard cannot track the update:

1. Updated my README.md according to the requirement and commit to a new branch called "Use-GFMD"
2. Merged "Use-GFMD" branch to the master branch, then push both the master branch and "Use GFMD" to my forked repo

The other increment updates are fine. Is there anything that I missed and what should I do for it to track this update?

Thanks in advance for any help.

**Comment by HugeNoob** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/268ceea0-635a-483e-b6c7-b0d97cb81f2b)
To fulfil the Use-GFMD task, you are supposed to update the description of your [iP PR](https://github.com/nus-cs2103-AY2324S1/ip/pull/295), and not your README.

**Comment by damithc** [comment]
@HugeNoob is correct. 👍

**Comment by tiif** [comment]
Oh I missed that, thank you!
