### ISSUE TITLE
Question regarding A-Assertions

### ISSUE THREAD

**Issue by zacwong2151** [nus-cs2103-AY2324S1/forum#135]
I am confused regarding how to implement assertions for Week 5 project. Are we supposed to run Duke.main()? Because earlier in Week 4 - Project, this was mentioned:

``` Note that you no longer need to keep the text-based UI after adding a GUI. Similarly, there is no need to use the I/O redirection style automated testing anymore (that technique is suited for text UIs only). ```

So do we still have to maintain our text-based UI on top of our GUI chatbot? Because from my understanding, assertions are only relevant when you run Duke.main, and are not relevant when you run the GUI chatbot. I ask this because I get this error when I try to run Duke.main ```JavaFX runtime components are missing, and are required to run this application```, and so I'm wondering if I need to fix this or simply remove everything that is not related to running the GUI chatbot

**Comment by damithc** [comment]
> assertions are only relevant when you run Duke.main

@zacwong2151 this is incorrect. Assertions can be used in any Java code that is executed. So, any code that is executed while running the GUI version can have assertions.

Perhaps a few others can share examples of how they did A-Assertions in their iP?

**Comment by ghost** [comment]
The error does not seem related to assertions, might be something to do with your java jdk as it was with mine. There are other open issues about the error you are facing, so maybe you can check them out.

**Comment by woojiahao** [comment]
This was how I used assertions: https://github.com/woojiahao/ip/pull/1

But also, assertions are useful to just ensure parameters are valid too, not just limited to text UI testing

**Comment by zacwong2151** [comment]
Thanks for the replies! I understand a bit better now. So do I still have to maintain my text-based UI and ensure it runs smoothly as before? Or just keep code that is only necessary for the chatbot GUI?

**Comment by woojiahao** [comment]
Believe prof answered this in another issue, no you don't have to

**Comment by zacwong2151** [comment]
aight thanks!
