### ISSUE TITLE
Java `getResource` returns null despite the path being correct

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2103-AY2324S1/forum#136]
I have been trying to import the image for the GUI, however, whenever i tried `this.getClass().getResource()`,
I get `java.lang.NullPointerException`. I have verified the correctness of the path by using `System.out.println(System.getProperty("user.dir"))`. 

I have also tried using `System.getProperty("user.dir")` to give the absolute path to no avail.

Anyone aware why this is not working.

**Comment by ghost** [comment]
Have you tried moving your resources to src/main/resources and using the path relative to src/main/resources? I believe this is where gradle defaults to searching for resource files.

**Comment by XihuaZ** [comment]
I noticed the issue, it seems the pathway set for `getResourceAsStream()` or `getResource()` is set to `/ip/out/production/ip` instead of `/ip/`.
