### ISSUE TITLE
Forgot to branch for some increments

### ISSUE THREAD

**Issue by TehOPanas** [nus-cs2103-AY2324S1/forum#137]
I have forgotten to branch out for 3 increments : A-CodingStandard, A-JavaDoc and Level-9. Is there anyway to fix it as I have no idea on how to get it done for my iP progress.

**Comment by KamJiaYue** [comment]
Can try to create that branch, create that tag and push again

**Comment by damithc** [comment]
@TehOPanas #27 might be related to your question

**Comment by TehOPanas** [comment]
Thanks for the response!
