### ISSUE TITLE
SourceTree frequently pops out CredentialHelperSelector in the background

### ISSUE THREAD

**Issue by larrywang0701** [nus-cs2103-AY2324S1/forum#138]
Hello professors and classmates

At the first day when I started using SourceTree, I noticed that whenever I push to remote repo, a window will pop up:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113608053/e74aaeb6-18b0-4235-a359-5cf0a24245a9)
It will pop twice with the same content, and I just directly click the "select" button twice.

But these days I found out that this window also automatically pops even though I didn't do any push actions or actions related to the remote repo. Same as when I manually push to remote repos, it pops twice. Sometimes I just left SourceTree stays in the system background without closing it, and when I was doing other things with my device, this window also frequently pops up randomly at any time. (Even when I'm writing this question now, it pops again in the background!) **Just like SourceTree is pushing something to the remote repo by itself even without my comfirmation???** Since weeks ago it won't like this, so I tried to solve it. But I couldn't solve it and even deleting all files in local repo then re-clone from remote repo won't solve. Could someone told me why this window pops automatically in the background randomly (without any direction operation or action from me) and how to solve this problem? (My OS is Windows 10) Thanks.

**Comment by damithc** [comment]
@larrywang0701 while waiting for others to pitch in, you can try these (if haven't done them already) https://se-education.org/guides/tutorials/sourcetree.html#connecting-sourcetree-to-your-github-account

Also, I assume you tried ticking the `Always use this from now on` box in the dialog?

**Comment by woojiahao** [comment]
Doing a quick Google of "SourceTree select credential helper" yields this search result: https://community.atlassian.com/t5/Sourcetree-questions/CredentialHelperSelector/qaq-p/1334704 

Have you tried it?
