### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by kayabuttertoastt** [nus-cs2103-AY2324S1/forum#139]
Hello professors and classmates. I am faced with this error and I am not sure what is the root cause. 
<img width="1446" alt="Screenshot 2023-09-13 at 12 43 58 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122214710/a772d5f6-5e9b-4795-8bbf-74e31ff31f54">

I am using a Mac (M2) and I am using the exact JDK distribution specified by the advisory for Mac Users. 
<img width="960" alt="Screenshot 2023-09-13 at 12 44 10 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122214710/a73862f4-ace2-4e84-ac91-efab42eea6ca">

This is my code for the Launcher class. 

import javafx.application.Application;

public class Launcher {
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
}

Could someone help me with this? Thank you!

**Comment by ghost** [comment]
Are you sure that is the JDK distribution recommended for mac users? I'm on m1 but I'm using the Azul version.

**Comment by kayabuttertoastt** [comment]
@chiayunrong Thank you for pointing that out. Issue is resolved.
