### ISSUE TITLE
Git commit subject violation

### ISSUE THREAD

**Issue by butteredyakiimo** [nus-cs2103-AY2324S1/forum#142]
Hi! When I was working on writing the full commit messages, I used an editor instead of source tree to add a git message. However, I only realised now that a full stop has been added to the commit headers, even though I did not add one :'D.

![Screenshot 2023-09-13 at 4 33 33 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/111829949/a50b50e3-8a28-4384-8763-13ec6c2f500e)

I tried to follow the steps [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) but realised they either create a new commit, or I have to rebase.

Would I be penalised for these full stops, or would it be fine as long as I adhere to the standards on subsequent commits 😞.

**Comment by damithc** [comment]
> would it be fine as long as I adhere to the standards on subsequent commits 😞.

@butteredyakiimo that is good enough.

**Comment by ghost** [comment]
You can rebase and force push to edit your previous commits if you want. Check out the command `git rebase -i`.

**Comment by damithc** [comment]
> You can rebase and force push to edit your previous commits if you want. Check out the command `git rebase -i`.

Yup, but keep in mind that this will change the timestamps of the commits, which in turn will affect the commit tracking by our scripts. The affected commits will be counted as done at the new time, not the original time of the commit.

**Comment by butteredyakiimo** [comment]
All right, thank you for the help! I'll close the issue now
