### ISSUE TITLE
Sourcetree branch merging is not working

### ISSUE THREAD

**Issue by TehOPanas** [nus-cs2103-AY2324S1/forum#143]
I have branched out for A-CodingStandard and want to merge it back to my master branch. However, when I finished the merging action, no result can be seen or found.

Edit : Solution found. 
The problem is raised due to me having my tag and branch at different commits, it causes Git to be confused on which one to choose based on the name. 
What I have done is specify which is it in the Git bash command, then it worked.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/ef1b3a7f-d65d-4e5c-b392-c62dd8fffab7)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/3c3dec26-bd55-482e-838e-8fa529e4c899)
This is the master branch and the branch I want to merge.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/34ef6404-8a91-4b1e-909e-557e3d9b8bba)
Options selected for merging.

And no results after I clicked **ok**.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/faf0d262-0361-493d-9ef5-62628307a911)

Does anyone have any idea on how to solve this issue?

**Comment by damithc** [comment]
@TehOPanas you can refresh the Sourcetree UI (F5 in Windows), just in case the UI didn't update after you merged.

**Comment by TehOPanas** [comment]
> @TehOPanas you can refresh the Sourcetree UI (F5 in Windows), just in case the UI didn't update after you merged.

I have tried to do so, but no result ;)

**Comment by damithc** [comment]
@TehOPanas You can try one more time using the UI (perhaps restart Sourcetree first), and if still no success, can try CLI alternative i.e., open a gitbash terminal from Sourcetree and type in the commands.

**Comment by damithc** [comment]
@TehOPanas solved? how?

**Comment by TehOPanas** [comment]
Sorry prof, I only wrote the solution in my post, gonna post in comment instead :


Solution found.
The problem is raised due to me having my tag and branch at different commits, it causes Git to be confused on which one to choose based on the name.
What I have done is specify which is it in the Git bash command, then it worked.


![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/f10f3fb0-1dcd-4c19-b8cc-3041699b21b3)
