### ISSUE TITLE
Practical exam time arrangment: leaving on 18:00

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#144]
On Nov 17, I have another GESS1025 exam in LT9 on 18:30. Would it be possible for me to leave the exam venue as soon as the PE ends, i.e. 18:00, so I can rush to the next exam? Thank you for helping.

**Comment by damithc** [comment]
@ChangruHenryQian Yes, the PE should end by 5.45pm, latest by 6pm. And most does the PE over Zoom - so you can do it from a location near your other exam venue.

**Comment by ChangruHenryQian** [comment]
@damithc Thank you for clarifying.
