### ISSUE TITLE
Error when pushing continuous integration set up

### ISSUE THREAD

**Issue by AprupKale** [nus-cs2103-AY2324S1/forum#145]
---
name: Continuous integration push to GitHub
about: Need help with workflow setup with OAuth
labels: 'type-HelpRequest'

---
```
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/gradle.yml` without `workflow` scope)
 ! [remote rejected] A-CI -> A-CI (refusing to allow an OAuth App to create or update workflow `.github/workflows/gradle.yml` without `workflow` scope)
```

I figured out that for some reason I don't have access with OAuth to push workflows/* to the remote repo. How do I fix that and push the commit to the remote repo?

Or is the reason for this error something else?

Thanks in advance!

**Comment by A1WAYSD** [comment]
Hiii I didn’t met this issue when setting up CI, but I guess you may set up a new personal token according to https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on
Or if still not working can try this: 
https://github.com/orgs/community/discussions/26254#discussioncomment-6101339

**Comment by vivienherq** [comment]
hello! i didnt face this issue either but ^^ the links posted above seem to be the top two results from google or you could maybe check that you've [given permission for github actions](https://docs.github.com/en/enterprise-server@3.6/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)? atb!

**Comment by timleow** [comment]
Hi! I experienced a similar issue and it has to do with the permission scope of the PAT (personal access token). But either way what I did was delete the commit and add the `.yml` file directly through github actions interface, and modify the contents from there (based on the example provided)


<img width="1249" alt="Screenshot 2023-09-15 at 12 25 06 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/64006665/cc9fc00e-6aab-456e-ae6e-02a10060b7d9">

**Comment by AprupKale** [comment]
Creating a Personal Access Token and then changing remote origin path in Sourcetree solves the issue!
