### ISSUE TITLE
Unable to use username for team GitHub organisation after deletion

### ISSUE THREAD

**Issue by rocketninja7** [nus-cs2103-AY2324S1/forum#149]
I tried to create the GitHub organisation for my team, but because my internet was facing issues, I decided to let my team mate do it instead. I deleted my team organisation and now am unable to use the organisation name for 90 days. Can I ask how my team should go about with naming the organisation? Currently we are thinking of creating an organisation with a separate name, and will rename it according to how we should when we can. Thank you.
![deletedorganisation](https://github.com/nus-cs2103-AY2324S1/forum/assets/43843106/4f539a2c-5157-4d39-9a25-38d626e2e109)

**Comment by damithc** [comment]
@rocketninja7 you can use `-0` instead of `-1` in the org name.

**Comment by rocketninja7** [comment]
Thank you for your advice. We will name our organisation accordingly.

**Comment by damithc** [comment]
@rocketninja7 BTW, this can throw off some of the dashboard scripts. If you notice some of your team's work is not being recognized by a dashboard, let me know.
