### ISSUE TITLE
Not sure what the following warning means when I run "git add" on the files I created to semi-automate my code

### ISSUE THREAD

**Issue by elhy1999** [nus-cs2103-AY2324S1/forum#15]
Hi there! I finished creating the test cases required for `A-TextUiTesting` and received the following warning when running `git add` on the `.txt` test case file and `.bat` script file:

`warning: in the working copy of 'text-ui-test/input.txt', LF will be replaced by CRLF the next time Git touches it`

I'm not really sure what this warning means. A search on the internet tells me that it has something to do with something called "Line Feed" and "Carriage Return", but I don't quite understand it. A post on StackOverflow suggested running some git config commands, but I'm worried that something might break. This is the link to the post I read: https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/67943858/4b40af92-09e7-4c57-896a-59fceb294d08)

**Comment by woojiahao** [comment]
Believe this is discussed in issue #2 as well, you can subscribe to that issue's notifications

**Comment by muhammadreyaaz** [comment]
Hi @elhy1999. I am unsure if you have solved this issue, but I found a relevant post which you might not have came across. 

[https://stackoverflow.com/questions/17628305/windows-git-warning-lf-will-be-replaced-by-crlf-is-that-warning-tail-backwar](url)

It seems that the warning will not break your system, and is not a critical warning. There are a couple of solutions there as well for windows. I hope this helps!

**Comment by elhy1999** [comment]
Hi @ARPspoofing, thanks for sharing the post. Yes, I noticed that ignoring the warning doesn't really have any noticeable effects. Thanks for confirming it for me! Thanks to @woojiahao as well for linking me to the other post 😄
