### ISSUE TITLE
User guide format to follow

### ISSUE THREAD

**Issue by brendanneojw** [nus-cs2103-AY2324S1/forum#150]
Hi all, just wondering because there is a README.md file given in the repo which has some guide on how the format should look like. However when compared with the AB3 user guide given in the website (https://se-education.org/addressbook-level3/UserGuide.html), the format seemed to be different. Hence I would like to know which format we should follow for this week's iP task.

The difference is that in the given README.md file, it is given to be describing the "Features" first then the "Usage" of the action to achieve this feature (the first picture) while the AB3 User's Guide kinda combine them both (the second picture)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29995121/df25c2b5-753a-4115-914c-f3b7d2c73e67)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29995121/8a76ff6d-ef56-4448-916f-f1060e42a977)

**Comment by damithc** [comment]
@brendanneojw Good question. You can use either one, or any other layout/structure that you think is suitable too. You can judge from the user's point of view and decide which works best for the user.
