### ISSUE TITLE
Tp CodeCov Help

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#151]
Hi friends,

After integrating CodeCov into our Tp fork as per specified by CodeCov's documents, the dashboard still shows the button "setup repo" in the homepage beside our fork. Anybody knows the fix for this? Thanks!

My CodeCov dashboard:
<img width="1578" alt="Screenshot 2023-09-19 at 3 13 54 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/84987837/e052183a-3a6e-4538-82fa-c1f0f38d4812">

Supposed to look like:
<img width="939" alt="Screenshot 2023-09-19 at 3 28 12 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/84987837/fd11144f-6195-4fa1-b1d5-2c9e6c7a352a">

**Comment by oeggy03** [comment]
Hi, from my experience, sometimes you need to wait for a while for the codecov page to update. Another thing you can try is to push a commit to your fork (e.g. ammend the README file) and create a pull request. This will prompt codecov to run and if you can see the codecov checks below the build checks like:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/80142959/59e3d94d-df07-46bd-a409-7ca7e7944d89)

Then you're probably doing it right

**Comment by lihongguang00** [comment]
> Hi, from my experience, sometimes you need to wait for a while for the codecov page to update. Another thing you can try is to push a commit to your fork (e.g. ammend the README file) and create a pull request. This will prompt codecov to run and if you can see the codecov checks below the build checks like:
> 
> ![image](https://user-images.githubusercontent.com/80142959/268882426-59e3d94d-df07-46bd-a409-7ca7e7944d89.png)
> 
> Then you're probably doing it right

Thanks to your help, I figured it out :D Appreciate it!
