### ISSUE TITLE
Issue with relative paths

### ISSUE THREAD

**Issue by zacwong2151** [nus-cs2103-AY2324S1/forum#153]
Hi guys, I'm facing some issue with locating my duke.txt file which is located in my data directory. I am searching for this file from multiple classes in my duke package, such as my `Duke.java` class. And yet when I run my code, I get the error 

```..\..\..\..\data\duke.txt (The system cannot find the path specified)```

Anyone has any idea why this happens? Is there an issue with my relative pathing? Attached below is my file directory and my `Duke.java` file
I previously used the absolute path `data/duke.txt` which worked, and now I face this issue when I try to change to relative paths.

Any help is much appreciated!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111118549/19b816a9-91d6-4844-aa1f-e3fbb09a6535)

**Comment by WZWren** [comment]
Hey @zacwong2151, I believe you can use the path `./data/duke.txt` to fix this issue - the IDE runs the program as if the `ip` folder is the root.

On a side note, you can look into the `java.nio.file.Paths` library - in particular, the `Paths.get` method can generate a relative path that is usable across different OS platforms, without having to deal with the file separators.

**Comment by zacwong2151** [comment]
@WZWren thanks so much! Your suggestion works. If I may ask though, why is my relative path wrong? Am I misunderstanding something about relative paths?

**Comment by zhanyang01** [comment]
Relative path is the location of the file relative to the working directory while absolute relative is location from the root directory. Based on @WZWren reply, you can also trace back after generating the relative file path to have a better understanding of how it works

**Comment by damithc** [comment]
@zacwong2151 Perhaps your mistake was in thinking that you need to specify the path relative to the location of the Java class it is specified in. Instead, it should be relative to the location the application is run (i.e., the working directory).

**Comment by zacwong2151** [comment]
Aight thanks all for replying! I understand now
