### ISSUE TITLE
Cannot deploy github-pages

### ISSUE THREAD

**Issue by longnguyentan** [nus-cs2103-AY2324S1/forum#155]
I cannot enable the GitHub Page feature (e.g. http://{your username}.github.io/{repo name}/). I checked the environment but there is no restriction.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/66206654/cc76707f-1cd1-493e-8f47-748442de2434)

**Comment by damithc** [comment]
As per https://www.githubstatus.com/ GitHub issues is experiencing difficulties at the moment, but there's no mention of any problems with the Pages feature. Nevertheless, you can try again after everything is back to normal, just in case.

**Comment by damithc** [comment]
@longnguyentan in the meantime, try Googling for the error message (the one in your screenshot).

**Comment by EricXiong420** [comment]
Hi, I'm facing the exact same issue, have you managed to fix it?

**Comment by longnguyentan** [comment]
@damithc I have tried again and it works. Thank you.
@EricXiong420 I think you can wait and re-deploy it. There is no need to change anything for me.
