### ISSUE TITLE
Cannot view own screenshot on iP showcase

### ISSUE THREAD

**Issue by yezkez10** [nus-cs2103-AY2324S1/forum#156]
Hi all, hope week 6 has been treating you well!
I have my Ui.png in my ip/docs folder, but I still am unable to view my Ui screenshot on the iP showcase. My friends are facing similar issues.
Any help would be much appreciated!
Cheers

**Comment by woojiahao** [comment]
It appears that you have not deployed your website to GitHub Pages, so the static asset is not accessible through the URL. The website should be available to view at https://yezkez10.github.io/ip

**Comment by yezkez10** [comment]
@woojiahao ooh got it thank you!
