### ISSUE TITLE
Tp Layout of product website after deployment

### ISSUE THREAD

**Issue by tohpinren** [nus-cs2103-AY2324S1/forum#157]
I followed all the instructions in the tP Team Repo Setup to set up my Team Repo and Product website using MarkBind. After deploying on github, my team product website looks slightly different from the one I see when I run it locally `npm run serve`. The actual website is missing the header and side bar.

Run locally using `npm run serve`:
<img width="1440" alt="Screenshot 2023-09-20 at 10 14 52 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/64828959/5a3c3ed5-1c6c-49d4-8b6c-5e1956dd34c9">

Actual product website on github pages:
<img width="1440" alt="Screenshot 2023-09-20 at 10 15 15 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/64828959/879f8c60-4259-46d1-b7c7-c229faaf9934">

I tried following all steps of the instructions again but I still got the same result. Is this the expected output? Or else, how can I fix it?

**Comment by tlylt** [comment]
Hi @tohpinren, can I get you to double-check the first two steps in https://se-education.org/guides/tutorials/markbind-forked-sites.html#initiating-the-site
?

Go into the repo settings and it should look something like this:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/9e16d3e0-e547-4675-a8f5-58927d5bef56)


You may need to try pushing some changes to master again/trigger the github action again to see if it helps

**Comment by tohpinren** [comment]
Hi @tlylt, thanks for the advice. I doubled checked the first two steps and it looks right. I also re run all the build and deploy actions again but it's still the same.

**Comment by tlylt** [comment]
Can you add me as admin into your repo temporarily? So that I can take a closer look later.

Btw I'm a MarkBind dev hence supporting this issue:)

**Comment by damithc** [comment]
@tohpinren As per https://github.com/AY2324S1-CS2103T-W09-3/tp/commits/master it looks like you manually merged something to the gh-pages branch which may have affected the GitHub pages behavior.  gh-pages branch is managed by GitHub and best not to merge from/to it.

**Comment by tohpinren** [comment]
@tlylt I have added you thank you!

**Comment by tohpinren** [comment]
Hi Prof @damithc gh-pages was a branch I created myself. Should I avoid naming it as such in the future? Should I revert commits and try everything again?

**Comment by damithc** [comment]
> Hi Prof @damithc gh-pages was a branch I created myself. Should I avoid naming it as such in the future? Should I revert commits and try everything again?

@tohpinren Yes, avoid that branch name. Try deleting that branch (in the remote repo) and triggering the publish action (e.g., re-run the GitHub action or push a dummy commit to the master branch). If that doesn't work, a more drastic remedy is to delete the fork and set it up again.

**Comment by tlylt** [comment]
@tohpinren its working now https://ay2324s1-cs2103t-w09-3.github.io/tp/

I basically changed the branch from master to gh-pages in the repo page setting.

Originally was:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/91f38c21-66c3-4e16-942d-530eba2e854f)

Updated one looks like the screenshot i attached in earlier reply.

**Comment by tohpinren** [comment]
@tlylt @damithc Thank you so much! I'll avoid the branch name in the future.
