### ISSUE TITLE
Merging gh-pages branch into master

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#158]
The `gh-pages` branch appears to be a standalone node when I deployed the user guide. 

Conventionally, is there a need to merge this into master?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108467437/a595ab61-a1b9-4229-80ad-ac403351a4b8)

**Comment by damithc** [comment]
@craigtonlian you can think of gh-pages as a special branch created and by GitHub. You can let it be. No need to merge it manually.

**Comment by craigtonlian** [comment]
Thank you! Will leave it alone then 😊
