### ISSUE TITLE
Smoke test: Issue running on windows

### ISSUE THREAD

**Issue by kiwibang** [nus-cs2103-AY2324S1/forum#159]
Context:
* OS: Mac OS Ventura 16.5
* IDE: IntelliJ

Issue: Smoke test when running jar file on local system works fine, but when running jar file on non-Mac OS system(e.g. Windows 10), it fails with the error described below. Would greatly appreciate any help!

What I think is the issue: JavaFX configuration is wrong(If it helps, I used the [second method](https://openjfx.io/openjfx-docs/#gradle) to set up JavaFX. However, googling has yielded no results for me(probably a skill issue).

[Link to latest release page](https://github.com/kiwibang/ip/releases/tag/A-Release)

My gradle.build configuration: 
```gradle
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'org.openjfx.javafxplugin' version '0.0.13'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

checkstyle {
    toolVersion = '10.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}

javafx {
    version = "17.0.7"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainModule = 'com.nyanbot.dukeguicontrollers'
    mainClass = 'com.nyanbot.dukeguicontrollers.DukeLauncher'
}

shadowJar {
    archiveBaseName = "com.nyanbot"
    archiveFileName = 'nyanbot.jar'
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run {
    standardInput = System.in
}
```

Error thrown when running the jar on Windows:
```
com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @464ea28f'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by AlagappanRa** [comment]
Are you above to see the following? (java fxml file configs)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/fa1f1040-6880-4a52-b18b-8b86a018477f)

Under Project Structure > Project Settings >Modules > ip > (main) [or wherever you main code directory is]

**Comment by AlagappanRa** [comment]
I believe the problem is in your build gradle file. Even though in the build task, you have indicated option for `depends on("distZip", "distJar")`, shadow jar probably didn't detect any dependencies associated with those (other) distributions.

Maybe you could try modifying the dependencies task your build gradle file to this 

```java
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    testImplementation 'org.mockito:mockito-core:3.12.4'

    String javaFxVersion = '17.0.8'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
    implementation 'org.openjfx:javafx-controls:17.0.8'
}
```
Of course, this would install javaFx version 17.0.8 in your repository (change it to your preferred version)

**Comment by kiwibang** [comment]
> Are you above to see the following? (java fxml file configs)
> 
> ![image](https://user-images.githubusercontent.com/96157054/269268404-fa1f1040-6880-4a52-b18b-8b86a018477f.png)
> 
> Under Project Structure > Project Settings >Modules > ip > (main) [or wherever you main code directory is]


<img width="843" alt="Screenshot 2023-09-20 at 9 00 04 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/66860275/5ed832c0-c3da-4f21-a072-45de761042cd">

^The above is mine. Seems like that might be the issue since it looks like there are only distributions for mac OS but not other OSes. However, my build.gradle file does not have what you have since I used the second method to do set up JavaFX. Adding your recommended dependencies breaks my checkstyle file. Thanks for the hint though!!

**Comment by damithc** [comment]
> ^The above is mine. Seems like that might be the issue since it looks like there are only distributions for mac OS but not other OSes. However, my build.gradle file does not have what you have since I used the second method to do set up JavaFX. Adding your recommended dependencies breaks my checkstyle file. Thanks for the hint though!!

🤔 hmm... We might have to remove the second method from our instructions if it is going to cause this problem at the end. I remember one other student faced this problem and solved it by updating the gradle file.

@kiwibang I suggest you update the build.gradle as suggested by @AlagappanRa and fix any resulting checkstyle problem (in fact, there is no good reason why it should cause a checkstyle problem, unless you accidentally changed something related to checkstyle while updating the gradle file).

**Comment by DeltonCheng** [comment]
Hi! Am facing the same issues as you are. I set up my JavaFx using the first method, but my java fxml file configs are similar to yours, so I am not sure if it is due to how you set up JavaFx.

**Comment by kiwibang** [comment]
> > ^The above is mine. Seems like that might be the issue since it looks like there are only distributions for mac OS but not other OSes. However, my build.gradle file does not have what you have since I used the second method to do set up JavaFX. Adding your recommended dependencies breaks my checkstyle file. Thanks for the hint though!!
> 
> 🤔 hmm... We might have to remove the second method from our instructions if it is going to cause this problem at the end. I remember one other student faced this problem and solved it by updating the gradle file.
> 
> @kiwibang I suggest you update the build.gradle as suggested by @AlagappanRa and fix any resulting checkstyle problem (in fact, there is no good reason why it should cause a checkstyle problem, unless you accidentally changed something related to checkstyle while updating the gradle file).

Ok thanks prof. I have taken these steps so far:
- Revert all traces of the second step by removing the JavaFX SDK and updating build.gradle to the first method
- loaded gradle changes
- ran: ./gradlew build
- Managed to get the project structure to the state that @AlagappanRa described:
<img width="902" alt="Screenshot 2023-09-21 at 12 52 36 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/66860275/d1c0927e-405f-4d61-877f-07ac3aae4033">

- However, this change breaks the following:
- The checkstyle: It seems to completely ignore the existence of the main file but somehow can run checks on the test file:

```
> Task :checkstyleMain FAILED

> Task :checkstyleTest FAILED
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:5:1: Import statement for 'org.junit.jupiter.api.Assertions.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:8:9: 'method def modifier' has incorrect indentation level 8, expected level should be 4. [Indentation]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:10:13: 'method def' child has incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:11:13: 'method def' child has incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:12:13: 'method def' child has incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:13: Line is longer than 120 characters (found 121). [LineLength]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:13:13: 'method def' child has incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListExceptionTest.java:14:9: 'method def rcurly' has incorrect indentation level 8, expected level should be 4. [Indentation]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyInputExceptionTest.java:5:1: Import statement for 'org.junit.jupiter.api.Assertions.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/dukeexceptions/DukeEmptyInputExceptionTest.java:12: Line is longer than 120 characters (found 132). [LineLength]
[ant:checkstyle] [ERROR] /Users/kw/ip/src/test/java/com/nyanbot/duketasks/TodoTest.java:5:1: Import statement for 'org.junit.jupiter.api.Assertions.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > An unexpected error occurred configuring and executing Checkstyle.
      > Unable to process files: [/Users/kw/ip/src/main/java/module-info.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeguicontrollers/DukeMain.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeguicontrollers/DukeMainWindow.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeguicontrollers/DukeLauncher.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeguicontrollers/Duke.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptionhandlers/DukeExceptionHandlers.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeuiclasses/DukeErrorUi.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeuiclasses/DukeUi.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptions/DukeEmptyTaskListException.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptions/DukeInvalidCommandException.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptions/DukeEmptyInputException.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptions/DukeInvalidIndexException.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptions/DukeInvalidTimeException.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeexceptions/DukeException.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeparsers/DukeTimeParser.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeparsers/DukeParser.java, /Users/kw/ip/src/main/java/com/nyanbot/duketasks/InvalidTask.java, /Users/kw/ip/src/main/java/com/nyanbot/duketasks/Event.java, /Users/kw/ip/src/main/java/com/nyanbot/duketasks/Task.java, /Users/kw/ip/src/main/java/com/nyanbot/duketasks/Deadline.java, /Users/kw/ip/src/main/java/com/nyanbot/duketasks/Todo.java, /Users/kw/ip/src/main/java/com/nyanbot/dukestorage/DukeStorageDatabase.java, /Users/kw/ip/src/main/java/com/nyanbot/dukeguielements/DukeDialogBox.java, /Users/kw/ip/src/main/java/com/nyanbot/duketasklist/DukeTaskList.java]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':checkstyleTest'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > Checkstyle rule violations were found. See the report at: file:///Users/kw/ip/build/reports/checkstyle/test.html
     Checkstyle files with violations: 3
     Checkstyle violations by severity: [error:11]

```

- Second error: Now the main file completely breaks, and I am unable to run the main file. 
- I have ensured that:
- The Java JDK is the Azul-Zulu 11.0.20 version(I am a Mac M2 user) as per the Mac Advisory
- Removed any other JDKs that might interfere 
- Set the `JAVA_HOME` and `JDK_HOME` to the `home` folder of the Azul-Zulu JDK
- Running java --version results in the following:
```
openjdk version "11.0.20.1" 2023-08-24 LTS
OpenJDK Runtime Environment Zulu11.66+19-CA (build 11.0.20.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+19-CA (build 11.0.20.1+1-LTS, mixed mode)
``` 

- This is the error:
```
Execution failed for task ':DukeLauncher.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
```

- Third error: Applying changes to the project structure leads to the following(see the bottom right message)
<img width="903" alt="Screenshot 2023-09-21 at 1 03 49 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/66860275/5be05906-5a8b-484a-872f-aa448729adc9">

It was not there before and I now cannot edit the project structure in this way.

I have tried looking for similar issues online but with not much success: [example](https://stackoverflow.com/questions/70188304/unable-to-process-files-error-in-gradle-checkstyle)
Thanks in advance guys. I have spent my whole Wednesday on this and I have learned my hands are cursed :disappointed:

**Comment by damithc** [comment]
@kiwibang to minimize the possibility of cached Intellij settings, you can try these, one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by damithc** [comment]
Also, ensure you've followed our advisory for Mac users given [here](https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html#programming-language) and used the precise Java distribution we have prescribed.

**Comment by AlagappanRa** [comment]
@kiwibang 

> > Are you above to see the following? (java fxml file configs)
> > ![image](https://user-images.githubusercontent.com/96157054/269268404-fa1f1040-6880-4a52-b18b-8b86a018477f.png)
> > Under Project Structure > Project Settings >Modules > ip > (main) [or wherever you main code directory is]
> 
> <img alt="Screenshot 2023-09-20 at 9 00 04 PM" width="843" src="https://user-images.githubusercontent.com/66860275/269290750-5ed832c0-c3da-4f21-a072-45de761042cd.png">
> ^The above is mine. Seems like that might be the issue since it looks like there are only distributions for mac OS but not other OSes. However, my build.gradle file does not have what you have since I used the second method to do set up JavaFX. Adding your recommended dependencies breaks my checkstyle file. Thanks for the hint though!!

**Old dependencies that worked**
```java
org.openjfx:javafx-fxml:mac-aarch64:17:0:7 
org.openjfx:javafx-controls:mac-aarch64:17:0:7 
org.openjfx:javafx-base:mac-aarch64:17:0:7 
org.openjfx:javafx-graphics:mac-aarch64:17:0:7 
```

Could you try installing a mix of dependencies (keeping the OS distributions for Linux and Windows, but reverting the dependenices for Mac ARM64). I suspect the ARM64 dependency for Mac differs from the general Mac distribution.

```java
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    // JavaFX 17.0.7 dependencies for macOS on ARM64
    implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64' 

    // JavaFX 17.0.7 dependencies for Linux
    implementation 'org.openjfx:javafx-base:17.0.7:linux'
    implementation 'org.openjfx:javafx-controls:17.0.7:linux'
    implementation 'org.openjfx:javafx-fxml:17.0.7:linux'
    implementation 'org.openjfx:javafx-graphics:17.0.7:linux'

    // JavaFX 17.0.7 dependencies for Windows
    implementation 'org.openjfx:javafx-base:17.0.7:win'
    implementation 'org.openjfx:javafx-controls:17.0.7:win'
    implementation 'org.openjfx:javafx-fxml:17.0.7:win'
    implementation 'org.openjfx:javafx-graphics:17.0.7:win'
}
```

**Comment by damithc** [comment]
I tried (on Windows) several jar files from [here](https://nus-cs2103-ay2324s1.github.io/website/admin/ip-showcase.html) that seem like they were built on a Mac (based on the screenshot) and did not encounter this problem
So, it doesn't seem to be a problem affecting _all_ Mac users 🤔

**Comment by DeltonCheng** [comment]
> * Revert all traces of the second step by removing the JavaFX SDK and updating build.gradle to the first method
> * loaded gradle changes
> * ran: ./gradlew build
> * Managed to get the project structure to the state that @AlagappanRa described:

Hi @kiwibang, could you share more on how you managed to get the project structure?
I originally installed Java11 using sdkman, but have tried uninstalling and installing from Azul directly but to no avail.

I used the first method to set up JavaFX, but could only load up distributions for MacOs as well.

> Could you try installing a mix of dependencies (keeping the OS distributions for Linux and Windows, but reverting the dependenices for Mac ARM64). I suspect the ARM64 dependency for Mac differs from the general Mac distribution.

I have also tried this set of dependencies, but the project structure came up empty.
<img width="915" alt="Screenshot 2023-09-21 at 1 10 12 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/66375177/27c486c2-2eab-42b9-bef7-a187db95e3f7">

Since, I did not implement Checkstyle I am unable to help with your current issues :( 
Thanks a lot! Hopefully we can find a solution to this

**Comment by kiwibang** [comment]
> > * Revert all traces of the second step by removing the JavaFX SDK and updating build.gradle to the first method
> > * loaded gradle changes
> > * ran: ./gradlew build
> > * Managed to get the project structure to the state that @AlagappanRa described:
> 
> Hi @kiwibang, could you share more on how you managed to get the project structure? I originally installed Java11 using sdkman, but have tried uninstalling and installing from Azul directly but to no avail.
> 
> I used the first method to set up JavaFX, but could only load up distributions for MacOs as well.
> 
> > Could you try installing a mix of dependencies (keeping the OS distributions for Linux and Windows, but reverting the dependenices for Mac ARM64). I suspect the ARM64 dependency for Mac differs from the general Mac distribution.
> 
> I have also tried this set of dependencies, but the project structure came up empty. <img alt="Screenshot 2023-09-21 at 1 10 12 PM" width="915" src="https://user-images.githubusercontent.com/66375177/269525764-27c486c2-2eab-42b9-bef7-a187db95e3f7.png">
> 
> Since, I did not implement Checkstyle I am unable to help with your current issues :( Thanks a lot! Hopefully we can find a solution to this

Hi Delton, I think you can refer to the additions to the build.gradle file that @AlagappanRa mentioned [above](https://github.com/nus-cs2103-AY2324S1/forum/issues/159#issuecomment-1728708305). I have fixed several issues related to the somewhat emotionally motivated [post](https://github.com/nus-cs2103-AY2324S1/forum/issues/159#issuecomment-1728126734) that I had made regarding reverting back to the first version so I'll be sharing more about how I fixed it in the next post.

**Comment by kiwibang** [comment]
**Update: I have since fixed my checkstyle not working and have managed to get my ip up and running again :)**

_Disclaimer: I am not sure whether the solutions I present here to my problems apply to non-mac OSes_

> Could you try installing a mix of dependencies (keeping the OS distributions for Linux and Windows, but reverting the dependenices for Mac ARM64). I suspect the ARM64 dependency for Mac differs from the general Mac distribution.
> 
> ```java
> dependencies {
>     testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
>     testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
> 
>     // JavaFX 17.0.7 dependencies for macOS on ARM64
>     implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
>     implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
>     implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
>     implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64' 
> 
>     // JavaFX 17.0.7 dependencies for Linux
>     implementation 'org.openjfx:javafx-base:17.0.7:linux'
>     implementation 'org.openjfx:javafx-controls:17.0.7:linux'
>     implementation 'org.openjfx:javafx-fxml:17.0.7:linux'
>     implementation 'org.openjfx:javafx-graphics:17.0.7:linux'
> 
>     // JavaFX 17.0.7 dependencies for Windows
>     implementation 'org.openjfx:javafx-base:17.0.7:win'
>     implementation 'org.openjfx:javafx-controls:17.0.7:win'
>     implementation 'org.openjfx:javafx-fxml:17.0.7:win'
>     implementation 'org.openjfx:javafx-graphics:17.0.7:win'
> }
> ```

Adding this to my build.gradle has solved the issue below:
> Execution failed for task ':DukeLauncher.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

Thanks @AlagappanRa :)

As for the checkstyle breaking, it turns out that I did not delete the module-info.java file from my repo, which is required for the first method of installing but not the second. So if anyone is reverting to the first method of including JavaFX, you might want to follow the steps below for reverting to the first method:
- Remove any JavaFX SDKs that you might have installed for the second method(delete it from whereever that you might have placed the JavaFX SDK in when you first set up JavaFX)
- Remove these lines that you had to add for the second method from your `build.gradle` file:
```gradle
javafx {
    version = "17.0.7"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```
- Delete any module-info.java files(not needed for including JavaFX using the first method)
- Include these lines in your dependencies file(credits: @AlagappanRa):
```gradle
dependencies {
    // JavaFX 17.0.7 dependencies for macOS on ARM64
    implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64' 

    // JavaFX 17.0.7 dependencies for Linux
    implementation 'org.openjfx:javafx-base:17.0.7:linux'
    implementation 'org.openjfx:javafx-controls:17.0.7:linux'
    implementation 'org.openjfx:javafx-fxml:17.0.7:linux'
    implementation 'org.openjfx:javafx-graphics:17.0.7:linux'

    // JavaFX 17.0.7 dependencies for Windows
    implementation 'org.openjfx:javafx-base:17.0.7:win'
    implementation 'org.openjfx:javafx-controls:17.0.7:win'
    implementation 'org.openjfx:javafx-fxml:17.0.7:win'
    implementation 'org.openjfx:javafx-graphics:17.0.7:win'
}
```
- note: what the above lines do is to include distributions for other OSes(as described in the comments), so the resulting jar file generated will be cross-platform(I have yet to try it out on other OSes but I will keep everyone posted)
- Next, run `./gradlew build` in order to set up the project dependencies to include the required JavaFX components in your project
- Verify that the dependencies have been added by going to `File -> Project Structure -> Project Settings -> Modules -> Dependencies`. You should see the below:
<img width="898" alt="Screenshot 2023-09-21 at 5 06 38 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/66860275/35435a56-9352-4aea-9f29-9bc3a0f34108">
- Ensure your ip still works by running your ip as per usual
- Ensure that your checkstyle still works after making the above changes(if applicable)

**Comment by LinWanLeii** [comment]
Hi everyone after crying for 6 hours i solved my issue and am able to open on both windows and macs
`````
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    // JavaFX 17.0.7 dependencies for macOS on ARM64
    implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64'

    // JavaFX 17.0.7 dependencies for Linux
    implementation 'org.openjfx:javafx-base:17.0.7:linux'
    implementation 'org.openjfx:javafx-controls:17.0.7:linux'
    implementation 'org.openjfx:javafx-fxml:17.0.7:linux'
    implementation 'org.openjfx:javafx-graphics:17.0.7:linux'

    // JavaFX 17.0.7 dependencies for Windows
    implementation 'org.openjfx:javafx-base:17.0.7:win'
    implementation 'org.openjfx:javafx-controls:17.0.7:win'
    implementation 'org.openjfx:javafx-fxml:17.0.7:win'
    implementation 'org.openjfx:javafx-graphics:17.0.7:win'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.Launcher")
}

shadowJar {
    archiveFileName = 'CathyTheChattyCat.jar'
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}
```````

solution is to not use the checkstyle by gradle but instead use intelj checkstyle which you can view on week 4 checkstyle assignment

**Comment by DeltonCheng** [comment]
Managed to get the jar file running on both windows and macOs by following the build.gradle [above](https://github.com/nus-cs2103-AY2324S1/forum/issues/159#issuecomment-1729226821) by @LinWanLeii.

Other than changing the dependencies in build.gradle, I also deleted a line from plugin:
```
    id 'org.openjfx.javafxplugin' version '0.0.13'
```
and the whole of javafx
```
javafx {
    version = "17.0.7"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```

Thanks everyone for the help!

**Comment by woojiahao** [comment]
I was digging through the official OpenJFX documentation to find a potential fix that continued using the (formerly) second method of importing JavaFX in Gradle:

![Screenshot 2023-09-22 at 09 48 38](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/52c6a140-9774-4cb6-adbf-34c001bd7f6e)

This is my `build.gradle` now. I've tested out the JAR on a Windows ARM build emulated on Mac M1 Pro machine:

```gradle
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'

    // Used for loops to clean up the imports
    def platforms = ["win", "linux", "mac"]
    def javafxDependency = ["javafx-graphics", "javafx-controls", "javafx-fxml"]

    for (plt in platforms) {
        for (dep in javafxDependency) {
            runtimeOnly "org.openjfx:$dep:$javafx.version:$plt"
        }
    }
}


// ...

javafx {
    version = '17.0.7'
    modules = ['javafx.base', 'javafx.controls', 'javafx.fxml', 'javafx.graphics']
}
```

Would be great if others could help perform a quick smoke test on native Windows machines. Perhaps this was the fix missing for the second method of setting up JavaFX:

|OS|Architecture|Works?|
|--|------------|------|
|MacOS|ARM (M1 Pro)| ✅ |
|Windows|ARM (Emulated)| ✅ |
|Windows|x86 (Native)| |

Note: I still have the Gradle checkstyle plugin

**Comment by kiwibang** [comment]
**Update: The jar file works on multiple platforms**

TL:DR - Ensure the following:
- Correct JDK version(especially for mac users)
- `build.gradle` for the javaFX components is configured correctly
- If reverting from the second version of setting up JavaFX to the first, ensure that all traces of the second method are deleted(e.g. the JavaFX JDK & `module-info.java`)
- JavaFX dependencies are present in the project structure

Last but not least, I would like to thank everyone for their help in helping me to resolve these issues!! :))
