### ISSUE TITLE
Level 0 naming requirements

### ISSUE THREAD

**Issue by Bryan-Goh** [nus-cs2103-AY2324S1/forum#16]
I misunderstood and forgot to change the file name from Duke.java to my own personal chatbot name therefore even though in the console it says its proper name the class and file name was still Duke will it affect my grade if i just change it at the level-5 commit onwards or do i need to update all the commits and change all of them one by one from level-0 commit and if so how do i do that?

**Comment by Bryan-Goh** [comment]
or do i just need to add the Level-0 tag to the commit that fixed it and remove the old tag?

**Comment by supermii2** [comment]
From website:

Q. How are the iP git tags used in grading?

A. Adding a git tag in the iP is a self-declaration that you think you are done with the iP increment. We take your word for it. We don't check the code to see if you have actually done the said increment. Therefore, it is just a mechanism for you to self-declare progress and for us to monitor those progress declarations.

So I think you can just change it at the Level-5 commit onwards

**Comment by damithc** [comment]
> So I think you can just change it at the Level-5 commit onwards

Yup. Just change the file name now and leave the old tag as it is. Thanks @supermii2 for your help.
