### ISSUE TITLE
iP Progress not showing jar release

### ISSUE THREAD

**Issue by cxo05** [nus-cs2103-AY2324S1/forum#160]
I have created a release with a jar file but it iP progress is not reflecting. 
https://github.com/cxo05/ip/releases/tag/A-Release

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/13196666/887f6c48-317f-4787-aa4f-cd5be1a2d666)

**Comment by rocketninja7** [comment]
From this link it seems your release cannot be seen: https://github.com/cxo05/ip/releases.
Maybe you might want to check how you published your releases?
For reference, this is the page that the course website refers to: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by rocketninja7** [comment]
From this link it seems your release cannot be seen: https://github.com/cxo05/ip/releases.
Maybe you might want to check how you published your releases?
For reference, this is the page that the course website refers to: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by cxo05** [comment]
Strange, https://github.com/cxo05/ip/releases/tag/A-Release works.

**Comment by damithc** [comment]
Good catch @rocketninja7 
@cxo05 if the release is still not reflected in the dashboard after the next dashboard update, let me know again.

**Comment by cxo05** [comment]
Turns out you need to tag with a version number
