### ISSUE TITLE
Cannot tp main file even though JDK is set to correct version

### ISSUE THREAD

**Issue by kiwibang** [nus-cs2103-AY2324S1/forum#161]
Remember to give sufficient details e.g.,
* OS: MacOS Ventura 13.5
* IDE: IntelliJ

Hi, I'm running the TP on the mac and cannot seem to get main to run 

Error generated:
```
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
```

What I have tried: 
- Deleting .idea and invalidating cache 
- Using the zulu ARM version of the JDK as per a previous issue(which still does not work)
- Changed the project structure

What I suspect is wrong:
<img width="1028" alt="Screenshot 2023-09-20 at 5 21 12 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/66860275/11d712c3-aee7-4209-aab0-81e416824b13">
I can't seem to apply changes due to `module tp is imported from gradle`
I have searched online to no avail 

Thanks in advance. I have been stuck on this for hours :(

**Comment by damithc** [comment]
@kiwibang is this solved now? For `application` and `shadowJar` sections of build.gradle, the following should be enough.

```
...

application {
    mainClass = 'com.nyanbot.dukeguicontrollers.DukeLauncher'
}

shadowJar {
    archiveFileName = 'nyan.jar'
}
```

* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by kiwibang** [comment]
Hi prof,
Editing my build.gradle file seemed to have did the trick. 
In case anyone is facing the same issue, refer to issue #159 
Thanks for the help everyone!!
