### ISSUE TITLE
iP Dashboard show that I didn't push any commits in week 4 but all increments are done

### ISSUE THREAD

**Issue by seewhyjay** [nus-cs2103-AY2324S1/forum#162]
The dashboard shows that I didn't make any commits in week 4, but all my increments for the week are done.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/57669931/403412b1-571a-47b1-a2c5-1721a48e220c)

Looking through the grading rubrics:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/57669931/b7911403-7064-4ce2-b67a-2710e3b4e15d)

It seems like as long as I have submitted some of the deliverables for this week I should be good as I'll hit the `at least 4 iP weeks` requirement for both, but am I understanding that right?

Would backdating a git commit to within week 4 fix this issue as well?

**Comment by damithc** [comment]
> It seems like as long as I have submitted some of the deliverables for this week I should be good as I'll hit the `at least 4 iP weeks` requirement for both, but am I understanding that right?

@seewhyjay Yes, not having any commits in week 4 will not affect your iP grade.

**Comment by seewhyjay** [comment]
Thank you!
