### ISSUE TITLE
Error while opening Jar files (request for people on mac to try opening my file, or to otherwise help debug the error)

### ISSUE THREAD

**Issue by RSXIX** [nus-cs2103-AY2324S1/forum#164]
So I had a friend open my jar on mac but they got a weird error. I'm attaching the Jar file as well as the error they got. I'm not sure if it's just them or got issue with the file. I am on Java 11.

https://imgur.com/a/ewhrPmB

https://github.com/RSXIX/ip/releases/tag/A-Release

**Comment by RSXIX** [comment]
It has worked for several friends who use window (as well as on my pc), but none who use mac (excluding my own macbook)

**Comment by EricXiong420** [comment]
Hi, I've tested out the jar and it works on mac! Just that since it's from an unidentified developer, they would need to Ctrl+click the file and select open in order to be able to open it.

**Comment by suryanshkushwaha** [comment]
Hi, upon testing it out as @EricXiong420 mentioned. It works fine for me too!

**Comment by damithc** [comment]
Anybody testing this on a Mac, be sure to test is using the precise JDK version we have prescribed [here](https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html#programming-language:~:text=%5BIMPORTANT%5D%20Advisory%20for%20%20Mac%20users). You can run the `java -version` command first to ensure you are using the correct JDK version.

e.g.,
```
$ java -version

$ java -jar JAR_NAME.jar
```
