### ISSUE TITLE
Compatibility Issue Running JAR File on Different Platforms

### ISSUE THREAD

**Issue by tiongjjyi** [nus-cs2103-AY2324S1/forum#165]
Hello everyone, 

I recently completed iP and successfully generated a JAR file that works fine on my MacBook, as well as some of my friend's MacBook. However, I've encountered a compatibility issue when another friend of mine, who also uses a MacBook, tried to run the same JAR file. Additionally, a friend using a Window laptop seems to be facing an incompatible environment issue too.

### **Error screenshot (on MacBook)**
<img width="856" alt="Screenshot 2023-09-21 at 2 35 43 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122203113/66a13517-f54d-4449-ac2b-84a89f043128">

### **Error screenshots (on Windows)**
![Screenshot 2023-09-21 at 2 40 12 AM](https://github.com/nus-cs2103-AY2324S1/forum/assets/122203113/8e7c376a-3628-444b-94ea-38c95a3bc1df)
and also 
![Screenshot 2023-09-21 at 2 40 51 AM](https://github.com/nus-cs2103-AY2324S1/forum/assets/122203113/742e76ab-cb2f-4190-a28f-7f48e354aafd)

### **Request for help:**
I am seeking assistance to understand why this compatibility issue is occurring. If you're willing to help to test my jar file, please access it [here](https://github.com/tiongjjyi/ip/releases/tag/A-Release).

Thank you!

**Comment by AlagappanRa** [comment]
Yes yes, the linkage error is caused by Java Fx dependencies. A couple of people who used Java Fx on Mac have faced the same problem regarding the jar file distribution. Hopefully we can find a solution to this. You can also refer to other threads for updates and try out the solutions recommended by Prof to see if it works for you @ https://github.com/nus-cs2103-AY2324S1/forum/issues/159

**Comment by RiyaMehta2211** [comment]
My jar file (made on Mac) also yielded linkage errors for Windows. My issue was resolved when I ran java --version on the terminal. Turns out, I was using OpenJDK version 20, and had to downgrade to 11 by manually deleting the other OpenJDK files of the other versions.
