### ISSUE TITLE
Which syntax should I follow?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#166]
My concern lies on the space where my cursor is pointing at:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/d2c2802a-8483-4b3f-96cc-35d3bd7615ba)

The checkstyle says that I must not have any white spaces after this asterisk, but the coding standard says that there must be a space after every '*'

Which syntax should I follow? Thanks in advance

**Comment by damithc** [comment]
@JasonRay168  The 'whitespace after *' rule applies only if there is some further content in that line.

**Comment by JasonRay168** [comment]
Thanks Prof!
