### ISSUE TITLE
Unsupported JavaFX configuration: classes were loaded from 'unnamed module @XXXXXXXX'

### ISSUE THREAD

**Issue by larrywang0701** [nus-cs2103-AY2324S1/forum#171]
Hello professor and classmates

When my iP program starts to run (both in IDEA and running the fat jar with `java -jar` command), the GUI window currectly pops out, but also leaving a warning message in the console
`Unsupported JavaFX configuration: classes were loaded from 'unnamed module @xxxxxxxx'`
(where xxxxxxxx is some random hexadecimal numbers, seems like some kind of object address)
Since it seems that this warning doesn't affect anything in my iP (everything works well except the warning itself), should I just submit the final version of my iP ignoring this warning, or should I fix that before submission? If I need to fix this warning, what should I do? 
(I confirm that JavaFX is inside my fat jar since when I unzip my jar file I see all javafx files inside)
Since the deadline for final iP submission is approaching, if this warning won't affect grading or any other thing, I may just ignore it  and save more time for checking and finalizing other things in iP.
Thanks!

**Comment by LinWanLeii** [comment]
try using this, first use checkstyle on i intelj instead of gradle, it can be done in 5 mins follow the week 4 project 
next change your dependancies to this 
``````
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    // JavaFX 17.0.7 dependencies for macOS on ARM64
    implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64'

    // JavaFX 17.0.7 dependencies for Linux
    implementation 'org.openjfx:javafx-base:17.0.7:linux'
    implementation 'org.openjfx:javafx-controls:17.0.7:linux'
    implementation 'org.openjfx:javafx-fxml:17.0.7:linux'
    implementation 'org.openjfx:javafx-graphics:17.0.7:linux'

    // JavaFX 17.0.7 dependencies for Windows
    implementation 'org.openjfx:javafx-base:17.0.7:win'
    implementation 'org.openjfx:javafx-controls:17.0.7:win'
    implementation 'org.openjfx:javafx-fxml:17.0.7:win'
    implementation 'org.openjfx:javafx-graphics:17.0.7:win'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.Launcher")
}

shadowJar {
    archiveFileName = 'CathyTheChattyCat.jar'
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}
`

**Comment by damithc** [comment]
> When my iP program starts to run (both in IDEA and running the fat jar with `java -jar` command), the GUI window currectly pops out, but also leaving a warning message in the console
> `Unsupported JavaFX configuration: classes were loaded from 'unnamed module @xxxxxxxx'`
> (where xxxxxxxx is some random hexadecimal numbers, seems like some kind of object address)
> Since it seems that this warning doesn't affect anything in my iP (everything works well except the warning itself), should I just submit the final version of my iP ignoring this warning, or should I fix that before submission? If I need to fix this warning, what should I do?

@larrywang0701  Sorry, I missed this earlier. This warning can be ignored.
