### ISSUE TITLE
[Smoke Test] Requesting help testing on non-Windows machine

### ISSUE THREAD

**Issue by Cloud7050** [nus-cs2103-AY2324S1/forum#172]
Hey everyone, I just finished my IP and put up a release. I would appreciate help with smoke testing, especially on a non-Windows machine. Thanks!

My release can be found [here](https://github.com/Cloud7050/ip/releases/tag/A-Release).

![](https://github.com/Cloud7050/ip/raw/A-Release/docs/Ui.png)

**Comment by jylow** [comment]
Sep 22, 2023 12:37:01 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 20.0.1 by JavaFX runtime of version 19.0.3. 

I got this error in my console but otherwise it works fine!

Btw i use a macbook with silicon

**Comment by tiif** [comment]
Operating system: Ubuntu 22.04.3 LTS
It successfully run all commands, but with the error message in terminal:
```
Sep 22, 2023 3:36:07 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 20.0.1 by JavaFX runtime of version 17.0.7
```
Also, I am not really sure the first line ``o/`` is intended behavior or a bug:

![Screenshot from 2023-09-22 15-36-35](https://github.com/nus-cs2103-AY2324S1/forum/assets/55319043/b37cf1bb-b38c-4323-ace5-e1b4beb57737)

**Comment by Cloud7050** [comment]
Thank you @jylow @tiif!

About the JavaFX warning, I get it too. My SceneBuilder app seems to save FXMLs in V20.0.1 even if I manually change the version in the raw file and reload. For me, my warning says my JavaFX runtime is `17-internal`. I hope it will be fine. I [searched it up a bit](https://stackoverflow.com/a/65991076/11536796), so maybe I can look into that for the TP.

> I am not really sure the first line `o/` is intended behavior or a bug:

Haha it's meant to be a wave. It's used in some internet communities.
