### ISSUE TITLE
iP page is down when trying to update the UG document (README.md)

### ISSUE THREAD

**Issue by longnguyentan** [nus-cs2103-AY2324S1/forum#174]
I have tried to update my UG after publishing it. The deployment is said to be successful, however, my iP page still does not exist (https://longnguyentan.github.io/ip/).
I tried to unpublish the site and re-do it again, but there was no change.

**Set-up**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/66206654/270ae96a-f504-4354-958f-5da8e3895528)

**Deployment log**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/66206654/1f5dec3d-0b92-4e63-9574-ebd89d1880a2)

**Comment by Elijah5399** [comment]
Hi, you may wish to try some of the solutions here: https://stackoverflow.com/questions/20895543/my-new-github-page-isnt-showing-up

**Comment by damithc** [comment]
@longnguyentan Looks like it's working now
