### ISSUE TITLE
Is FXML use required for full marks for the iP?

### ISSUE THREAD

**Issue by supermii2** [nus-cs2103-AY2324S1/forum#175]
Sorry if this is a last minute question, but I realised I did not use FXML as I found it more intuitive to add different UI elements with JavaFX on its own. I was wondering if this would get me penalised under making a GUI at least as good as the original.

**Comment by damithc** [comment]
@supermii2 use of FXML is not mandatory. So, no penalty for not using FXML.

**Comment by supermii2** [comment]
Thank you!
