### ISSUE TITLE
Requesting for help for smoke test (for non-Mac users)

### ISSUE THREAD

**Issue by inezkok** [nus-cs2103-AY2324S1/forum#176]
Hey everyone, I just finished my IP and put up a release. I would appreciate help with smoke testing, especially on a non-Mac machine. Thanks!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/74bef6ba-3d29-4e99-be7c-b235af82ac16)

**Comment by tiif** [comment]
Operating system: ``Ubuntu 22.04.3 LTS``
Java version: ``openjdk 11.0.20.1``
Command used: ``java -jar duke.jar``

It does not load, and the error message shown is:
```
Error: JavaFX runtime components are missing, and are required to run this application
```
Possible error: Maybe the jar file is not fat jar file?

**Comment by inezkok** [comment]
> Operating system: `Ubuntu 22.04.3 LTS` Java version: `openjdk 11.0.20.1` Command used: `java -jar duke.jar`
> 
> It does not load, and the error message shown is:
> 
> ```
> Error: JavaFX runtime components are missing, and are required to run this application
> ```
> 
> Possible error: Maybe the jar file is not fat jar file?

Hi @tiif ! I changed my build.gradle file and re-realised a new jar file, could you maybe help to try running it again? Thank you :)

`build.gradle` before:
```
application {
    mainClass.set("duke.Main")
}
```

`build.gradle` after:
```
application {
    mainClass.set("duke.Launcher")
}
```

**Comment by tiif** [comment]
> > Operating system: `Ubuntu 22.04.3 LTS` Java version: `openjdk 11.0.20.1` Command used: `java -jar duke.jar`
> > It does not load, and the error message shown is:
> > ```
> > Error: JavaFX runtime components are missing, and are required to run this application
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Possible error: Maybe the jar file is not fat jar file?
> 
> Hi @tiif ! I changed my build.gradle file and re-realised a new jar file, could you maybe help to try running it again? Thank you :)
> 
> `build.gradle` before:
> 
> ```
> application {
>     mainClass.set("duke.Main")
> }
> ```
> 
> `build.gradle` after:
> 
> ```
> application {
>     mainClass.set("duke.Launcher")
> }
> ```

Yes it works now.
