### ISSUE TITLE
Smoke test request on Mac

### ISSUE THREAD

**Issue by tiif** [nus-cs2103-AY2324S1/forum#177]
Hi, I would like to request anyone who uses Mac to help running a smoke test on my program. The release can be found here: https://github.com/tiif/ip/releases/tag/v0.2

Command list and expected response: https://github.com/tiif/ip/tree/master/docs#usage

Thank you in advance!

**Comment by Tim-Siu** [comment]
It works on my Mac (m1 pro).

**Comment by tiif** [comment]
Nice, thank you!

**Comment by inezkok** [comment]
Hi, the GUI opens fine. However, I noticed that there are some errors when working on it?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/75be39e4-d4ac-47bb-9161-1fcdd4287441)

The commands don't seem to work and there isn't a greeting message (not sure if it's just my computer's problem)

Also my Mac has an m2 chip

**Comment by Tim-Siu** [comment]
> Hi, the GUI opens fine. However, I noticed that there are some errors when working on it?
> 
> ![image](https://user-images.githubusercontent.com/117144224/269901176-75be39e4-d4ac-47bb-9161-1fcdd4287441.png)
> 
> The commands don't seem to work and there isn't a greeting message (not sure if it's just my computer's problem)
> 
> Also my Mac has an m2 chip

She is using ls as the command for list

**Comment by inezkok** [comment]
> > Hi, the GUI opens fine. However, I noticed that there are some errors when working on it?
> > ![image](https://user-images.githubusercontent.com/117144224/269901176-75be39e4-d4ac-47bb-9161-1fcdd4287441.png)
> > The commands don't seem to work and there isn't a greeting message (not sure if it's just my computer's problem)
> > Also my Mac has an m2 chip
> 
> She is using ls as the command for list

Oh sorry my bad, I tried again according to her user guide and yup it works fine :)
