### ISSUE TITLE
[Smoke Test] Requesting help testing on non-Mac machine

### ISSUE THREAD

**Issue by Tim-Siu** [nus-cs2103-AY2324S1/forum#178]
Hello everyone!

I'm seeking volunteers to help me conduct a smoke test on my ip release which is currently available on GitHub. While I've tested on a Mac, I'm particularly interested in how it performs on non-Mac machines.

### **Details**
- **Repository:** Tim-Siu/ip
- **Release:** [A-Release](https://github.com/Tim-Siu/ip/releases/tag/A-Release)

Any and all feedback is greatly appreciated!

**Comment by tiif** [comment]
Operating system: ``Ubuntu 22.04.3 LTS``
Java version: ``openjdk 11.0.20.1``

Yes it works.

**Comment by Tim-Siu** [comment]
> Operating system: `Ubuntu 22.04.3 LTS` Java version: `openjdk 11.0.20.1`
> 
> Yes it works.

Thanks!

**Comment by jacobcuison** [comment]
Hi, your app works on my Windows 10 laptop! Nice GUI :)

**Comment by Tim-Siu** [comment]
> Hi, your app works on my Windows 10 laptop! Nice GUI :)

Thank you!
