### ISSUE TITLE
User guide is not rendered properly in the link

### ISSUE THREAD

**Issue by aliciamichellew** [nus-cs2103-AY2324S1/forum#179]
Hi I'm facing the issue on how my user guide is not properly rendered in the website but it can render correctly in the github page. 
For your reference here is my link: https://aliciamichellew.github.io/ip/

An example of the difference is: 
<img width="772" alt="Screenshot 2023-09-22 at 17 20 57" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/93108253/73bf0546-5105-4306-9ddc-ea1779d02502">
This is how it looks like in github and how it should look like in the website. 
However, when I go to the website, it shows like this: 
<img width="1260" alt="Screenshot 2023-09-22 at 17 21 45" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/93108253/3bcfb0e7-2650-4d91-900a-8dfbcc2b3f60">
I have tried deploying it again, but it still shows the wrong thing. 
Anyone face this issue before?

**Comment by woojiahao** [comment]
How are you deploying the website? On Jekyll?

**Comment by aliciamichellew** [comment]
> How are you deploying the website? On Jekyll?

I am referring to this https://aliciamichellew.github.io/ip/  website. I tried to run the deployment again using this. 
<img width="1728" alt="Screenshot 2023-09-22 at 17 31 05" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/93108253/19e0b2ae-63f1-4d11-ac35-4c7f74418458">

**Comment by damithc** [comment]
@aliciamichellew Markdown requires a blank line before the table contents. So, ensure there is a blank line separating the table and the content just above it.
