### ISSUE TITLE
Follow-up on A-TextUIesting error when creating multiple Scanners

### ISSUE THREAD

**Issue by antonTan96** [nus-cs2103-AY2324S1/forum#18]
regarding the issue mentioned in [https://github.com/nus-cs2103-AY2324S1/forum/issues/6](url) , the following error rises when a "new" Scanner is created during a while loop that doesn't terminate until "bye" is detected:
```
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1656)
        at Cracker.startService(Cracker.java:15)
        at Cracker.main(Cracker.java:67)
 
```
Why does this arise when manually entering the input does not throw any exceptions?
My hypothesis is that System.in throws the .txt file into the scanner and when a new Scanner is created, the txt file is somehow cleared.

**Comment by KamJiaYue** [comment]
why create multiple scanners?

**Comment by antonTan96** [comment]
Do we need to create multiple scanners? absolutely not. I'm just curious why creating more scanners will cause problems during automated testing.

**Comment by woojiahao** [comment]
It's likely something to do with redirection relying on a single `System.in`: https://stackoverflow.com/questions/27286690/in-java-is-it-possible-to-re-open-system-in-after-closing-it

When reading input from the redirected file, the first Scanner closes `System.in` and so resulting uses of `System.in` will fail. This doesn't occur in manual input since `System.in` is available for each new line you enter

**Comment by woojiahao** [comment]
For the sake of easy replication, you can simulate this on a much smaller scale:

`Test.java`
```java
import java.util.Scanner;

public class Test {
  public static void main(String[] args) {
    while (true) {
      Scanner sc = new Scanner(System.in);
      String input;
      input = sc.nextLine();
      System.out.println(input);
      if (input.equals("bye")) {
        break;
      }
    }

    System.out.println("Outside");
  }
}
```

`input.txt`
```text
hi
bye
```

**Comment by antonTan96** [comment]
So what you're trying to say is that during automated testing the First scanner will close System.in for some reason when creating a new scanner? That's quite weird.

**Comment by woojiahao** [comment]
That's my guess, further investigation would require setting breakpoints within the Java standard library to assert if this is the case

**Comment by antonTan96** [comment]
Got it. Thanks!

**Comment by damithc** [comment]
> So what you're trying to say is that during automated testing the First scanner will close System.in for some reason when creating a new scanner? That's quite weird.

Also keep in mind that when using manually, the `System.in` is mapped to the keyboard input while when using I/O redirection for testing, the `System.in` is coming from a text file.
