### ISSUE TITLE
Smoke Test request for non-Mac machine

### ISSUE THREAD

**Issue by MadLamprey** [nus-cs2103-AY2324S1/forum#180]
Could anyone run this on a non-Mac machine?

The ```jar``` file can be found [here](https://github.com/MadLamprey/ip/releases/tag/A-Release)

**Comment by jacobcuison** [comment]
I'm able to open and run it on my Windows 10 laptop!

**Comment by kimshitong** [comment]
Looks Good from Window 10 as well. 

Free to Go. Great UI btw haha

**Comment by MadLamprey** [comment]
Thank you!!!

**Comment by Cloud7050** [comment]
Works for me on my Windows 11 machine.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/44526554/c96f7320-f678-4575-8ca9-23182cd5f3aa)

Just a minor thing I noticed. The text may overflow the bubble, and it's also possible to scroll to the right using <kbd>Shift</kbd> + Scroll Wheel, meaning the real width is longer than it appears.
