### ISSUE TITLE
[MarkBind] Cannot find the "switch-docs-to-markbind" branch

### ISSUE THREAD

**Issue by JizhuoChen** [nus-cs2103-AY2324S1/forum#181]
One of the TP instructions given to set up project website was to "merge the given switch-docs-to-markbind branch to the master branch". But I could not find the "switch-docs-to-markbind" branch. Does anyone know?

**Comment by damithc** [comment]
@JizhuoChen It's possible that when you forked the repo, you only copied the master branch. In that case, you can get the missing branch from the upstream repo https://github.com/nus-cs2103-AY2324S1/tp

You can find instructions for getting an upstream branch in [Week 3 iP instructions](https://nus-cs2103-ay2324s1.github.io/website/admin/ip-w3.html#:~:text=do%20using%20Gradle.-,If%20your%20fork%20doesn%27t%20have%20the,-add%2Dgradle%2Dsupport)
