### ISSUE TITLE
Smoke Test request on Mac

### ISSUE THREAD

**Issue by aexolate** [nus-cs2103-AY2324S1/forum#182]
I would really appreciate if someone using mac can help me test my application to see if it can run. I had some issues with javafx and hope this release has fixed it. Thank you!

https://github.com/aexolate/ip/releases/download/v0.2/carbonbot.jar

**Comment by inezkok** [comment]
It works fine! I'm using a m2 mac

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/e2f40c24-bb54-43bc-9e35-f3238d97f481)

**Comment by aexolate** [comment]
Thank you so much!
