### ISSUE TITLE
Smoke Test - Mac User Help me Pleaseee <3 

### ISSUE THREAD

**Issue by kimshitong** [nus-cs2103-AY2324S1/forum#184]
Hey Peers! I am looking for assistance from anyone whos using Mac to do Smoke Test.

https://github.com/kimshitong/ip/releases/tag/A-Release

I am more than happy to help you on doing Smoke Test if needed :)

Thanks,
Shi Tong

**Comment by wr1159** [comment]
Works well for me on M1 Pro Macbook 👍 
<img width="401" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/56021409/b775fe2a-8bcd-4954-8892-6a503942400c">
