### ISSUE TITLE
Can run jar file on own device, Others cant seem to run it.

### ISSUE THREAD

**Issue by Nid21cs** [nus-cs2103-AY2324S1/forum#185]
I have the jar file which works on my own device but doesn't seem to work when i send it to my friends. They get an error saying 

Error: LinkageError occurred while loading main class duke.Launcher
 java.lang.UnsupportedClassVersionError: duke/Launcher has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
gopi@Baskars-MacBook-Pro ~ %

I searched online and found that the error is caused by an incorrect version of java. Upon checking, my project structure was set to java 13 which i changed to java 11 and remade the jar file using gradle after running ./gradlew clean shadowJar. But my friend still encounters the same error  

Heres a link to my release with the jar file as well.
https://github.com/Nid21cs/ip/releases/tag/A-Release

Any help is greatly appreciated

**Comment by woojiahao** [comment]
If your friend is getting this error, it means that their Java version is behind. Ask them to check via `java -version` and see if it matches your machine's (major) version, i.e. Java 11

**Comment by Nid21cs** [comment]
> If your friend is getting this error, it means that their Java version is behind. Ask them to check via `java -version` and see if it matches your machine's (major) version, i.e. Java 11

I ran java -version on his computer and it does say 11

**Comment by woojiahao** [comment]
<img width="90" alt="Screenshot 2023-09-22 at 20 23 05" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/7c1db09f-f43b-4876-aaf0-e8e1bc437344">

The JAR file is still on Java version 13. I just tested it on my machine too. Could you try re-building the JAR via Intellij's Gradle task manager instead? I have a feeling your terminal's Java version is still 13 so even when you ran `./gradlew shadowJar`, it was still using Java 13, not 11 as per your project

**Comment by Nid21cs** [comment]
> <img alt="Screenshot 2023-09-22 at 20 23 05" width="90" src="https://user-images.githubusercontent.com/29497029/269935175-7c1db09f-f43b-4876-aaf0-e8e1bc437344.png">
> The JAR file is still on Java version 13. I just tested it on my machine too. Could you try re-building the JAR via Intellij's Gradle task manager instead? I have a feeling your terminal's Java version is still 13 so even when you ran `./gradlew shadowJar`, it was still using Java 13, not 11 as per your project

Thank you very much for replying i changed my java version to version 11 and now it doesnt give that error anymore
