### ISSUE TITLE
[Smoke Test] Requesting help to test on non-Macos machine

### ISSUE THREAD

**Issue by jibtaf** [nus-cs2103-AY2324S1/forum#186]
Hi friends, I just put up a release for my ip. Really appreciate help with smoke test on non-Macos machine. Thanks in advance!

My release is [here](https://github.com/jibtaf/ip/releases/tag/v0.2).

<img width="401" alt="Ui" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122149501/9a03ecda-8dc2-4c10-9c1c-2204ba57236e">

**Comment by marcellaantania** [comment]
I tried running your jar file using windows and ubuntu and it does not run unfortunately. Double clicking does not run anything, and running using the terminal gives the following error.

![photo1695389451](https://github.com/nus-cs2103-AY2324S1/forum/assets/104759709/a1ccd03d-9086-4e02-be5e-53fc3d262358) 

Not sure how to fix it, maybe check the build.gradle dependencies?

**Comment by jibtaf** [comment]
> I tried running your jar file using windows and ubuntu and it does not run unfortunately. Double clicking does not run anything, and running using the terminal gives the following error.
> 
> ![photo1695389451](https://user-images.githubusercontent.com/104759709/269953084-a1ccd03d-9086-4e02-be5e-53fc3d262358.jpeg)
> 
> Not sure how to fix it, maybe check the build.gradle dependencies?

Thank you so much! I will look into it.
