### ISSUE TITLE
When run on mac throws this error for javafx

### ISSUE THREAD

**Issue by newway1814** [nus-cs2103-AY2324S1/forum#187]
jar file not running on mac showing this error, when run any suggestions? (It works on some macs when you double click it but not command line in some other) 

File Works on Mac with M1 or M2 but does not work with Mac intel
![photo1695387406](https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/5ea4b5ab-be27-4d78-9f17-b91f63fcf594)

**Comment by damithc** [comment]
@newway1814 a shot in the dark (I'm not a Mac user) but you can try including both variants of mac dependencies in build.gradle

```
    implementation 'org.openjfx:javafx-base:17.0.7:mac'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac'

    implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64'
```

**Comment by newway1814** [comment]
Hi prof, it works well with mac intel but now on M1 or M2 it shows this ![photo1695394640](https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/411b00b4-724c-4f6a-98d3-22944a50dca9)

**Comment by damithc** [comment]
@newway1814 This is a different problem. It appears you used Java 19 (i.e., version 63) to compile the JAR file this time.

**Comment by newway1814** [comment]
Hi prof, I made sure that SDK is set to 11, and then same issue came as before.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/ac3e44f7-574e-44a3-a9fb-d7808c10a5d8)

**Comment by damithc** [comment]
@newway1814 Your own computer (in which the JAR was created) a Mac? Which variant?
What do you see when you run `java -version` in your terminal that you used to run the `./gradlew shadowJar` command?

**Comment by newway1814** [comment]
Hi prof, I am on a windows machine, however when i do java -version it gave me 19 version, I tried deleting it and now when i run the same command it did not give any output. I have both sdk 11 and 19, I ensured that in intellij it is getting compiled with SDK 11, but now after deleting SDK 19, it is not showing me any output when I run java -version. I also checked Environment variables the SDK 11 path is there.

**Comment by damithc** [comment]
@newway1814 You might need to restart the terminal and try again.  Also try setting the JAVA_HOME environment variable to point to JDK 11.

**Comment by newway1814** [comment]
Hi Prof, my JAVA_HOME environment variable was pointing to jdk 11 already, I restarted my device however still it did not show anything.
<img width="419" alt="jdk11" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/38e45d44-9c49-42db-93c9-cd4c1de3a9e0">

**Comment by damithc** [comment]
@newway1814 You can also check the PATH variable and ensure it doesn't have any references to Java 19.
It's odd that there is no output to `java -version` command. Perhaps also try `java` or `javac` to see if you get any output?

**Comment by newway1814** [comment]
Checked prof my path variable does not hold any reference to 19, Moreover, when I do java and javac it still does not give me any output

**Comment by damithc** [comment]
> Checked prof my path variable does not hold any reference to 19, Moreover, when I do java and javac it still does not give me any output

Can give a screenshot of the terminal?

**Comment by newway1814** [comment]
Sure prof, please find attached the screenshot

<img width="572" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/a5ec69b3-cd16-4978-a82b-07b9b6dea281">

**Comment by damithc** [comment]
I see. Strange. Try this:

Go to system variables, edit the PATH variable, and, add the location of your JDK 11 java.exe. Move it to the top of the locations in that variable.
Open a normal MS DOS terminal (e.g., `Win + R`, type `cmd` and hit enter)
Run `java -version`.

**Comment by newway1814** [comment]
This is my current path now 
<img width="412" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/9f478773-49be-47ea-9130-2436890f9b93">

and after opening cmd it still gave me this
<img width="469" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/d02ba3ab-3ef4-45e8-bfe4-74ab703fd159">

**Comment by damithc** [comment]
@newway1814 `\java.exe` should not be in the path. Just up to `\bin` only. Remember to restart the terminal after changing env variables. Also, check the `PATH` variable under 'User variables' section (and update it if necessary). 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/c0e8b3b7-4f35-4fcf-9c70-ae812ad65bef)

**Comment by newway1814** [comment]
Yes Prof it worked!, Thank you so much, However, when I run  ./gradlew shadowJar, The jar file is showing this error on mac intel.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/ac3e44f7-574e-44a3-a9fb-d7808c10a5d8)

This is my build.gradle

```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    implementation 'org.openjfx:javafx-base:17.0.7:mac'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac'

    implementation 'org.openjfx:javafx-base:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-controls:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-fxml:17.0.7:mac-aarch64'
    implementation 'org.openjfx:javafx-graphics:17.0.7:mac-aarch64'

    implementation 'org.openjfx:javafx-base:17.0.7:linux'
    implementation 'org.openjfx:javafx-controls:17.0.7:linux'
    implementation 'org.openjfx:javafx-fxml:17.0.7:linux'
    implementation 'org.openjfx:javafx-graphics:17.0.7:linux'

    implementation 'org.openjfx:javafx-base:17.0.7:win'
    implementation 'org.openjfx:javafx-controls:17.0.7:win'
    implementation 'org.openjfx:javafx-fxml:17.0.7:win'
    implementation 'org.openjfx:javafx-graphics:17.0.7:win'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

jar {
    archiveBaseName = "duck"
    archiveClassifier = null
    archiveFileName = 'duck.jar'
}

application {
    mainClass.set("Launcher")
}

shadowJar {
    archiveBaseName = "duck"
    archiveClassifier = null
    archiveFileName = 'duck.jar'
}

run{
    standardInput = System.in
}
```

**Comment by damithc** [comment]
@newway1814 Start a new thread on this as this thread has a bunch of comments that are no longer relevant to the problem. Also push the latest version of the code to your fork and the current version of your jar file so that others can test it.
