### ISSUE TITLE
Github Pages build seems to fail

### ISSUE THREAD

**Issue by s-kybound** [nus-cs2103-AY2324S1/forum#189]
On generating github pages documentation, my README.md successfully builds, but deployment constantly fails. The error log is shown here:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/72686534/934ae117-ffcb-4874-9283-2dc14ed9d5f8)

It seems to be related to this issue [here](https://github.com/orgs/community/discussions/67961)

May I ask if anyone else is facing this issue at the moment?

**Comment by damithc** [comment]
@s-kybound If is it a GitHub issue, it's out of our hands. You can try again (i.e., rerun the GitHub action) a bit later.

**Comment by wr1159** [comment]
I get the same error right now. I have been running the workflow for the last hour or so.

**Comment by lamchenghou** [comment]
Same here, my issue was triggered by replacing the `Ui.png` image and pushing. No fix till now.

**Comment by aslam341** [comment]
I have the same issue.
Thing I have tried:

1. Tried to google my problem, but can't seem to find anyone facing this exact problem.
2. Manually re-running the workflow every few minutes.
3. Went to my other github project with a README.md file, tried to setup GitHub pages for that, following similar instructions from CS2103T website, and still got the same deploy failed issue as in the screenshot above.
4. Checked [GitHub status](https://www.githubstatus.com/), everything is normal, including pages.
5. Created an empty commit to trigger a rebuild as stated in a comment from [stackoverflow](https://stackoverflow.com/a/58358375).

Seeing that there are other students facing this issue as well, I am guessing it is a GitHub issue then.

**Comment by lamchenghou** [comment]
Yep I think other people in the GH community are facing the same issue as well: https://github.com/orgs/community/discussions/67961

**Comment by damithc** [comment]
GitHub folks have noticed the problem https://www.githubstatus.com/

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/ce39234e-0448-4247-b722-53078a1227de)

**Comment by damithc** [comment]
Seems to be fixed now ... https://www.githubstatus.com/

**Comment by aslam341** [comment]
Yup, it is fixed now. However, I had to manually re-run the pages-build-deployment workflow in the `Actions` tab. Seems like it does not automatically re-run it for you.
