### ISSUE TITLE
Will commits after Level-6 commit be marked?

### ISSUE THREAD

**Issue by kiwibang** [nus-cs2103-AY2324S1/forum#19]
Hey everyone! I decided to refactor my code after pushing the level-6 commit to Github. I was wondering whether it will be considered in marking(since it seems that the iP is autograded), or do I have to merge it with the level-6 commit instead? TIA!

**Comment by damithc** [comment]
@kiwibang It's fine to update code after adding a tag. More info in [this FAQ](https://nus-cs2103-ay2324s1.github.io/website/schedule/week2/project.html#:~:text=FAQ%20about%20iP%20increments)

**Comment by IsabelChong** [comment]
Hi there @kiwibang, just a senior dropping in with a friendly reminder to close this issue if it has been resolved 👍. 
Do keep the questions coming if you have any more doubts!
