### ISSUE TITLE
Github pages cannot be deployed

### ISSUE THREAD

**Issue by aslam341** [nus-cs2103-AY2324S1/forum#190]
Hi, I was able to publish my website for the iP the first time. My `Ui.png` screenshot even showed in the [iP showcase](https://nus-cs2103-ay2324s1.github.io/website/admin/ip-showcase.html). But, the website had some minor formatting issues, so I changed the `README.md` file and committed the changes. But, the website did not reflect the changes. Initially, I thought it was some website cache problem, so I deleted my cache and even tried opening in a different browser, still no changes. Therefore, I tried to force the change by unpublishing the website and trying to republish it. Searching online, I found that to republish the website, I had to go to the repo's `Actions` tab and rerun the `pages-build-deployment` workflow. However, every single time that I did, the deploy failed.

**Deployment**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65384645/a871f481-acd4-409c-94c8-b221287f4940)

Thing I have tried:

1. Tried to google my problem, but can't seem to find anyone facing this exact problem.
2. Manually re-running the workflow every few minutes.
3. Went to my other github project with a README.md file, tried to setup GitHub pages for that, following similar instructions from CS2103T website, and still got the same deploy failed issue as in the screenshot above.
4. Checked [GitHub status](https://www.githubstatus.com/), everything is normal, including pages.
5. Created an empty commit to trigger a rebuild as stated in a comment from [stackoverflow](https://stackoverflow.com/a/58358375).

Perhaps I should not have unpublished my website to try to republish it.
What can I do?

**Comment by aslam341** [comment]
I just saw that this issue was posted just now by another fellow student. Should I delete this? I did not see that issue beforehand.

**Comment by damithc** [comment]
@aslam341 you can close this issue.
