### ISSUE TITLE
Git convention Full Commit

### ISSUE THREAD

**Issue by Bryan-Goh** [nus-cs2103-AY2324S1/forum#192]
So I realised one of the two full commit's body violated one of the git convention where the char is above 72 and it said that i dont need to change past commits is that ok? like will it affect my grading and what do i need to do if it does

**Comment by damithc** [comment]
@Bryan-Goh No need to change past commits. It will not affect your grade.

**Comment by Bryan-Goh** [comment]
I also checked i made a minor typo in the commit message of one of the recent commits am i correct to say that also doesnt. affect my grade?

**Comment by damithc** [comment]
> I also checked i made a minor typo in the commit message of one of the recent commits am i correct to say that also doesnt. affect my grade?

@Bryan-Goh yes, it will not.
