### ISSUE TITLE
Deployment error in Github while uploading Ui.png

### ISSUE THREAD

**Issue by yyyaohhh** [nus-cs2103-AY2324S1/forum#193]
Hi, I tried uploading my `Ui.png` a few times yesterday but they all failed. May I know if there is a solution to this? Thanks!

<img width="975" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/da9fcefc-8610-4b7d-bd7a-eb6e1ba4c655">

**Comment by damithc** [comment]
@yyyaohhh see if #189 is relevant

**Comment by yyyaohhh** [comment]
Thanks the problem was solved today!
