### ISSUE TITLE
Smoke test request on Mac

### ISSUE THREAD

**Issue by anthonytamzil** [nus-cs2103-AY2324S1/forum#194]
Hi! I would like to request anyone who uses Mac to help running a smoke test on my program! The release can be found here: https://github.com/anthonytamzil/ip/releases/tag/A-Release

Thank you so much!

**Comment by LINCHENYU2030S** [comment]
When i run it on my mac terminal, i get the following error:
Error: LinkageError occurred while loading main class chatter.Launcher
	java.lang.UnsupportedClassVersionError: chatter/Launcher has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	
What is your java version?

**Comment by hyc17003** [comment]
I had the same error for my own JAR files, I think you can run java -version on your command terminal to see which version of java you're using, class file version 63.0 would be java 19 if I'm not wrong. You can try manually deleting the other versions of java and leaving only java 11, then make a new JAR file and see if it works.

**Comment by anthonytamzil** [comment]
Thank you so much! I changed my Java version to 11 and made a new JAR file. The linkage error seems to be gone. Thanks for advice!
