### ISSUE TITLE
TP project website choice of tool

### ISSUE THREAD

**Issue by Cloud7050** [nus-cs2103-AY2324S1/forum#195]
Hello, I was curious if we are allowed to use other tools for our TP project website other than the listed Jekyll and MarkBind.

**Comment by damithc** [comment]
@Cloud7050 what do you have in mind?
In theory, the tool shouldn't matter, but the two choices given are compatible with our grading scripts and submission requirements, but we can't guarantee the same for other tools.

**Comment by Cloud7050** [comment]
Thank you for the quick response. Our team doesn't really have a specific tool in mind at the moment, and I was just curious to know what our full options were. To avoid complications, I suppose we will stick with the two tools specified.

We seem impartial towards them both. Are there any recommendations for which tool to choose? Perhaps one has historically been more popular than the other among teams?

**Comment by damithc** [comment]
@Cloud7050 This is the first time we are introducing MarkBind as an option. So, no historical data.
But Jekyll is a globally popular tool (millions of users), while MarkBind is a home-grown product (i.e., made in NUS). So, if popularity is your criteria, you can go with Jekyll, which is also the default choice.

**Comment by Cloud7050** [comment]
Understood, thank you. We will discuss based on this information.
