### ISSUE TITLE
Tutorial 2 tP week 6

### ISSUE THREAD

**Issue by zhanyang01** [nus-cs2103-AY2324S1/forum#197]
I have followed the tp tutorial instructions but there is failed tests, may i ask how to go about it?
<img width="960" alt="Screenshot 2023-09-23 211321" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/92120a83-f25c-4258-b094-ed96cc187f2f">

**Comment by damithc** [comment]
@zhanyang01 perhaps you can share the link to your tutorial PR here so that others can see the exact code you have?

**Comment by zhanyang01** [comment]
The link is as below:
https://github.com/AY2324S1-CS2103-W14-1/tp/pull/12

**Comment by damithc** [comment]
@zhanyang01 While waiting for inputs from others, you might want to remove all those irrelevant changes from the PR e.g., .class files

**Comment by damithc** [comment]
> The link is as below:
> [AY2324S1-CS2103-W14-1/tp@master...zhanyang01:tp:tutorial-adding-command](https://github.com/AY2324S1-CS2103-W14-1/tp/compare/master...zhanyang01:tp:tutorial-adding-command)

I think you meant https://github.com/AY2324S1-CS2103-W14-1/tp/pull/12 ?

**Comment by zhanyang01** [comment]
Yes, but how do i remove irrelevant changes in a PR, isnt it fixed once i create a pull request?

**Comment by damithc** [comment]
@zhanyang01 The PR shows the difference between the master branch and the _latest_ state of your branch.

Previously, you added .class files (which is a mistake), committed, and pushed to the PR branch. Now, you need to remove those files, commit again, and push again to the same branch. The adding and removing will cancel off each other and the file will no longer visible in the PR.

**Comment by zhanyang01** [comment]
ya it been removed

**Comment by jedkohjk** [comment]
Hmm there is a sort of model solution [here](https://github.com/se-edu/addressbook-level3/compare/tutorial-add-remark), though it is slightly different in terms of some directories and file locations. Maybe you could check the diff between what you have and this?

**Comment by jedkohjk** [comment]
Also, gradle should generate a test report in build/reports/tests/test/index.html, which should show the values passed into the assertions. Perhaps you can refer to that too.

**Comment by zhanyang01** [comment]
ooh ok thanks will check it out
