### ISSUE TITLE
Can week 5 `Merge PR` ip task be done for different commits and branches instead

### ISSUE THREAD

**Issue by gohyongjing** [nus-cs2103-AY2324S1/forum#199]
[Asking on behalf of student, posting here so that everyone else benefits from the answer too]

The merging PR task was meant for parallel branches for the week 5 tasks. Due to a shortage of time (was trying to rush the iP before the proper deadline), I missed out on the merging PR task for week 5. However, I still did the PR merging task for my week 6 tasks (as practice and to fulfil the merging PR requirements).

May I ask if the iP grading for merging PR’s will be specifically based on if we did the parallel branches for week 5? Or is it just graded on the presence of merging PR’s in our repo?

**Comment by damithc** [comment]
@gohyongjing It should be fine. The important thing is the student learns how to do parallel PRs one way or the other. We don't check it specifically when grading.

**Comment by gohyongjing** [comment]
Thanks prof!
