### ISSUE TITLE
Permission to merge add-gradle-support branch into master branch

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#20]
Are we allowed to pull and merge the add-cradle-support branch into our master branch so that we can use gradle as a dependency management tool if we are planning to include third party libraries?

**Comment by damithc** [comment]
@yucongkoo It's among week 3 iP tasks, but you can go ahead and do it now if you wish to add a third party library right now (in which case you should first post here a separately a request to use the said library). Otherwise you can hold off a few more days until we have reached week 3.

**Comment by yucongkoo** [comment]
Okay noted. Thanks for clarifying.
