### ISSUE TITLE
Requesting mac users to help in smoke testing

### ISSUE THREAD

**Issue by newway1814** [nus-cs2103-AY2324S1/forum#200]
Requesting mac users to please test my jar file and see if it is working.

Here is the link to my jar file: https://github.com/newway1814/ip/releases/tag/A-Release

Thanks

**Comment by SungMatt** [comment]
Please upload your jar file to the release -- I can't see it!

**Comment by newway1814** [comment]
Done.

**Comment by WangCheng0116** [comment]
<img width="489" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/111694270/85f639af-a594-4828-a831-dfcacdd6fa61">
it works :)

**Comment by sp4ce-cowboy** [comment]
Works on my mac running OpenJDK 11.0.20.

<img width="612" alt="Screenshot 2023-09-24 at 12 36 50 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/ce43e8e1-29d9-463a-8cfe-74e9bd1142f3">

**Comment by damithc** [comment]
> Works on my mac running OpenJDK 11.0.20.

@sp4ce-cowboy Do use the exact JDK version we have prescribed for Mac users in https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html Otherwise you can run into serious problems at times, especially during the practical exam.

**Comment by newway1814** [comment]
> Works on my mac running OpenJDK 11.0.20.
> 
> <img alt="Screenshot 2023-09-24 at 12 36 50 AM" width="612" src="https://user-images.githubusercontent.com/19762596/270120426-ce43e8e1-29d9-463a-8cfe-74e9bd1142f3.png">

Hi thank you for testing may I check whether you have mac m1/m2 or intel?

**Comment by newway1814** [comment]
>  Works on my mac running OpenJDK 11.0.20.
> 
> <img alt="Screenshot 2023-09-24 at 12 36 50 AM" width="612" src="https://user-images.githubusercontent.com/19762596/270120426-ce43e8e1-29d9-463a-8cfe-74e9bd1142f3.png">

@sp4ce-cowboy Hi, thank you for testing may I ask if you are using mac intel or mac m1/m2?

**Comment by newway1814** [comment]
> <img alt="image" width="489" src="https://user-images.githubusercontent.com/111694270/270117941-85f639af-a594-4828-a831-dfcacdd6fa61.png"> it works :)
@WangCheng0116 Hi, thank you for testing may I ask if you are using mac intel or mac m1/m2?

**Comment by EmilyOng** [comment]
Hi @newway1814, I'm from your senior batch (dropping by in this forum to see if I can help you guys)

Tested on my Mac (Intel):

<details>
<summary>Screenshot</summary>

![Screenshot 2023-09-25 at 1 32 13 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/21200681/3bec111d-4e20-4cbe-8041-0fbb31a29594)
</details>

It generally works well! There is just one minor nit where the window does not scale well when resized.

<details>
<summary>Screenshot</summary>

![Screenshot 2023-09-25 at 1 33 25 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/21200681/b48fa909-bc6d-45ca-ac94-467bb2333ebb)
</details>

**Comment by melissaharijanto** [comment]
Hi @newway1814 I'm from a senior batch and a Mac Intel user. Your jar file runs well in my computer :)

<img width="499" alt="Screen Shot 2023-09-25 at 17 19 39" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/97304787/d3f69a68-a398-4024-87f7-6a4be8091c67">

like the previous commenter, I am also facing the same issue with resizing the window:

<img width="499" alt="Screen Shot 2023-09-25 at 17 20 26" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/97304787/2e7a933f-8cbf-4df7-9cdb-0f172f0a143f">

**Comment by sp4ce-cowboy** [comment]
@newway1814 I'm using a 2023 MacBook Pro with the M2 Pro chip running macOS Ventura 13.5

**Comment by newway1814** [comment]
@damithc Dear prof, My jar file works now thanks to you and all the testers, just had one query I have fixed the minor nit, Can I update my jar file?

**Comment by damithc** [comment]
> I have fixed the minor nit, Can I update my jar file?

Sure, @newway1814

**Comment by francisyzy** [comment]
Senior dropping in.

Tried the release you uploaded at `2023-09-25 7:58 PM GMT+8`

Works on my Intel Mac VM with `openjdk 11.0.20.1 2023-08-24 LTS`

<img width="706" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/24467184/37579695-7817-4daf-ae59-c772e9f5992d">

**Comment by muhammadreyaaz** [comment]
Hey senior here, using an Intel Mac 2017 pro. Works well!

<img width="1267" alt="Screenshot 2023-09-27 at 9 30 32 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/67105732/48b91edd-ef04-4cea-86a5-ca0afd96768e">
