### ISSUE TITLE
Error while running tP fork

### ISSUE THREAD

**Issue by RSXIX** [nus-cs2103-AY2324S1/forum#202]
So I have set up the tP fork and cloned it to my computer locally. I set up the SDK to Zulu 11 and have tried setting the Java Lang to both Java 11 and the SDK Default (not sure which they want again) and then assembled using gradle, but I am getting errors when I run the Main method. I had similar issues with running my iP tests.

Here's what happens:

<img width="722" alt="Screenshot 2023-09-23 at 10 28 05 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/29cdd6c0-d85a-4fe4-800e-8824da1d2d86">

**Comment by damithc** [comment]
@RSXIX perhaps share a screenshot of Intellij project settings page (i.e., the place where the project SDK is set)?

**Comment by RSXIX** [comment]
<img width="797" alt="Screenshot 2023-09-24 at 1 14 34 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/38df1aff-5f0f-4c2d-8be7-c45403edc2a3">
<img width="870" alt="Screenshot 2023-09-24 at 1 15 01 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/56417e3e-44b1-49b5-99b2-e68919b07a49">

Thanks Prof

**Comment by MadLamprey** [comment]
I am facing the same issue

**Comment by damithc** [comment]
> <img alt="Screenshot 2023-09-24 at 1 14 34 AM" width="797" src="https://user-images.githubusercontent.com/122437482/270130158-38df1aff-5f0f-4c2d-8be7-c45403edc2a3.png"> <img alt="Screenshot 2023-09-24 at 1 15 01 AM" width="870" src="https://user-images.githubusercontent.com/122437482/270130179-56417e3e-44b1-49b5-99b2-e68919b07a49.png">

@RSXIX As per screenshot, the project SDK does not seem to be the one we prescribed.

**Comment by RSXIX** [comment]
The prescribed SDK is Zulu 11 right? I have also tried with that

**Comment by damithc** [comment]
> The prescribed SDK is Zulu 11 right? I have also tried with that

@RSXIX Keep that selected at all times. 

Try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by damithc** [comment]
@RSXIX see if https://github.com/nus-cs2103-AY2324S1/forum/issues/225#issuecomment-1740247726 helps
