### ISSUE TITLE
Error loading image and launching program in jar file but runs locally

### ISSUE THREAD

**Issue by yuxunn** [nus-cs2103-AY2324S1/forum#203]
Development env: 
openjdk 11.0.19, OpenJDK Runtime Environment Zulu11, MacOS M1 Chip

My progam runs locally and launches the GUI fine, but the jar file doesnt seem to work, with the corresponding error message:
<img width="1129" alt="Screenshot 2023-09-24 at 4 05 39 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/108646986/3d5ebea3-f0e6-4b11-b8dd-9cb0d3e0d4dd">

I have confirmed that the file path to the images are correct. 

This is my build.gradle file.
<img width="656" alt="Screenshot 2023-09-24 at 4 08 08 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/108646986/d85b2fa9-96df-4096-b4d0-dffdb7cbf91d">
<img width="220" alt="Screenshot 2023-09-24 at 4 08 17 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/108646986/14be8dfb-1bca-48dc-ab96-028ee80d788f">

Thank you!

**Comment by lamchenghou** [comment]
I believe `duke.Main` should have a no parameter constructor defined.

**Comment by lamchenghou** [comment]
This section of fx docs might help: https://openjfx.io/javadoc/17/javafx.graphics/javafx/application/Application.html#launch(java.lang.Class,java.lang.String...)

**Comment by yuxunn** [comment]
Hello, I realised the problem was caused by this line:
<img width="820" alt="Screenshot 2023-09-24 at 11 36 40 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/108646986/963c5e67-534b-49d1-86f2-5c71dbb33d9f">

I forgot to capitalise the "i" in /Images/DaDuke.png and /images/DaUser.png and the jar file, when run, could not recognise the file path because it is case-sensitive. 

Thank you for taking the time to help me with this issue! :D
