### ISSUE TITLE
Request for help: Smoke testing 

### ISSUE THREAD

**Issue by joeng03** [nus-cs2103-AY2324S1/forum#204]
Previously, my linus.jar has failed the automated smoke test due to differences in Java version (19 and 11).

On Windows, using Java 11, for the linus.jar uploaded on 09-20-2023 (MM-DD-YYYY) at 20:56:29:
Error: LinkageError occurred while loading main class linus.Launcher java.lang.UnsupportedClassVersionError: linus/Launcher has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 55.0
On Linux, using Java 11, for the linus.jar uploaded on 09-20-2023 (MM-DD-YYYY) at 20:56:29:
Error: LinkageError occurred while loading main class linus.Launcher java.lang.UnsupportedClassVersionError: linus/Launcher has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 55.0
On Mac, using Java 11, for the linus.jar uploaded on 09-20-2023 (MM-DD-YYYY) at 20:56:29:
Error: LinkageError occurred while loading main class linus.Launcher java.lang.UnsupportedClassVersionError: linus/Launcher has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 55.0

After removing Java 19 and installing Java 11, I created a new linus.jar file that runs well on my machine(Windows). However, I am unsure if it really is compiled under Java 11, nor its compatibility with Linux and MacOS. Would really appreciate if anyone running Linux/MacOS could help me do a smoke test! 

[link to jar file](https://github.com/joeng03/ip/releases/tag/A-Release2)

**Comment by LicongHuang** [comment]
My java version:
```
java --version
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04, mixed mode, sharing)
```

Works in my Ubuntu machine.

**Comment by joeng03** [comment]
> My java version:
> 
> ```
> java --version
> openjdk 11.0.20.1 2023-08-24
> OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04)
> OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04, mixed mode, sharing)
> ```
> 
> Works in my Ubuntu machine.

Thanks, Licong!

**Comment by LicongHuang** [comment]
Sorry, I would like to make a correction, I did not realise during my testing, there was some issues with the file system. I got the `The file system experienced an unexpected error` in the application. 
![Screenshot from 2023-09-24 12-17-42](https://github.com/nus-cs2103-AY2324S1/forum/assets/29672264/402b1a93-6d52-494f-ad9c-1489e92d62f2)
Every other functionality works well though.

**Comment by HugeNoob** [comment]
Tested on macOS Ventura 13.5.
```
java --version
openjdk 11.0.20 2023-07-18 LTS
OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
```

<img width="396" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/7bdd27d9-9624-429d-9fbf-3d318d01371f">

Seems to run fine, but there's "The file system experienced an unexpected error." after most commands (tested help, list, todo, mark only).

**Comment by joeng03** [comment]
Sorry, I have forgotten to handle the case where the storage file does not exist yet. Here is the latest JAR file:
https://github.com/joeng03/ip/releases/tag/A-Release-v0.4

**Comment by HugeNoob** [comment]
Seems to work fine now.

<img width="498" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/cff1ef4e-7b3d-4ff9-8989-174151881d41">

**Comment by LicongHuang** [comment]
Also works fine in ubuntu

**Comment by joeng03** [comment]
Thank you guys for your help! I am closing this issue now
