### ISSUE TITLE
Requesting for help with Linux smoke test 

### ISSUE THREAD

**Issue by seanpzk** [nus-cs2103-AY2324S1/forum#205]
Hello, can anyone try to help me with my smoke test with Linux OS? I received an automated smoke test results for my first submission of duke.jar as shown in the image at the end.

What I have tried: 
- Dual booting with Ubuntu to test my original jar file that failed the automated smoke test. However, it seems to be able to run fine with Ubuntu 22.04.3 LTS. Java version: 
```
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```
- I tried the fix offered here in #173. Could any Linux users help me to test my latest jar file to see if it work on yours? Thank you!

My latest jar file: https://github.com/seanpzk/ip/releases/tag/A-Release

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122248828/07fcae12-98b6-4e69-bd8c-74848c08663d)

**Comment by francisyzy** [comment]
Hi, senior from your previous dropping by to help with smoke testing, it works on my Kali installation. Seems like it works! However `☹` doesn't want to render properly tho.

```bash
java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1, mixed mode, sharing)
```

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/24467184/e1dfee05-ea6b-4c92-8e67-df0a99e47bc3)

**Comment by jefrai** [comment]
Hi, also a senior here. The current jar works on Ubuntu 20.04.4 LTS + Java 11.0.18 as well; can confirm about `☹` rendering.

I'd assume the issue with the original jar was resolved by the fix, but if you wanted to be sure, you could also upload that original and see if anyone has an OS variant which it doesn't work on.

![](https://github.com/nus-cs2103-AY2324S1/forum/assets/30693850/216f6e08-fee8-472d-81b5-fcc164af9de5)

**Comment by seanfirefox** [comment]
Hi, another senior here, this jar file works on Arch Linux with the following environment, though it has the same issue of ☹ rendering as the others above. Perhaps you can attempt to search up the byte code of the emoji and create a string based on that. Not sure if it works though.
```
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
```

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/35872524/996ca564-6641-472c-8db7-62a6c5636118)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/35872524/8566eaaf-ac31-402d-bc6e-16dbe37433f7)

**Comment by muhammadreyaaz** [comment]
Hi yet another senior here, and in Linux's Ubuntu 22.04, it works as well!
![Screenshot from 2023-09-24 22-30-58](https://github.com/nus-cs2103-AY2324S1/forum/assets/67105732/fa915807-94a0-4e3d-80e2-9c40dc4db397)

It seems like the emoji rendering is common across different distros so far

**Comment by LicongHuang** [comment]
I believe the rendering problem stems from the difference of character set from linux distros and windows, not 100% sure about that though. My neovim set up displays weird icons as compared to the one in windows.

**Comment by RussellDash332** [comment]
Hi! Dropping by from the senior batch, here's what I found during testing your product using Ubuntu 18.04.5
```sh
russellsaerang@LAPTOP-EJR5EENU:~$ java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

russellsaerang@LAPTOP-EJR5EENU:~$ java -jar duke.jar
Sep 25, 2023 2:49:56 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3cbf1b4f'
There is no file found, likely to be first-time user.
Sep 25, 2023 2:49:56 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 20.0.1 by JavaFX runtime of version 17.0.7
```

Same as everyone else, it doesn't seem to render the emojis properly, which again might differ on different distros (not sure about Fedora or Arch 😄)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/63991775/38150b54-2470-4791-9f8f-a7d88646c19d)

While the JavaFX on my end seems to be an issue, the whole JAR is still able to run.  This is probably because I don't use the JDK that handles JavaFX well unlike Azul Zulu.

Overall, the functionalities seems to work as intended (aside from me messing around with wrong date formats). All the best on your further testing!

**Comment by cheeheng** [comment]
Hi. I am a student from a previous batch. I am using Ubuntu 23.04 and openjdk 11.0.20.1. The graphics appear to render correctly. However, resizing the window causes the chat to get truncated and the 'Send' button to disappear. Emojis appear to render correctly.

Output of ```java -version```:
```
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04, mixed mode, sharing)
```

GUI when window is resized:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/13196670/549679c9-71d9-4aab-9d15-e60464d5f869)

**Comment by seanpzk** [comment]
Hello @francisyzy @jefrai @seanfirefox @LicongHuang @cheeheng @RussellDash332 @ARPspoofing ,

Thank you all for helping me with the smoke test, will amend the errors accordingly! :D
