### ISSUE TITLE
duke.jar cannot be ran with Error: java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by wjacobw** [nus-cs2103-AY2324S1/forum#206]
I can run duke.jar from my ip folder with: 
```java
java -jar ./build/libs/duke.jar 
```

but not with:
```java
cd build/libs
java -jar duke.jar
```

I use relative path to input the duke.txt file (in my case it is called zenith.txt) but the program still cannot find the file with error: java.io.FileNotFoundException: ./data/zenith.txt (No such file or directory)

```java
    public Duke() throws Exception {
        try {
            String filePath = "./data/zenith.txt";
            loadFile = new LoadFile(filePath);
            TaskList lst = new TaskList();
            loadFile.load();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
```

```java
    public void load() throws FileNotFoundException {

        File f = new File(getFilepath());
        this.file = f;
        Scanner s = new Scanner(getFile());
        while (s.hasNext()) {
            String line = s.nextLine();
            TaskList task = new TaskList(line);
            task.load();
        }
        s.close();
    }

    public String getFilepath() {
        return this.filepath;
    }

    public File getFile() {
        return this.file;
    }
```

**Comment by lamchenghou** [comment]
I think when you run from root folder, then `./data/zenith.txt` exists. Within `libs`, it won't exist. Can fix this by creating `./data/zenith.txt` if not exists.

**Comment by wjacobw** [comment]
> I think when you run from root folder, then `./data/zenith.txt` exists. Within `libs`, it won't exist. Can fix this by creating `./data/zenith.txt` if not exists.

Thank you for the suggestion! but I thought the purpose of jar file is to make all the files to be one file that can be ran? so if I make a jar file, the zenith.txt will automatically be inside as well? And where should i create the ./data/zenith.txt file if it does not exist?

**Comment by wjacobw** [comment]
> I think when you run from root folder, then `./data/zenith.txt` exists. Within `libs`, it won't exist. Can fix this by creating `./data/zenith.txt` if not exists.

The suggestion you gave to me works, Thank you!
