### ISSUE TITLE
Cannot run Main file in ab3

### ISSUE THREAD

**Issue by MadLamprey** [nus-cs2103-AY2324S1/forum#208]
I tried running the Main file and building the project but it gave an error both ways. I simply cloned the fork without making any changes.

<img width="892" alt="Screenshot 2023-09-24 at 2 51 45 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/114080910/ac93e810-fba9-49d8-84dc-0797115799d8">

<img width="1341" alt="Screenshot 2023-09-24 at 2 55 42 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/114080910/0260ba7d-7aa3-47eb-87d2-9aa8389e3db9">
<img width="793" alt="Screenshot 2023-09-24 at 2 56 07 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/114080910/a1da0a87-14a4-4551-8d28-3023512a9308">

**Comment by AlagappanRa** [comment]
Hi, this problem might be similar to #159. You could try to make changes to the dependency task in build gradle file within the tp folder and see if the error resolves.

The JavaFX dependency for the Mac M1 (Architecture: ARM 64) differs from Mac Intel (Architecture: x86_64). I assume you are facing this problem.

**Comment by damithc** [comment]
@MadLamprey ensure the project SDK you have selected is the same as the one we have prescribed for Mac users (i.e., the Azul distribution). This doesn't seem to be the case as per your screenshot.

**Comment by MadLamprey** [comment]
Thanks prof, I reinstalled the JDK and it works now!

**Comment by Nid21cs** [comment]
> #159

Hi sorry im having the same issue as you, all you did was change the jdk in the project structure? 

This is my current one


<img width="1024" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/0d22cb65-6185-48f7-acf9-8f7e790e8137">
