### ISSUE TITLE
About updating the tags

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#209]
I recently made changes to the user guide and the app itself, so I want to update the A-UserGuide and A-Release tags
But is it still fine if I submit these tags today?

I know that the release can be updated until Thursday of week 7, but I'm curious if updating past tags is also allowed

Thanks in advance

**Comment by damithc** [comment]
@JasonRay168 There is no need to (but you are welcome to) update past tags. The dashboard checks for the existence of the tag, not which commit it is attached to.

**Comment by JasonRay168** [comment]
Oh so that's how it works
Thanks very much Prof!
