### ISSUE TITLE
Level-5 Exception Handling

### ISSUE THREAD

**Issue by Bryan-Goh** [nus-cs2103-AY2324S1/forum#21]
what does it mean to handle at least two types of error? does that mean i have to make two different exception java class? or does that mean i handle the two types of error with one Exception class but they just print different things

**Comment by Bryan-Goh** [comment]
am i allowed to just print out the error messages in some of the errors without a try and catch block? because in some of them theres an if else where the else is an error so should i put a try and catch block in the else where the try only throws the error and the catch immideately catches said error and print it?

**Comment by damithc** [comment]
@Bryan-Goh

> what does it mean to handle at least two types of error? does that mean i have to make two different exception java class? or does that mean i handle the two types of error with one Exception class but they just print different things

The number of exception classes is up to you.

> am i allowed to just print out the error messages in some of the errors without a try and catch block? because in some of them theres an if else where the else is an error so should i put a try and catch block in the else where the try only throws the error and the catch immideately catches said error and print it?

For this, and for other similar cases, consider them as opportunities for you to evaluate alternatives and make judgement calls based on pro and cons. Feel free to discuss them in the forum as well, to get inputs from classmates.
