### ISSUE TITLE
Unable to execute Launcher.main()

### ISSUE THREAD

**Issue by kayabuttertoastt** [nus-cs2103-AY2324S1/forum#210]
Hello professors and fellow peers, 
I was able to run the application properly from IntelliJ and downloaded and submitted my jar file on Friday. However, I got an email saying that my jar file was not working properly. After trying to rebuild the gradle file, I got this error when I try to run the Launcher class from IntelliJ. 

<img width="1294" alt="Screenshot 2023-09-24 at 6 00 33 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122214710/121c2eb5-a850-4132-bd0c-e087ee3692d0">

I tried this method that was recommended by prof in another issue but I still get the same error. 
<img width="818" alt="Screenshot 2023-09-24 at 5 55 45 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122214710/22c5d154-e4e4-4fce-8872-e9aba327f62e">

The code that I am using is the same as the one in my ip repo. Would appreciate any assistance regarding this issue. Thank you so much in advance.

**Comment by woojiahao** [comment]
The error at the end hints at the fact that it's failing because of `Storage`. You might want to check that you handle the case where you are loading from an empty file

**Comment by kayabuttertoastt** [comment]
@woojiahao Your suggestion works. Thank you so much! :)
