### ISSUE TITLE
tP Team Organization Setup

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#211]
Hi, for the tp team organization setup step, my team didn't create a "developers" team and so the code is in the main organization repo. Transferring the repo over will remove any existing pull requests, but its still relatively early in the project phase. Should we transfer now (any grading scripts reliant on this) or should we just contine with our existing setup?

**Comment by damithc** [comment]
@papataco14 You can create a 'developers' team in your team org now and add an existing repo to it.  Repos and teams are independent; you can create them in any order, and link them up later.

**Comment by papataco14** [comment]
oh i see. Thank you!
