### ISSUE TITLE
For `C-BetterSearch`, would finding incomplete tasks yet to pass due date be counted under this category?

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2103-AY2324S1/forum#212]
For my implementation under this category, I went about searching for only incomplete tasks that have a deadline further than user's stipulated time period. Would this classify as BetterSearch?

**Comment by damithc** [comment]
@XihuaZ describe how exactly it works so that others can comment on it. Perhaps reproduce here the relevant part of your user guide here?

**Comment by XihuaZ** [comment]
This is the description for the BetterSearch:

Finding Tasks to be done within period

Retrieve incomplete tasks with deadlines that fall within a specified time frame. This can be done with:

    `within [d/MM/YYYY HH:MM]`

Example:
```
within 22/09/2023 18:00
```

**Comment by damithc** [comment]
@XihuaZ I see. Assuming this is in addition to a normal _search_ feature (i.e., search by keyword), this is better than the normal search, and hence, qualify for C-BetterSearch

**Comment by XihuaZ** [comment]
Thank you for the clarification.
