### ISSUE TITLE
Requesting for help with non-Mac smoke testing

### ISSUE THREAD

**Issue by jannnice** [nus-cs2103-AY2324S1/forum#214]
Hi! 

Previously, I encountered some error with the smoke testing on non-Mac computers as listed below: 

On Windows, using Java 11, for the duke.jar uploaded on 09-21-2023 (MM-DD-YYYY) at 12:40:00:
```Error: JavaFX runtime components are missing, and are required to run this application```
On Linux, using Java 11, for the duke.jar uploaded on 09-21-2023 (MM-DD-YYYY) at 12:40:00:
```Error: JavaFX runtime components are missing, and are required to run this application```

Can I get some help with testing my update jar file? [Here](https://github.com/jannnice/ip/releases/tag/A-Release-2) is my latest jar file.

Thanks!

**Comment by dinde2004** [comment]
It runs well on my Windows laptop! (Java 11)

**Comment by VN-Hao** [comment]
It runs well on my Linux virtual machine (Java 11)
![Screenshot (1426)](https://github.com/nus-cs2103-AY2324S1/forum/assets/111359733/c8a0e6bb-9aab-4d07-b3e4-f3471ec30474)

**Comment by lunaflight** [comment]
Works fine on Fedora Linux :)

**Comment by jannnice** [comment]
> It runs well on my Windows laptop! (Java 11)

Thank you so much!!

**Comment by jannnice** [comment]
> It runs well on my Linux virtual machine (Java 11) ![Screenshot (1426)](https://user-images.githubusercontent.com/111359733/270572304-c8a0e6bb-9aab-4d07-b3e4-f3471ec30474.png)

Thankyou!!!

**Comment by jannnice** [comment]
> Works fine on Fedora Linux :)

Thank you :DD

**Comment by johnnythesnake12** [comment]
![Screenshot (227)](https://github.com/nus-cs2103-AY2324S1/forum/assets/98082700/fd7f0822-52d4-4b03-8ab5-405b92e62e18)
Hi it works fine for me too
