### ISSUE TITLE
Requesting for help with Linux smoke testing

### ISSUE THREAD

**Issue by ruo-x** [nus-cs2103-AY2324S1/forum#216]
Tried to do a smoke test by running my .jar file on my WSL Ubuntu but got this error:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122598707/fb17fc0f-03c7-4b62-a285-f6f8b2621c2d)

However, I have came across a comment saying that WSL does not support GUI which was most likely the reason why this error has occurred.

Hence, would really appreciate it if Linux users can help to check if my app works! Thank you :)
Here is my latest release: [https://github.com/ruo-x/ip/releases/tag/A-Release](https://github.com/ruo-x/ip/releases/tag/A-Release)

**Comment by aexolate** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/20797128/eb38afdd-e6e7-4010-8edc-3ee13b578bfd)

Works fine on my Ubuntu!

**Comment by Nauxe** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/51425614/d95598b7-5ed0-43e5-a465-2dc0f400c6ea)
Works on openSUSE Tumbleweed!

**Comment by sp4ce-cowboy** [comment]
I'm running virtualized Ubuntu 22.04 with [Parallels](https://www.parallels.com) on my mac, and I get this error. Not sure if it's because of the jar file or if it's because I'm running Linux in a VM.

<img width="1891" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/6b171f99-9217-4172-b4b4-c470ad8505d2">

**Comment by flexibo** [comment]
> I'm running virtualized Ubuntu 22.04 with [Parallels](https://www.parallels.com) on my mac, and I get this error. Not sure if it's because of the jar file or if it's because I'm running Linux in a VM.
> 

works for me, im using Ubuntu 22.04.3 on VMWare Workstation

**Comment by ruo-x** [comment]
@aexolate @Nauxe @sp4ce-cowboy @flexibo Thank you everyone for your help! Will close this issue now :))
