### ISSUE TITLE
Requesting for help: LinkageError when running JAR File

### ISSUE THREAD

**Issue by nicrandomlee** [nus-cs2103-AY2324S1/forum#217]
I received an email saying that there is a LinkageError when running my [JAR file](https://github.com/nicrandomlee/ip/releases/tag/A-Release) and I am not sure how to fix. I tried to follow an [online guide](https://stackoverflow.com/questions/64742252/how-to-fix-java-unsupportedclassversionerror) and reconfigured my project structure, and after getting my teammates to help me test out, I am still facing the same issue. Has anyone encountered a similar issue? 

<img width="548" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110522291/52d9011c-4f07-409e-afab-54a7ec84dc01">  

<br/><br/>

>My build.gradle file:
```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

checkstyle {
    toolVersion = '10.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("runner.Launcher")
}

shadowJar {
    archiveBaseName = "Cupid"
    archiveClassifier = null
    archiveFileName = 'Cupid.jar'
    dependsOn("distZip", "distTar")
}

run {
    standardInput = System.in
    enableAssertions = true
}
```

**Comment by dinde2004** [comment]
What I did is:
1. Go to Project Structure in IntelliJ, then download and change the SDK version to 11.
2. Change the java version in your local computer to 11, by following step 2 [here](https://www.happycoders.eu/java/how-to-switch-multiple-java-versions-windows/). Note that the value of the variable JAVA_HOME should be the path to your java version 11 you have downloaded in IntelliJ. For example `C:\Users\Admin\.jdks\corretto-11.0.20.1`.
3. Check java version of your local computer by running `java -version` in terminal to make sure it has been changed to 11.
4. Run the jar file again.

**Comment by nicrandomlee** [comment]
Update: Managed to fix the issue. Thank you @dinde2004 for your help.

What I did was:
1. Redownload SDK version 11
2. Overwrite value of environment variable JAVA_HOME to my java version 11 path following step 2 (here)[https://www.happycoders.eu/java/how-to-switch-multiple-java-versions-windows/]
3. Go to project structure and change SDK to 11 and language level to 11
4. Delete .idea and .gradle file
5. Click on Build > Rebuild Project
6. Recreate JAR file using [tutorial link](https://se-education.org/guides/tutorials/jar.html)

Other issues I encountered during my rebuilding of project:
IntelliJ cannot open Terminal Window
1. Go to IntelliJ and click on Settings > Tools > Terminal
2. Change shell path to: `C:\Windows\System32\cmd.exe`
3. Apply changes and restart IntelliJ
