### ISSUE TITLE
Requesting help for smoke testing from windows/mac/linux users

### ISSUE THREAD

**Issue by btaanish** [nus-cs2103-AY2324S1/forum#218]
Hi everyone!

I needed some help for smoke testing my .jar file. Would be grateful for feedback from both windows/mac/linux users.

You can have a quick look [here](https://github.com/D-Limiter/ip/releases/tag/A-Release) 

PS: Am using macOS.

TIA!

**Comment by damithc** [comment]
@D-Limiter perhaps give here the link to your JAR file for the convenience of testers?

**Comment by btaanish** [comment]
Noted Prof, I've added it now

**Comment by billieboy7** [comment]
Windows user here. I cant seem to open it and get this error. Is it a fat jar file?
![Help error msg](https://github.com/nus-cs2103-AY2324S1/forum/assets/86971803/58a37c5d-b806-43d5-8bd6-5ecd2b3f8aa8)

**Comment by s0ngyang** [comment]
<img width="612" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/83893048/894ab8e5-a06a-43a6-a278-7cca7274e818">

Same issue on windows here.

**Comment by aarontxz** [comment]
Hi I am using MacOS here, I am able to run the program and add tasks to the list, however there seems to be some issue with the storage as the tasks that i added are not shown again on the list after i close and reopen the program. 

this is the error
An exception occurred: ./src/main/java/data/tasks.txt (No such file or directory)

**Comment by sp4ce-cowboy** [comment]
I'm using macOS as well, I am able to open and run the application but I am unable to save tasks to file. 

I get this error:
<img width="737" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/bfc9bfad-33f4-436e-8e36-d457ca7df18a">

**Comment by btaanish** [comment]
Thanks for the reviews everyone. I have managed to solve the file path issue. However, I did create a fat JAR file by running `./gradlew clean shadowJar` but not sure why the error:

> <img alt="image" width="612" src="https://user-images.githubusercontent.com/83893048/270735424-894ab8e5-a06a-43a6-a278-7cca7274e818.png">
> Same issue on windows here.

persists. I've tried cleaning project and rebuilding it but can't seem to  find a way to solve this. Any advice on how I can address this ?

Thank you!

**Comment by Tang-Moyan** [comment]
I have ran your jar file on my windows computer and I have the same error message. Maybe you can check how others wrote their gradle.build and other relavant files which may give you a hint of where you went wrong :). (Check out the peer review PRs for example)

**Comment by damithc** [comment]
> I've tried cleaning project and rebuilding it but can't seem to find a way to solve this. Any advice on how I can address this ?

@D-Limiter run the following commands when creating the jar file. Use the first one to confirm you are using the correct JDK to create the JAR file. The second one cleans the project before creating the new far jar file.
```
java -version
./gradlew clean shadowJar
```

**Comment by sp4ce-cowboy** [comment]
> Thanks for the reviews everyone. I have managed to solve the file path issue. However, I did create a fat JAR file by running `./gradlew clean shadowJar` but not sure why the error:
> 
> > <img alt="image" width="612" src="https://user-images.githubusercontent.com/83893048/270735424-894ab8e5-a06a-43a6-a278-7cca7274e818.png">
> > Same issue on windows here.
> 
> persists. I've tried cleaning project and rebuilding it but can't seem to find a way to solve this. Any advice on how I can address this ?
> 
> Thank you!

@D-Limiter I had the same issue on macOS, I tried `./gradlew shadowJar` without the `clean` option and it worked afterwards, although I'm not sure why, maybe you can try that. Additionally, you could also try running the shadowJar command from Gradle in IntelliJ instead of the command line.

**Comment by btaanish** [comment]
Thanks a lot everyone! I have made the suggested edits. Would be really grateful if you could help me take a quick look at the project one last time :)

**Comment by Cloud7050** [comment]
It works for me on Windows. JavaFX was able to show the GUI and the program was able to save to & load from disk.

I will note that the save path relative to the jar was nested into `.\src\main\java\data\tasks.txt`. Just something that I thought was notable.

**Comment by ryanozx** [comment]
It works for me on MacOS. The app opens up a GUI and can save and load from disk. As @Cloud7050 mentioned, the app created the following file path relative to the location of the jar file: "./src/main/java/data/tasks.txt", which I'm not sure if it is intended. 

Also, the following warning pops up when I try to open the app:
`/Users/ryano/Downloads  $ java -jar alcazar.jar             09-28-2023 23:05:07
Sep 28, 2023 11:05:15 PM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
WARNING: Timeout while waiting for app reactivation`

**Comment by jedkohjk** [comment]
Hi, the app runs on my windows laptop, but the bye command does not seem to close the app.

**Comment by papataco14** [comment]
The app works on my windows laptop and pc, unless you intended to close the application with bye command, I think its safe to say its good for windows.

**Comment by ghost** [comment]
Works fine on Windows, tested with Windows Sandbox (Windows 11). App launches with the following console output:
```
Sep 28, 2023 11:18:56 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @7a324d7f'
```

The app created a file in the following directory `./src/main/java/data/tasks.txt`, presumably for data storage

============

Works fine on Linux, tested on Ubuntu 22.04 with VMWare Workstation 17. App launches with the following console output:
```
Sept 29, 2023 12:05:06 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5767b04b'
```

The app created a file in the following directory`./src/main/java/data/tasks.txt`, presumably for data storage

============

Additionally, a quick round of test revealed that the app does not get terminated when using the `bye` command, but will be terminated on the next command input. If that is not the expected behaviour, you may want to change the logic flow of the program

**Comment by suryanshkushwaha** [comment]
Mac M2 user here.

I just tested your jar file and everything seems to be working fine. I received no errors as previously mentioned by @ryanozx.

App reads the stored data perfectly fine. One suggestion, personally I would not keep the data file inside the src/main/java folder, to avoid any confusion :).

Looks good to me for release.
