### ISSUE TITLE
IP Autograder not detecting progress

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#22]
Hi all,

I have pushed my IP code to my github forked repo, but the IP progress tracker seems to not have picked it up. I was wondering if I am doing something wrong? Any help would be appreciated! Thanks!

EDIT: Currently for my repository setting, I have set the fork behaviour to "To contribute to the parent repository", was wondering if I have to change it to "For my own purposes" instead?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/84987837/569516bf-2d74-46f4-9980-2d06f54f2b7a)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/84987837/6124f880-b9f8-4353-bfc6-55432d1bae33)

**Comment by Tim-Siu** [comment]
I think the dashboard is not updated realtime.

**Comment by lihongguang00** [comment]
> I think the dashboard is not updated realtime.

I have finished level 0 to 4 a few days ago though, but they're also not detected :-(

**Comment by woojiahao** [comment]
Did you push the tags with `git push --tags` ?

**Comment by lihongguang00** [comment]
> Did you push the tags with `git push --tags` ?

yup, did exactly that, its shown in the bottom screenshot

**Comment by joeng03** [comment]
You should tag Level-0 instead of seperating it into Level-0a and Level-0b

**Comment by lihongguang00** [comment]
> You should tag Level-0 instead of seperating it into Level-0a and Level-0b

I have 2 tags for Level-0b, namely Level-0b and Level-0, was lazy to undo commit for level-0a :p

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/84987837/3cae9bb8-aaed-4929-be40-b483001228a5)

**Comment by HugeNoob** [comment]
> yup, did exactly that, its shown in the bottom screenshot

I'm not able to see your git tags when visiting your repository. Maybe verify again that you have pushed the tags?

From your profile:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/0f842ed6-e28b-45c4-82da-4aa42dbbc0f8)

What it should look like:  
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/9d2dcc76-87c9-4ce5-b76c-c1350c3c699b)

**Comment by damithc** [comment]
Thanks everyone for your inputs. You are on the right track to solve this issue. I suspect it's just one more step before we nail it. :-)

**Comment by lihongguang00** [comment]
> > yup, did exactly that, its shown in the bottom screenshot
> 
> I'm not able to see your git tags when visiting your repository. Maybe verify again that you have pushed the tags?
> 
> From your profile: ![image](https://user-images.githubusercontent.com/65714641/263008785-0f842ed6-e28b-45c4-82da-4aa42dbbc0f8.png)
> 
> What it should look like: ![image](https://user-images.githubusercontent.com/65714641/263009082-9d2dcc76-87c9-4ce5-b76c-c1350c3c699b.png)

Thanks! I don't know if it'll work but I made 7 releases 1 for each version lol, fingers crossed. Appreciate your help, I see the relevant tags under the tags now!

**Comment by damithc** [comment]
@lihongguang00 You are mixing up commit messages with tags. Previously, you used `Level-0` etc. as commit messages instead of tags. That's why there were no tags in your repo.
When doing a release, GitHub automatically creates a tag, but that is just a side effect, not the intended way to create a tag.

**Comment by lihongguang00** [comment]
> @lihongguang00 You are mixing up commit messages with tags. Previously, you used `Level-0` etc. as commit messages instead of tags. That's why there were no tags in your repo. When doing a release, GitHub automatically creates a tag, but that is just a side effect, not the intended way to create a tag.

Hi prof, I'm new to git and it's quite confusing so please correct me if my current sequence of git commands is wrong. 

`git add <file>`
`git commit -m <commit_header> -m <commit_message>`
`git tag <relevant_tag>`
`git push`

My current understanding is that using `git tag <relevant_tag>` creates the tag on the latest commit?

**Comment by woojiahao** [comment]
You need `git push --tags` otherwise your tag will not be published

`git tag` alone will only add a tag locally, your remote repository does not contain the tag

**Comment by lihongguang00** [comment]
> You need `git push --tags` otherwise your tag will not be published

Ohhhhhhhh, i'll go try that right now, thank you!

**Comment by woojiahao** [comment]
I would also add that it's best if you don't try to think of commands as a sequence to memorise but rather as a set of tasks that need to be done, this way it's easier to handle issues like merge conflicts or multiple branches:

1. `git add <file>`: stage the file for the next "snapshot"/commit
2. `git commit -m`: create the "snapshot"/commit with a message
3. `git tag`: provide the current "snapshot"/commit with a human readable tag name
4. `git push`: bring changes from local repository to remote repository, does not include tags
5. `git push --tags`: bring all local tags to remote repository

This way, it's much easier when dealing with larger commits/projects, hope this helps

**Comment by lihongguang00** [comment]
> I would also add that it's best if you don't try to think of commands as a sequence to memorise but rather as a set of tasks that need to be done, this way it's easier to handle issues like merge conflicts or multiple branches:
> 
> 1. `git add <file>`: stage the file for the next "snapshot"/commit
> 2. `git commit -m`: create the "snapshot"/commit with a message
> 3. `git tag`: provide the current "snapshot"/commit with a human readable tag name
> 4. `git push`: bring changes from local repository to remote repository
> 5. `git push --tags`: bring all local tags to remote repository
> 
> This way, it's much easier when dealing with larger commits/projects, hope this helps

ah, that's good advice, appreciate your input! Will take note for future ip iterations :p

**Comment by damithc** [comment]
Good advice, @woojiahao 💯
