### ISSUE TITLE
Error when running tests in tp. "can't load library libprism_es2.dylib"

### ISSUE THREAD

**Issue by winson8222** [nus-cs2103-AY2324S1/forum#220]
`Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/winsonzheng/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/winsonzheng/.openjfx/cache/17.0.7/libprism_es2.dylib
`

I am using zulu 11 SDK and language default on Macos. I tried changing JavaFx version but it does not work. All the other tests are okay.

**Comment by damithc** [comment]
@winson8222 what's the output when you run the following commands in your terminal?

```
java -version
./gradlew run
```

**Comment by winson8222** [comment]
`winsonzheng@Winsons-MacBook-Pro tp % java -version
openjdk version "11.0.20" 2023-07-18 LTS
OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
winsonzheng@Winsons-MacBook-Pro tp % ./gradlew run

> Task :run
Sep 27, 2023 12:21:54 AM seedu.address.Main main
WARNING: The warning about Unsupported JavaFX configuration below can be ignored.
Sep 27, 2023 12:21:54 AM seedu.address.MainApp init
INFO: =============================[ Initializing AddressBook ]===========================
Sep 27, 2023 12:21:54 AM seedu.address.MainApp initConfig
INFO: Using config file : config.json
Sep 27, 2023 12:21:54 AM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file config.json found.
Sep 27, 2023 12:21:54 AM seedu.address.commons.core.LogsCenter init
INFO: Log level will be set as: INFO
Sep 27, 2023 12:21:54 AM seedu.address.MainApp initPrefs
INFO: Using preference file : preferences.json
Sep 27, 2023 12:21:54 AM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file preferences.json found.
Sep 27, 2023 12:21:54 AM seedu.address.MainApp initModelManager
INFO: Using data file : data/addressbook.json
Sep 27, 2023 12:21:54 AM seedu.address.MainApp initModelManager
INFO: Creating a new data file data/addressbook.json populated with a sample AddressBook.
Sep 27, 2023 12:21:54 AM seedu.address.MainApp start
INFO: Starting AddressBook V0.2.2ea
Sep 27, 2023 12:21:54 AM seedu.address.ui.UiManager start
INFO: Starting UI...
Sep 27, 2023 12:22:06 AM seedu.address.MainApp stop
INFO: ============================ [ Stopping Address Book ] =============================

BUILD SUCCESSFUL in 12s
`

**Comment by damithc** [comment]
@winson8222 So, seems to work? When do you see the error you posted in the first comment?

**Comment by winson8222** [comment]
> @winson8222 So, seems to work? When do you see the error you posted in the first comment?

When I run all the tests under tests.

**Comment by damithc** [comment]
> When I run all the tests under tests.

Via Intellij or via `.\graldew test`?

If the former, can you share a screenshot of the project settings page?

**Comment by winson8222** [comment]
<img width="1006" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/63703992/e30adca5-f8cd-44b7-a7a8-9fa065332a70">
<img width="1014" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/63703992/76f1b5df-b3d0-442a-811e-550855266466">
<img width="1025" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/63703992/6138a236-8f47-4a99-9c2d-aed0c7d2a5c0">

**Comment by winson8222** [comment]
I ran using intellij.

**Comment by damithc** [comment]
Perhaps remove the other SDK and try File -> Invalidate caches?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/ef12b492-bebf-4674-8ca4-c33018e6eb88)

**Comment by winson8222** [comment]
> Perhaps remove the other SDK and try File -> Invalidate caches?
> 
> ![image](https://user-images.githubusercontent.com/1673303/270738241-ef12b492-bebf-4674-8ca4-c33018e6eb88.png)

Thanks this works!
