### ISSUE TITLE
Checkstyle configuration for tp

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#221]
Currently, this is how the checkstyle is configured in the build.gradle file: 
```

plugins {
    id 'java'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'application'
    id 'jacoco'
}

mainClassName = 'seedu.address.Main'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

checkstyle {
    toolVersion = '10.2'
}
```

Are we supposed to use the checkstyle.xml file (under tp/config/checkstyle) or online plugins for standardization?

**Comment by damithc** [comment]
@papataco14 You should use the given config files, but you may modify them as you see fit. Not sure what you meant by 'online plugins' though. Can give an example?

**Comment by papataco14** [comment]
What I meant by online plugins is like currently, i think the build.gradle file is using online checkstyle plugins and their own definitions of checkstyle (the plugin: id checkstyle) instead of the definitions in the checkstyle.xml file

**Comment by damithc** [comment]
> What I meant by online plugins is like currently, i think the build.gradle file is using online checkstyle plugins and their own definitions of checkstyle (the plugin: id checkstyle) instead of the definitions in the checkstyle.xml file

@papataco14 In the iP, the checkstyle tool is downloaded from an online repository (by Gradle) but you need to supply your own checkstyle config file. Both remans the same in the tP.

**Comment by papataco14** [comment]
Oh i see, thank you!
