### ISSUE TITLE
Week 6 Tutorial: Tracing code help

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#223]
> 9. Step into the line where user input in parsed from a String to a Command, which should bring you to the AddressBookParser#parseCommand() method (partial code given below):
<img src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/3dcfd73e-0dcf-4406-9d73-55c3839c7024" width = "700">

___
> 13. Let’s see what EditCommandParser#parse() does by stepping into it. You might have to click the ‘step into’ button multiple times here because there are two method calls in that statement: EditCommandParser() and parse().
<img src = "https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/408e956c-920c-4a59-a5b4-eff96d94027d" width="700">

___
However, upon stepping into EditCommandParser().parse(arguments) , the debugger ends up at the class declaration of the EditCommandParser class instead of the parse() method of the class.
<img src ="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/a94a40ee-db06-4a67-8ecc-c5520f92c034" width="700">

___
Stepping over or stepping into that frame returns me to the previous frame parseCommand:60.
<img src = "https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/1c7b6abf-aa02-4b47-8bb3-52ad2e5a5b1f" width="700">

What could I be missing out here such that I was not able to step through the parse method of the EditCommanfParser class?

**Comment by damithc** [comment]
@s-peiran This statement in concern has two method calls, chained together. So, `EditCommandParser()` comes first, followed by `parse()`. 
Try repeating step-into followed by step-out until you reach the `parse()` method.

**Comment by s-peiran** [comment]
Thanks prof for the prompt response. Repeating step-into followed by step-out solved the issue.
