### ISSUE TITLE
The correct PR settings for AB3 Tutorial 2 (add remark command)

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#224]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/abd79207-8776-49b4-bfc7-0575efe70430)

Just to make sure, once the branch is pushed to my fork, do i directly create a PR to upstream master branch? Thanks

**Comment by damithc** [comment]
@JasonRay168 Yes, that's correct.

**Comment by JasonRay168** [comment]
Alright thanks Prof!
