### ISSUE TITLE
Request for help on smoke testing from linux users

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#227]
Hi I need some help on smoke testing from linux users. Grateful for any feedback from linux users as well as win and mac.

You can find the .jar file [here](https://github.com/ChangruHenryQian/ip/releases)

Thank you for helping and hope you are enjoying the recess week!

**Comment by cheeheng** [comment]
Hi @ChangruHenryQian, I am a student from a previous batch. I have tested the .jar file on Ubuntu 23.04 and it seems to be working fine, except for window resize issues.

Output of ```java -version```:
```
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04, mixed mode, sharing)
```

Output of ```java -jar duke.jar```
```
Sep 29, 2023 5:34:57 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @602ffa63'
```
GUI image:
![Screenshot from 2023-09-29 17-35-50](https://github.com/nus-cs2103-AY2324S1/forum/assets/13196670/af49c4c3-ccff-4188-9685-ada5dead0695)

**Comment by seanfirefox** [comment]
Hi @ChangruHenryQian, I am a student from a previous batch. I have tested your jar file on Arch Linux (lts version) and it seems to be working as well, with the same problem as what Chee Heng mentioned above.
java --version:
```
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
```

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/35872524/4890b6cf-fd19-4077-8e23-27ea0849b4bd)

**Comment by RussellDash332** [comment]
Hi, I'm from the senior batch dropping by. Here are the tests that I did:

<details>
<summary>
<b>Windows 10, Java 18</b>
</summary>

The Java spec that I had here is as follows

```
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

Similar to the rest, I encounter an issue where the window looks off upon resizing, shown below.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/63991775/65f52535-ee71-4376-afd5-8d176559bc79)

As an extra, I tried doing `deadline test /by 12` and a long error message is shown.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/63991775/11a4421d-e8d9-42c3-9d5c-e3f657b8d78f)

Similarly for simply inputting `event` or `delete`.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/63991775/0e3fa8c2-d41b-40eb-a020-42db4c60caf6)

Lastly, `bye` doesn't quit the app, so it essentially "just says goodbye".
</details>

<details>
<summary>
<b>Ubuntu 18.04.5, Java 11</b>
</summary>

The Java spec that I had here is as follows

```
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

Same as the one I had at Windows, the window resizing issue persists.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/63991775/1b8f0313-c28f-4f0a-9a3e-0cb4d5a5352e)

The rest is also the same that of Windows.
</details>

Happy further testing!
