### ISSUE TITLE
YAML-style Frontmatter Syntax not being parsed by gh-pages using MarkBind docs

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#228]
On my skeletal ppp file, the top of the file contains a frontmatter syntax that specifies the page layout and title as shown below.
`docs/team/craigtonlian.md`:
```
---
  layout: default.md
  title: " Project Portfolio Page"
---

### Project: Staff-Snap
```

However, for some reason, this frontmatter is being displayed on the UI as shown below.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108467437/05ddfcf6-4137-4b36-b0db-35b22ae5f427)

<hr>

On the AboutUs.md I have a similar frontmatter syntax, but on that page it doesn't have the problem of displaying on the UI.
`AboutUs.md`:
```
---
  layout: default.md
  title: "About Us"
---

# About Us
```

About Us page UI:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108467437/28153bef-7dac-4f9a-af62-ebd5a125975f)

It feels like I'm overlooking a MarkBind specific configuration here. Any help is appreciated!

**Comment by damithc** [comment]
@craigtonlian can you share the full content of the file in concern?

**Comment by damithc** [comment]
@craigtonlian also try removing the leading space in `" Project ...` to see if that helps.

**Comment by craigtonlian** [comment]
Here's the full content.

docs/AboutUs.md:
```
---
  layout: default.md
  title: "About Us"
---

# About Us

We are a team based in the [School of Computing, National University of Singapore](http://www.comp.nus.edu.sg).

You can reach us at the email `craigton.lian[at]gmail.com`

## Project team

### Craigton Lian Ee John

<img src="images/craigtonlian.png" width="200px" height = "200px" style = "border-radius: 50%;">


* Links: 
  [[github](https://github.com/craigtonlian)]
  [[portfolio](team/craigtonlian.md)]
* Role: Developer
* Responsibilities:
  * Overall coordination
  * Ensure proper testing
  * Version and release control
  * Repo maintenance and integration

### Austin Huang De Yu

<img src="images/austinhuang1203.png" width="200px" height = "200px" style = "border-radius: 50%;">

* Links: 
  [[github](http://github.com/austinhuang1203)]
  [[portfolio](team/austinhuang1203.md)]
* Role: Developer
* Responsibilities:
  * Review coding standards

### Ivan Lee Kai Kiat

<img src="images/ivanleekk.png" width="200px" height = "200px" style = "border-radius: 50%;">


* Links:
  [[github](http://github.com/ivanleekk)]
  [[portfolio](team/ivanleekk.md)]
* Role: Developer
* Responsibilities:
  * Monitor deadlines
  * Format deliverables

### Celestine Tan Yen Tong

<img src="images/celestinetan03.png" width="200px" height = "200px" style = "border-radius: 50%;">


* Links:
  [[github](http://github.com/celestinetan03)]
  [[portfolio](team/celestinetan03.md)]
* Role: Developer
* Responsibilities:
  * Define and assign tasks
  * Maintain issue tracker
  * Manage project board

### Wang Jingting

<img src="images/jingting1412.png" width="200px" height = "200px" style = "border-radius: 50%;">


* Links:
  [[github](http://github.com/jingting1412)]
  [[portfolio](team/jingting1412.md)]
* Role: Developer
* Responsibilities:
  * Coordinate documentation

```

docs/team/craigtonlian.md:
```
---
  layout: default.md
  title: "Project Portfolio Page"
---

# Project: Staff-Snap

> ***Craigton Lian's*** *Project Portfolio Page*<br>

### Overview<hr>
Staff-Snap is a desktop HR management application used for managing employees. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about <span style="color:red">**[TO BE UPDATED]**</span> 10 kLoC.

### Summary of Contributions<hr>

* **New Feature**: Added the ability to undo/redo previous commands.
  * What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
  * Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
  * Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
  * Credits: *{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}*

* **New Feature**: Added a history command that allows the user to navigate to previous commands using up/down keys.

* **Code contributed**: [RepoSense link]()

* **Project management**:
  * Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub

* **Enhancements to existing features**:
  * Updated the GUI color scheme (Pull requests [\#33](), [\#34]())
  * Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests [\#36](), [\#38]())

* **Documentation**:
  * User Guide:
    * <span style="color:red">**[TO BE UPDATED]**</span> Added documentation for the features `delete` and `find` [\#72]()
    * Did cosmetic tweaks to existing documentation of features `clear`, `exit`: [\#74]()
  * Developer Guide:
    * <span style="color:red">**[TO BE UPDATED]**</span> Added implementation details of the `delete` feature.

* **Community**:
  * <span style="color:red">**[TO BE UPDATED]**</span> PRs reviewed (with non-trivial review comments): 
      [\#31](https://github.com/AY2324S1-CS2103T-W08-1/tp/pull/31), 
      [\#32](), 
      [\#19](), 
      [\#42]()
  * Contributed to forum discussions (examples: 
      [\#2](https://github.com/nus-cs2103-AY2324S1/forum/issues/2), 
      [\#121](https://github.com/nus-cs2103-AY2324S1/forum/issues/121), 
      [\#158](https://github.com/nus-cs2103-AY2324S1/forum/issues/158), 
      [\#228](https://github.com/nus-cs2103-AY2324S1/forum/issues/228))
  * <span style="color:red">**[TO BE UPDATED]**</span> Reported bugs and suggestions for other teams in the class (examples: [1](), [2](), [3]())

* **Tools**:
  * Integrated a third party library (Natty) to the project ([\#42]())
  * Integrated a new Github plugin (CircleCI) to the team repo

```

**Comment by damithc** [comment]
@craigtonlian you can use this simple brute force technique to locate the problem:

1. Backup a copy of your PPP file.
2. Replace your PPP content with AboutUs content. Confirm the problem doesn't appear.
3. Incrementally replace content bit by bit and check output to figure out which content cause the regression.

**Comment by tlylt** [comment]
Hi @craigtonlian, the issue is due to indentation, because YAML is very particular about [white space](https://www.elastic.co/guide/en/beats/heartbeat/current/yaml-tips.html#:~:text=Indentation%20is%20meaningful%20in%20YAML,recommend%20you%20do%20the%20same.). Meaning accidental indentation can break the file.

In your case, you actually can see an error warning right in the GitHub UI at https://github.com/craigtonlian/tp/blob/master/docs/team/craigtonlian.md
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/5b56199e-68cb-4495-80c1-0dbff197c2d0)

The problem is that you had 2 white space before the "title".

I believe 
```
layout: ...
title: ...
```
or
```
  layout: ...
  title: ...
```
Will fix the issue.

Also as noted by @damithc, you might want to update " Project Portfolio Page" to "Project Portfolio Page".

---

For info, you can find out any potential error logs in your action workflow run that will be triggered when you merge your PRs into master. This is how your deployed MarkBind website gets updated when you make changes to the documentation. For example, you will see error message in this MarkBind Action run that is triggered by your PR that updates the aboutus.md:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/a31e5bc9-9264-4435-8f3a-3bdda7f945d7)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/7ea96e45-2877-48ed-8893-cf1fc6e3bd91)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/0cc12cf8-7505-4a33-9e73-93a509afa8aa)

**Comment by craigtonlian** [comment]
Excellent detective work @tlylt ! 

Is there any way we can check if the markbind action will go through error-free before merging the PR? I feel like even though I can see a preview of the markdown file in my IDE during editing, it doesn't always build correctly when shipped to gh-pages. 

Basically, what I'm asking is, is there a way to check how the MarkBind will render before I merge the PR?

**Comment by tlylt** [comment]
Yes, you can setup PR preview. I will put it up as a TODO for the MarkBind team to create a custom instruction for CS2103T tP users to give easy to follow instructions to enable this. Right now there's what I can come up with quickly:

1. Checkout to the PR branch and preview the MarkBind site locally

First checkout to the PR branch, follow the steps in https://se-education.org/guides/tutorials/markbind-forked-sites.html to install relevant dependencies, and also the command to run MarkBind locally.
- Pro: does not depend on external service
- Con: need to checkout and run locally, can take a bit of time

2. Set up PR preview using an external service such as Netlify and Surge.

The general guide is available here: https://markbind-master.netlify.app/userguide/deployingthesite#previewing-pull-requests-for-markbind-sites

It's much more involved as you will need to make some changes according to the tP setup, or need to general tokens etc.

Here I give a quick example using Netlify:
- read the guide here for Netlify: https://markbind-master.netlify.app/userguide/deployingthesite#deploying-to-netlify
- for the configuration in Netlify, follow the screenshot below instead:
- ![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/030998ee-5584-4490-a467-ebf8d2803c92)
- that's it
- Pro: only initial setup is required, then PR preview will be activated. See example: https://github.com/tlylt/ab3-docs-demo/pull/1
- Con: you need to have a Netlify free account. The free account has some monthly deploy limit that if you make PRs too frequently, you might hit it and have no more PR preview for the rest of the month.

For Surge, similar changes are needed for configuring the build/folder setting, please follow the general guide.

**Comment by craigtonlian** [comment]
Very cool. The PR review works perfectly now! Thanks so much.
