### ISSUE TITLE
Output issue after implementing Remark command

### ISSUE THREAD

**Issue by brendanneojw** [nus-cs2103-AY2324S1/forum#229]
Hi all, I've followed the tP tutorial 2 for adding in the Remark command. After finish implementing everything, I tried to use the remark command but the output seems abit weird compared to the one given in the website as shown below:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29995121/6cb3f106-1b79-4a9a-aef1-38c2a48f39a4)

The line where it says "Added remark to Person:..." seem like is outputting the object itself. I've ensured that my toString() method in the Person class is the same as the one in the tutorial. The link to my branch is here: https://github.com/brendanneojw/tp/tree/tutorial-adding-command

Hoping to get some help on this and if anyone had the same problem

**Comment by damithc** [comment]
@brendanneojw this looks like a nice debugging 'mystery' that is fun to solve together. Thanks for posting it. Let's see if anyone can figure out the cause.

**Comment by AriellaCallista** [comment]
Hi, I encountered the same issue. I fixed it by adding a `Messages.format` function in `RemarkCommand::generateSuccessMessage`.

```
private String generateSuccessMessage(Person personToEdit) {
        System.out.println("person to edit" + personToEdit.toString());
        String message = !remark.value.isEmpty() ? MESSAGE_ADD_REMARK_SUCCESS : MESSAGE_DELETE_REMARK_SUCCESS;
        return String.format(message, Messages.format(personToEdit));
}
```

**Comment by brendanneojw** [comment]
Thank Ariella for the help!
