### ISSUE TITLE
Requesting Permission to use Jackson library

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#23]
## Library

[jackson](https://github.com/FasterXML/jackson)

## Purpose

I am planning to use this library to help convert my class into/from JSON format to be saved to/loaded from local hard disk.

## License

Apache License 2.0. Link: https://github.com/FasterXML/jackson/wiki/FAQ

**Comment by damithc** [comment]
Approved, @yucongkoo

**Comment by yucongkoo** [comment]
Ok, thanks Prof.
