### ISSUE TITLE
For participation, do each member have to contribute at every part of the project?

### ISSUE THREAD

**Issue by juliusgambe** [nus-cs2103-AY2324S1/forum#230]
```
As mentioned before, while it is more convenient for one person to update the entire UG, we recommend that each person updates their own part of the docs so that we can easily track the contribution of each member using RepoSense
```
Due to this statement, our team is unsure whether for every part of the project, do we all have to contribute in some way? We are worried that because we did not contribute to a certain aspect, we would get penalised in some way.  For example, for the README page, do we have to contribute a sentence or two? It wouldn't make sense if all 5 members try to participate by contributing a sentence when there's only a few lines. It'll be more efficient if one person does it.

Thank you!

**Comment by damithc** [comment]
@juliusgambe every member is expected to contribute to the UG, and the DG, but it is not a requirement for the README.
Similarly, every member is expected to contribute to implementation, testing, and project management.

**Comment by juliusgambe** [comment]
> @juliusgambe every member is expected to contribute to the UG, and the DG, but it is not a requirement for the README. Similarly, every member is expected to contribute to implementation, testing, and project management.

I see thank you! Would it be alright if after everyone contributes their section, there would be one member who would help to clean up and standardise the document? We are wondering if this would affect the grading script as it might potentially create overlapping areas of in our commit history and affect our contribution.

**Comment by damithc** [comment]
> I see thank you! Would it be alright if after everyone contributes their section, there would be one member who would help to clean up and standardise the document? We are wondering if this would affect the grading script as it might potentially create overlapping areas of in our commit history and affect our contribution.

@juliusgambe Yes, that should be fine. But yes, the lines modified by the 'clean-up' person will be attributed that person in the tP code dashboard, as it goes by the last author of a line. However, there is [a way to override that](https://nus-cs2103-ay2324s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking:~:text=If%20the%20code%20does%20not%20match%20the%20actual%20authorship) and specify which part of the doc belongs to which member.
