### ISSUE TITLE
How exactly should I pull from the group repo for tP?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#232]
What I did to pull latest changes to the group repo was to set up upstream as the group repo link, then `git pull upstream master` directly on my local repo

But what I forgot about was that I was able to use GitHub to fetch the latest changes from the group repo to my fork, then from there pull to my local repo, without having to access the upstream directly

Are both approaches fine to do? Or is there a specific requirement? Thanks in advance

**Comment by damithc** [comment]
@JasonRay168 We prefer the former, as it is the more standard method (i.e., not GitHub specific).

**Comment by JasonRay168** [comment]
Alright thanks Prof!
Also, after `git pull upstream master`, will my remote fork's master branch be updated, or only the local master branch is updated?

**Comment by damithc** [comment]
> Also, after `git pull upstream master`, will my remote fork's master branch be updated, or only the local master branch is updated?

Good question, but this is easy to find out: just compare your local with the fork to see if there is a difference.

**Comment by JasonRay168** [comment]
Oh sorry, I should have been more specific:
I know that my own fork master branch was not updated, but my friend said it is updated. So I was only asking for the usual behaviour, although in my case, no it wasn't updated

**Comment by damithc** [comment]
@JasonRay168 a pull from upstream to your local repo will not update your fork, unless you push to your fork afterwards.

**Comment by JasonRay168** [comment]
Alright thanks Prof! Sorry for the rather long-winded question
