### ISSUE TITLE
Unable to run Main file in ab3

### ISSUE THREAD

**Issue by miljyy** [nus-cs2103-AY2324S1/forum#233]
I am not able to run the Main file from ab3. However, there are no errors when I use `gradle run`. I've checked my SDK (Java 11) and am a Windows user! The error from running Main is as shown:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108989233/060bf413-a309-4d1b-acce-0649fd927c81)

**Comment by damithc** [comment]
@miljyy While waiting for others to chime in, try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij -> set the correct JDK

Also, share a screenshot of your project settings here.

**Comment by miljyy** [comment]
Thanks prof for your help! I have resolved the issue.
