### ISSUE TITLE
Clarification on Forking Workflow

### ISSUE THREAD

**Issue by brendanneojw** [nus-cs2103-AY2324S1/forum#234]
Hi all, would like to ask for help with regards to this scenario that happens in order:
1) Currently working on a branch in my local repo
2) A teammate of mine have finished their branch feature, pushed it into their fork and create a pull request to the upstream repo (the team's repo) master branch.
3) I reviewed it and approved of the pull request and merged the pull request with the upstream repo's master branch
4) To ensure my local repo is in sync with the upstream repo, I pull the master branch of the upstream repo into my local repo
5) I then push the master branch of the local repo into my fork to ensure that it is in sync

My question here is, between step 4 and step 5, the branch that I am working on will not be the synced master branch that I pulled in step 4. Hence, how do I ensure that that the branch that I am working on is in sync with the pulled master branch?

**Comment by damithc** [comment]
Good question @brendanneojw . Let's wait to see if any classmates can pitch in with a suggestion.

**Comment by rocketninja7** [comment]
I think you can continue working on your feature branch until you finish it. Then merge the master branch into the feature branch.

**Comment by woojiahao** [comment]
The beauty of Git and version control is that you get to work asynchronously and sync your work anytime in the flow (but before you push to `master`). Generally, if the upstream `master` is updated, you could merge the latest changes into your branch using:

```
git fetch upstream master
git merge upstream/master
```

Run on your local branch, before anymore dev work. But fret not if you did not do so, you can do it after you've finished your changes, or through Github's PR UI that will also prompt you to merge to `master` to remain latest before you can merge your PR :)

**Comment by damithc** [comment]
Yup, as @woojiahao  mentioned, we recommend that you sync your local unmerged branches by merging the latest master branch to them periodically.

Thanks @brendanneojw for raising this question. As a result, I've updated the course website to mention this specifically.
