### ISSUE TITLE
Clarification on v1.1 Deadline and DG updating

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY2324S1/forum#236]
On the course website it states that tP v1.1's practice iteration is due by the midnight before the group's tutorial. Is this a specified hard deadline to have v1.1 reached by then?
Because the tutorial for week 7 includes the task of refining the DG after the tutorial.

I was wondering if it would make more sense to leave the PRs for the DG unmerged so that those branches can still be updated (refined) after the tutorial and have v1.1 delivered after the refinement is done (but still before 'Week 8' - before the lecture on Friday)

But this would mean that the v1.1 issues would not be fully solved and the milestone achieved by the midnight before the tutorial session.

**Comment by damithc** [comment]
Good question @JasonLCY-Temp 
Answer: The refining of the DG can be done as part of v1.2. So, try to finish v1.1 before the tutorial, but as usual, you can take a few more days if you can't finish it on time.
In general, every document is likely to be refined multiple times as the project evolves i.e., there is no need to put all changes to a document into one PR.

**Comment by ghost** [comment]
Understood, thank you very much for the clarification.

**Comment by damithc** [comment]
@JasonLCY-Temp Thanks for raising this, and kudos for catching this gap in instructions.
I've updated tutorial instructions to mention this.
