### ISSUE TITLE
Unable to push to my remote repo for forking workflow

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#237]
After pulling from the main repo from our team to update my local repo, I encounter the following error when pushing the update from my local repo to my remote repo:
```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --set-upstream origin master:master
POST git-receive-pack (chunked)
Pushing to https://github.com/ChangruHenryQian/tp.git
To https://github.com/ChangruHenryQian/tp.git
 ! [remote rejected]   master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/docs.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/ChangruHenryQian/tp.git'


Completed with errors, see above.

```
May I know how to fix this? Thanks for helping!

**Comment by damithc** [comment]
General comment: From the error message pick the phrase that seems representative of the problem but not specific to your repo/project, and do a Web search. For example, `refusing to allow an OAuth App to create or update workflow`

**Comment by ChangruHenryQian** [comment]
> General comment: From the error message pick the phrase that seems representative of the problem but not specific to your repo/project, and do a Web search. For example, `refusing to allow an OAuth App to create or update workflow`

I searched online and found https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on. The solutions generally require me to update or create new access token. I check on Personal access tokens in my github account and find one called CS2103T. I have already forgotten what the token is for. Am I allowed to update it or create a new one?

**Comment by damithc** [comment]
> Am I allowed to update it or create a new one?

@ChangruHenryQian Yes, the GitHub PAT is entirely under your control. The course does not impose any restrictions on how you use it.

**Comment by ChangruHenryQian** [comment]
> > Am I allowed to update it or create a new one?
> 
> @ChangruHenryQian Yes, the GitHub PAT is entirely under your control. The course does not impose any restrictions on how you use it.

@damithc Thank you for replying. May I confirm where is the token being used for this course, so I can update the token in proper places?

**Comment by woojiahao** [comment]
PATs are used as replacements for your personal password when you push/pull via HTTPS. I don't believe the course mandates that you follow a certain convention (HTTPS vs SSH), so if your error is a PAT, re-generating it and using it should resolve the issue

**Comment by damithc** [comment]
> PATs are used as replacements for your personal password when you push/pull via HTTPS. I don't believe the course mandates that you follow a certain convention (HTTPS vs SSH), so if your error is a PAT, re-generating it and using it should resolve the issue

Yup. 
@ChangruHenryQian which tool/method do you use to push commits?

**Comment by ChangruHenryQian** [comment]
> > PATs are used as replacements for your personal password when you push/pull via HTTPS. I don't believe the course mandates that you follow a certain convention (HTTPS vs SSH), so if your error is a PAT, re-generating it and using it should resolve the issue
> 
> Yup. @ChangruHenryQian which tool/method do you use to push commits?

Sourcetree, as suggested on the course website.

**Comment by damithc** [comment]
> Sourcetree, as suggested on the course website.

@ChangruHenryQian Sorry forgot to ask. Which OS?

**Comment by ChangruHenryQian** [comment]
> > Sourcetree, as suggested on the course website.
> 
> @ChangruHenryQian Sorry forgot to ask. Which OS?

Windows11 22H2

**Comment by damithc** [comment]
@ChangruHenryQian You can try the following:

1. Deactivate the current PAT (via GitHub)
2. [Create a new **classic** PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic) with `repo` and `workflow` permissions 
3. Use option 3 [here](https://se-education.org/guides/tutorials/sourcetree.html#:~:text=Connecting%20Sourcetree%20to%20Your%20GitHub%20Account) to configure your Windows/SourceTree to use the new PAT (failing that, try option 2)

**Comment by ChangruHenryQian** [comment]
> @ChangruHenryQian You can try the following:
> 
> 1. Deactivate the current PAT (via GitHub)
> 2. [Create a new **classic** PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic) with `repo` and `workflow` permissions
> 3. Use option 3 [here](https://se-education.org/guides/tutorials/sourcetree.html#:~:text=Connecting%20Sourcetree%20to%20Your%20GitHub%20Account) to configure your Windows/SourceTree to use the new PAT (failing that, try option 2)

@damithc Thank you for your kind assistance. This method solves the issue!
