### ISSUE TITLE
PR naming convention

### ISSUE THREAD

**Issue by J-hta-n** [nus-cs2103-AY2324S1/forum#238]
Hi all, for a PR which only partially fixes an issue, is it okay to still include the issue number in the PR title for clarity?

(screenshot from [here](https://se-education.org/guides/conventions/github.html))
<img width="772" alt="Screenshot 2023-10-04 at 1 29 29 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/103252521/28aba6f9-c572-438f-ab11-82f9d270500c">

**Comment by damithc** [comment]
> for a PR which only partially fixes an issue, is it okay to still include the issue number in the PR title for clarity?

@J-hta-n We have no objections from course admin point of view i.e., it can be a team decision.

**Comment by J-hta-n** [comment]
> > for a PR which only partially fixes an issue, is it okay to still include the issue number in the PR title for clarity?
> 
> @J-hta-n We have no objections from course admin point of view i.e., it can be a team decision.

Okay thank you prof!
