### ISSUE TITLE
iP Failing Smoke Test

### ISSUE THREAD

**Issue by Mohammed-Faizzzz** [nus-cs2103-AY2324S1/forum#239]
The jar file I submitted for iP failed the automated smoke tests for Linux and Windows.

I have installed the correct version of Java as instructed:
```
openjdk 11.0.19 2023-04-18 LTS
OpenJDK Runtime Environment Zulu11.64+19-CA (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.64+19-CA (build 11.0.19+7-LTS, mixed mode)
```

I use a Macbook, and encounter no issues or warnings when running the jar file on my local machine. The email also states that there is no issue with running my jar file on Mac. Can anyone guide me as to what changes I might need to make in order to make my jar file compatible with Windows and Linux? I have attached the relevant errors below.

![telegram-cloud-photo-size-5-6120840490501912981-y](https://github.com/nus-cs2103-AY2324S1/forum/assets/110959467/f898e46c-b9c5-48d1-82a8-82a3977918ac)

**Comment by damithc** [comment]
@Mohammed-Faizzzz Very likely another JDK version in your computer is being used to create the JAR file. To be safe, you can remove all other JDKs. Another student had an issue with the JDK version on Mac posted [this](https://github.com/nus-cs2103-AY2324S1/forum/issues/225#issuecomment-1744945712).

**Comment by Mohammed-Faizzzz** [comment]
Solved the issue. My gradle.build file was not set up correctly, leading to the issue. If you're facing similar issues, I think taking a look at others' gradle.build files and checking if it is consistent with yours would be helpful.
