### ISSUE TITLE
Tracker did not record tags found in fork even though it is in my fork

### ISSUE THREAD

**Issue by zhanyang01** [nus-cs2103-AY2324S1/forum#24]
So i did my IP for week 2 and have tagged the respective levels , Level-0 for eg but it is not recorded in the IP dashboard, may i ask how do i go about fixing it? 

<img width="698" alt="Screenshot 2023-08-26 120448" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/94ddbe9a-28cd-453a-aa21-874efacb1db1">
<img width="960" alt="Screenshot 2023-08-26 120829" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/b1d55d86-6dc6-415f-91b8-b084bfbe1e01">

PS: The AI fix by itself

**Comment by damithc** [comment]
@zhanyang01 Sorry, it was due to a temporary network outage (the dashboard failed to pull some forks). Should be fine now.

**Comment by zhanyang01** [comment]
It fine sometimes things can happen. Thanks prof
