### ISSUE TITLE
Team list not showing information

### ISSUE THREAD

**Issue by rocketninja7** [nus-cs2103-AY2324S1/forum#240]
Hi prof, after looking at the team list, we realise that our ```Target user``` and ```Value proposition``` shows ```[not available yet]```. The ```Project notes``` also links back to the same page instead of our Google Docs. We were wondering if it was related to this issue? #149
![image (1)](https://github.com/nus-cs2103-AY2324S1/forum/assets/43843106/b7d91706-5e26-481f-ad56-75a8d32ad25b)

**Comment by damithc** [comment]
@rocketninja7 it is indeed a complication arising from #149 Will sort it out within the next few days.

**Comment by damithc** [comment]
@rocketninja7 Fixed.

**Comment by rocketninja7** [comment]
Sorry for the late reply and the inconvenience caused. Thank you prof!
