### ISSUE TITLE
Asking whether our tp design fullfills the requirement.

### ISSUE THREAD

**Issue by Tang-Moyan** [nus-cs2103-AY2324S1/forum#241]
Our tp design involves three types of users: project manager, team leader and developer. Each has different level of accessibility to the stored information. It is like project manager can create, read and write; Team leader can read and write; And developer can only read.

We are planning to ask the user what is your type of user when our application starts and enable functionalities accordingly. In this way, only one user is using the system at one time on a single computer, but does this satisfies the Single-User Constraint of tp?

If not, then we are planning to make our target user be only the project manager, but we are just worried that not sufficent work is done for tp.

**Comment by damithc** [comment]
@Tang-Moyan Suppose the user is  developer, which means the user can only read data (as per your description). What data is s/he going to read because no other user is there to add data (as per the [`Constraint-Single-User`](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-constraints.html#constraint-single-user:~:text=Constraint%2DSingle%2DUser))?

**Comment by Tang-Moyan** [comment]
So our project is creating a tree structure to store contact information of a team for a sofeware development project where the root node the is the project manager's contact information. Others are divided into groups with one team leader for each group. The project manager has reference to all the team leaders. The team leaders have reference to the project manager and the developers in their group while all developers only have reference to their team leader.

It is up to the project manager to create the tree structure first and team leaders can help fill in all the contact information. Then, if anyone, including developers, needs to find someone's contact information. He can use our application to find it.

**Comment by damithc** [comment]
>It is up to the project manager to create the tree structure first and team leaders can help fill in all the contact information. Then, if anyone, including developers, needs to find someone's contact information. He can use our application to find it.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/d000475b-40c4-4bda-9bf5-91647ea1c58a)

@Tang-Moyan Given the above, how is the data added by the PM and team leaders are shared with other users?

**Comment by Tang-Moyan** [comment]
Our system will just store all the contact information added by the PM and team leaders on the computer which our applicaiton runs on. When other users come and use our application on the computer, the system will display the contact information, maybe with some addtional information as well, and that is all. However, the PM has the ability to hide his contact information to developers because they should contact their team leaders first rather than contact the PM directly.

Team leaders can edit or update his and his developers' information, but only the PM can create or delete identities (ie. add or delete a developer or a team leader). All the modifications are done on one computer and developers can just search and view.

**Comment by damithc** [comment]
> Our system will just store all the contact information added by the PM and team leaders on the computer which our applicaiton runs on. When other users come and use our application on the computer, the system will display the contact information, maybe with some addtional information as well, and that is all. However, the PM has the ability to hide his contact information to developers because they should contact their team leaders first rather than contact the PM directly.

@Tang-Moyan doesn't that violate the following?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/f170b534-91c1-4ab5-9860-c25bcbb435f7)

**Comment by Tang-Moyan** [comment]
So if we target our application just for the PM to manage all the contact information of developers in the software development team, would that be ok?

**Comment by damithc** [comment]
> So if we target our application just for the PM to manage all the contact information of developers in the software development team, would that be ok?

@Tang-Moyan Yes, a user should be able to download the application and use it on his/her own, without any other user involved.
