### ISSUE TITLE
Commits tracked incorrectly

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2103-AY2324S1/forum#243]
I believe my local Git account was incorrectly configured before. So the commits that I have been making thus far was recorded under the name "DESKTOP-ITF4GUD\94866"
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/97677245/513fc17d-a3a7-4404-819a-a1f298ca4ba5)
therefore, my code change has not been recorded here: https://nus-cs2103-ay2324s1.github.io/tp-dashboard/?search=mamayuan&breakdown=true

I have changed it and it seems to be correct now
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/97677245/ee0f69f9-8c5c-42a4-ab61-6e61bd470c3d)

But what can i do to make the previous contribution recorded

**Comment by damithc** [comment]
@mamayuan It's fine. When we detect commits made by "unknown" authors, we configure our settings to link them to the correct author. But it might take a few cycles of dashboard updates for these additional configurations to propagate to the code dashboard. You can check again about a day later.
