### ISSUE TITLE
Requesting help for smoke testing from windows/mac/linux users

### ISSUE THREAD

**Issue by InfiBeyond** [nus-cs2103-AY2324S1/forum#244]
Hi everyone!

I know this is very late. I've tested the jar file on Windows and Mac myself but would like some help double-checking my work.

I needed some help with smoke testing my .jar file. Would be grateful for feedback from both Windows/Mac/Linux users.

You can have a quick look [here](https://github.com/InfiBeyond/ip/releases/tag/A-Release)

I'm using a Mac.

Thank you so much!

**Comment by sp4ce-cowboy** [comment]
@InfiBeyond It works on my mac but I'm unable to list any files using the list command, are you using a different command for listing tasks?

Edit: I read your User Guide, it seems like you are using the `print` command instead, it works now!

<img width="594" alt="Screenshot 2023-10-05 at 10 57 20 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/470bc89e-d427-47c3-9212-419654ed6019">

**Comment by Mohammed-Faizzzz** [comment]
I had an issue where I failed smoke tests. My gradle.build file was not set up correctly, leading to the issue. If you're facing similar issues, I think taking a look at others' gradle.build files and checking if it is consistent with yours would be helpful.

**Comment by oeggy03** [comment]
Hi, I am testing on Windows, and am following the user guide according to https://infibeyond.github.io/ip/. It runs but:

**1. Conflicts in your user guide**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/80142959/125d634c-6705-41fb-a5dc-1558221d1057)
For instance, it states that the DATE_TIME format of the deadline task needs HH:mm, but your example does not require the HH:mm. I think your UG for `event` has the same conflicts.

**2. Your deadline command doesn't work:**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/80142959/bfd92b32-7130-46ce-99f4-cac97f7438d2)
I tested both inputs (With and without HH:mm, both do not work. I also copypasted the exact example in your UG)

Other than that I think everything works!

**Comment by jedkohjk** [comment]
Hi, I tested it on my windows laptop. The bye command does not exit the app. Additionally, perhaps because my laptop screen is smaller, the window does not fit on my screen and I can't see the bar to type commands in. If I click somewhere else I can't type anymore. Additionally, I can't see the close button because of the window size and the only way I can exit is to close the command line from which I launched the program. Otherwise, the app seems to work fine.

**Comment by jedkohjk** [comment]
Cute UI tho :)

**Comment by InfiBeyond** [comment]
> Hi, I am testing on Windows, and am following the user guide according to https://infibeyond.github.io/ip/. It runs but:
> 
> **1. Conflicts in your user guide** ![image](https://user-images.githubusercontent.com/80142959/273107946-125d634c-6705-41fb-a5dc-1558221d1057.png) For instance, it states that the DATE_TIME format of the deadline task needs HH:mm, but your example does not require the HH:mm. I think your UG for `event` has the same conflicts.
> 
> **2. Your deadline command doesn't work:** ![image](https://user-images.githubusercontent.com/80142959/273107759-bfd92b32-7130-46ce-99f4-cac97f7438d2.png) I tested both inputs (With and without HH:mm, both do not work. I also copypasted the exact example in your UG)
> 
> Other than that I think everything works!

Hi! Thank you so much for testing, I noticed that on the screenshot you used /by: instead of /by (an extra colon). I think that's the reason neither command worked.
