### ISSUE TITLE
Clarification on iP Reviewing standards

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY2324S1/forum#245]
I was wondering for the following sections, how should I proceed with the evaluation of the product.

Bugs - 
The description for **below expectations** is `Major bugs. App hardly usable` while the description for **Meets expectations** is `Only minor bugs`
If there is the presence of 2 medium-major bugs (2 commands are straight up unusable - Shows the error message instead of properly performing the command) Should I review as Below or Meets expectations as the current state does not cleanly fit into either of the categories.

Abstraction (methods) - 
The description for **below expectations** is `Very long methods. Deeply nested code` while the description for **Meets expectations** is `No very long methods or deep nesting`.
If there is 1 very long method but the rest of the code mostly has short methods and low levels of nesting should I review it as 'Below expectations' still due to the prescence of the 1 violating method?

**Comment by damithc** [comment]
@JasonLCY-Temp When choosing between two equally possible options, you can choose the more lenient one but give specific feedback about the problems you found when you give qualitative comments.
