### ISSUE TITLE
Proper way of implementation of Storage in TP

### ISSUE THREAD

**Issue by StevenLiudw** [nus-cs2103-AY2324S1/forum#247]
Are we supposed to stick for JSON format for TP storage? Or can we change to use other ways like txt file as IP. Our team tried to modify that but found out that there was a default configuration using JSON. Are there any other teams trying to do something similar?

**Comment by damithc** [comment]
> Are we supposed to stick for JSON format for TP storage? Or can we change to use other ways like txt file as IP.

@StevenLiudw You may use any format but note that there is a [tP constraint](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-constraints.html) that relates to the format of the data file.

**Comment by damithc** [comment]
@StevenLiudw Feel free to discuss here the reason you want to change the data format, pros, cons etc., as learning to make better project decisions is more important than learning to change the datafile format.
