### ISSUE TITLE
Question regarding merging of PRs that fails codecov tests

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#248]
Are we allowed to merge PRs that fails codecov test because the test coverage decreased, the reason of this decrease is because we added UI components to modify the GUI.

**Comment by damithc** [comment]
@yucongkoo Yes, this decision is up to the team. Indeed in some cases the drop in test coverage is justifiable/unavoidable in which case there is no choice but to merge the PR.

**Comment by yucongkoo** [comment]
Alright, thanks prof!
