### ISSUE TITLE
Query on Method assumptions and JUnit testing for tP

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#249]
Hello friends,

To set the context, I am looking to implement a calendar feature for the tP. Following the project structure of AB3, I added a class called `Calendar` to model a calendar, which would store `Event` objects.

Now, I want to implement a command that allows the user to delete some `Event` at some index (similar to the delete function in the iP). Again, following the structure of AB3, I would add a `DeleteEvent` command class, and a `DeleteEventParser` class to handle user input for this command. Naturally, this would mean that for any user input that is invalid (e.g. calendar only has a total of 2 events, but user tries to delete the event at index 10), it would be caught at the `DeleteEventParser` level. Now, I am wondering what would be the better practice to write my `Calendar` class `deleteAt(int index)` method, knowing that the index will definitely be valid?

(A) No assumption about `index` validity
```
public void deleteAt(int index) {
    if (index < 0 || index > this.size - 1) {
        throw new IndexOutOfBoundsException()
    }

    eventList.delete(index);
}
```

(B) Assuming `index` is always valid: 
```
public void deleteAt(int index) {
    assert(0 <= index < this.size); // Assert that the index is at least 0, and at most the calendar's size -1

    eventList.delete(index);
}
```

Personally, I have chosen to adopt approach B, and I am now having trouble doing testing for this method because I am unsure of how to test the `assert(0 <= index < this.size)` statement. Any help would be appreciated!

**Comment by damithc** [comment]
Good question @lihongguang00 Let's see what others think.

**Comment by damithc** [comment]
> I am unsure of how to test the `assert(0 <= index < this.size)` statement.

@lihongguang00 One approach you can explore is to first identify if the assertion failure throws a specific Error object. If it does, you can then try to test if that specific Error object is thrown as expected.

Separately, note that you can add a description to the assert, instead of a comment e.g.,

`assert 0 <= index < this.size) :  "index should be at least 0, and at most the calendar's size -1";`

The description will be printed if the assertion failed.

**Comment by AlagappanRa** [comment]
You can test for the error being thrown. (Similar to what Prof Damith has said)

Example:
```java
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

public class CalendarTest {

    @Test
    public void testDeleteAtInvalidIndex() {
        Calendar calendar = new Calendar();
        // Add some events to the calendar

        assertThrows(AssertionError.class, () -> {
            calendar.deleteAt(-1); // or any invalid index
        });
    }
}
```

Specifically, you may find AssertionError.class to be useful here.

**Comment by lihongguang00** [comment]
Thank you prof and dear friend for the helpful replies!
