### ISSUE TITLE
Will using Conventional Commits violate the course's Git conventions?

### ISSUE THREAD

**Issue by jiakai-17** [nus-cs2103-AY2324S1/forum#25]
In the [Conventional Commits format](https://www.conventionalcommits.org/), the subject line would be prefixed with a type, such as `feat` or `fix`, which is in lowercase. This conflicts with the [course's Git conventions](https://se-education.org/guides/conventions/git.html), which require the first letter of the subject line to be capitalized.

Are we allowed to use the Conventional Commits format? 

Example: `feat: Add save/load functionality`

Or should we follow the course's Git conventions strictly, and use the following instead?

Example: `Feat: Add save/load functionality`

Or are we not allowed to use Conventional Commits at all?

Example: `Add save/load functionality`

Thank you.

**Comment by damithc** [comment]
@jiakai-17 Capitalizing the _scope_ part is not a requirement. So, `feat: Add save/load functionality` is fine.

**Comment by jiakai-17** [comment]
Okay, thank you Prof!
