### ISSUE TITLE
Quiz early-submission window

### ISSUE THREAD

**Issue by jedkohjk** [nus-cs2103-AY2324S1/forum#250]
Hi, I just wanted to confirm when the early-submission window for the canvas quizzes are.
I'm asking because for the week 7 quiz, I submitted on 23 Sep, the day after lecture, but did not get the points for early submission.
It doesn't affect my overall participation marks, but I just wanted to clarify for future quizzes when the early-submission window is.
Thank you!

**Comment by ghost** [comment]
same here, submitted on 23 Sep at 13:59 and didn't get the participation mark 😕

**Comment by damithc** [comment]
@jedkohjk @chiayunrong There was a bug in the dashboard code that affected students who submitted quiz during Sep 22-30.  Thanks for the heads up. Should be fixed now.

**Comment by jedkohjk** [comment]
@damithc Noted prof thank you!
