### ISSUE TITLE
Dashboard not picking up PR

### ISSUE THREAD

**Issue by InfiBeyond** [nus-cs2103-AY2324S1/forum#256]
The dashboard has not been able to pick up my PR for tP.

This is my process, please let me know what am I doing wrong:

- Create a pull request from the forked repo, a separate branch
- Link issue and pull request
- After teammate approves pull request -> merge pr

**Comment by damithc** [comment]
@InfiBeyond can you also provide links to the PRs in concern?

**Comment by InfiBeyond** [comment]
This is the PR in concern:
https://github.com/AY2324S1-CS2103T-W11-1/tp/pull/50

I created this PR specifically for testing.

**Comment by damithc** [comment]
> This is the PR in concern: [AY2324S1-CS2103T-W11-1/tp#50](https://github.com/AY2324S1-CS2103T-W11-1/tp/pull/50)
> 
> I created this PR specifically for testing.

Good. Let's wait to see if anyone whose PRs are already detected by the dashboard can help you troubleshoot this problem.

**Comment by yyyaohhh** [comment]
Hi, I see that you did not add a milestone to the PR. Maybe you can try adding a milestone(shown at the right of the pull request page) to your PR, maybe v1.2?
<img width="264" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/394562d7-c4b0-4593-a18e-e3c896b6e217">

**Comment by damithc** [comment]
> Hi, I see that you did not add a milestone to the PR. Maybe you can try adding a milestone(shown at the right of the pull request page) to your PR, maybe v1.2?

Good observation @yyyaohhh 
@InfiBeyond does the above solve the problem?
