### ISSUE TITLE
Changing Value Proposition / Problem Addressed

### ISSUE THREAD

**Issue by lerxuann** [nus-cs2103-AY2324S1/forum#257]
We had submitted our target users, problem addressed, and value proposition in an earlier TEAMMATES submission in week 4/5, but after re-evaluating the goal of our app, we realised that we would like to propose a different value proposition compared to what we submitted at the start. Is it possible to change the problem addressed / value proposition in this stage of the tP?

**Comment by damithc** [comment]
@lerxuann you can change it any time. Just email me the new name, target audience, and the value proposition.
