### ISSUE TITLE
Query on v1.2 PR in individual tP progress tracker

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#258]
Hi Prof,

May I ask for the v1.2 PR in the individual tP progress tracker, if we would be penalised in the situation where the PR has been created and commits with functional code continually added before the deadline, but just not merged yet before the deadline? 

Thanks!

**Comment by damithc** [comment]
@lihongguang00 It's fine, provided the PR is merged eventually. Such overshooting of the deadline is not unexpected at early iterations as you are still getting used to the workflow and the code base -- just learn from the mistakes (e.g., think about why it couldn't get merged on time) and try to avoid them in future iteration.

**Comment by lihongguang00** [comment]
Understood. Thanks prof!
