### ISSUE TITLE
Clarify Workflow

### ISSUE THREAD

**Issue by Mohammed-Faizzzz** [nus-cs2103-AY2324S1/forum#259]
If some of my groupmates/myself have completed our features, but are failing the CI checks due to failing testcases/checkstyle/codecov issues, would it be okay if I/my other team members approved their PR so the others can fix the issues?

**Comment by damithc** [comment]
> If some of my groupmates/myself have completed our features, but are failing the CI checks due to failing testcases/checkstyle/codecov issues, would it be okay if I/my other team members approved their PR so the others can fix the issues?

@Mohammed-Faizzzz PR quality control decisions are left to the team's discretion.
That said, why is approval needed to fix issues? 
If you are proposing to _merge_ the CI-failing PRs first so that the problematic code becomes available in the main code base for others to fix the CI problems, this decision is up to your team.

**Comment by Tim-Siu** [comment]
> > If some of my groupmates/myself have completed our features, but are failing the CI checks due to failing testcases/checkstyle/codecov issues, would it be okay if I/my other team members approved their PR so the others can fix the issues?
> 
> @Mohammed-Faizzzz PR quality control decisions are left to the team's discretion. That said, why is approval needed to fix issues? If you are proposing to _merge_ the CI-failing PRs first so that the problematic code becomes available in the main code base for others to fix the CI problems, this decision is up to your team.

In such cases, can we merge the pull request to another branch of the team repo, and later merge the branch back to the master of the team repo? Will the contributions of all members be correctly tracked and credited?

**Comment by damithc** [comment]
> In such cases, can we merge the pull request to another branch of the team repo, and later merge the branch back to the master of the team repo? Will the contributions of all members be correctly tracked and credited?

@Mohammed-Faizzzz Sure. One downside is that the work will not be detected until that other branch is merged to the `master` branch. So, merge it to `master` as soon/often as you can.
