### ISSUE TITLE
Status not reflected in the Dashboard

### ISSUE THREAD

**Issue by yyyaohhh** [nus-cs2103-AY2324S1/forum#26]
Hello! I have completed and pushed the commits with tags on 24th August, but the Dashboard did not reflect the commits I have made from tag Level 3 to Level 6. Is there something I have done wrong?
<img width="780" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/275ec8f9-2c2f-4a54-a1c2-ef165b11ad3f">
<img width="310" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/35fe6a69-8c01-40ba-8cd6-0d4808632f2b">

<img width="1024" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/f01df43c-0c7b-42b2-9055-d123eea0c5d8">

**Comment by HugeNoob** [comment]
It seems like you haven't pushed your tags to GitHub.

When you run `git tag` on your machine, it only creates the tags in your local repository. Doing `git push` will only push your commits to the remote repository, and will not include the tags you have created locally. You have to do an extra step of `git push --tags` to push your local tags to the remote repository. 

See https://github.com/nus-cs2103-AY2324S1/forum/issues/22#issuecomment-1691864201 for an overview of what you should be doing.

You can confirm this by checking your repository.
(this is what yours looks like now)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/7296b97a-5a88-4ffc-b2ee-416bda86684d)

**Comment by damithc** [comment]
@HugeNoob is correct. 
@yyyaohhh Once the tags are in your fork, the dashboard will turn them green at the next update.

**Comment by yyyaohhh** [comment]
Thank you very much!!!
