### ISSUE TITLE
Request for the use of TestFX Library

### ISSUE THREAD

**Issue by kokrui** [nus-cs2103-AY2324S1/forum#261]
## Library

[TestFX](https://github.com/TestFX/TestFX)

## Purpose

I intend to use it for automated JavaFX GUI testing for the tp. TestFX is a library [mentioned in the course textbook](https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/testing.html#automated-testing-of-guis) as a viable library to perform automated JavaFX GUI testing.

## License

EUPL 1.1 (https://github.com/TestFX/TestFX/blob/master/LICENSE.txt)

**Comment by damithc** [comment]
Approved.
Note that it is not easy to get GUI tests running in a CI environment (e.g., CI is running on an environment without a screen). But it can be done e.g., the now defunct [AB4](https://github.com/se-edu/addressbook-level4) uses TextFX for GUI testing.

**Comment by kokrui** [comment]
Thanks!
