### ISSUE TITLE
Is improving code quality(abiding to OOP principles) of original codebase compulsory?

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#262]
I am wondering if we notice pieces of code in the original codebase that breaks OOP principles taught in our course, is it necessary for us to fix the code accordingly if it does not lead to a bug? Will these be penalised in PE if pointed out by peers? My concern is, changing and refactoring the code might cause certain regressions and lead to a bug, which will then be penalised to the individual that refactored the code if discovered, should an individual actually pick up this responsibility and risk in the aim of improving the overall code quality?

**Comment by damithc** [comment]
> I am wondering if we notice pieces of code in the original codebase that breaks OOP principles taught in our course, is it necessary for us to fix the code accordingly if it does not lead to a bug?

@yucongkoo It's optional. You can earn credit for doing so but not _required_ to do so.

 >Will these be penalised in PE if pointed out by peers? 

No penalty for existing internal design issues (e.g., OOP issues). But someone needs to take responsibility for bugs, even if they are inherited from AB3 or introduced during refactoring.

>My concern is, changing and refactoring the code might cause certain regressions and lead to a bug, which will then be penalised to the individual that refactored the code if discovered, should an individual actually pick up this responsibility and risk in the aim of improving the overall code quality?

Once some part of the code is claimed as done by you, you become responsible for code quality issues in that code e.g., coding standard violations. 

For bugs arising from refactoring, someone needs to take responsibility but it is up to the team to decide who (for example, a team can decide some members will do the refactoring but the rest will pitch in with reviews, and any bug arising from these refactorings will be shared by all team members). 

Any refactoring carries the cost of the extra effort needed to do it, and to deal with the possible regressions. The benefits are that a better design makes the code easier to work with, and can even reduces risk of further bugs. So, you need to weigh pros and cons for each case and choose whether to refactor or not.

**Comment by yucongkoo** [comment]
I see, thanks for clarifying!
