### ISSUE TITLE
Issue pushing on source tree

### ISSUE THREAD

**Issue by RSXIX** [nus-cs2103-AY2324S1/forum#263]
So I pulled my team's repo and am currently attempting to push my code on source tree. I get the following error.

For more context, I have this error occur countless times in the semester. I used CLI commands sometimes when I had issues, and even there, I am asked to produce my password or a Github TOKEN.

<img width="592" alt="Screenshot 2023-10-15 at 9 47 25 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/f37472de-ec85-4bfc-8b9f-c880d329a7d7">

**Comment by lamchenghou** [comment]
Hi, I think you could generate a Personal Access Token (classic) under GitHub's Developer Settings. From there, check workflow along with other repo permissions.

**Comment by lamchenghou** [comment]
I think this token will work after you enter it, till it expires.

**Comment by bnahor** [comment]
yep, that it what fixed the error for me

**Comment by ChangruHenryQian** [comment]
I faced the issue before. Basically you need to ensure that your PAT has `workflow` permission. Then you will have to make sure the tool you are using has the updated PAT.
