### ISSUE TITLE
Manually mark Week 7 Task as done in tP dashboard?

### ISSUE THREAD

**Issue by conradsoon** [nus-cs2103-AY2324S1/forum#264]
Hi, checking tP dashboard and I found out that one of my tasks is marked as undone.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/18553610/2826a4fe-b026-42c5-83fa-16d98f31e9b6)

However, I have made a PR during that week here (but I merged from master instead of merging from a branch). https://github.com/AY2324S1-CS2103T-T13-2/tp/pull/12

Is it possible for this task to be marked as done manually?

Sorry for the trouble!

**Comment by damithc** [comment]
@conradsoon Following the forking workflow is a requirement for that item to be marked as done. So, the current 'not done' status is correct.

**Comment by damithc** [comment]
To add, missing a tP deliverable  _occasionally_ will not affect tP marks, provided not too many such 'misses'.

**Comment by conradsoon** [comment]
Yep, fully understand prof! Could I still ask if you guys would still be willing to mark it as done in this case though? Would really appreciate it, but fully understand in any case since it's my own fault for not checking.

**Comment by damithc** [comment]
@conradsoon It is automatic. Any manual change will be overwritten at the next dashboard update.

**Comment by damithc** [comment]
> @conradsoon It is automatic. Any manual change will be overwritten at the next dashboard update.

@conradsoon Consequently, if a qualifying PR is added to v1.1 even at this stage, the item will turn to green. Wouldn't make a difference in terms of learning or grading though.
