### ISSUE TITLE
CodeCov fail causing CI fail when gradle.yml has been configured

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#265]
I refer to PR #75: https://github.com/AY2324S1-CS2103T-W08-1/tp/pull/75

The CodeCov here is failing as I added some lines of code to MainApp.java and some UI components where testing is not done.

Under my `.github/workflows/gradle.yml`, I have configured `fail_ci_if_error: false`. But my CI appears to still fail when CodeCov fails.

May I know if there are any known workarounds for this so that I can pass my CI?

Thanks! 😄

**Comment by damithc** [comment]
@craigtonlian the team can decide if the reduction in code coverage is justified, and merger the PR despite the CI failure.
