### ISSUE TITLE
./gradlew test, passes all tests in my IntelliJ but fails Java CI in team repo when I create PR

### ISSUE THREAD

**Issue by ChuanXinNg** [nus-cs2103-AY2324S1/forum#266]
I try to implement an import method to import data from .csv files.
I use relative path to get my .csv files from src/test/data/ImportDataTest in my ImportCommandParserTest, and the tests pass when I run ./gradlew test in my IntelliJ. However, after I create my PR, the Java CI shows that the checks on my test cases are not successful.

This is how I obtain my file path in ImportCommandParser.
```java
        String projectPath = System.getProperty("user.dir");
        String path = projectPath + "/" + args.trim();

        File csvFile = new File(path);
        if (!csvFile.exists()) {
            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, ImportCommand.MESSAGE_USAGE));
        }
```

This is how I create my file path to my test data.
```java
void parseCsvSuccess() {
        // Create a relative path to the ImportDataTest directory
        Path relativePath = Paths.get("src", "test", "data", "ImportDataTest");

        String fileName1 = relativePath + "/" + "test_data_successful.Csv";
        List<Student> expectedList1 = new ArrayList<>();
        expectedList1.add(AMY);
        expectedList1.add(BOB);

        // whitespace only preamble
        assertParseSuccess(parser, fileName1, new ImportCommand(expectedList1, fileName1));

        String fileName2 = relativePath + "/" + "test_data_no_subjects.Csv";
        List<Student> expectedList2 = new ArrayList<>();
        expectedList2.add(HOON);
        expectedList2.add(IDA);

        // whitespace only preamble
        assertParseSuccess(parser, fileName2, new ImportCommand(expectedList2, fileName2));
    }
```

If you all want to see my code, you all can get from [here.](https://github.com/ChuanXinNg/tp.git) 
The code are in branch-ImportData, the classes related are ImportCommand, ImportCommandParser, and ImportCommandParserTest.

The code passes the test case using ./gradlew test
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122215000/a8360881-22c5-4c19-8b92-4b4e9d0b8fab)

The code fails Java CI
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122215000/2bfd023f-7b88-429c-8213-35b63e923ce5)

**Comment by damithc** [comment]
@ChuanXinNg it might help if you share the link to the relevant PR as well.

**Comment by Bombbird2001** [comment]
Try changing .Csv to .csv in ImportCommandParserTest.java - I believe file names are not case-sensitive on Windows but are on Linux

**Comment by ChuanXinNg** [comment]
https://github.com/AY2324S1-CS2103T-W13-2/tp/pull/96

this is the link to the PR

**Comment by ChuanXinNg** [comment]
Wowww, thanks for the suggestion, it works now!!!!

**Comment by damithc** [comment]
Good catch @Bombbird2001 👍
