### ISSUE TITLE
Codecov Coverage Last 2 checks not passing

### ISSUE THREAD

**Issue by newway1814** [nus-cs2103-AY2324S1/forum#267]
Hi, Can someone tell me why these 2 checks are not passing, is it because of the new lines that i have added are not being tested?
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/6bc672bc-998a-4c02-adaf-6c2c691c940f)

**Comment by lihongguang00** [comment]
Hi, codecov is to ensure that your code is well tested.

To pass patch, you need to ensure that for new code that you are adding, at least ~75% of it needs to be well tested with Junit

To pass project, you need to ensure that overall ~75% of your whole project needs to be well tested with JUnit.

The way the % is calculated is based on lines tested i'm guessing, but i'm not too sure. Anyways you just have to do more testing of your code, and it should hopefully pass!

**Comment by aarontxz** [comment]
Yup the 2 checks requires your newly added lines to be tested with Junit test. I believe you are still allowed to merge even without passing these checks but just take note that you will still have to test these newly added lines of code eventually so might as well pass these two checks now.

**Comment by craigtonlian** [comment]
Another possibility (if you want the pretty green tick) is you can go to your Organisation's CodeCov page at https://app.codecov.io/account/gh/AY2324S1-CS2103T-W15-1/yaml and lower the passing threshold for codecov/project and codecov/patch.

Global YAML:
```
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5.0
```

This will allow CodeCov to pass the PR if your coverage dropped within 5% from the base commit. But do monitor the code coverage so you can ensure good overall coverage 😄

**Comment by ldinghan** [comment]
Yes, thorough testing of new lines that you have added is required to pass the codecov.
By thorough, it refers to testing the expected vs actual results of **BOTH** if-else paths, as well as whenever exceptions are thrown etc. Clicking on the "details" button next to the failing codecov checks would also show you which lines are not covered by tests. Alternatively, (a method i prefer) is to directly go into the "files changed" tab and scroll through it - the parts not covered by tests should be highlighted, and you could add these tests 1 by 1.

**Comment by newway1814** [comment]
Thank you so much for all the replies!
