### ISSUE TITLE
Will failing Code Coverage in CI affect grading?

### ISSUE THREAD

**Issue by lordidiot** [nus-cs2103-AY2324S1/forum#268]
My understanding is that to wrap up a milestone, our tagged version must pass CI

> CI passing for the version tagged/released.

If our tagged commit fails CI because of code coverage, will that count as an improperly wrapped up milestone?

**Comment by damithc** [comment]
> If our tagged commit fails CI because of code coverage, will that count as an improperly wrapped up milestone?

@lordidiot As it is OK to ignore Codecov failures in other commits, it is OK to ignore it for this purpose as well.
