### ISSUE TITLE
What to do if increment requires multiple actions (e.g. branch-then-merge with tags) but was already completed previously

### ISSUE THREAD

**Issue by wxwern** [nus-cs2103-AY2324S1/forum#27]
I understand that if some increments have been implemented in prior weeks, we can either tag the relevant commit or latest commit with said increment. However, what if an increment requires more actions than just a commit tag?

---

For example, in my case, I wrote documentation as I code by habit. Hence, I might have no commits to do in `branch-A-JavaDoc`, nothing to tag `A-JavaDoc` to, etc. 

Suppose I still: 
- create the `branch-A-JavaDoc` branch anyway, 
- tag the top commit with `A-JavaDoc`, and 
- push it with no additional commits (so `master` and `branch-A-JavaDoc` are still pointing to the same commit).

Would that be okay for the auto-grader, or should I intentionally leave some docs out just so I can make a commit with the branch?

Similarly, does this apply to all future increments which may require multiple steps, but are inadvertently completed previously?

**Comment by damithc** [comment]
@wxwern It's fine to omit a few iP git requirements if you can't find a meaningful way to comply. The scripts will flag them as 'not done' but that is fine, as you can get full marks even if you miss a small number of requirements.

Alternatively, 'faking' is fine too, as it will give you more practice on doing those git tasks. 

In this particular case, you can look through the existing JavaDoc comments to see if anything can be improved. If you find such places to improve, you have something to commit in the branch in concern.

In the end, the more important objective is to increase your competence in performing the tasks in concern. Making all 'green' in the dashboard is not as important.

**Comment by wxwern** [comment]
Thank you @damithc for the input.
