### ISSUE TITLE
Are we required to do testing on our GUI components?

### ISSUE THREAD

**Issue by keaganpzh** [nus-cs2103-AY2324S1/forum#271]
We recently did an overhaul of our UI and I'm not sure if we need to test the GUI aspect of the project, i.e. components rendering correctly, or UI elements responding correctly to user input, etc.

Furthermore, CodeCov screams at me for missing lines during testing (everything in the `ui` package) and I would like to know how others get around that.

Hope to get some clarity on this!

**Comment by damithc** [comment]
> We recently did an overhaul of our UI and I'm not sure if we need to test the GUI aspect of the project, i.e. components rendering correctly, or UI elements responding correctly to user input, etc.

@keaganpzh Automated testing of the GUI is not required, as AB3 doesn't do it either. But you still need to ensure it is working correctly e.g., by testing it manually.

> Furthermore, CodeCov screams at me for missing lines during testing (everything in the `ui` package) and I would like to know how others get around that.

You can ignore code coverage issues for parts of the code your team decided not to do automated testing.

**Comment by keaganpzh** [comment]
okay cheers prof!
