### ISSUE TITLE
Requesting for approval to use CalendarFX

### ISSUE THREAD

**Issue by techjay-c** [nus-cs2103-AY2324S1/forum#272]
## Library

[CalendarFX](https://dlsc.com/products/calendarfx/)

## Purpose

{We intend to use this library to include a calendar view in our ToothTracker App. We will only be using the Day View and Month View calendar, and the addition of appointments will still be via the CLI.}

## License

{Apache 2.0, pkg:maven/com.calendarfx/view@11.12.6}

**Comment by damithc** [comment]
Approved.
