### ISSUE TITLE
In our CI, are we allowed to generate the coverage report with a different runner?

### ISSUE THREAD

**Issue by kokrui** [nus-cs2103-AY2324S1/forum#273]
Following the approval of TestFX as an external library, our team has begun implementing automated GUI tests. As @damithc pointed out in his comment, https://github.com/nus-cs2103-AY2324S1/forum/issues/261#issuecomment-1763339592, getting the GUI tests running in CI might be difficult

We've successfully managed to get the GUI tests running in CI when the macOS or Windows Github Actions runner is used, but not for the ubuntu runner. Since it's been mentioned that GUI testing is optional in the first place (https://github.com/nus-cs2103-AY2324S1/forum/issues/271#issuecomment-1768943242), can we then proceed with:

1. Skipping UI tests for the Ubuntu Github Actions runner (dirtily implemented here: https://github.com/AY2324S1-CS2103T-T13-2/tp/blob/00b41c45deaa2091b55b45dbea2612b843b541e8/build.gradle#L24-L29)
2. Having our coverage report be uploaded by the MacOS (or Windows) runner instead of the Ubuntu runner, so CodeCov recognises our GUI test coverage (implemented here: https://github.com/AY2324S1-CS2103T-T13-2/tp/blob/00b41c45deaa2091b55b45dbea2612b843b541e8/.github/workflows/gradle.yml#L42)

**Comment by damithc** [comment]
@kokrui Kudos for getting the GUI testing to work.

We have no objections to 1 or 2.

**Comment by kokrui** [comment]
Thanks!
