### ISSUE TITLE
1.2 VS 1.2b: Must we group week 9 work as 1.2b or they can be under milestone 1.2?

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#276]
<img width="620" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/3bc86be9-448c-47ef-a3a6-bb2ea4590341">

Our Group tag all work under milestone 1.2. Is there a need for us to reorganize?

**Comment by damithc** [comment]
@s-peiran As v1.2b is optional, either way is fine. But the original intention was to get you to create two milestones v1.2 and v1.2b.

**Comment by s-peiran** [comment]
Thank you for the clarifications Prof
