### ISSUE TITLE
Query if this is considered a bug that needs to be fixed

### ISSUE THREAD

**Issue by flexibo** [nus-cs2103-AY2324S1/forum#277]
Let's say if I tamper with the JSON files (by putting an invalid datetime for example) so that when it loads, it still runs but it resets all the data to blank. Is this considered a bug that we need to fix?

**Comment by damithc** [comment]
Good question @flexibo 

Our stance of the expected level of support for editing the data file:

>**Handling manual edits to the data file:**  AB3 UG specifies the current level of support for manually editing the data file. At least that level of support should be supported in the new product as well.

So, the current AB3 behavior for this (i.e., resetting the data if the data file is not in the correct format) is considered acceptable i.e., not a bug

**Comment by flexibo** [comment]
Noted, thanks prof!
