### ISSUE TITLE
Phrasing of Issues in our team repo's issue tracker.

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2103-AY2324S1/forum#279]
Just to clarify, do **all** our issues (and issues associated to milestones) have to conform to the user story format, instead of just the user story specific ones?

If, let's say, we are working on a specific implementation that does not directly pertain to any single user story but is in itself a pre-requisite for the feature specified in the user story (and other relevant user stories) to be developed, can we create issues like `Storage: Fix persistence bug` or our own format, then assign those issues to the version milestones to better track and document our team's progress? This way, even if a user story or a feature specified has multiple components, each part can be assigned to different members, PRs, and issues so we can more easily evaluate our own progress.

**Comment by damithc** [comment]
> Just to clarify, do **all** our issues (and issues associated to milestones) have to conform to the user story format, instead of just the user story specific ones?

@sp4ce-cowboy just the user story specific ones

**Comment by sp4ce-cowboy** [comment]
@damithc Thank you prof
