### ISSUE TITLE
Checking whether file/directory exists in Level 7

### ISSUE THREAD

**Issue by brendanneojw** [nus-cs2103-AY2324S1/forum#28]
Hi all I would like to clarify if the checking of the file/directory that we are supposed to save to should be done:
1. At the start of the program, if file/directory doesn't exist then exit the whole program
2. Keep the programming running while taking user input, if file/directory doesn't exist, user can choose to create it and do not have to exit the whole program

**Comment by damithc** [comment]
Good question @brendanneojw 
From the admin side, we expect _you_ to decide the more **appropriate way to handle this situation**.
Let's see what others think about how to handle this situation.

**Comment by brendanneojw** [comment]
In my opinion, I think the 2nd option would be more intuitive and if deciding to go even more adventurous, the program can even create the directory and file for the user. Of course additional checks have to be done to ensure security and permission rights.

**Comment by inezkok** [comment]
I think that your bot should check if the file exists, if it does it should load that file at the start to show the previous tasks, if it does not it can create the file and maybe tell the user that it has created a file. Then after each command, it updates the file accordingly.

**Comment by leezhanpeng** [comment]
I think that exiting the programme shouldn't be the approach. If a user do have this problem, it's likely going to be a never-ending loop of the programme auto-exiting when run. Creating the missing file/directory sounds more logical to me!

**Comment by muhammadreyaaz** [comment]
Hello, I agree with @inezkok and @leezhanpeng. But I think instead of the user choosing whether he can create a file in the directory, a simpler approach would be to simply create it. I feel this would save time as well as accomplish the goals of the iP.

**Comment by larrywang0701** [comment]
From my experiences, commonly when your program needs to store files locally (I've used this before in my video game projects, about storing player records for the game), here is what I usually do:
```
First, check whether the specific file exists on the disk
  If the file not exists, use one of the two options below:
    --Create the file and initialize the file with initial contents. Then check whether the creation is successful or not. (Exception may happen when space is not enough, doesn't have permission (e.g.: Windows UAC) etc. ) and preceed to the next step
    --Use initial data for this user session, skip the next step and write data later in the write phase (actually I prefer this one)
  If the file exists:
    Preceed to the next step
Second, preceed read/write the file like normal. (the so-called "next step" in the above sentences)
```

So to your question, option 2 is much more reasonable than option 1 since users are not expected to create the data file by themselves in this situation. And what's more, I think you don't need to ask the user whether to save the file, just save it automatically to increase the ease of usage.
