### ISSUE TITLE
launching main on intellij does not show GUI on Laptop, but works fine on desktop and all other teammates' device

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#280]
Windows, JDK 11.0.15

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/041fab2e-2f08-419f-8c4d-3b98df5421fc)

Performed ./gradlew clean and ./gradlew build without errors.
IP application can launch without issues on problematic laptop.

<img width="269" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/71cd2b3d-ee56-49bb-8065-88944b4643aa">
Would i have to reinstall javafx?

Thank you for any inputs.

**Comment by damithc** [comment]
@s-peiran Is this the first time you are running the tP in this computer?

**Comment by damithc** [comment]
Something to try: delete the `preferences.json` file created by AB3 and run again (in case it saved some undesirable preferences in a previous run).

**Comment by s-peiran** [comment]
Thank you prof. That seems to fix the issue.
