### ISSUE TITLE
Is force-pushing (for unmerged PR) in order to edit previous commit messages allowed?

### ISSUE THREAD

**Issue by geraldngjx** [nus-cs2103-AY2324S1/forum#282]
May I ask if force pushing commits after rebasing to edit previous commit messages allowed? Due to the feedback from the previous automated tP review, I was informed that my commit messages were too long, hence I decided  to edit my commit messages for my current PR since it was not merged (hence this does not affect my team members branch history) but this requires a rebase and a force-push afterwards. Technically, I believe that it is a legitimate method in order to fix commit messages for accuracy (and I had done so with the knowledge that it does not affect my team member's commit history as the PR was yet to be merged) but I was wondering if I would be marked down for it. If it is approved, how do I ensure I do not get marked down during the practical as it is flagged that I force pushed in Github? Should I leave a comment message which informs my evaluator that it is approved? Thank you!

**Comment by damithc** [comment]
@geraldngjx If you push edited commits onto an unmerged branch that others haven't pulled from, the only downside is that the commits will appear as if done later than their original commit time. For example, a commit initially done in week 9 can appear as if it was done in week 10. Normally this wouldn't have a major impact but in some cases it can cause you to have no commits in some weeks -- this should not affect your marks if you have commits in at least 4 (out of 6) tP weeks.

**Comment by geraldngjx** [comment]
Thank you Professor Damith for the prompt response. I have committed changes in the previous week in another PR so this will not be an issue. Could I double confirm that it would not be considered a "bad software development practice" where I could be marked down? If it is not, should I leave a comment to inform the evaluator that the force-push to update the commit comment was approved?

**Comment by damithc** [comment]
@geraldngjx It is not a bad practice at all. In fact rebasing (and force-pushing) is a common practice. The only reason why we discourage using it in the tP is because it interferes with our tracking of weekly progress.

**Comment by geraldngjx** [comment]
I see! Thank you for clarifying, Professor!
