### ISSUE TITLE
Question regarding UML sequence diagram reference frames

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#283]
Lets say we have a sequence diagram and want to omit certain details(such as parsing of arguments), are we allowed to simply add a reference frame for parse argument that omit all those details, but do not actually provide the interactions that happen within the reference frame?

Using the example from the CS2103 website:
<img width="694" alt="Screenshot 2023-10-22 at 11 18 46 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/b4cc05de-57bd-4c6b-90fc-cbf7219ea1c5">
Are we allowed to omit the second (seperate) sequence frame that provides the details to get minefield appearance?

**Comment by damithc** [comment]
@yucongkoo If you omit the reference frame, mention that it has been omitted so that user knows not to look for it.

**Comment by yucongkoo** [comment]
@damithc I see, understood. Thanks.
