### ISSUE TITLE
Generics in Class Diagrams

### ISSUE THREAD

**Issue by B-enguin** [nus-cs2103-AY2324S1/forum#286]
Hi, I would like to ask what would be the appropriate  way to represent generic types that have been specified. Suppose a piece of code as below, what would be the best way to represent this relationship

    class foo<T> {}
    
    class bar<T> extends foo<T> {}

    class baz extends foo<Apple> {}

I believe the notes did specify on how to represent generic classes,
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/46633877/0abfdaf2-882b-4b11-a820-a41f8ac5fa46)

But I'm not so sure how we should represent relationships involving generic classes. Thank You

**Comment by damithc** [comment]
@B-enguin How far you get and which part did you get stuck in?

**Comment by B-enguin** [comment]
After Reading some sources online, I was thinking to represent it in the following format.

![Test](https://github.com/nus-cs2103-AY2324S1/forum/assets/46633877/dfdc9571-eb5e-495d-bda9-3cdfd00395f3)

However I am not sure if this is considered a valid format.

**Comment by damithc** [comment]
> After Reading some sources online, I was thinking to represent it in the following format.
> 
> ![Test](https://user-images.githubusercontent.com/46633877/277369347-dfdc9571-eb5e-495d-bda9-3cdfd00395f3.png)
> 
> However I am not sure if this is considered a valid format.

@B-enguin Good attempt. ~~Instead of the notation for implementing an interface (i.e., `<|-------`), use a dependency arrow (`<----`)~~ See https://github.com/nus-cs2103-AY2324S1/forum/issues/286#issuecomment-1775450233 instead.

**Comment by B-enguin** [comment]
Ah yes, sorry must have missed that out when I was trying to covert to a more general diagram.

![Test](https://github.com/nus-cs2103-AY2324S1/forum/assets/46633877/35640386-7601-4a17-b91c-e3b6ead77bce)

I think this would be more representative of 

    class foo<T> {}

    class baz extends foo<Apple> {}

However, would the representation format between the generic types be acceptable in the above diagram for use in this course?

**Comment by damithc** [comment]
@B-enguin consider this code (very similar to your example):

```java
class Foo<T> {
}

class Bar<T> extends Foo<T> {
}

class Goo extends Foo<String> {
}
```

The following matches the above code.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/9e852d06-d9c2-43d9-b140-8c97035d7c86)


In this course, you can omit the `<<bind>> <T -> String>` part as it wasn't covered (and the diagram is clear even without it) i.e.,
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/0ff04d3b-e2e2-4f0d-9ba3-5ac4a9c86039)

**Comment by B-enguin** [comment]
Okay thank you very much for the help Prof, I understand the format now.
