### ISSUE TITLE
Add features of keyboard shortcuts for TP

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2103-AY2324S1/forum#287]
One of the tp constraints states that:
Constraint-Typing-Preferred
The product should be targeting users who can type fast and prefer typing over other means of input.

If we wish to introduce keyboard shortcuts as new features in v1.3, is it considered violation of this contraints?

**Comment by damithc** [comment]
@mamayuan suppose the same outcome can be achieved using these three ways:
a) by typing a command
b) with a keyboard shortcut
c) with a GUI action

Given the target user can type fast, if you think `a` is faster than `b` and `b` is faster than `c`, you should implement `a` first, then `b`, and so on. However, which is faster depends on the exact feature. In some cases `c` might be fastest.

Also note the guidelines given under [Recommendation-CLI-First](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-constraints.html#recommendation-cli-first:~:text=Recommendation%2DCLI%2DFirst)

**Comment by mamayuan** [comment]
Noted. Thanks prof!
