### ISSUE TITLE
Request for using org.controlsfx.control.Rating

### ISSUE THREAD

**Issue by ncmathan** [nus-cs2103-AY2324S1/forum#288]
## Library

Rating 
https://controlsfx.github.io/javadoc/11.0.3/org.controlsfx.controls/org/controlsfx/control/Rating.html

## Purpose

To allow our target audience, project managers in software companies, to give a rating to other developers and view the rating in a user friendly format. This would allow the project manager to make a informed decision when deciding which developer to assign for a new project.

## License

https://github.com/controlsfx/controlsfx

**Comment by damithc** [comment]
Approved, and applies to the entire ControlsFx library.
