### ISSUE TITLE
JavaDoc conventions, AB3 or Java Coding Standard?

### ISSUE THREAD

**Issue by junhonglow** [nus-cs2103-AY2324S1/forum#289]
Some parts of AB3 currently uses the following convention for writing Javadoc.
```java
/**
 * Replaces the given person {@code target} in the list with {@code editedPerson}.
 * {@code target} must exist in the address book.
 * The person identity of {@code editedPerson} must not be the same as another existing person in the address book.
 */
public void setPerson(Person target, Person editedPerson) {
    requireNonNull(editedPerson);

    persons.setPerson(target, editedPerson);
}
```
Given the same piece of code, if I choose to follow the Java Coding Standard, I might expect something of the following instead, with the most notable difference being the uses of @ tags.
```java
/**
 * Replaces the given person in the list with the edited person.
 * The given person must exist in the address book.
 * The identity of the edited person must not be the same as an existing person in the address book.
 * 
 * @param target Person to be replaced in the address book.
 * @param editedPerson The person to replace the target with.
 */
```
Should Javadoc be written strictly following the Java Coding Standard? 
If so, I assume that we would not need to modify any previously written Javadoc in AB3?

**Comment by damithc** [comment]
@junhonglow `@param` tags can be omitted if they don't add value e.g., the description of the parameter is clear from its name or it is already implied by the main description of the method

**Comment by junhonglow** [comment]
Thank you for the clarification!
