### ISSUE TITLE
Is it fine to add .class to .gitignore so that I don't have to deal with manually adding each file?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#29]
Since we are asked not to submit .class files, I was wondering if I can update the .gitignore file to exclude .class files

I also made sure not to commit changes done to .gitignore, so it is purely for my convenience.

Would this be permitted?

**Comment by zhanyang01** [comment]
I did just that and i think it fine.

**Comment by JasonRay168** [comment]
> I did just that and i think it fine.

Alright thankss! I'll open this issue for around 1 more day to hear more about others opinions

**Comment by damithc** [comment]
> I also made sure not to commit changes done to .gitignore, so it is purely for my convenience.

@JasonRay168 It's fine to update the .gitignore file to fit your needs.

**Comment by leezhanpeng** [comment]
Don't think it will pose any problems, I updated .gitignore as I required.

**Comment by JasonRay168** [comment]
Thanks everyone and Prof, I'll close the issue now
