### ISSUE TITLE
Request for using iText 7

### ISSUE THREAD

**Issue by jibtaf** [nus-cs2103-AY2324S1/forum#290]
## Library

[itext7](https://github.com/itext/itext7)

## Purpose

It can help the target user of our app, HR managers, to easily generate pay slips.

## License

[LICENSE](https://github.com/itext/itext7/blob/develop/LICENSE.md)

**Comment by damithc** [comment]
Approved. Looks like there is a commercial aspect to this product, so, use at your own risk.
