### ISSUE TITLE
💡 Auto fix imports on save

### ISSUE THREAD

**Issue by JCSnap** [nus-cs2103-AY2324S1/forum#291]
I used to order the imports manually, which is very time-consuming manually. So here's the configuration for you to auto order your inputs every time you save on Intellij!

1. Go to `Settings/System Preference` > `Tools` > `Actions on Save` and tick `Optimise Imports`
2. Go to `Code Style` > `Java` >  `Imports` > `General` and tick `Use fully qualified class names`. This makes sure all uses of `*` are expanded
3. Under the same `Imports` tab, go to `Import Layout` and rearrange the imports as such:
a) import static all other imports
b) <blank line>
c) import javax.*
d) import java.*
e) <blank line>
f) import all other imports
4. Click `Apply`
<img width="729" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/111076731/8cc08184-f724-4439-962d-4da7d9eff057">

That's it!

**Comment by damithc** [comment]
Thanks for sharing this @JCSnap 
Is it same as the info given in the AB3 DG [here](https://se-education.org/addressbook-level3/SettingUp.html#:~:text=Configure%20the%20coding%20style) ?

**Comment by JCSnap** [comment]
> Thanks for sharing this @JCSnap Is it same as the info given in the AB3 DG [here](https://se-education.org/addressbook-level3/SettingUp.html#:~:text=Configure%20the%20coding%20style) ?

Oh I did not notice the DG guide, it is similar!
