### ISSUE TITLE
Condition in branch nodes and multiple end nodes for activity diagram?

### ISSUE THREAD

**Issue by zhonghan721** [nus-cs2103-AY2324S1/forum#293]
In the textbook, all the conditions for alternate paths in activity diagram are specified as guard conditions.
May I know if it is okay to specify the conditions in the branch nodes instead.

Also, is it possible for an activity diagram to have multiple end nodes, to specify the end of the activity after throwing an exception.

Thank you.

**Comment by damithc** [comment]
> In the textbook, all the conditions for alternate paths in activity diagram are specified as guard conditions.
> May I know if it is okay to specify the conditions in the branch nodes instead.

@zhonghan721 follow the convention in the textbook, for consistency i.e., use guard conditions.



> Also, is it possible for an activity diagram to have multiple end nodes, to specify the end of the activity after throwing an exception.

Yes, it's fine.

**Comment by zhonghan721** [comment]
Noted. Thank you Prof!
