### ISSUE TITLE
Week 10 Team Progress Task: Released v1.3(trial) jar file on GitHub in week 10

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#294]
Hi, can I ask for the above tp task requirement, is it detected by the script or manually by the tutor? My team has done up the release (in week 10) but it is not being detected currently. 

If it is detected by the script, is there anything specific that needs to be done to be detected? 

Thanks!

**Comment by damithc** [comment]
@papataco14 it is checked by a script. The script previously checked if there is a jar file released during the expected period, and either release tag or the name starts with `v1.3`. I guess yours failed the second check. I've removed the second check from the script. It should get detected in the next dashboard update.

**Comment by papataco14** [comment]
Ah, ok. The release is now detected. Thanks for the help!
