### ISSUE TITLE
tP Page Deployment using MarkBind not fully rendering

### ISSUE THREAD

**Issue by revdrag** [nus-cs2103-AY2324S1/forum#298]
Hi, after pushing changes on the `DeveloperGuide.md` file, and the page has been successfully deployed, I realised that after a certain point/line, the page does not load the remaining portion of the md file. If anyone knows what is the issue, please give some advice, thanks!

A snippet of the part where the md file stop rendering is below. The link to the repo file is [here](https://github.com/AY2324S1-CS2103T-T15-3/tp/blob/master/docs/DeveloperGuide.md?plain=1). The link to the website where it cuts off is [here](https://ay2324s1-cs2103t-t15-3.github.io/tp/DeveloperGuide.html#edit-student-feature).

```
The following activity diagram summarizes what happens when a user executes an `edit /s` command.
<puml src="diagrams/EditStudentActivityDiagram.puml" alt="EditStudentActivityDiagram">

// Stop loading beyond this line.
Given below is an example usage scenario and how the edit student operation behaves at each step.
...
```

**Comment by kokrui** [comment]
I believe you need to close the `puml` tag, i.e. switch from

`<puml src="diagrams/EditStudentActivityDiagram.puml" alt="EditStudentActivityDiagram">`

to 

`<puml src="diagrams/EditStudentActivityDiagram.puml" alt="EditStudentActivityDiagram" />`

**Comment by damithc** [comment]
@revdrag tip: You can check the rendering locally, which means you can catch this kind of issues while editing the code.

**Comment by damithc** [comment]
> I believe you need to close the `puml` tag

@kokrui good catch 👍

**Comment by revdrag** [comment]
> I believe you need to close the `puml` tag, i.e. switch from
> 
> `<puml src="diagrams/EditStudentActivityDiagram.puml" alt="EditStudentActivityDiagram">`
> 
> to
> 
> `<puml src="diagrams/EditStudentActivityDiagram.puml" alt="EditStudentActivityDiagram" />`

Thanks! @kokrui
