### ISSUE TITLE
Request for using JavaWuzzy

### ISSUE THREAD

**Issue by jibtaf** [nus-cs2103-AY2324S1/forum#299]
## Library

[JavaWuzzy](https://github.com/xdrop/fuzzywuzzy#javawuzzy)

## Purpose

Our user needs to type the reason for a deduction or benefit added. With this library used, they do not need to type the exact wording of the reasons in order to match the `Reason` enum.

## License

[LICENSE](https://github.com/xdrop/fuzzywuzzy/blob/master/LICENSE)

**Comment by damithc** [comment]
Approved.
