### ISSUE TITLE
Is Decoupling TaskList and Storage Necessary?

### ISSUE THREAD

**Issue by KamiliArsyad** [nus-cs2103-AY2324S1/forum#30]
I personally think creating two different classes for list of tasks and storage is not necessary. The reason for which is as follows:
1. One cannot exist without the other. TaskList will be stored using Storage and Storage serves only as an intermediary between file storage and TaskList; a task already achieved by `IO::File` class.
2. One cannot operate without the other. TaskList's method is continuously calling Storage's method and Storage's method needs TaskList's data passed to it to operate.
3. Neither is used by other feature. At least as of right now, neither TaskList nor Storage is used by any other class and it is hard for me to see in which scenario this won't be the case.

As such, we've created a scenario where we try to separate two tightly coupled systems to achieve what could be done better (in terms of performance, ease of development, and design) by simply implementing additional methods. In case I missed anything, I would love to hear more reason as to why creating the Storage class is actually necessary. Thank you

**Comment by damithc** [comment]
This is a good topic for discussion @KamiliArsyad Thanks for raising it. Let's see what others think.

**Comment by wxwern** [comment]
A situation where having a `Storage` class may help is if you plan to store other data files alongside your task list in the future (for example, user settings), and you want to ensure they are stored in a common system- or user-defined location.

Example: Data storage conventions are different across different OSes. For instance, these are possible conventions you might follow (may differ depending on environmental variables or OS versions):

- Windows: `~/AppData/Local/AppName/`
- macOS: `~/Library/Application Support/AppName`
- Other Linux/Unix variants: `~/.config/AppName`

where `~` represents the home directory.

By having a separate `Storage` class, even if it is simply a wrapper on top of the built-in `File`, you can abstract away any operations dealing with the base directory. For instance, when providing a relative path to `Storage` to save a file to, it may auto-create a missing base directory behind the scenes, then auto-prepend the appropriate base directory to the provided relative path before saving.

With this separate wrapper class, any new files used by future features can easily share the same behaviour above.

**Comment by KamiliArsyad** [comment]
Hm I see what you mean, thanks for the response. Elaborating on your case, however, unless we want to impose an implicit rule on how the data is formatted for every kind of data (which we don't), we need to basically create an interface with "save" and "load" method that will be implemented differently for each data format. Then we proceed by creating a `TaskStorage implements Storage` class which will be tightly coupled with our `TaskList` class.

While I understand that this is preferable in projects that have multiple features with other data files, I think creating a `Storage` as a class (and not interface) for our project is rather useless; it doesn't solve the problem you mentioned and at least the first two issues I brought up with this design still persist.

**Comment by wxwern** [comment]
I believe the reasons mentioned in 1 and 2 are actually two sides of the same coin. 

Notice `File` and other relevant Java classes themselves are also classes that:

1. require the user to continuously call it, and 
2. requires data passed to it to function. 

and hence technically exhibits the same problem you noted in reason 2. 

With that, since `Storage` is an intermediary of `File` operations (reason 1) it hence makes sense that it exhibits the same "dependency" on each other like `File` (reason 2). 

I feel these design concerns aren't really a big issue if even Java is organised this way.

---

Personally, I think whether you decouple TaskList and Storage is okay either way:

- **IO operations in Storage:** 
  - Since the provided `File` Java APIs also have ways to load and save with different formats via polymorphism, if the purpose of `Storage` is to be a higher-level IO wrapper for internal files, having said class could possibly help in code organisation and future convenience.
  - See also: Java's `BufferedReader`, which is designed to take in and wrap another reader such as `FileReader` for improved performance via buffering.

- **IO operations in TaskList**: 
  - Since it's only used in one place at the moment and we are focusing on iterating on the iP, calling Java File IO APIs within `TaskList` directly has no real downsides yet.

**Comment by damithc** [comment]
A general guideline: When in doubt, go for the simpler solution. You can switch to a more complex alternative in a later iteration, when you are sure the benefits outweigh the additional complexity.

**Comment by eyelessrhyme7** [comment]
I appreciate the thoughtful discussion on whether to have a separate Storage class in our project. I'd like to share some strengths and advantages of having a dedicated Storage class, despite the tight coupling with TaskList that we've observed:

1. Isolation of Saving/Writing Operations:

One of the key benefits of introducing a Storage class is that it provides a clear separation of concerns. It isolates the task of saving and writing data from the rest of the application logic. This separation makes our codebase more maintainable and adheres to the Single Responsibility Principle (SRP), a fundamental principle in software design.
By encapsulating file I/O operations within the Storage class, we reduce the risk of scattering file-related code throughout the TaskList class. This isolation can help us manage and debug these operations more effectively.

2. Error Handling and Abstraction:

Another advantage of having a Storage class is the opportunity it provides for centralized error handling and abstraction. We can implement error-checking and exception handling in one place within the Storage class, ensuring that any issues related to data storage are handled consistently.
Furthermore, as pointed out by another participant. if we decide to support different data storage formats or locations in the future, the Storage class can serve as an abstraction layer. This allows us to change the underlying storage mechanisms without affecting the TaskList class or other parts of our application. It promotes flexibility and future-proofing.

3. Code Organization and Readability:

From a code organization perspective, having a Storage class can improve the overall readability of our code. It abstracts away low-level file operations and provides a more human-readable interface for saving and loading data. This can make the code within the TaskList class cleaner and easier to understand. 

4. Potential for Future Features:

While our project may not currently have additional data storage needs beyond the TaskList, designing a Storage class can set a foundation for future features. If we ever need to manage other data files alongside the task list, having a dedicated Storage class will make it easier to extend our codebase without introducing unnecessary complexity. Also helps to facilitate reading of same file to multiple task lists and vice versa, helping with versions of files and tasks list.
