### ISSUE TITLE
Request for approval for OpenCSV Library for import/export commands

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#300]
## Library

[OpenCSV](https://opencsv.sourceforge.net/apidocs/index.html)

## Purpose

For allowing import and export CSV functions.

## License

{Apache License 2.0}
https://docs.oracle.com/en/cloud/saas/field-service/22d/falid/c-opencsv-5-6.html#c_opencsv_5_6

**Comment by damithc** [comment]
Approved.
