### ISSUE TITLE
Concern about dashboard tracking of commits

### ISSUE THREAD

**Issue by freshcabbage123** [nus-cs2103-AY2324S1/forum#303]
May I know if the dashboard is able to track contributions if I added my name to .gitconfig? The reason i added my name was because I noticed duplicate authors in my commit history which has not posed a problem thus far. As such, I tried to follow my friend's gitconfig and added my own name. 

However, I only recently noticed that my username is not being shown on commits. As such, I am wondering if my contributions can still be tracked by dashboard. If not, what are the measures I should take to rectify the issue?

Thanks in advance!

### Current Problem: Commits from the past week
<img width="1249" alt="Screenshot 2023-10-27 at 9 19 34 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/79037826/0e3d41df-fe53-4722-99c8-acdc1e21c521">

### Previous Problem I encountered and tried to fix: Duplicate authorship
<img width="1249" alt="Screenshot 2023-10-27 at 9 24 12 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/79037826/21941848-43cd-4618-a832-1470556d2487">

### Current .gitconfig layout
<img width="571" alt="Screenshot 2023-10-27 at 9 25 17 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/79037826/4ec630f7-3dc4-44e2-af5e-359cbf8563a6">

**Comment by damithc** [comment]
@freshcabbage123 you can check from the [tP code dashboard](https://nus-cs2103-ay2324s1.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other)

**Comment by freshcabbage123** [comment]
> @freshcabbage123 you can check from the [tP code dashboard](https://nus-cs2103-ay2324s1.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other)

@damithc Prof, I have checked the dashboard and it does reflect commits from my GitHub username as expected. I have since changed my .gitconfig's name back to my GitHub username instead of my actual name. May I know if there is any way to include the commits I have done under 'Alan Lim' as part of the tP code dashboard tracking?

### Current .gitconfig
<img width="357" alt="Screenshot 2023-10-27 at 6 49 26 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/79037826/0f2e3d22-e196-4c0f-97f9-d9abfbbe04ba">

**Comment by damithc** [comment]
> May I know if there is any way to include the commits I have done under 'Alan Lim' as part of the tP code dashboard tracking?

@freshcabbage123 We have updated our scripts to include that as well. It will take 1-2 more update cycles before those commits are reflected in the dashborads.

**Comment by freshcabbage123** [comment]
@damithc Thank you for the clarification prof
