### ISSUE TITLE
Test coverage not detected?

### ISSUE THREAD

**Issue by btaanish** [nus-cs2103-AY2324S1/forum#304]
I've been adding test classes for the tP, but even after running a test class, for eg. XXCommandTest.java, its coverage is not reflected, i.e, XXCommand.java shows 0% coverage for methods or lines of code, even though i'm explicitly using them inside the test assertions.

Any advice on how to improve this would be really helpful.

TIA!

**Comment by damithc** [comment]
@D-Limiter If there is a PR that illustrates this problem, it might help to share it here.

**Comment by btaanish** [comment]
Thank you for the advice Prof. The PR link can be found [here](https://github.com/AY2324S1-CS2103T-T11-4/tp/pull/201)

**Comment by damithc** [comment]
@D-Limiter As this PR is quite big, perhaps you can specify one specific example of the problem? e.g., pick a specific test case, the code it is expected to cover, and where does it say the said code is not being covered.

**Comment by btaanish** [comment]
Thanks Prof, i can run the tests now. Seems to be have been a directory path issue for tests.
