### ISSUE TITLE
Request for using Apache POI

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#306]
## Library

[Apache POI](https://poi.apache.org/)

## Purpose

{We intend to use the library to read data of Microsoft Excel format files by POI-XSSF. The data is used as user input words and their translations for our flashcard app and to support the `load` command.}

## License

[License](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by damithc** [comment]
Approved.
