### ISSUE TITLE
Are asterisks imports allowed for FXML files?

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#307]
Good day Prof,

May I ask if asterisks imports are allowed for FXML file, because they are not flagged by checkstyle, and they are also employed in the base AB3 codebase.

`MainWindow.fxml` example:
<img width="470" alt="Screenshot 2023-10-28 at 3 16 18 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/84987837/59d8202e-dc50-499f-88fd-d381eaccdc47">

Thanks!

**Comment by damithc** [comment]
Good catch @lihongguang00 
For the purpose of grading, we consider the Java coding standard as applying to .java files only, but you are welcome to (and it would be good to) follow the same in fxml files as well.
