### ISSUE TITLE
JavaDoc in tp

### ISSUE THREAD

**Issue by yyyaohhh** [nus-cs2103-AY2324S1/forum#309]
May I know if JavaDocs is graded for tp? The original JavaDocs for the AB3 is also in a different format from the one we are taught, may I know which standard should we follow?

**Comment by damithc** [comment]
@yyyaohhh Yes, the code you write should have JavaDocs, as required by the coding standard. Yes, JavaDocs are graded. 
How do existing JavaDocs differ from the one in the coding standard?

**Comment by lhy-hoyin** [comment]
> The original JavaDocs for the AB3 is also in a different format from the one we are taught

@yyyaohhh perhaps you can provide some examples of which files (of AB3) contains JavaDocs which are different from what was taught? So that the teaching team can look into it.

**Comment by yyyaohhh** [comment]
I think some methods did not have `@param` in JavaDocs even though they accept some parameters. One example will be [AddCommandParser.java](https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/logic/parser/AddCommandParser.java)

**Comment by damithc** [comment]
> I think some methods did not have `@param` in JavaDocs even though they accept some parameters. One example will be [AddCommandParser.java](https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/logic/parser/AddCommandParser.java)

@yyyaohhh It's OK to omit `@param` if including them doesn't add any new information (e.g., the parameter name is already descriptive enough or they are already described in the method description)

**Comment by yyyaohhh** [comment]
Thank you very much for the clarification!
