### ISSUE TITLE
Do bindings constitute cyclic depedencies?

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#310]
Hi all,

For part of my UI in JavaFX, I have separate classes for the container and elements contains within the container, and I need the dimensions of the container and it's elements to be consistent (Or else the container might outgrow the elements contained). However, the dimensions are only calculated in the element class, and it would not make sense for the dimensions to be calculated in the container class. In this case, if I were to use bindings to synchronize their dimensions, would this be creating some cyclic dependency?

Thanks!

**Comment by damithc** [comment]
@lihongguang00 It might help to share the relevant code, or point to a relevant PR.

**Comment by lihongguang00** [comment]
> @lihongguang00 It might help to share the relevant code, or point to a relevant PR.

Hi prof,

Unfortunately, I do not have any PR or code to point to because I have chosen to take another route around it. 

But to give more context for the purposes of discussion, our project involves a calendar system (similar to NUSMods), and we have a `StackPane` (container) that holds the 1. background of the calendar and 2. the event cards for the calendar. However, because our team wanted to make the calendar only display the necessary time periods to minimise clutter (similar to how NUSMods will change the time periods displayed according to the earliest class and latest class of the day), this requires the width of the background to be updated (as more hours displayed will require more pixels). As a result, the container is not synchronized with the background, resulting in spaces in the container that are not filled by the background. Hence, the intention was to use binding as a means of synchronising their widths.
