### ISSUE TITLE
Updating of overall DG

### ISSUE THREAD

**Issue by mfjkri** [nus-cs2103-AY2324S1/forum#311]
How much of the DG are we expected to update to make in line with the latest project?

Referring to the part on `Design` section and how much of our new features need to be included in the `Implementation` details.

**Comment by damithc** [comment]
@mfjkri You can use the following for guidance i.e., as much as you think is needed to achieve the two objectives given

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/30b36de5-5de0-454c-908c-8ec164433e0c)

You can use AB3 DG as a benchmark for the first objective.

**Comment by mfjkri** [comment]
I see thank you!
