### ISSUE TITLE
Update iP for code reuse credit

### ISSUE THREAD

**Issue by InfiBeyond** [nus-cs2103-AY2324S1/forum#312]
Are we still allowed to update our iP to give credit for code reuse?

I just realized I missed giving proper credits in parts of my code.

Thank you very much!

**Comment by damithc** [comment]
@InfiBeyond Yes, go ahead.

**Comment by InfiBeyond** [comment]
After we update our iP, do we need to release a new jar file?

**Comment by damithc** [comment]
No need, unless there is a change to the functionality.

**Comment by InfiBeyond** [comment]
I think I need to change some pictures used in my iP (due to copyright). Do I need to update my jar file in this case?

**Comment by damithc** [comment]
Yes, in that case better to update the JAR file as well (if the images are packaged in side the JAR file)

**Comment by InfiBeyond** [comment]
I realized that part of the code missing proper credits is in the previous iterations of iP which have since been deleted. I'm wondering what can we do about that. Thank you!

**Comment by damithc** [comment]
@InfiBeyond It's good enough if the current version of the code is properly credited for reuse.
