### ISSUE TITLE
Best course of action for imported library class name conflict

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#314]
Hi all,

My team has decided to import an external library, however, some classes that we are interested in using from the library have the same class name as the code that we have written. Are there any ways to resolve this without needing to refactor our entire codebase? Alternatively, online sources have cited the possibility of using fully qualified names for the class that will be utilised less, but I was wondering if this breaks any SWE principles. Any advice would be greatly appreciated, thank you!

**Comment by SPWwj** [comment]
Hi @lihongguang00 I am a senior from previous batch,
For your case you may choose to use:
- Fully Qualified Class Names: 
   - When you have two classes with the same name, you can use the full package name along with the class name to specify which one you're referring to. For instance:
    ```
    com.myapp.MyClass myClassInstance = new com.myapp.MyClass();
    com.externallibrary.MyClass externalClassInstance = new com.externallibrary.MyClass();

    ```
- Use an Adapter Pattern: 
  -  If you find yourself needing to use both classes frequently and don't want to keep using fully qualified names, consider wrapping the external library class in an adapter. This will not only resolve the naming conflict but can also serve to isolate your codebase from direct dependencies on the external library.
    ```
    public class ExternalLibraryClassAdapter {
    private com.externallibrary.MyClass instance;
    
    public ExternalLibraryClassAdapter() {
        this.instance = new com.externallibrary.MyClass();
    }
    
    // add methods to interact with the instance
   }

    ```
    
Hope this help ;).

**Comment by IsabelChong** [comment]
Hi! I am a senior from the previous batch. I understand your concern and I do not think this breaks any SWE principle from my understanding.

However, using the fully qualified names for just one or two classes would really depend on how many instances of the class you are calling, how long the imports look visually as this affects how easy to read the code is, and also if it introduces any sort of confusion in your code (if read by other humans). 

I think a good step ahead would be to discuss this with your team members thoroughly and choose a standard to follow throughout your code, but let's look at what others think too!

**Comment by lihongguang00** [comment]
Hi @SPWwj and @IsabelChong,

Appreciate the advice! I'll discuss it with my team, thank you!
