### ISSUE TITLE
Question about Constraint-PDF-Friendly

### ISSUE THREAD

**Issue by lordidiot** [nus-cs2103-AY2324S1/forum#315]
My team currently uses Markbind for our UG and DG. We've made use of the expandable panel `<panel>` with default expanded.

Will this violate the following [constraint](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-constraints.html#constraint-pdf-friendly)? It should not cause issues when we generate the PDF as its expanded by default.

**Comment by damithc** [comment]
@lordidiot It should be fine, provided the panel is expanded by default and the full content appear in the PDF file.
