### ISSUE TITLE
What are constants in java.

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#317]
Quoting the following coding standard we are supposed to adhere to:
```Constant names must be all uppercase using underscore to separate words.```

I am wondering what are constants in java generally, does static final imply constant? More specifically, I am stuck when deciding how should I name private static final variables.

**Comment by ruiyangzh** [comment]
Hi, as far as I’m aware from when I asked a similar question, static final variables are not necessarily constants. Take for example a static final list, as I can still modify this list by adding in new entries even after it’s been initialized. 
Constants can’t be determined just from the modifiers; you have to ensure that the variable is deeply immutable.

**Comment by ruiyangzh** [comment]
This is dependent on the type of the object, by the way, as Google style guide mentions, since just you intending for the variable never to be modified is not enough to call it a constant.

**Comment by ruiyangzh** [comment]
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

**Comment by yucongkoo** [comment]
Ahh totally agree with that, however, for the sake of following the naming convention, do you think that we should name private static final variables as constants? Or do we have to analyse whether the variable is indeed immutable and is actually a constant before applying the naming convention to it?

**Comment by ruiyangzh** [comment]
Yes you should check if it’s actually immutable. Otherwise you are indicating to readers of the code that the variable is a constant even though that’s not true. Access modifiers like public/private shouldn’t affect whether something is a constant.

**Comment by yucongkoo** [comment]
@ruiyangzh Okayy thank you so much for your information!
