### ISSUE TITLE
Question regarding level of support required for handling manual edits to data file

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#318]
I understand that we should be able to support the same level of support AB3 provides when it comes to handling manual edits to data file, but how to we actually define the same level of support? If an editing the data file will cause the application to crash(not able to launch), will this be considered a bug? Or is our application suppose to be able to always handle invalid data files and fail gracefully(launch with an empty dataset)

**Comment by damithc** [comment]
@yucongkoo As per AB3 UG (which states the current level of support for editing the data file manually), only valid edits will be supported. If the file is invalid, the app will start with an empty file (not crash). So, crashing will be considered a bug.

**Comment by yucongkoo** [comment]
@damithc okay, thanks prof.
