### ISSUE TITLE
Testing of Import Csv Function during PE

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#320]
Suppose we have an import csv command for our tP that imports the data from a csv file into the system.
The csv file would have to be placed in the same directory as the `jar` file in order to be imported.

How should we prepare our release `jar` file with a template csv so that it can be conducive for testers to test it without having to manually create a csv file?

**Comment by damithc** [comment]
@craigtonlian You can upload it to your tP website and give the link in the UG where the import feature is described (assuming it is useful to real users as well).
