### ISSUE TITLE
Grading of tp

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2103-AY2324S1/forum#321]
Hi Prof,
May I know how grading will be affected if a feature written by another individual is overwritten and improved upon by another? Will the first person be deemed as having contributed nothing to the implementation of the feature since it was completely overwritten by the second individual?

@damithc

**Comment by damithc** [comment]
@XihuaZ 
When grading contribution, we go by what your team members say that you contributed (you get a chance to submit objections if you don't agree with their view).
When grading code quality, we grade you based on the code the [code dashboard](https://nus-cs2103-ay2324s1.github.io/dashboards/contents/tp-progress.html) attributes to you. Note that you can override the code authorship auto-detected by the code dashboard (which is based on Git data), using `@@author` tags (see [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking) for more details).
