### ISSUE TITLE
Increasing of CodeCov in v1.4

### ISSUE THREAD

**Issue by seantehds** [nus-cs2103-AY2324S1/forum#322]
Hi Prof,

My group and I would like to check if increasing CodeCov values in v1.4 would be possible? We assumed that the increasing of CodeCov through the writing of test cases would be classified as fixing bugs, as we would be writing these tests in order to find such bugs.

**Comment by damithc** [comment]
@seantehds Yes, it is allowed. More details [here](https://nus-cs2103-ay2324s1.github.io/website/schedule/week12/project.html#:~:text=improving%20the%20testing%20aspect).

**Comment by seantehds** [comment]
Okay, thank you prof!
