### ISSUE TITLE
Validity of bugs in PE

### ISSUE THREAD

**Issue by leezhanpeng** [nus-cs2103-AY2324S1/forum#323]
Hi all, I'd like to ask a question about reporting bugs explicitly discouraged in the documentation. 

For instance, if the user guide warns against following a particular command sequence, which, as expected, resulted in a bug. 

Or if modifying the data file, despite being cautioned not to in the guide, breaks the app, should we still report these issues, or are they unlikely to be accepted due to prior documentation?

**Comment by damithc** [comment]
@leezhanpeng 

> For instance, if the user guide warns against following a particular command sequence, which, as expected, resulted in a bug.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/b62ad939-93dd-46f9-ab21-4c4516e7243b)


So, depends on if the instructions given are _reasonable_ or just a 'cover up' for a bug that should have been fixed.

> Or if modifying the data file, despite being cautioned not to in the guide, breaks the app, should we still report these issues, or are they unlikely to be accepted due to prior documentation?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/b051b1e0-82e7-4f30-845f-f52086e29dd9)

Also related https://github.com/nus-cs2103-AY2324S1/forum/issues/318

**Comment by leezhanpeng** [comment]
I see, alright thanks prof!
