### ISSUE TITLE
Requesting permission to use Apache Commons Numbers Library

### ISSUE THREAD

**Issue by jedkohjk** [nus-cs2103-AY2324S1/forum#324]
Hi friends,

Our team just saw the "Constraint-External-Software" constraint on the course website, which states that we have to request to use third party libraries/services before using them. We've already based much of our project on (this library)[https://mvnrepository.com/artifact/org.apache.commons/commons-numbers-fraction] before seeing the constraint on the website. We hope we would get the permission to use it, else we may have to implement it ourselves. :worried:

Thank you!

## Library

[Common Numbers Fraction](https://mvnrepository.com/artifact/org.apache.commons/commons-numbers-fraction)

## Purpose

Use fractions to handle rational numbers

## License

[Apache](https://commons.apache.org/proper/commons-numbers/commons-numbers-fraction/)

**Comment by damithc** [comment]
Approved.
