### ISSUE TITLE
PE: type of tests/behaviour to be deemed as a Bug

### ISSUE THREAD

**Issue by saltedfishxx** [nus-cs2103-AY2324S1/forum#325]
Hello, I would like to clarify on what kinds of bugs are considered valid for PE, in relation to the ambiguity of the UG.

**Scenario 1:**
1. UG did not state whether a command parameter is case-sensititve (e.g. Command `addClass class/CLASS_NAME`, where `CLASS_NAME` is not specified as case-sensitive, so an example value of `CLASS_NAME` will be `class1`)
2. When executing another command that uses the same parameter value but with different casing (e.g. `assignClass 1 class/cLaSS1` ), the command succeeds in execution.
3. However, the tester is unable to deem if this is a bug or intended feature due to the different casing.

Do we consider this feature to be a bug, as there is ambiguity in the UG? 

**Scenario 2:**
1. UG did not state what considers a command parameter value to be invalid (e.g. `addPerson n/NAME, p/PHONE`, it is unknown what values are invalid for `PHONE`.)
2. When executing the command, an error occurred (e.g. `addPerson n/Alice, p/1234567E` results in error)

Do we consider this feature to be a bug, as there is ambiguity in the UG?

**Comment by damithc** [comment]
@saltedfishxx There are some guidelines about determining bugs [here](https://nus-cs2103-ay2324s1.github.io/website/schedule/week12/project.html#3-polish-the-deliverables) Let me know if there are any remaining doubts. In general, either the behavior should follow natural expectations of a user or the the specific behavior should be clearly specified in the UG.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/b5bf2a3b-6072-4257-b694-d4dda2804b37)
