### ISSUE TITLE
Questions regarding v1.4 and PE

### ISSUE THREAD

**Issue by AryanG01** [nus-cs2103-AY2324S1/forum#326]
Good morning everyone,
I wanted to clarify some doubts i had regarding v1.4. Firstly, can I confirm if we are still abl;e to make UG and DG changes next week. Lastly, it is a bit late, but any tips for PE. What's the thought process like as you go ahead and try to find bugs?
Thanks.

**Comment by eyelessrhyme7** [comment]
Yes, both the UG and DG submissions for v1.3 are draft submissions. The final submissions are due later, along with the v1.4. Although for the purpose of PE-Dry Run, teams should try to ensure that their UG is as close to expected behaviour so that the testing team can test appropriately.

**Comment by damithc** [comment]
> Yes, both the UG and DG submissions for v1.3 are draft submissions. The final submissions are due later, along with the v1.4. Although for the purpose of PE-Dry Run, teams should try to ensure that their UG is as close to expected behaviour so that the testing team can test appropriately.

Good answer @eyelessrhyme7 


> Lastly, it is a bit late, but any tips for PE. What's the thought process like as you go ahead and try to find bugs?

This is a good topic to discuss and share strategies. Thanks for raising it @AryanG01 
BTW, there are two tips given [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-ped.html#:~:text=team%27s%20releases%20page.-,Testing%20tips,-Use%20easy%2Dto).

**Comment by AryanG01** [comment]
Thanks a lot for the answers everyone.
