### ISSUE TITLE
PE-D Jar Release after 10 am

### ISSUE THREAD

**Issue by mfjkri** [nus-cs2103-AY2324S1/forum#327]
Which jar release do I use if the group I am assigned to re-released a new jar **after** 10 am today on Friday?

Also can I include any coding standard violations (checkstyle) or should it be purely based on the jar file using the UG (not supposed to look at the code).

**Comment by damithc** [comment]
> Which jar release do I use if the group I am assigned to re-released a new jar **after** 10 am today on Friday?

@mfjkri The latest.



> Also can I include any coding standard violations (checkstyle) or should it be purely based on the jar file using the UG (not supposed to look at the code).

Given [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-ped.html#b-what-to-test-2)
