### ISSUE TITLE
PE-D and PE

### ISSUE THREAD

**Issue by dhruvir29** [nus-cs2103-AY2324S1/forum#328]
Can I ask if we are able to use 2 screens (eg. our laptop and an external monitor) for the PE? Also are we allowed to access any material/website we want online/on harcopy?

**Comment by damithc** [comment]
@dhruvir29 No screen count restriction for PE-D but only one screen allowed for PE. Detailed instructions for PE are given https://nus-cs2103-ay2324s1.github.io/website/admin/tp-pe.html
