### ISSUE TITLE
Participation for Week 12 and 13

### ISSUE THREAD

**Issue by InfiBeyond** [nus-cs2103-AY2324S1/forum#329]
I'm wondering since we don't have tutorial nor after-lecture quizzes for weeks 12 and 13, how will our participation marks be calculated?

Thank you!

**Comment by damithc** [comment]
@InfiBeyond In the weekly schedule page, you can identify those participation points bearing deliverables from the `(P)` icon e.g.,

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/d4d3d60b-2389-4029-b271-0be3d4f9cb6c)

**Comment by InfiBeyond** [comment]
Thank you!
