### ISSUE TITLE
Request for the use of GSON library

### ISSUE THREAD

**Issue by TehOPanas** [nus-cs2103-AY2324S1/forum#33]
## Library

GSON (com.google.code.gson:gson:2.10.1)

## Purpose

I intend to use it for the save feature, where I convert my save data directly into JSON and load from it.

## License

Apache 2.0 license agreement (https://github.com/google/gson/blob/main/LICENSE)

**Comment by damithc** [comment]
@TehOPanas Approved.

**Comment by lhy-hoyin** [comment]
Hello @TehOPanas,
It looks like your issue has been resolved. If that is the case, perhaps you can close this issue. Otherwise, perhaps you can elaborate on what you still wish to clarify.
