### ISSUE TITLE
Clarification about PE

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2103-AY2324S1/forum#330]
During PE Dry-Run today, we did not examine the DG of the product. But based on the information on the website, we will need to examine both DG and UG in the actual PE. May I just confirm that the information on the website is accurate?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/97677245/a548f316-5aaf-473d-a7ef-4f965f427f54)

**Comment by damithc** [comment]
@mamayuan Yes, correct. PE is longer and covers the DG as well.

**Comment by mamayuan** [comment]
> @mamayuan Yes, correct. PE is longer and covers the DG as well.
Noted. thank you!
