### ISSUE TITLE
Regarding bugs/feature flaws related to UI

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#331]
I wanted to ask about how to handle bug reports related to UI.

My group had added UI buttons for features that we want to put in our Planned Implementation section in the DG, but did not plan to implement now. Our intention was to have these buttons present but disabled to remind users that these were features that were coming to the product in the future. However, we had failed to disable these buttons when we did a release.

As part of v1.4, we are allowed to correct unintentional errors, but we aren't allowed to make any UI changes.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/115881359/6099d2fb-9eae-461c-80ec-4e739e20dbfa)

Can I ask how our group should handle this issue?

**Comment by damithc** [comment]
@WZWren I've reworded that as follows:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/eb43bd9c-c231-4be6-90be-aa65a1f7cc5f)

So, you can go ahead and disable those buttons.

**Comment by WZWren** [comment]
OK, thank you prof!
