### ISSUE TITLE
Tweaking error messages for consistency

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#333]
Suppose we have a bug report as shown below:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108467437/2979b7db-de32-42dd-a02b-f2ed79a58143)

Would we be allowed to adjust this error message in v1.4 considering that the current text is not 'incorrect' according to the specifications below:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108467437/d178fb4d-2ed4-4df0-931a-c67e62da73f0)

**Comment by damithc** [comment]
@craigtonlian If the current message is not incorrect, not allowed to change it.
