### ISSUE TITLE
Pull Request not Approved

### ISSUE THREAD

**Issue by wjacobw** [nus-cs2103-AY2324S1/forum#334]
Hi Prof,

My pull request for week 11 was not approved for some reasons, and now I had no PR for week 11. I wonder how this will affect my tp grade? Thank you!

@damithc

**Comment by damithc** [comment]
@wjacobw missing an occasional weekly tP deliverable should not affect marks. Our grading always has a safety buffer to absorb such occasional 'misses' -- we all miss a few things now and then :-p.

**Comment by wjacobw** [comment]
I see... got it thanks prof!
