### ISSUE TITLE
What should be considered as an "enchancement" in the planned enhancements section?

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#335]
If I have different fields in my application (for e.g. Name, Company Name), and we wish to allow for non-alphanumeric characters as input for those fields, can we group them together as planned enhancement of allowing non-alphanumeric characters for string inputs for those fields? The logic for string validation for those fields are the same, currently.

**Comment by damithc** [comment]
@papataco14 If it is the a single validation rule change (e.g., allow non-alphanumeric characters), applied for similar fields, for the same reason, and can be implemented in one place, it is OK to group as one enhancement.
But if it is two different rule changes (e.g., allow non-alphanumeric characters, make input case insensitive), it should be considered two changes.

**Comment by papataco14** [comment]
Oh i see, thank you!
