### ISSUE TITLE
Bug involving floating point number

### ISSUE THREAD

**Issue by aexolate** [nus-cs2103-AY2324S1/forum#337]
We have a salary field that is implemented as a float. Sometimes, there is floating-point error (e.g. $1000.00000001), but we only planned to display it up to 2 decimal points such as ($1000.00).

1. Can we change our implementation to use integers instead of floats? Will that be considered a feature-change?

2. Can we still change our attribute to be strictly integer instead of floating point values?

**Comment by damithc** [comment]
@aexolate If this causes _incorrect_ results (e.g., balance is 10.00001 when it should be 10.00), you may fix it.
Furthermore, currency amounts are expected to be shown with two decimal points only (i.e., precision level no finer than a cent) -- unless the context of your application demands a higher precision. So, that can be fixed as well.

**Comment by aexolate** [comment]
@damithc Thank you!
