### ISSUE TITLE
UI window size bug or enhancement

### ISSUE THREAD

**Issue by jedkohjk** [nus-cs2103-AY2324S1/forum#338]
Hi friends,

My team had previously implemented a feature where we dynamically fixed the minimum window size based on the users' screen resolution. This was done because our app displays quite a lot of data and we didn't want the window size to be too small.

This feature was implemented before the feature freeze and was in our PE-D jar file.

However, after the PE-D, we realised that if the user changes their settings (sets a smaller screen resolution) after launching our app, the app becomes unusable as the minimum window size will become too big. This would violate one of the TP constraints, where the app should be usable on 150% at 1280 x 720.

We found a solution where we can listen for changes in screen resolution and re-set the minimum window size when such an event triggers.

As this issue causes our app to become unusable when it crops up, we think of it as a bug and want to fix it. However, we wanted to confirm that setting an event trigger as described is not considered an enhancement.

Would appreciate guidance on the matter!

Thank you!

**Comment by damithc** [comment]
@jedkohjk Is there a workaround the user can apply if this happens? e.g., kill the app and relaunch

**Comment by jedkohjk** [comment]
Oh yes, that would fix the issue. Thank you!
