### ISSUE TITLE
UI startup size issue

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#339]
This issue is similar to #338 . However, currently at startup, the app launches at a non-optimal screen resolution, in which you cannot view all the information. Are we allowed to fix this bug by resizing the page on startup for the optimal resolution?

**Comment by damithc** [comment]
@AlagappanRa is the user able to resize the application manually? If so, it will be just a one-time extra step (as the app saves the current size for future use), and starting with a more optimal size can be left as a future enhancement.

**Comment by AlagappanRa** [comment]
Yes to the first qn. And understood for the future enhancement part. Thank you!
