### ISSUE TITLE
How to make change build.gradle?

### ISSUE THREAD

**Issue by AlainS87** [nus-cs2103-AY2324S1/forum#34]
I do not understand how I should make change to build.gradle to make it work. It gives me this error when i run the program. 
![dad9366392214eca7b0cb961666715d](https://github.com/nus-cs2103-AY2324S1/forum/assets/50228466/fc9c911b-f181-4ffb-b716-00a362914bb1)
![ec1c10a4e43d14fbed672bdbf1a3e47](https://github.com/nus-cs2103-AY2324S1/forum/assets/50228466/22aede08-02a6-40e1-a328-e1569a81b2ef)
![7bf069a0919627310cd84f6c967d013](https://github.com/nus-cs2103-AY2324S1/forum/assets/50228466/77748946-e1bc-4370-be78-b8986fd288df)
![cc3c923c0080a6f21aabfb4d48996c5](https://github.com/nus-cs2103-AY2324S1/forum/assets/50228466/e7e51493-bfc3-4499-b96a-e6c409bbd731)

**Comment by AlainS87** [comment]
BTW my main() is inside ChatbotAlain.java

**Comment by sopa301** [comment]
My mainClass doesn't have the java part, so it's like "alain.ChatbotAlain". Maybe it's that?

**Comment by jiakai-17** [comment]
In your commit [eb7ee36e19a68ee666531b5ff0a7246361f19ee0](https://github.com/AlainS87/ip/commit/eb7ee36e19a68ee666531b5ff0a7246361f19ee0), I noticed you moved your files out of the `src/main/java/` folder. I think that you should try putting your `alain` package in the `src/main/java/` folder.

The structure should look something like this:
```
ip
├── src
│   └── main
│       └── java
│           └── alain
│               ├── AlainException.java
│               ├── ChatbotAlain.java
│               ├── Deadlines.java
│               ├── Events.java
│               ├── Storage.java
│               ├── Task.java
│               ├── TaskList.java
│               ├── ToDos.java
│               └── Ui.java
```

Then change the `application` field in `build.gradle` to:
```
application {
    mainClass.set("alain.ChatbotAlain")
}
```

**Comment by B-enguin** [comment]
As @jiakai-17 has mentioned, you should place your package in the `src/main/java/` folder, Gradle's Java plugin assumes that your code will be in that directory, unless set otherwise. You may see the gradle documentation for more details, [The Java Plugin](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout)

**Comment by IsabelChong** [comment]
A great and very detailed discussion guys! Just a senior dropping in. 
@AlainS87 looking at your latest commit you should be on the right track already! 👍
Do enquire if you have any more related problems , if not you can close the issue if its resolved.
