### ISSUE TITLE
Regarding number of bugs for PE and PE-D 

### ISSUE THREAD

**Issue by tjch-o** [nus-cs2103-AY2324S1/forum#340]
If I happen to evaluate a team that has many bugs worth reporting, and I so happen to have raised less bugs than other testers testing the same project while still reporting more bugs than the average of 9 to 10, will I be penalised for not matching the number of bugs other testers have found?

**Comment by damithc** [comment]
@tjch-o In PE grading, we give full marks if the tester has found at least a certain percentage of the bugs, or a certain number of bugs, **whichever is lower**. In both cases we consider bug type, severity, etc. not just the raw bug count.

In  PE-D, it depends on the evaluation of the receiving team. Again, you get full marks if you meet at least a certain bar.
