### ISSUE TITLE
Markbind print-to-pdf removes component background colors

### ISSUE THREAD

**Issue by kokrui** [nus-cs2103-AY2324S1/forum#341]
When we Print-to-PDF our User Guide, what appears as a light blue box on the website

<img width="616" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/29654756/6eb7e194-7c7d-4886-bcb1-cd57356c57d8">

Becomes a white box with a light blue outline in the PDF

<img width="759" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/29654756/90d2d00f-de1d-46ea-aaa2-c2b2ad7fe0ed">

Does anyone know any way to avoid this?

**Comment by damithc** [comment]
@kokrui I believe this is a built-in optimization for printing (to save ink, and also, to preserve readability in black and white print).
Let me check with the MarkBind team to see if there is a way to disable/override this behavior. In the meantime, you can also consider [`seamless` and `light` style boxes](https://markbind.org/userGuide/components/presentation.html#boxes) that have light backgrounds but still stand out.

**Comment by kokrui** [comment]
our cs2101 tutorial-mate @zhonghan721 told us that their group found a solution -- when we perform the printing-to-pdf we can enable this `Background graphics` option and the bg colors will be preserved!

<img width="393" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/29654756/85859fae-af69-4b52-ba3f-a71738a2546a">

**Comment by conradsoon** [comment]
thank you @zhonghan721

**Comment by damithc** [comment]
> our cs2101 tutorial-mate @zhonghan721 told us that their group found a solution -- when we perform the printing-to-pdf we can enable this `Background graphics` option and the bg colors will be preserved!
> 
> <img alt="image" width="393" src="https://user-images.githubusercontent.com/29654756/280643591-85859fae-af69-4b52-ba3f-a71738a2546a.png">

Nice. I too forgot about it, but it is mentioned in [our instructions](https://se-education.org/guides/tutorials/savingPdf.html).
