### ISSUE TITLE
Question regarding the feature freeze

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#342]
May I confirm whether are we allowed to change our choice of flags/prefixes after the feature freeze.

For example, the following is our current command format:
<img width="856" alt="Screenshot 2023-11-06 at 10 51 09 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/e76b629e-f7dc-4fb9-a009-cfe86ec20dd5">

Are we allowed to change one of the prefixes to another prefix, say changing `t/<tag>` to `tg/<tag>`?

**Comment by damithc** [comment]
@yucongkoo See [here](https://nus-cs2103-ay2324s1.github.io/website/schedule/week12/project.html#:~:text=Can%20we%20tweak%20the%20command%20format%3F)

**Comment by yucongkoo** [comment]
@damithc Okay thank you prof.
