### ISSUE TITLE
PE Prewritten Materials Question

### ISSUE THREAD

**Issue by cbj252** [nus-cs2103-AY2324S1/forum#344]
Apologies, I was looking at https://nus-cs2103-ay2324s1.github.io/website/admin/tp-pe.html and didn't find an answer:

For the PE, are prewritten notes (both physical and digital) allowed?

**Comment by damithc** [comment]
@cbj252 Yes, you can use any existing digital/physical notes during the PE.

**Comment by cbj252** [comment]
Alright, thank you prof!
