### ISSUE TITLE
Clarification of a feature change

### ISSUE THREAD

**Issue by rionshocker** [nus-cs2103-AY2324S1/forum#345]
Hi Prof, my team would like to ask if removing a part of a feature, in this case, the last bullet point in the attached image right before the examples, be considered a type of feature change?
![Screenshot 2023-11-06 at 8 14 09 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/114156943/5babc731-a3ff-40d4-b943-f8dcdcc6d748)
For context, this part of the feature isn't working as intended and raised as a bug due to an error in the code, thus we were thinking of removing this part.
Thank you!

**Comment by damithc** [comment]
@rionshocker yes, removing it is allowed.

**Comment by rionshocker** [comment]
Thank you!
