### ISSUE TITLE
Question regarding writing our PPP

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#346]
I am in the midst of writing my PPP, and I came across a UI component that I wrote(which is used by multiple features to display their information), I was wondering whether this UI component implementation is considered a new feature or an enhancement to existing features as I don't feel like it is actually a new feature, but it is not an existing feature enhancement too.

**Comment by damithc** [comment]
@yucongkoo It doesn't matter which category you put that in. What matters is that it is something you contributed to the project. PPP is used primarily by your team members to estimate your contribution to the project (and by the teaching team, but only if there is a dispute regarding the level of contribution).

**Comment by yucongkoo** [comment]
@damithc I see, thank you prof!
