### ISSUE TITLE
Feature freeze question

### ISSUE THREAD

**Issue by aexolate** [nus-cs2103-AY2324S1/forum#347]
We have an `export FILE_PATH` command that exports the data file to the specified file path. However, an empty name file name gave unexpected behaviours on mac devices when used like this: `export .json`.

Will adding a check and adding a new error message that the file name must be non-empty be allowed in v1.4? since it seems to meet the criteria that 

> Q5: Can we tweak validity checks for a user input, or error/exception handling?
> A: Only if the current behavior causes the software to crash, to give incorrect results, or make it unusable for typical users.

**Comment by damithc** [comment]
> However, an empty name file name gave unexpected behaviours on mac devices when used like this: `export .json`.

@aexolate what is the exact behavior when that happens?

**Comment by aexolate** [comment]
@damithc It was reported that the file could not be found in the same directory. It might have been written as a hidden files which is not the intended behavior.

**Comment by damithc** [comment]
@aexolate While the error message is not ideal, it is a 'garbage-in, garbage-out' situation (the user shouldn't have entered an empty filename to begin with) that doesn't cause any harm. So, in the interest following a strict feature freeze, I think for now you can just mention in the UG that the filename should be a non-empty string. You can also list it under a planned enhancement, to avoid a penalty.

**Comment by aexolate** [comment]
@damithc Thanks prof! Another issue was when the user entered `export /`. The application would get a NullPointerException in v1.3 as the code did not consider the case of missing file name. Can a new error message be introduced to warn users when their path does not consist of the file?

**Comment by damithc** [comment]
> @damithc Thanks prof! Another issue was when the user entered `export /`. The application would get a NullPointerException in v1.3 as the code did not consider the case of missing file name. Can a new error message be introduced to warn users when their path does not consist of the file?

Yes, this should be fine.
