### ISSUE TITLE
Request to use GSON library

### ISSUE THREAD

**Issue by woojiahao** [nus-cs2103-AY2324S1/forum#35]
## Library

[GSON](https://github.com/google/gson)

## Purpose

I wish to use GSON to parse and handle JSON files for saving data files

## License

Apache License 2.0 (https://github.com/google/gson/blob/main/LICENSE)

**Comment by Merrickneo** [comment]
Hi @woojiahao, you can refer to issue #33 where this question has previously been addressed.

**Comment by woojiahao** [comment]
I understand, but I thought requests to use external libraries are approved individually

**Comment by damithc** [comment]
@woojiahao Once a library is approved for one student/team, others can use it as well. No need to request again. I will mention that in the course website.

**Comment by woojiahao** [comment]
Ah, alright, understood, thank you! @damithc @Merrickneo
