### ISSUE TITLE
Question on feature freeze and logging enhancements

### ISSUE THREAD

**Issue by ruiyangzh** [nus-cs2103-AY2324S1/forum#350]
Hi, wanted to ask if improvements to logging are allowed/will be noted negatively if not improved. I couldn't find any issues on this and I don't think it's mentioned anywhere in the CS2103T website. Thanks for helping!

**Comment by damithc** [comment]
@ruiyangzh Yes, logging can be improved during the feature freeze. Yes, logging is factored in when grading code quality.

**Comment by ruiyangzh** [comment]
Okay thank you Prof!
