### ISSUE TITLE
Question regarding feature flaws

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#353]
For deciding between two alternatives for a certain behaviour of a feature, since it is impossible to get the best of both worlds, is justifying that the pros of the current behaviour outweigh the cons sufficient for the bug to be categorised as not in scope?

Specifically saying, our product has a feature that allows users to add or delete multiple tags in one command, we have decided to ignore deletion of non-existing tags (as we believe that it is better not to disallow the command that may include multiple tags to update just because of one error tag), however, this will cause a problem of error message not being specific enough(say the user deletes only one non-existing tag, the error message will say that the person is not updated). Originally I was planning to include this in my planned enhancements, but I felt that it was like an either A or B choice, its not possible to get both A and B.

Are there any suggestions to handle these kinds of situations?

**Comment by damithc** [comment]
@yucongkoo Specifically, what are the alternatives you are trying to choose from?

**Comment by yucongkoo** [comment]
@damithc The design alternatives and decision are stated [here](https://ay2324s1-cs2103t-w16-2.github.io/tp/DeveloperGuide.html#aspect-deletion-of-non-existing-tags). The problematic behaviour is as reported [here](https://github.com/AY2324S1-CS2103T-W16-2/tp/issues/256), which I totally agree too, but I'm not quite sure what I can to resolve this problematic behaviour if I were to keep my original design choice(which I think has more benefits).

**Comment by damithc** [comment]
@yucongkoo Note that there are other alternatives. Two off the top of my head are: proceed but give a warning, ask user to confirm before proceeding

However, you are not allowed to change behavior during this time unless it is a bug.

As for https://github.com/AY2324S1-CS2103T-W16-2/tp/issues/256, the current error message is not incorrect but it could also be misleading/confusing to the user, which pushes this case a bit towards a bug. So, a possible fix that minimizes code changes is to add something like the following to the error message, if appropriate: `(possible reasons: the specified tag does not exist)`

**Comment by yucongkoo** [comment]
@damithc I think the updating of error message would indeed help, but am I allowed to update this(i.e. is this considered a bug and can be fixed now)? If yes, as we allowed adding of existing tags too, maybe I include that in our error message too?

**Comment by damithc** [comment]
> @damithc I think the updating of error message would indeed help, but am I allowed to update this(i.e. is this considered a bug and can be fixed now)? If yes, as we allowed adding of existing tags too, maybe I include that in our error message too?

Yes, these two changes can be allowed. I assume these will be two simple string insertions.

**Comment by yucongkoo** [comment]
@damithc Okay, great. Yeah indeed simple string insertions will do the job!
