### ISSUE TITLE
How should I draw the elements of an ArrayList in an object diagram?

### ISSUE THREAD

**Issue by glenngnng** [nus-cs2103-AY2324S1/forum#354]
Forgive the bad handwriting:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/69976907/50dedc7c-a9c0-4cc9-9b74-49c1c57c6c2c)
I am trying to draw the elements of an arraylist in order to show the changes after certain commands have been executed. I.e. the presence of elements or absence. 
But, how should I name the elements? Would index 1,2,3... suffice? or simply Person?

**Comment by damithc** [comment]
@glenngnng Don't feel like this _has_ to be an object diagram. You can use some other visualization e.g., a table

index | `Person` object
----|----
0| John
1| Adam
