### ISSUE TITLE
Penalty for breaking feature freeze

### ISSUE THREAD

**Issue by Cloud7050** [nus-cs2103-AY2324S1/forum#356]
May I ask what the penalty for breaking the feature freeze is? For example, if we were to submit a product that has a merged code change which the graders deem a feature enhancement as opposed to a bug fix. I would appreciate being directed to more information on this aspect of grading, such as perhaps a link to highlight of the course website.

**Comment by damithc** [comment]
@Cloud7050 `-1` per team member, per violation. Can be higher if the change is more drastic.
If you have merged such a change already, you can revert the change to avoid the penalty.

**Comment by Cloud7050** [comment]
Understood, thank you.
