### ISSUE TITLE
Determining whether misleading error message is a bug.

### ISSUE THREAD

**Issue by TehOPanas** [nus-cs2103-AY2324S1/forum#357]
Here's some context for our project, we enforces the implementation that no 2 contacts can have the same phone number or email.
However, our error message is not telling the accurate reason for doing so like the screenshot provided below of one of the tester for our PE-D.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/35374526-d5dd-4479-b13f-09bada089b95)

So I would like to ask if this is considered an bug or feature flaw because, it's is suppose to tell user that have entered duplicate value but it shows a somewhat unrelated message.

Below is our constraint on the values in UG.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/b87a7223-fa8c-49a9-abfd-23b084a8548c)

**Comment by damithc** [comment]
@TehOPanas The error message is not incorrect, given that phone number is used as the identity field. 
During the feature freeze, you can make this clear in the UG i.e., the fact that if the number is already present it will be treated as the person already exists.
Giving a more precise error message can be a future enhancement.

**Comment by TehOPanas** [comment]
Got it, thanks prof.
