### ISSUE TITLE
PE-D bug processing progress

### ISSUE THREAD

**Issue by bhnuka** [nus-cs2103-AY2324S1/forum#359]
Our tutor asked us to update them regarding the bug processing progress. Would it be fine to just list the issue numbers, how we triaged them (i.e what their type and severity was) and who was assigned to fix it? Or are we required to go more in-depth in terms of a full breakdown from start to finish on how we categorised each issue in terms of type and severity/ how we decide who has to take on which issue? Thank you!

**Comment by damithc** [comment]
@bhnuka You can use [this example](https://nus-cs2103-ay2324s1.github.io/website/schedule/week12/project.html#:~:text=Our%20team%27s%20mid%2Dv1.4%20progress) for guidance

**Comment by bhnuka** [comment]
Thank you!
