### ISSUE TITLE
TP code dashboard count

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2103-AY2324S1/forum#360]
I have noticed that the number of code changes on my part actually decreased by quite a bit compared to what I saw a few weeks ago even though i having been working on tp this period. I think this caused by changes over the same part of code later by my teammates. May I check whether this will effect my effort marks during grading…

**Comment by damithc** [comment]
@mamayuan 

tP contribution level of each member is decided primarily based on peer evaluations from team members (inputs from the teaching team is used only if there is no consensus in the team). So, the code attribution in the tP code dashboard doesn't matter for that purpose, normally. Nevertheless, we recommend that you ensure the tP code dashboard at least roughly reflects who contributed which part of the code. 

Also note that your code quality will be evaluated based on the code attributed to you in the tP dashboard. For this aspect, it is important that the tP code dashboard is not too far off from the real code authorship of the codebase.

If needed, you can override the LoC attribution using `@@author` tags, as explained [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking).

Also relevant is [this](https://nus-cs2103-ay2324s1.github.io/website/schedule/week12/project.html#:~:text=6-,Ensure%20the%20code%20is%20RepoSense%2Dcompatible,-Ensure%20your%20code).
