### ISSUE TITLE
UI Bug or Feature Flaw Question

### ISSUE THREAD

**Issue by tyouwei** [nus-cs2103-AY2324S1/forum#361]
Hi, we have a question regarding on a bug that we currently have for our UI. 
Here is the brief overview:

1. We originally intended for the ListCells in our UI to be selected whenever an add, edit, or view command is executed as shown below.
2. Commands that delete or shuffle the ordering of the list such as delete, find/filter, and sort will then deselect all the ListCells.

However one of our testers has brought to our attention that the sort command does not deselect the ListCells.

The problem is that we did not document this in our UserGuide, because this minute feature is meant to be purely cosmetic and to avoid confusion for users.

In such a scenario, is my team allowed to fix this bug? Given that this cosmetic feature is not present in the UserGuide?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/93871694/2b0ffb57-8cb7-444a-9e0d-ac7e4ef34c3b)

**Comment by damithc** [comment]
@tyouwei can this lead to a UI state where the app is giving the user incorrect information? e.g., the details shown on right is for a different person than the one in the selected cell 
If so, can you specify the sequence of actions leading to that state and why the information is incorrect?

**Comment by tyouwei** [comment]
There is no output of incorrect information. However, it just has this behavior whereby the ListCell in this example below is selected, but there is nothing shown on the right panel. Our original intended behavior was for it to be deselected to avoid confusion.

But because this intended behavior was not documented anywhere, we are not very sure if it would be classified under a Feature Flaw or a Functionality Bug.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/93871694/f1cb5289-43fd-4e1a-a29c-1efc3a926ff6)

**Comment by damithc** [comment]
This can be allowed to fix, as it results in a UI anomaly where a cell is selected but it's information is not appearing in the form.
On a related note, it is fine for the UG to not specifically mention this kind of intuitive/natural UI behaviors, as users will know what to expect.
