### ISSUE TITLE
Approval for correction of unintended behaviours

### ISSUE THREAD

**Issue by geraldngjx** [nus-cs2103-AY2324S1/forum#363]
I understand that there is a feature freeze in v1.4 and I believe that the changes I am making are fixing unintended behavior which we did not foresee in our application. However, may I verify that these can be done?

- Fix multiple prefixes allowed for notePerson issue (For example, notePerson 1 1 r/Likes to dance. r/Likes to swim) - This is an unintended behaviour that can be fixed simply. This does not change how the feature works.
- Incorrect command result output (This is yet again another unintended behaviour that can be fixed easily without changing how the feature works.)
- Fixing unintended behaviour of the command

P.S. The following changes are made based on the fact that the outcome is incorrect or unintended and there are no additional features added or changed. I was wondering due to the gray area between what can and cannot be changed, will we be penalized if we have incorrectly classified certain changes as "bug fixes" but it was actually a "feature change". I have made the following changes already and was wondering if I could push this code to the main repo, hence I hope to seek clarification before doing so. Hope to be able to be advised on this! Thank you.

**Comment by damithc** [comment]
@geraldngjx 

> * Fix multiple prefixes allowed for notePerson issue (For example, notePerson 1 1 r/Likes to dance. r/Likes to swim) - This is an unintended behaviour that can be fixed simply. This does not change how the feature works.

What happens in this case? I assume either the first or the last occurrence is taken? Either is not incorrect, and hence not a bug, unless the UG specify a different behavior. So, you can document the current behavior clearly in the UG, rather than change the code. Any change in behavior you wish to do can be given as a _planned enhancement_.
 

> * Incorrect command result output (This is yet again another unintended behaviour that can be fixed easily without changing how the feature works.)

Need more specifics. e.g., what's the current behavior and how do you propose to change it?

> * Fixing unintended behaviour of the command

Same as above.

> I was wondering due to the gray area between what can and cannot be changed, will we be penalized if we have incorrectly classified certain changes as "bug fixes" but it was actually a "feature change".

Yes, there will be penalty for feature freeze violations. So, if in doubt, check first.

**Comment by geraldngjx** [comment]
Thank you for the prompt response. In this case, we will make most of the amendments in the UG. As for the incorrect command result output, the result is shown in the image below. We intended to show a more user-friendly success message instead of the convulated connectify.model.person { ... } message. May I ask if that is allowed? Or should this be flagged in the UG?

![fe42c2a9-05f4-4549-b60a-bc9c9e3c5366](https://github.com/nus-cs2103-AY2324S1/forum/assets/102348985/fe78aa68-5863-48eb-8a54-95dc7e6d4254)

**Comment by damithc** [comment]
> Thank you for the prompt response. In this case, we will make most of the amendments in the UG. As for the incorrect command result output, the result is shown in the image below. We intended to show a more user-friendly success message instead of the convulated connectify.model.person { ... } message. May I ask if that is allowed? Or should this be flagged in the UG?
> 
> ![fe42c2a9-05f4-4549-b60a-bc9c9e3c5366](https://user-images.githubusercontent.com/102348985/281326448-fe78aa68-5863-48eb-8a54-95dc7e6d4254.png)

Yes, This can be considered as the 'incorrect' format to use in an user-facing message. You may fix this but try to minimize code changes.

**Comment by geraldngjx** [comment]
Thank you very much for the clarification! Appreciate your help sincerely.
