### ISSUE TITLE
Representing nested/inner classes in UML class diagrams

### ISSUE THREAD

**Issue by woojiahao** [nus-cs2103-AY2324S1/forum#364]
I'm currently documenting one feature that uses nested/inner classes, is there a convention that this module requires for such documentation? Or are we free to use something like this: https://users.cs.jmu.edu/bernstdh/web/common/lectures/summary_nested-classes.php where inner classes are represented as such 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/d638b7e9-0146-4411-a658-5e761acf15cd)

For more context, the pattern used is the `Builder` pattern and I have designed it as such:

```java
class Parent {
  private Parent() {}
  public static class Builder {}
  private static class OtherNested {}
}
```

Thanks!

**Comment by damithc** [comment]
@woojiahao While there is no clear consensus on this, the notation you cited above seems to be the most appropriate. That said, that notation is not within the scope of our course. So, I suggest choosing one of these options:
1. Omit such classes from the diagram. The work done by nested classes is likely to be localized and might not be that relevant to the overall picture.
2. Draw it as a regular class and use a UML note to mention which classes are nested in which other class.

**Comment by woojiahao** [comment]
Gotcha, will explore whichever makes the DG clearest, thank you @damithc
