### ISSUE TITLE
Request to use 3rd party library

### ISSUE THREAD

**Issue by winson8222** [nus-cs2103-AY2324S1/forum#365]
## Library

[Flexmark](https://github.com/vsch/flexmark-java)

## Purpose

This is used to allow for MarkDown styling in the the display result.

## License

[License](https://github.com/vsch/flexmark-java/blob/master/LICENSE.txt)

**Comment by damithc** [comment]
@winson8222 
This is for the app or for the documentation?
If the former, are you using this already in v1.3? If not, UI tweaks are not allowed in v1.4 due to the feature freeze.

**Comment by winson8222** [comment]
Hello, this is for the app. I have already implemented this in v1.3.

**Comment by damithc** [comment]
Approved.
