### ISSUE TITLE
Question about feature freeze and validity checks of user input

### ISSUE THREAD

**Issue by freshcabbage123** [nus-cs2103-AY2324S1/forum#366]
I would like to ask if handling extreme user inputs that cause the app to lag and become unresponsive would be considered a violation of feature freeze in v1.4?

Perhaps validity checks can be tweaked to accommodate the upper and lower bounds of user input? Bearing in mind of the feature freeze, there will be no new error messages added to the UI or shown to the user. Instead, I intend to use the standard invalid command error message that has been present in the v1.3 codebase.

In the case of 'extreme' inputs such as adding a person's name that contains 1 million characters which in turn causes the app to lag considerably, I am not clear if this would fall under bug (q5) or planned enhancement (q8) based on this week's [tutorial](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-w12.html#2-start-fixing-ped-bugs-before-the-tutorial)), hence the question. Thanks in advance!

![Screenshot 2023-11-08 at 5 52 26 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/79037826/fa31eea2-9896-4547-87ee-2cfbb083d776)

**Comment by damithc** [comment]
@freshcabbage123 In the interest of minimizing code changes, you can simply update the UG to caution users about limits of input size and consequences of exceeding those. Actively blocking such input can be a _planned enhancement_ for future.

**Comment by freshcabbage123** [comment]
@damithc Thank you Prof for the quick clarification!
