### ISSUE TITLE
Feature Freeze: Whether can delete features and duplicate features

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#367]
Hi generally we have 2 questions regarding the bug fixes.
1. Can we remove features if the bug is difficult to be completely eliminated? We are considering to remove the address attribute of contacts.
2. Our app has two modes. Contact mode and meeting mode. If one feature is available in the meeting mode, can we copy it over (duplicate) to contact mode as well?

contact mode:
<img width="679" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/709fc164-c208-456f-ba8d-5c8e5b91f6e8">

meeting mode:
<img width="680" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/8ba4879c-68d9-46cc-9b45-073156859b33">

Thank You.

**Comment by damithc** [comment]
@s-peiran 

> * Can we remove features if the bug is difficult to be completely eliminated? We are considering to remove the address attribute of contacts.

Yes.

> * Our app has two modes. Contact mode and meeting mode. If one feature is available in the meeting mode, can we copy it over (duplicate) to contact mode as well?

No, this is still a violation of the feature freeze.

**Comment by s-peiran** [comment]
Thank you prof.
