### ISSUE TITLE
Converting to PDF using MarkBind

### ISSUE THREAD

**Issue by tjch-o** [nus-cs2103-AY2324S1/forum#368]
Hi, I was converting my group's UG into a PDF just to test and I realised that the CSS styling I did for the UG does not reflect properly in the PDF.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/119966583/d2c738da-977b-4859-a5a1-7bea69908230)

Is there a way to solve this problem?

**Comment by yucongkoo** [comment]
@tjch-o Hi, have you tried the suggestions provided in [this](https://github.com/nus-cs2103-AY2324S1/forum/issues/341) issue?

**Comment by tjch-o** [comment]
@yucongkoo oh oops I missed that! shall check it out.... thank you!
