### ISSUE TITLE
Feature flaw and functionality bug at the same time

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY2324S1/forum#369]
We received both feature flaws and functionality bugs with this one feature and was wondering if we can fix it in v1.4: 

We changed the parser to work a little differently than it was in AB3 where if a user types `delete` they would have to specify `id/1` instead of just `1`. However this introduced some bugs such as error messages not showing which would be resolved if we reverted back to the AB3 way of parsing. Can we proceed with doing so?

**Comment by damithc** [comment]
@chiayunrong can give an example of such a bug so that I can confirm it indeed qualifies for a code change during the feature freeze?

**Comment by ghost** [comment]
@damithc https://github.com/AY2324S1-CS2103-W14-2/tp/issues/156

**Comment by damithc** [comment]
Yes, https://github.com/AY2324S1-CS2103-W14-2/tp/issues/156 qualifies.
Yes, you may fix the problem using a means that minimizes code changes (so as to minimize the risk of introducing more bugs)

**Comment by ghost** [comment]
Thank you!
