### ISSUE TITLE
Error of ☹ when testing using runtest.bat

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#37]
I encountered the `'javac' is not recognized as an internal or external command, operable program` when running runtest.bat in cmd in Intellij. After solving this using the solution I found on https://stackoverflow.com/questions/7709041/javac-is-not-recognized-as-an-internal-or-external-command-operable-program-or (set `PATH` in environment variable), I encountered the following error:
```
..\src\main\java\Duke.java:38: ┤φ╬≤: ▒α┬δ GBK ╡─▓╗┐╔╙│╔Σ╫╓╖√ (0xB9)
                        throw new DukeException("Γÿ? OOPS!!! The description of a todo cannot be empty.");
                                                  ^
..\src\main\java\Duke.java:77: ┤φ╬≤: ▒α┬δ GBK ╡─▓╗┐╔╙│╔Σ╫╓╖√ (0xB9)
                    throw new DukeException("Γÿ? OOPS!!! I'm sorry, but I don't know what that means :-(");
```

It seems to be the issue with `☹` in error message such as  `☹ OOPS!!! The description of a todo cannot be empty.` in level 5. After removing the emoji, everything works fine. May I ask how to fix this or am I allowed to just remove it from the error message?

**Comment by woojiahao** [comment]
I believe the instructions said that you don't have to copy the outputs exactly so long as the behavior is implemented, so I would err towards the latter

**Comment by damithc** [comment]
> am I allowed to just remove it from the error message?

@ChangruHenryQian Yes, you can change the error message format, as @woojiahao mentioned.

**Comment by ChangruHenryQian** [comment]
@damithc @woojiahao Thank you for helping!
