### ISSUE TITLE
Feature Flaw or Functionality Bug?

### ISSUE THREAD

**Issue by wr1159** [nus-cs2103-AY2324S1/forum#370]
## Context
My team's tp has a feature to enrol a member to an event and there are several operations that can be performed. First of all, we can go into this 'view' mode where user views the members enrolled to the specific event and vice versa. In this view mode, we can then run several operations to edit the data regarding the enrolment.

| Original View | Event View Mode |
|--------|--------|
| <img width="1483" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/56021409/98a32e7a-5ff4-4a07-880b-14c3217f1679"> | <img width="1485" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/56021409/49f532ea-a4ed-476b-8bf8-5079062629b8"> |

## Questions

1. When editing the enrolment information, the newly edited information does not show up on the UI and can only be seen when running the view command again. This was not our intended behaviour as the UI should refresh immediately, however, the team is conflicted - is this a functionality bug or a feature flaw?

2. Similarly, users can unenrol the member from the event which should result in the UI updating, removing the member from the list, however the user remains in the view. Similarly to above, the user can run the view command again to view the refreshed UI. Is this a functionality bug or feature flaw since users might be mistaken that the command did not work.

3. In the event view mode, when users edit the attributes of the member / event (not the enrolment), the UI bounces back to the main view. This differs from the intended behaviour where user should remain on their current view. The team was leaning towards it being a feature flaw but we would like to confirm whether it is indeed a feature flaw.

Edit: Added a third question.

**Comment by damithc** [comment]
@wr1159 In both cases, the user ends of seeing incorrect information. So, OK to fix.

**Comment by wr1159** [comment]
Okay thank you prof! In that case, for the 3rd question, since the edit command does display the new information albeit in a different view, that will be a feature flaw?

**Comment by damithc** [comment]
> Okay thank you prof! In that case, for the 3rd question, since the edit command does display the new information albeit in a different view, that will be a feature flaw?

Yes. Further enhancements to that can be listed as a planned enhancement.

**Comment by wr1159** [comment]
Thank you
