### ISSUE TITLE
Feature Freeze: Dealing with undefined or ambiguous behavior

### ISSUE THREAD

**Issue by CJ-Lee01** [nus-cs2103-AY2324S1/forum#371]
Suppose that we have a delete command that have 2 modes: deleting Type-A and deleting Type-B

e.g. `delete INDEX` to delete Type-A,  and  `delete --B INDEX` to delete Type-B 

However, it turns out that both can be specified together: `delete INDEX --B INDEX`, and the command will delete Type-B and ignore Type-A

This behavior is not documented in the UG.

Would changing this behavior to give the user a command syntax error violate the feature freeze?

**Comment by damithc** [comment]
@CJ-Lee01 
What does the result status message say after executing `delete INDEX --B INDEX` Does it clearly indicate which of the two got deleted?

What happens for the command `delete INDEX INDEX`?

**Comment by CJ-Lee01** [comment]
`delete INDEX INDEX` will give the user an invalid ID error message (this is expected as my team's current delete command also accepts ID as a parameter for deletion instead of index, and the delete command can only delete 1 at a time unless it is specified to be recursive)

However, `delete INDEX_1 --B INDEX_2 ` will give the message that the item of Type-B is deleted, and if INDEX_2 is invalid, it will give the error message related to deleting Type-B. This also does not check if INDEX_1 is a valid index.

**Comment by damithc** [comment]
> However, `delete INDEX_1 --B INDEX_2 ` will give the message that the item of Type-B is deleted, and if INDEX_2 is invalid, it will give the error message related to deleting Type-B. This also does not check if INDEX_1 is a valid index.

I see. This seems to stray a bit too far from what we can consider 'good enough for now; can correct in future'. You can fix it.

**Comment by CJ-Lee01** [comment]
Thank you for the clarification. I will close the issue now.
