### ISSUE TITLE
Questions about bug fixing

### ISSUE THREAD

**Issue by revdrag** [nus-cs2103-AY2324S1/forum#372]
Right now, our product's edit student command that requires 2 compulsory parameters which is explicitly stated in our user guide. (eg. `edit /s STUDENT_INDEX /c CLASS_NAME [n/ NAME]` where `/s` and `/c` are compulsory parameters.
However, if a user fails to provide one of the parameters, no error is shown as feedback, instead a `NoSuchElement` runtime exception is thrown. Are we allowed to fix this by catching this exception?

Another question is that in our user guide, we only allow users to input numeric characters but failed to catch these exceptions in our code. For example, setting a number to `3` but do not allow `three` as input. A runtime `NumberFormatException` is thrown but not caught. Are we allowed to catch this exception as well?

**Comment by damithc** [comment]
@revdrag Yes to both.

**Comment by revdrag** [comment]
@damithc hi prof, just to clarify again, these runtime exceptions mentioned above that are not caught did not cause any application crashes, and we intend to catch them which will be shown as feedback message, are they still counted as bug fixes and allowed to fix?

**Comment by damithc** [comment]
> @damithc hi prof, just to clarify again, these runtime exceptions mentioned above that are not caught did not cause any application crashes, and we intend to catch them which will be shown as feedback message, are they still counted as bug fixes and allowed to fix?

@revdrag for each of the two cases, what does the user see (success message?), and what happens internally (e.g., is the change saved?) Can you give me specific examples or screenshots?

**Comment by revdrag** [comment]
@damithc For the first case, the error occurs as shown in the screenshot, in the try catch block where it parses `Index` and `ClassName`. If the `ClassName` is missing (ie. performing a command like `edit /s 1 /n John` without the `/c` parameter), the `NoSuchElementException` which is thrown by `.get()` is not caught when it is supposed to, in order to throw a `ParseException`. As for the GUI, nothing changes and no error message is shown.

Code:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94689523/6720af48-f166-4d90-8ade-f22a370d8cfe)

Runtime Exception:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94689523/035fe41c-3a81-4536-b162-4830817984a7)

For the second case, the error occurs when I try to perform the command `setlesson /c T1 /l five` instead of `setlesson /c T1 /l 5`. 
As shown here, nothing changes for the GUI.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94689523/c867d733-fbde-47e3-9a65-62619f68f873)

We indicated in our UG that we do not allow non-integer inputs and while parsing we did not catch the `NumberFormatException`  which causes this runtime exception:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94689523/260448a7-ec6b-402c-ba26-0e97e361a7b2)

We intend to show invalid command format message to the user so that they will not be confused by any invalid commands they inputted.

Thanks for the clarification!

**Comment by damithc** [comment]
@revdrag The normal expectation is that every command gives a reaction in the UI, as a status message and/or as a change in some other UI element. A command terminating silently without any response to the user (I assume that is the case here?) can be considered a bug and fixed.

**Comment by revdrag** [comment]
@damithc Yup that is the case. Thanks so much for the clarification!
