### ISSUE TITLE
Renaming of packages

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#373]
Hi, may I know if we would have to take into consideration about the naming of our packages? Currently, everything is under "address" but it's not really relevant anymore since we have changed the name of our address book app. 

If the naming of the packages matters, are we allowed to change it, considering it's a refactor of code in v1.4? 

Thank you!

**Comment by damithc** [comment]
> If the naming of the packages matters, are we allowed to change it, considering it's a refactor of code in v1.4?

@GlendaChong It doesn't matter, unless the name violates the coding standard. So, recommended not to change package names at this point as it can sometimes wreak havoc with code authorship tracking.

**Comment by GlendaChong** [comment]
Okay, thank you!
