### ISSUE TITLE
Third-Party Libraries: README

### ISSUE THREAD

**Issue by kokrui** [nus-cs2103-AY2324S1/forum#374]
Hi, the course website states that if we used third-party libraries, we should state so in the DG's acknowledgements section.

<img width="556" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/29654756/3cd8983d-aefe-41a8-b834-19f67ed5b2a0">

Could I just confirm that we do not have to state it in our project README?

P.S. I came across this because the code reuse declaration "quiz" on Canvas has a typo in that it links to last semester's course website, which I originally unwittingly followed and noticed that they ask for a README mention

<img width="846" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/29654756/ea8b2939-8429-4971-87fc-0e06ea3506d3">

**Comment by damithc** [comment]
@kokrui 

> Could I just confirm that we do not have to state it in our project README?

Yes, no need to do mention it in the README, in the tP. Only DG.


> P.S. I came across this because the code reuse declaration "quiz" on Canvas has a typo in that it links to last semester's course website, which I originally unwittingly followed and noticed that they ask for a README mention
> 
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/29654756/281591624-ea8b2939-8429-4971-87fc-0e06ea3506d3.png">

Thanks for the heads up. I specifically updated it earlier but somehow, Canvas has reverted it to the older version. I've updated it again just now.
