### ISSUE TITLE
Question about UML Class Diagram

### ISSUE THREAD

**Issue by yanghengtang** [nus-cs2103-AY2324S1/forum#376]
Our UI involves quite a few repeated components that have the same functionality but handles different entities, if I were to include all of it in our Class Diagram, it would look like this:
![NewUiClassDiagram1](https://github.com/nus-cs2103-AY2324S1/forum/assets/24840938/798dd562-f764-4d29-8978-6430997e0741)

I was wondering if we can make it neater by generalising the component with what the Logic Class Diagram does:
![NewUiClassDiagram2](https://github.com/nus-cs2103-AY2324S1/forum/assets/24840938/d873bebb-825d-44ec-be1e-19420f699d36)

Is this UI Class Diagram acceptable?

**Comment by damithc** [comment]
@yanghengtang Yes, this kind of simplifications is acceptable.

**Comment by yanghengtang** [comment]
Thank you prof for your clarification.
