### ISSUE TITLE
Question on whether planned enhancement is too large and broad

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#377]
Hi, our team is currently planning on what to include in our planned enhancements and came across this enhancement that we plan to include, and we think that this enhancement is suitable for two different features(which behaves nearly identically).

Specifically saying, the two features are the [tag](https://ay2324s1-cs2103t-w16-2.github.io/tp/UserGuide.html#tagging-a-customer-tag) and [insurance](https://ay2324s1-cs2103t-w16-2.github.io/tp/UserGuide.html#updating-insurance-of-a-customer-insurance) features, and the planned enhancement is stated [here](https://ay2324s1-cs2103t-w16-2.github.io/tp/DeveloperGuide.html#appendix-planned-enhancements).

I am wondering whether is this planned enhancement considered too large since it covers two features? On top of that, are the information included in the current planned enhancement sufficient, or do we need to provided our proposed implementation too?

**Comment by damithc** [comment]
@yucongkoo If adding the enhancement to tags doesn't automatically apply it to insurance as well (I don't think that's the case here), we consider them as two distinct enhancements. 

No need to provide implementation details. Just explain it from user POV.

**Comment by yucongkoo** [comment]
@damithc Ah okay I see, a follow-up question would be, if these were not included in planned enhancements and both are reported as a feature flaw, would these be considered duplicate bugs? As we will be going into the PE soon, I am just wondering would it be worth reporting two bugs of the same behaviour but in different features?

**Comment by damithc** [comment]
@yucongkoo We use a similar rule when deciding if they are duplicates. See below:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/fd3da492-cfb6-429f-bfb0-9ef08327fa98)

**Comment by yucongkoo** [comment]
@damithc Okay thank you prof.
