### ISSUE TITLE
App icon copyright issue, is it allowed to change in feature freeze session?

### ISSUE THREAD

**Issue by WangCheng0116** [nus-cs2103-AY2324S1/forum#378]
Our app utilized the icon from Duolingo and made some changes, which apparently violates the copyright issue. However, we have drawn our own icon. I am wondering if is it allowed to replace it in the feature freeze session.

**Comment by damithc** [comment]
@WangCheng0116 Yes, you may replace it.

**Comment by WangCheng0116** [comment]
Thank you :)
