### ISSUE TITLE
Question on fixing ui related bug

### ISSUE THREAD

**Issue by tiongjjyi** [nus-cs2103-AY2324S1/forum#379]
My team and I recently encountered a bug report concerning a specific field, such as 'remark,' not displaying the complete sentence when the remark is lengthy, even after maximizing the window. I recognize that this issue relates to the user interface (UI), and we need to avoid making UI changes. However, my perspective is that the inability to view the entire remark constitutes a functionality bug that should be addressed. I would like to request clarification on this matter from professor. Thank you.

**Comment by damithc** [comment]
@tiongjjyi You can fix it but only if there is no other way for the user to view the hidden part of the text in the current UI.

**Comment by tiongjjyi** [comment]
> @tiongjjyi You can fix it but only if there is no other way for the user to view the hidden part of the text in the current UI.

Noted, thank you prof!
