### ISSUE TITLE
Suggestions of turning classes compiled in Java 17 to Java 11.

### ISSUE THREAD

**Issue by TiwKangXu** [nus-cs2103-AY2324S1/forum#38]
I'm fully aware that we should use Java 11 instead of Java 17 before the tasks and I've setted it up, from CS2040S experience. However, eventually it turns out that Java 17 is the one working for the whole time. Does anyone has any suggestions on turning classes compiled in Java 17 back to Java 11? Thanks in advance.

**Comment by woojiahao** [comment]
Just recompile the files with Java 11 and they'll be "Java 11". You don't have to downgrade your Java version. `jenv` is a way to manage multiple Java installations (if you're on MacOS): https://www.jenv.be/

If you're on Windows, believe you can just install Java 11 and point the path variable to the Java 11 installation instead (but I've not used Windows in quite a while so any Windows folks, feel free to correct me)

**Comment by TiwKangXu** [comment]
Hi @woojiahao ,

Thanks for the suggestion. Should I remove the compiled classes, switch to Java 11 from jenv, recompile the classes?

**Comment by woojiahao** [comment]
If you're using Intellij, that's not necessary, Intellij will just do that for you

**Comment by TiwKangXu** [comment]
So installing jenv is sufficient?

**Comment by woojiahao** [comment]
Yeah, and update Intellij to use Java 11: https://www.baeldung.com/intellij-change-java-version

**Comment by TiwKangXu** [comment]
@woojiahao 

Thanks for your help! I believe I have had both Java 11 and Java 17 installed previously.

My particular error: 
Files executed successfully if SDK under Project Structure is 17. Since this project requires Java 11, I tried switching SDK to 11 but when running Duke.java, error occurs. 

My steps of resolving the error:
1. File -> Project Structure -> SDK (choose 11) -> Language Level (choose Default) -> Apply -> OK. (https://www.baeldung.com/intellij-change-java-version from CS2040S setup / @woojiahao )

2. IntelliJ IDEA (beside File) -> Build, Execution, Deployment -> Compiler -> Java Compiler -> Project bytecode version (set to 11) -> Apply -> OK. (from https://stackoverflow.com/questions/67098514/java-error-release-version-17-not-supported)

3. Build (same menu bar as File and IntelliJ IDEA) -> Rebuild Project.

4. Run Duke.java. Should run successfully.
