### ISSUE TITLE
Feature Flaw or Functionality Bug for ambiguous feature description

### ISSUE THREAD

**Issue by Jweewee** [nus-cs2103-AY2324S1/forum#380]
For this [bug](https://github.com/AY2324S1-CS2103T-W16-2/tp/issues/264), would it qualify as a functionality or feature flaw? 

Since the end-user(salesman) would expect the result of unmarking an appointment to recover its details, am I correct in saying that this feature has become less useful in simply just decrementing the appointment counter, and hence it is a feature flaw?

**Comment by damithc** [comment]
@Jweewee Based on the limited knowledge I get from https://github.com/AY2324S1-CS2103T-W16-2/tp/issues/264, it seems like a feature flaw.
