### ISSUE TITLE
Incorrect App Name

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#381]
Hi, we realised that our app shows an incorrect name as "Address App" in the title. Our product does not have anything to do with addresses, as detailed in our UG as well, which might mislead our users. Hence, we identify it as a bug in our app. 

Can we clarify if we are able to make this change to the title of our app's UI? 

Thank you!

**Comment by damithc** [comment]
@GlendaChong Yes you can fix it, as that is an incorrect information shown on the UI.

**Comment by GlendaChong** [comment]
Okay, thank you!
