### ISSUE TITLE
Questioning whether our team's proposed enhancement adheres to the constraints outlined in version 1.4

### ISSUE THREAD

**Issue by Clin-lyx** [nus-cs2103-AY2324S1/forum#382]
Hi, our team is currently facing challenges in determining whether the enhancements listed below align with the v1.4 constraints. Could you please identify which enhancements comply with the constraints and which ones may not? Thank you!

1. Current constraints allow appointments with dates before the current date to be added, which does not make sense in the context of an appointment tracker. However, we did not introduce this constraint in our current iteration, is this still considered a bug and as such we can increase the constraints to only accept the dates after the current date.

2. NRIC parameter accepts invalid NRICs such as ones starting with A, which does not accurately reflect real world context. However, this does not affect the overall functionality of the app as valid NRICs are still being accepted, can we increase the constraint to only accept valid NRICs?

3. As our app is an addressbook for patient management, some patients might not have an NRIC, eg foreigners. Is it considered a bug to have the NRIC parameter be a compulsory field when adding a patient?

4. Name parameter currently does not allow dots and dashes. As some people’s names may contain dots or dashes, could we edit the parameter to allow them?

5. When an invalid patient index is entered, our current output is “Invalid output”. A suggestion during PE-D was to make it more verbose. As such, can we edit it to reflect the maximum allowable index that is valid?

6. When a record with duplicate conditions or medications is added, our app allowed the duplicates and ui shows multiple entries of the same conditions and medication. Suggestion was made during PE-D to filter out duplicate entries. Would implementing such suggestion be violation of feature freeze?

7. Is it considered a violation to change the "wraptext" attribute to true for the name label on the current name card, considering that the existing name might be quite lengthy, and enabling wrapping would display the overflow in ellipsis?

**Comment by oeggy03** [comment]
Hi, I'm not prof but I think 7. might not be valid. In case it isn't, some workarounds that you can use can be placing it under "planned enhancements' or "known issues". Prof also told my group (privately on teams) that we can "update the UG to guide users on how to proceed in a case like this".

**Comment by damithc** [comment]
@oeggy03 

> * Current constraints allow appointments with dates before the current date to be added, which does not make sense in the context of an appointment tracker. However, we did not introduce this constraint in our current iteration, is this still considered a bug and as such we can increase the constraints to only accept the dates after the current date.

This is an enhancement. Not allowed to fix during feature freeze.

On a related note, notice how calendar apps such as Google calendar allow recording events in the past. 

> * NRIC parameter accepts invalid NRICs such as ones starting with A, which does not accurately reflect real world context. However, this does not affect the overall functionality of the app as valid NRICs are still being accepted, can we increase the constraint to only accept valid NRICs?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/15341700-390e-42d8-a5cd-116480d8324a)

The above applies. So, most likely, no.

> * As our app is an addressbook for patient management, some patients might not have an NRIC, eg foreigners. Is it considered a bug to have the NRIC parameter be a compulsory field when adding a patient?

For now, the UG can be updated to explain what alternative can be used in place of NRIC e.g., passport number

> * Name parameter currently does not allow dots and dashes. As some people’s names may contain dots or dashes, could we edit the parameter to allow them?

Yes, assuming the recording of exact name is critical for this application. 

> * When an invalid patient index is entered, our current output is “Invalid output”. A suggestion during PE-D was to make it more verbose. As such, can we edit it to reflect the maximum allowable index that is valid?
 
Did you mean 'invalid input'?
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/454897e2-0767-435f-b8f7-ab4818c8d2e4)
The above applies. So, most likely no.

> * When a record with duplicate conditions or medications is added, our app allowed the duplicates and ui shows multiple entries of the same conditions and medication. Suggestion was made during PE-D to filter out duplicate entries. Would implementing such suggestion be violation of feature freeze?

Only if having duplicates hinder typical usage. Otherwise, it can be left as a future enhancement.

> * Is it considered a violation to change the "wraptext" attribute to true for the name label on the current name card, considering that the existing name might be quite lengthy, and enabling wrapping would display the overflow in ellipsis?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/a1c76a71-dd34-435f-88be-4b221b9a89a0)

The above applies.
If you are asking if long names can be truncated using `...`, a similar logic applies.

If any of the answers above are not clear, feel free to ask again.

**Comment by Clin-lyx** [comment]
Thanks for your help!!! I'm closing this issue
