### ISSUE TITLE
How to handle 6 separate, extra DG pages that came with AB3

### ISSUE THREAD

**Issue by Cloud7050** [nus-cs2103-AY2324S1/forum#383]
AB3 came with 6 separate, extra pages linked in the DG. These are the setup/getting started, documentation, logging, testing, configuration & devops pages.

The grading details on the course website state:

> The main content you add should be in the `docs/DeveloperGuide.md` file (for ease of tracking by grading scripts).

Our changes to the product render some of these extra pages outdated. We have also already made some updates to these pages. Additionally, some of these pages are rather short as is (like the configuration page).

May I know what a good way to handle these extra pages would be? Some potential options I could think of:

- Make minimal updates to the pages such that they aren't outdated
- Or flesh out the content of the pages
- Or scrap the pages entirely
- Or merge the pages into the DG (presumably to ensure they count for grading)
- etc.

There are also the tutorials that we used to familiarise with AB3, but we have already scrapped those.

**Comment by damithc** [comment]
@Cloud7050 Those pages are not within the scope of tP. So, you are free to do whatever you want with them. 
You are welcome to, but not required to update them. If you do update them, that work can be counted as a contribution. More importantly, any problems in those pages will not count against your team.

**Comment by Cloud7050** [comment]
Ok thank you.

I also located this mention in the week 10 schedule:

> You are discouraged from moving sections currently in `DeveloperGuide.md` to additional markdown files. Reasons: 1. You need to submit the DG as a single PDF file at the end of the semester. 2. When checking DG-related tP increments, we only check your contributions to that file.
> 
> A similar requirement applies to the `UserGuide.md` too.

Considering it sounds like the pages won't be submitted, perhaps we will opt to just scrap them.

**Comment by damithc** [comment]
> Considering it sounds like the pages won't be submitted, perhaps we will opt to just scrap them.

@Cloud7050 I think best to let them be. Deleting them can result in broken links in your DG, which can be reported as bugs.
