### ISSUE TITLE
tP progress Individual Dashboard UG Draft not marked as completed

### ISSUE THREAD

**Issue by rayshawntan** [nus-cs2103-AY2324S1/forum#386]
I just noticed that in the individual dashboard, the UG Draft item for me was marked uncompleted in week 11. I'm wondering if it's caused a groupmate edited the UG and changed some of my parts after my commits in the same week and thus resulted in the number of lines that I wrote to drop.

**Comment by damithc** [comment]
> I just noticed that in the individual dashboard, the UG Draft item for me was marked uncompleted in week 11. I'm wondering if it's caused a groupmate edited the UG and changed some of my parts after my commits in the same week and thus resulted in the number of lines that I wrote to drop.

@rayshawntan Yes, that is the likely reason. You can email me the link to the commit/PR in which you updated the DG in week 11.

**Comment by rayshawntan** [comment]
Thank you
