### ISSUE TITLE
Git resetting

### ISSUE THREAD

**Issue by juliusgambe** [nus-cs2103-AY2324S1/forum#387]
We decided for v1.4 to rename our package as we thought it was necessary as our product name is no longer address book. We did the renaming and merged our code. We continued to merged other code in. We realised that this might cause problems for repo-sense [#373 ](https://github.com/nus-cs2103-AY2324S1/forum/issues/373) regarding authorship.

Now, we are considering to reset back to the last previous commit where we made the merge. Would this be a better idea to prevent any potential conflict regarding authorship or any other problems that may arise? If we reset it back, would that cause other authorship problems? 

Thank you.

**Comment by damithc** [comment]
@juliusgambe I updated the code dashboard just now. Check if the package renaming has significantly messed up authorship tracking (e.g., almost all code is not attributed to the person who did the package renaming). If the current authorship attributions are more or less OK, you don't have to revert anything. Any small discrepancies in authorship attribution can be fixed using `@@author` tags, as explained [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking).

**Comment by juliusgambe** [comment]
> @juliusgambe I updated the code dashboard just now. Check if the package renaming has significantly messed up authorship tracking (e.g., almost all code is not attributed to the person who did the package renaming). If the current authorship attributions are more or less OK, you don't have to revert anything. Any small discrepancies in authorship attribution can be fixed using `@@author` tags, as explained [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking).

Thank you for your reply at this hour. Upon looking at the changes in authorship, I think we are deciding to git reset to when the change was made. However, this would cause the merge commits we made so far to be removed if we reset. Thus, we would like to ask if firstly, would this help to revert back the authorship to its original state and also, because some of our PPP code was merged in between, would this affect the hard deadline for the draft PPP?

Thank you

**Comment by damithc** [comment]
> Thank you for your reply at this hour. Upon looking at the changes in authorship, I think we are deciding to git reset to when the change was made. However, this would cause the merge commits we made so far to be removed if we reset. Thus, we would like to ask if firstly, would this help to revert back the authorship to its original state and also, because some of our PPP code was merged in between, would this affect the hard deadline for the draft PPP?

@juliusgambe Should be fine if the updated history is available by 4pm Friday, and the reset affects only commits done after last Friday.

**Comment by juliusgambe** [comment]
Thank you prof!
