### ISSUE TITLE
Incorrect error message for Clear Command

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#388]
Hi, our team will like to check if we are able to edit the error message for our Clear Command, as the current error message shows "Address Book has been cleared", but our app's functionality does not follow an address book currently, since we have changed the context. 

Is this allowed as a bug fix for v1.4 as the current error message is different in functionality from our app? 

Thank you!

<img width="1147" alt="Screenshot 2023-11-10 at 12 36 25 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/47603827/976c4f59-6a23-48cb-b007-c8a19528e135">

**Comment by damithc** [comment]
@GlendaChong Yes, any mention of old app name in the UI (including error messages) is incorrect and can be changed.
