### ISSUE TITLE
Is this bug fix allowed for v1.4

### ISSUE THREAD

**Issue by ryanongwx** [nus-cs2103-AY2324S1/forum#389]
https://github.com/AY2324S1-CS2103T-T12-4/tp/issues/138#issue-1976918121

The attached link above details the uncaught exception occurring when a opening a file that has been deleted from the local device. I have implemented a fix which catches the exception and lets users know the error. Before the fix, nothing will happen upon clicking on the link.

Is this fix allowed for v1.4?

**Comment by damithc** [comment]
@ryanongwx Yes, failing silently is the incorrect behavior here. OK to fix.
