### ISSUE TITLE
My program keeps throwing an IOException and refuses to create a .txt file although it had worked the first time

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#39]
I used ObjectOutputStream and ObjectInputStream for Level-7, and tried to load the list of tasks from a .txt file, but to no avail. I deleted the  .txt file and tried to redo what I just did, however now it throws IOException and will not produce the .txt file anymore, no matter how many times I undo and redo my code.

How do I fix this, and is there any other method to read and write data?

**Comment by woojiahao** [comment]
You should explore ways to create the file programmatically when the file does not exist

**Comment by JasonRay168** [comment]
So this would work without having to rely on manually adding the file, right? Alright thanks!

**Comment by woojiahao** [comment]
Yes, that's the whole point of ensuring that the bot is self-sufficient to run
