### ISSUE TITLE
Approval to fix uncaught exception

### ISSUE THREAD

**Issue by geraldngjx** [nus-cs2103-AY2324S1/forum#390]
Hello! There is an unintended uncaught exception thrown by one of the commands and we hope to seek confirmation if we are able to fix it. The fix is relatively simply with marginal code change. Thank you.

Link to PR: https://github.com/AY2324S1-CS2103T-T15-4/tp/pull/192

**Comment by damithc** [comment]
What's the current behavior (from user POV) and how do you propose to change it? If possible, give a precise example.

**Comment by geraldngjx** [comment]
Sorry for the lack of clarity! Currently, the application throws an uncaught exception and the application hangs as a result. In order to fix the application, we simply plan to add a check to see if the input is valid. Thank you!

**Comment by damithc** [comment]
> the application throws an uncaught exception and the application hangs as a result

This is a bug that needs to be fixed. So, go ahead.

**Comment by geraldngjx** [comment]
Thank you for the clarification!
