### ISSUE TITLE
Java CI failing because of timeout

### ISSUE THREAD

**Issue by newway1814** [nus-cs2103-AY2324S1/forum#391]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110995876/9705187d-7902-4541-bdbe-80af74bd5fb5)
Hi,
How do I correct this timeout, I think its on the main cs2103t repo.

Please [click here](https://github.com/nus-cs2103-AY2324S1/tp/actions/runs/6821025712) to go to the window

**Comment by damithc** [comment]
@newway1814 can you share a link to this page in the screenshot?

**Comment by newway1814** [comment]
Here is the link prof -> [link](https://github.com/nus-cs2103-AY2324S1/tp/actions/runs/6821025712)

**Comment by newway1814** [comment]
It worked just merged another commit!

Thanks
