### ISSUE TITLE
Questions regarding severity categorisation for UML diagrams error

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#393]
I am wondering what kind of severity should we categorise errors in UML diagrams to? Does it depend on how the error affects the readability/understandability?

A simple example would be, in a sequence diagram where we want to indicate loops:

**Scenario 1:**
We used the label `for` instead of `loop` in the top left corner.
I would categorise this as a severity.veryLow since it does not actually cause misunderstanding, rather just a wrong notation.

**Scenario 2:**
We used the label `opt` instead of `loop` in the top left corner.
This would then upgrade to a severity.Low or severity.Medium since it will cause misunderstanding?

If the above example is correct, would that mean syntax/notation errors that do not cause misunderstanding can be categorised as severity.veryLow bugs, whereas bugs that actually cause misunderstanding will categorised from severity.Low upwards depending on how much it affects? But then there would be a grey area of when the diagram is too cluttered which affects readability(even though the diagram is totally correct), which I am not very sure how we should categorise, since it is technically a cosmetic issue, but it will also heavily affect readers to understand the diagram.

All in all, I understand that a lot of these need to be determined on a case by case basis, but I am just wondering whether are there any general guidelines on categorising severity of UML diagram errors?

**Comment by damithc** [comment]
> Does it depend on how the error affects the readability/understandability?

@yucongkoo yes, this can be the main criterion.

That said, using incorrect notation is also a rather serious issue, as it affects the credibility of the information in the diagram i.e., if the diagram doesn't even follow the correct notation, how much can we trust it to give a true representation of what it models?

**Comment by yucongkoo** [comment]
@damithc Hmm, so does it mean that if there were wrong notations discovered, it can be tagged as severity.Low also?

**Comment by damithc** [comment]
> @damithc Hmm, so does it mean that if there were wrong notations discovered, it can be tagged as severity.Low also?

Yes, or higher. Certainly not `severity.VeryLow`.

**Comment by yucongkoo** [comment]
Okay, understood.

**Comment by yucongkoo** [comment]
Hi, as I was examining my UML diagrams to spot out possible notation errors, I came across this question of whether method names in sequence diagrams are compulsory(as they are not stated as optional elements, I took it as compulsory), but if so, may I confirm that writing the constructor method name in sequence diagrams is not compulsory(as it might make the diagram more complicated if the constructor takes in a lot of arguments), so a diagram as follows is correct:
<img width="308" alt="Screenshot 2023-11-13 at 5 04 16 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/7586627a-49e9-415a-9e5d-769012fddabe">

**Comment by damithc** [comment]
> Hi, as I was examining my UML diagrams to spot out possible notation errors, I came across this question of whether method names in sequence diagrams are compulsory(as they are not stated as optional elements, I took it as compulsory), but if so, may I confirm that writing the constructor method name in sequence diagrams is not compulsory(as it might make the diagram more complicated if the constructor takes in a lot of arguments), so a diagram as follows is correct:
> <img alt="Screenshot 2023-11-13 at 5 04 16 PM" width="308" src="https://user-images.githubusercontent.com/122191710/282412368-7586627a-49e9-415a-9e5d-769012fddabe.png">

@yucongkoo Constructor can be omitted if it is not important for the reader to know.

Also, in the example diagram, it is better to use `result:CommandResult` rather than give object name as a return value. It is implied that the constructor returns the constructed object (i.e., no need to specify a return value).

**Comment by yucongkoo** [comment]
@damithc 
> Constructor can be omitted if it is not important for the reader to know.

Okay, thank you for your response.

> Also, in the example diagram, it is better to use result:CommandResult rather than give object name as a return value. It is implied that the constructor returns the constructed object (i.e., no need to specify a return value).

Regarding this, is the current notation in the above diagram wrong? Or is it just less straightforward? I used the following notation as I need to use the name `result` as a return value of another function, as follows:

<img width="416" alt="Screenshot 2023-11-13 at 5 17 43 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/143c2245-8f8f-432b-8d7b-3a240c719fcc">

But if I were to use `result:CommandResult`, as it is increasing the width of the whole diagram, it will cause the fonts to shrink(which I feel like is also less ideal).

**Comment by damithc** [comment]
>  is the current notation in the above diagram wrong? Or is it just less straightforward? 

Yes, less straight forward but not strictly wrong.

> But if I were to use `result:CommandResult`, as it is increasing the width of the whole diagram, it will cause the fonts to shrink(which I feel like is also less ideal).

Use `r:CommandResult`?

**Comment by yucongkoo** [comment]
@damithc Say in my code, I named the `CommandResult` object to be `result`, and I use `r:CommandResult` in my UML sequence diagram, is this allowed?

**Comment by damithc** [comment]
> @damithc Say in my code, I named the `CommandResult` object to be `result`, and I use `r:CommandResult` in my UML sequence diagram, is this allowed?

Yes, that should be an acceptable simplification.

**Comment by yucongkoo** [comment]
@damithc 

> Yes, that should be an acceptable simplification.

Ok, thank you prof.

I have another question about random names appearing in sequence diagrams, take an example as follows:

Before(note the random but descriptive names in the red box):
<img width="980" alt="Screenshot 2023-11-13 at 6 15 16 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/42329de2-447f-4ca4-8dc0-d2d66dccfd51">

After:
<img width="852" alt="Screenshot 2023-11-13 at 6 36 22 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/45260a03-de6a-418e-b193-cdc0bfcb7ee0">

My question is, was the original use of names not defined in the diagram a notation error, if so, will my fix as shown in the second diagram fix the issue(where I define the names in the notes)?

**Comment by damithc** [comment]
> My question is, was the original use of names not defined in the diagram a notation error, if so, will my fix as shown in the second diagram fix the issue(where I define the names in the notes)?

It is preferred that the diagram follows the names used in the code, but in some cases it is acceptable to use others names if it helps to improve the usability of the diagram.

In the case of parameters, you can use `foo(...)` to indicate that they have been omitted from the diagram, if they are not that important to the purpose of the diagram.

**Comment by yucongkoo** [comment]
@damithc Ok, thank you prof.
