### ISSUE TITLE
Are we allowed to fix this UI truncation bug?

### ISSUE THREAD

**Issue by shishirbychapur** [nus-cs2103-AY2324S1/forum#394]
![Screenshot (302)](https://github.com/nus-cs2103-AY2324S1/forum/assets/95522842/73f8a29e-e5bc-4a1d-a36e-0cee81860772)

The name gets truncated if the number of characters crosses a certain threshold. It is static, and expanding/minimizing the window doesn't cause the truncation to get removed. It was also reported as a PE-D bug. 

Is my team allowed to fix this UI bug? [This happens for non-extreme inputs like `Johnathan Tan`]

**Comment by damithc** [comment]
@shishirbychapur you can apply the following guideline:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/e18b7d06-171c-4402-8196-327f8cd6feba)

So, a pertinent question is whether there is another way for the user to see the full name.

**Comment by shishirbychapur** [comment]
There is no other way to view the full name (other than viewing the data file directly). So, would it be safe to assume that I can adjust the UI to fix the bug?

**Comment by damithc** [comment]
> There is no other way to view the full name (other than viewing the data file directly). So, would it be safe to assume that I can adjust the UI to fix the bug?

Yes, OK to fix.

**Comment by shishirbychapur** [comment]
Okay, Thanks Prof!
