### ISSUE TITLE
Query on tP code reuse

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#395]
Hi prof,

In the case that our group requested to use 3rd person library, and there are commits that have code using the 3rd person library, but the work done in the commits were eventually scrapped by v1.3, would we need to declare that there is reusing of content in the tP code reuse declaration?

Thanks!

**Comment by damithc** [comment]
@lihongguang00 If the current version doesn't use that library, there is no need to acknowledge it in the current version.
