### ISSUE TITLE
Error message for Add Command

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#396]
Hi, our team would like to check if our current implementation might be deemed as a bug and/or feature flaw. 

Currently, our implementation for Add Command checks whether all prefixes are valid, before checking for duplicate prefixes. For example, if there's a duplicate `n/` prefix, but a missing compulsory prefix `d/`, the error message will be showing invalid command format. 

As such, the duplicate prefix check will never be called if compulsory prefixes are absent even though there are duplicate prefixes.

Our team's stance is that it is neither a bug nor a feature flaw, because it is indeed true that with a missing compulsory prefix, it is an invalid command format. Hence, we would like to seek a 2nd opinion on this matter. 

Thank you!

**Comment by damithc** [comment]
@GlendaChong As the more urgent decision to make is whether this is a bug that is allowed to be fixed during the feature freeze, I'll address that first. I agree with you that it is not a bug, as the error message is not incorrect.

As to whether this is a feature flaw, I'll give some time for others to pitch in first.
