### ISSUE TITLE
Question on acceptable bug fixes

### ISSUE THREAD

**Issue by ylyma** [nus-cs2103-AY2324S1/forum#399]
Hi! Our team wanted to check if fixing the following issue would be acceptable as a bug fix: 

One of our commands does not work because of 1 missing word in the code. After adding the word, everything works correctly.

**Comment by damithc** [comment]
@ylyma Can you give an example of that command? What happens when that command is run?

**Comment by ylyma** [comment]
It is a list command that is supposed to list the persons that are not hidden by a hide command. However, the bug is that it lists all persons and ignores the hide command, rendering the hide command and itself useless.

**Comment by damithc** [comment]
@ylyma Assuming there is a clear expectation that the said list command should not show hidden items, you can fix it to work as expected.
