### ISSUE TITLE
IP A-TextUiTesting question

### ISSUE THREAD

**Issue by saltedfishxx** [nus-cs2103-AY2324S1/forum#4]
We were given a section to test our code using the I/O redirection technique:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/37168931/5bd99c22-eceb-4000-9ae4-34f676f26f07)

However in our `.gitignore` file the directory for `text-ui-test` folder is excluded.
How can we show that we have used this feature in our increments?

**Comment by jianrong7** [comment]
I don't think the `.gitignore` file includes the entire `text-ui-test` directory by default. It should only ignore the `EXPECTED-UNIX.TXT` and `ACTUAL.TXT` files.

**Comment by craigtonlian** [comment]
The is the default `.gitignore` from the forked repo:
```shell
# IDEA files
/.idea/
/out/
/*.iml

# Gradle build files
/.gradle/
/build/
src/main/resources/docs/

# MacOS custom attributes files created by Finder
.DS_Store
*.iml
bin/

/text-ui-test/ACTUAL.TXT
text-ui-test/EXPECTED-UNIX.TXT
```

So only `text-ui-test/ACTUAL.TXT` and `text-ui-test/EXPECTED-UNIX.TXT` are untracked by Git.

In order words, your testing input file `text-ui-test/input.txt` and the expected output file `text-ui-test/EXPECTED.TXT` will still be tracked and can be committed 😄

**Comment by saltedfishxx** [comment]
Thanks for the answers!

**Comment by saltedfishxx** [comment]
Thanks for the answers!
