### ISSUE TITLE
fatal: branch-level-8 cannot be resolved to branch

### ISSUE THREAD

**Issue by AaronJT1** [nus-cs2103-AY2324S1/forum#40]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

i am using macOS intellij.

Just finished level-8 and was pushing to remote repository. Managed to push both tags and master, however when i try to push the branch-level-8, it gives me the follow error

<img width="624" alt="Screenshot 2023-08-28 at 10 01 46 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/134244836/1867bc4c-d4eb-4044-b2ee-f432b8e1e4fa">

Have tried searching for solutions online, but still unresolved. Would appreciate help, thanks

**Comment by cxo05** [comment]
Check if the branch name is correct. You can try using `git branch -a` to see all branches.

**Comment by ncduy0303** [comment]
What happens if you write `branch-Level-8` instead of `branch-level-8`? I think it is some case sensitive issue as mentioned here: https://stackoverflow.com/questions/38034866/cant-push-to-remote-branch-cannot-be-resolved-to-branch

**Comment by AaronJT1** [comment]
Hi @ncduy0303 yup, it was case sensitive. Appreciate the help!!!
