### ISSUE TITLE
v1.4 is adjusting the GUI due to regression from bug fixing allowed?

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#400]
After we remove the tags feature from contacts, the GUI has changed in the following way.
Before:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/6e19039e-e455-4e9f-ae8e-d38feca794b5)
After:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/4fc1c5b4-33ad-488e-ad64-e237765436e8)
Now we have a gap in the contactDetailPanel above the name "Sarah Woo".

1. Are we allowed to reduce the gap in this case?
2. On a sidenote are we allowed to freely change the UG and DG?

**Comment by damithc** [comment]
> * Are we allowed to reduce the gap in this case?

@s-peiran Yes, as this is part of a feature removal.

> * On a sidenote are we allowed to freely change the UG and DG?

Yes.

**Comment by s-peiran** [comment]
@damithc Thank you for the clarification Prof.

I do have another question about v1.4
Issue: https://github.com/AY2324S1-CS2103-W14-2/tp/issues/162
 
Right now my meeting class is holding an ArrayList of the contacts it contains. However if the contact is removed from model.unfilteredContactList via deleteContact command, it is not automatically removed from the meeting's arrayList. Is implementing an observer pattern to fix this issue allowed under the feature freeze?

**Comment by damithc** [comment]
> Right now my meeting class is holding an ArrayList of the contacts it contains. However if the contact is removed from model.unfilteredContactList via deleteContact command, it is not automatically removed from the meeting's arrayList. Is implementing an observer pattern to fix this issue allowed under the feature freeze?

@s-peiran From the user POV, what is the current behavior, and how will it be changed?

**Comment by s-peiran** [comment]
Currently, When the user removes the contact via deleteContact command:
<img width="487" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/ca1022b2-320d-4b78-a0c4-68f3a3ef2865">
The same contact is still residing in the Meeting's ArrayList<Contact>
<img width="445" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/4655ee7f-ea26-4333-aa05-4b427cd6c635">

To change the behavior, we will have an ArrayList in Contact class that keep tracks of the Meetings that contains it (ObserverList). If the contact is delete via deleteContact command, the contact object will notify all the meetings in the observerList to remove the contact from its own ArrayList.

**Comment by damithc** [comment]
> The same contact is still residing in the Meeting's ArrayList

@s-peiran This behavior is incorrect and can be fixed.

**Comment by s-peiran** [comment]
Thank you for clarifying
