### ISSUE TITLE
Clarification of bug fix for sorting

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#401]
Hi! Currently for our app, if we sort the list of companies, it shows the user the full list of companies, even if they have a filtered list that initially only shows a subset of the full list, which is different from what we intended and what's in the user guide, which states that it sorts the current showed list. 

Just wanted to clarify if this can be fixed.

**Comment by GlendaChong** [comment]
Hi prof @damithc, could we clarify if this will be a bug that we could fix in v1.4? Thank you!

**Comment by damithc** [comment]
@papataco14 @GlendaChong Yes, you can fix it. Sorry, I missed this post somehow.

**Comment by papataco14** [comment]
No worries! Thanks for helping to clarify all our questions prof :)
