### ISSUE TITLE
Are we allowed to show methods and fields in UML class diagrams? 

### ISSUE THREAD

**Issue by tayruxin** [nus-cs2103-AY2324S1/forum#402]
In `style.puml`, which is the default puml style that was given to us from AB3, it `hides members`, as such methods and fields in UML class diagram are not shown. 

If I wish to display methods in my class diagram will that be allowed? Will it be okay to remove that setting?

**Comment by woojiahao** [comment]
You can toggle members by using `show members` in each individual PlantUML file, after the include `style.puml` statement

**Comment by damithc** [comment]
> If I wish to display methods in my class diagram will that be allowed?

@tayruxin Yes, this is certainly allowed.


> You can toggle members by using `show members` in each individual PlantUML file, after the include `style.puml` statement

Good tip @woojiahao

**Comment by tayruxin** [comment]
Thank you so much!
