### ISSUE TITLE
Special Characters in tP Submission File

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#403]
According to the email blast on tP submission file names, we should:
> Replace PRODUCT_NAME with the actual product name (but remove spaces and special characters from the product name e.g, Tasks Pro -> TasksPro -- as they can cause problems when running it).

To clarify, does this mean if my product name is "Staff-Snap", then I should submit it as "StaffSnap", without the hyphen?

**Comment by damithc** [comment]
@craigtonlian In this case, either should be fine as this is unlikely to cause problems when running the jar command.
