### ISSUE TITLE
Clarification on whether a change will be a fixing a feature or improving code quality

### ISSUE THREAD

**Issue by seantehds** [nus-cs2103-AY2324S1/forum#406]
Hi Professor

Thank you for reading this question! I would like to clarify whether a change my group wishes to make would be considered attempting to fix a feature or just improving code quality.

We would like to make a few small changes to the code of one of our existing features to improve the code quality that would not affect the functionality of that command.
```
public Command(Input input) {
    requireNonNull(input);

   A = new Person(constant);
   B = input;
}
```

As an example, you can refer to the example snippet above. 

The field initially had the field A only. B was added to the command later on as an improvement to the command, which was done in v1.3. However, due to an error on our part, in the initialization of the command, A is initialized to a certain fixed value, as the individual who updated this command did not remove it before the end of v1.3.

The only method currently utilizing field A is the toString method of that command, as can be seen below:

```
@Override
public String toString() {
    return new ToStringBuilder(this)
            .add("A", A)
            .toString();
}
```

If we 1) remove the field A from the command, 2) remove the field from the constructor entirely, and 3) change the toString method of the command to not use the field A, but the newly added field B instead, would it be violating the feature freeze? We would like to reiterate that the toString method is not being used in anywhere else in the application, and thus would not be improving any current features of the application.

**Comment by damithc** [comment]
@seantehds From the user POV, what's the current behavior of the affected feature, and how will it change after this fix?

**Comment by seantehds** [comment]
From the user's POV, when the command is executed, the command will do what it is supposed to the model, the user will receive a command successful message if its successful, and whatever error message if it failed.

This change does not affect anything user-facing, and does not change how they use the application/what is displayed to them in the UI.

To clarify prof, as long as the changes we make doesn't 1) affect what the user does/is able to do and 2) does not change what they see (UI), it is ok to fix?

**Comment by damithc** [comment]
@seantehds If there is no impact on external behavior, it is a bug that doesn't affect the current functionality. So, the safe thing (in the interest of minimizing code changes) is to postpone the fix until a future version. But as it is a bug, you are allowed to fix it during the feature freeze, technically.

**Comment by seantehds** [comment]
Ok, thank you prof!
