### ISSUE TITLE
Is tweaking PDF export font size allowed?

### ISSUE THREAD

**Issue by wxwern** [nus-cs2103-AY2324S1/forum#407]
We are intending to tweak the apparent font size of the entire team project website to be smaller specifically in our PDF conversions, either via CSS or website scaling (rationale: the default sizes look too big compared to what text on an A4-sized paper usually looks like).

This will only impact the PDF exports from the output when invoking print, and there will not be apparent changes to font size on the website itself.

I would suppose that is allowed for the UG and DG since there are no restrictions for those. However, the PPP has page limits - hence, would a difference in font size be allowed there?

**Comment by damithc** [comment]
@wxwern It is fine to do reasonable adjustments to the style but don't do that on account of UG/DG page limits. Exceeding the page limit is not penalized but excessive content  can be reported as bugs (because documentation should be minimal and sufficient) irrespective of the font size or the number of pages.

**Comment by wxwern** [comment]
Thank you @damithc 

Updating the font size is done to improve the readability of the page, so that it doesn't look unnaturally big. Despite this, our site will still potentially create similar or more pages than the defaults, as we also included automatic page breaks on areas like headings for similar viewing improvements of the PDF.

My main concern right now is on the PPP. Unlike the UG and DG, it's mentioned on the website that the PPP has a "hard limit" of 2 pages. Reducing the font size has an unintended side effect of making it theoretically possible to fit more content there, so should we be limiting it by something like an approximate word count instead?

**Comment by damithc** [comment]
@wxwern It should be fine if the actual content is a few lines short of 2 pages (at smaller font size).

**Comment by wxwern** [comment]
Thank you prof!
