### ISSUE TITLE
Do all user stories in our DG need to be implemented?

### ISSUE THREAD

**Issue by nathanielcalimag** [nus-cs2103-AY2324S1/forum#409]
Do all user stories in our DG need to be implemented?

Some of our user stories have not been implemented but can be considered for future iterations. Should these be removed for DG?

**Comment by damithc** [comment]
@nathanielcalimag 
Requirements section of the DG applies to current and future. It should certainly cover (and match) the requirements implemented already but also contain other requirements not implemented yet, as this is supposed to be an ongoing project.
