### ISSUE TITLE
Accidentally continued working at branch-Level-7 instead of branch-Level-8

### ISSUE THREAD

**Issue by juliusgambe** [nus-cs2103-AY2324S1/forum#41]
I was wondering if it's possible to continue at branch-Level-7 as I accidentally overlooked that I had to create a separate branch-Level-8. Or, do I need to split the branch-Level-7 as I already committed my changes for branch-Level-8?

**Comment by damithc** [comment]
@juliusgambe OK to continue but welcome/encouraged to try to rectify too.
