### ISSUE TITLE
Clarification regarding acceptable bug fixes

### ISSUE THREAD

**Issue by ryanozx** [nus-cs2103-AY2324S1/forum#410]
Hi Prof, while reviewing our existing commits for v1.4, our team realised there were some bug fixes that we were unsure whether they might violate the feature freeze, and thus, we would like to seek clarification to decide whether we may have to revert some of our changes. They are as follows:

1) For some of the commands, we noted in the UG that missing fields and invalid inputs would throw specific error messages, but currently they all return the generic "Invalid command format" error message (e.g. [106](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/106) , [113](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/113) ). Our team feels that since the app is not behaving according to what the UG describes, it might be considered a bug, but we would like to seek your opinion nonetheless.

2) There is a bug where adding a tag to the person would cause the employee list to reset and display all employees rather than showing the same filtered view as before (see [120](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/120) ). Our team feels that the reasonable behaviour would be not to reset the list when a tag is added and has identified a fix involving deleting one line of code, but are unsure if it can be considered a bug.

3) Within the usage message for one of our commands (`add-leave`), it incorrectly lists the Description field as a required field rather than an optional field, which is the behaviour of the app as well as what the UG describes (see [124](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/124) ). Are we allowed to change the usage message to reflect the correct format?

4) Currently, the name field only accepts alphanumeric characters and spaces. However, this would mean that valid names e.g. Daniel Day-Lewis would be rejected, as it involves a hyphen. As such, can we modify the validation to accept these names?

5) Our app currently uses a CSV parser with semicolons as the delimiter. However, we are considering switching to comma delimiters instead, as highlighted by (135)[https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/135] . From the bug report created, it is arguably not a bug on the part of our app, as the imported CSV file does not use semicolons as delimiters due to Excel's overwriting of the file. As such, our team is unsure whether we can fix this issue.

6) For the issue of text wrapping/truncation, may we clarify if typical inputs for a particular field would likely result in text overflow, that we are allowed to fix it? For instance, we provide a field for adding descriptions to leaves in our app. Our team estimated that since a typical leave description could be well over 100-200 characters, it would likely encounter text overflow. In this context, may we be allowed to fix it?

7) May we clarify if refactoring exception handling is allowed for v1.4? Currently, we have a PR that refactors exception handling, such that they are handled in a lower abstraction layer. This change will not cause any regressions, but may reduce the likelihood of uncaught exceptions being thrown during PE due to better exception handling. As such, our team would like to know if we are allowed to merge these changes into our repo.

Thank you!

**Comment by damithc** [comment]
@ryanozx  my answers below

> * For some of the commands, we noted in the UG that missing fields and invalid inputs would throw specific error messages, but currently they all return the generic "Invalid command format" error message (e.g. [106](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/106) , [113](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/113) ). Our team feels that since the app is not behaving according to what the UG describes, it might be considered a bug, but we would like to seek your opinion nonetheless.

As the current behavior is not incorrect, the remedy is to update the UG to match the behavior (in the interest of minimizing code changes).

> * There is a bug where adding a tag to the person would cause the employee list to reset and display all employees rather than showing the same filtered view as before (see [120](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/120) ). Our team feels that the reasonable behaviour would be not to reset the list when a tag is added and has identified a fix involving deleting one line of code, but are unsure if it can be considered a bug.

OK to fix.

> * Within the usage message for one of our commands (`add-leave`), it incorrectly lists the Description field as a required field rather than an optional field, which is the behaviour of the app as well as what the UG describes (see [124](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/124) ). Are we allowed to change the usage message to reflect the correct format?

OK to fix

> * Currently, the name field only accepts alphanumeric characters and spaces. However, this would mean that valid names e.g. Daniel Day-Lewis would be rejected, as it involves a hyphen. As such, can we modify the validation to accept these names?

OK to fix

> * Our app currently uses a CSV parser with semicolons as the delimiter. However, we are considering switching to comma delimiters instead, as highlighted by (135)[https://github.com/[[PE-D][Tester D] Import feature does not work for valid CSV file AY2324S1-CS2103T-W11-1/tp#135](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/135)] . From the bug report created, it is arguably not a bug on the part of our app, as the imported CSV file does not use semicolons as delimiters due to Excel's overwriting of the file. As such, our team is unsure whether we can fix this issue.

In the UG, explain this limitation. Switching to a different format can be a planned enhancement.

> * For the issue of text wrapping/truncation, may we clarify if typical inputs for a particular field would likely result in text overflow, that we are allowed to fix it? For instance, we provide a field for adding descriptions to leaves in our app. Our team estimated that since a typical leave description could be well over 100-200 characters, it would likely encounter text overflow. In this context, may we be allowed to fix it?

Only if this field is not viewable (through the UI) in any other way either.

> * May we clarify if refactoring exception handling is allowed for v1.4? Currently, we have a PR that refactors exception handling, such that they are handled in a lower abstraction layer. This change will not cause any regressions, but may reduce the likelihood of uncaught exceptions being thrown during PE due to better exception handling. As such, our team would like to know if we are allowed to merge these changes into our repo.

OK, but only if it doesn't affect the current behavior (from user POV)

**Comment by ryanozx** [comment]
Thanks prof! One last clarification from our team:

We currently have a bug (110)[https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/110] in which our find-all-tag command does not work as advertised in the UG. Currently, what it does is that if the user queries for employees with tags A, B, and C, it returns employees who only have tags A, B, and C exactly. An employee with tags A, B, C, D would not be returned, since it contains a tag D that was not queried by the user. If we changed the method so that this employee is also returned, would it be considered a feature enhancement? Our team is unsure as we have differing interpretations of "match all the specified tags exactly" as mentioned in the UG, and thus would like to know if we could consider this a case of actual behaviour not following advertised behaviour. Thank you!

**Comment by damithc** [comment]
> We currently have a bug (110)[https://github.com/[AY2324S1-CS2103T-W11-1/tp/issues/110](https://github.com/AY2324S1-CS2103T-W11-1/tp/issues/110)] in which our find-all-tag command does not work as advertised in the UG. Currently, what it does is that if the user queries for employees with tags A, B, and C, it returns employees who only have tags A, B, and C edactly. An employee with tags A, B, C, D would not be returned, since it contains a tag D that was not queried by the user. If we changed the method so that this employee is also returned, would it be considered a feature enhancement? Our team is unsure as we have differing interpretations of "match all the specified tags exactly" as mentioned in the UG, and thus would like to know if we could consider this a case of actual behaviour not following advertised behaviour. Thank you!

@ryanozx What does the UG say exactly? Can give a screenshot?

**Comment by ryanozx** [comment]
@damithc This is what we wrote in our UG regarding the `find-all-tag` command as of v1.3:

<img width="854" alt="Screenshot 2023-11-11 at 6 01 50 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/59072730/79fe8e07-b6f8-4245-8914-06a3eb5c7a5f">

**Comment by damithc** [comment]
@ryanozx based on the UG as well as normal user expectations, I the feature should return results that have all specified tags, irrespective of whether the item has other tags not mentioned in the command.

On a separate note, also note the following mentioned in week 6 tP instructions:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/0ff277c3-6f98-4bdc-a472-6d2cf53189c9)

**Comment by ryanozx** [comment]
Thanks prof! I'll close the issue
