### ISSUE TITLE
Details regarding Sequence Diagram

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#411]
Hi Prof, 

1. Can the arguments for the methods involved in the sequence diagram not be shown for simplicity sake?

Or if needs to be shown, can we choose to omit objects within the arguments that are not involved in the sequence diagram (meaning as a boxed class at the top of the diagram?)

2. Consider a static nested class B within class A. Say within class C, `randomMethod` makes a call to the constructor of class B.

```
public class A {
    A (String str) { }
    public static class B extends A {
        B (String str) {
           super(str)
        }
    } 
}
```

```
public class C {
     public void randomMethod() {
         A.B("Hello");
     }
}
```

During the instantiation of class B, should class B take the label `<<class>> B` or just `B`.
The confusion here is regarding the `static` nature of the nested class.

3. In which cases is it appropriate to show an object de-reference? Is it only in the case when a method returns an object or throws an exception?

**Comment by damithc** [comment]
@AlagappanRa 
1. Yes, can omit, but consider using `...` to indicate the omission e.g., `foo(a, ...)`
2. If possible, omit this kind of complicated interactions. You can use UML notes or mention in the accompanying text explanations to mention the parts omitted.
3. Can give an example? Or did you mean object deletion?

**Comment by AlagappanRa** [comment]
Qn 1 and 2: Ok, will take note
Qn 3: Yes, i was referring to object deletion (or rather when to put the X and when not to)

**Comment by damithc** [comment]
> Qn 3: Yes, i was referring to object deletion (or rather when to put the X and when not to)

Use it when you want to tell the reader that the object is no longer referenced from the other objects in the system, to say "this object is thrown away at this point". Whether the reader would want to know that information depends on the purpose of the diagram.

**Comment by AlagappanRa** [comment]
1. So if I understand you correctly, the X is not compulsory notation - only if you want to demonstrate the "object being thrown away", you will use it.

2. Regarding the correctness of the X, after a sequence of linear method calls, won't all objects be irrelevant after deactivation? In that case when is it meaningful to put an X underneath?

Maybe a small example of when it is meaningful to show the X would help.

Thank you!

**Comment by damithc** [comment]
> Maybe a small example of when it is meaningful to show the X would help.

For example, it can visually indicate objects that live only within the scope of a method call (i.e., created and discarded within the the method itself), especially if there is a need to differentiate them from another object created within the method but lives on (because it is returned from the method).

**Comment by AlagappanRa** [comment]
Ah ok thank you. I will close this now.
