### ISSUE TITLE
We cant seem to fix some issues we have when converting UG to PDF

### ISSUE THREAD

**Issue by Nid21cs** [nus-cs2103-AY2324S1/forum#412]
This is what our preview looks like before PDF conversion

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/285e08c1-9edb-41d2-8d05-e23fa75b22a3)

This is what it looks like after. We have tried converting it on both edge and chrome but cant seem to get our "boxes" to be filled in. Are there any other other teams facing this? If so any advice?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/b8d44658-3529-4f22-81b0-7df62906bdbf)

**Comment by Nid21cs** [comment]
To anyone facing the same issue, you can tick the box Background and it fixes it

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/0e08bd2b-5335-4828-8fbf-49c17457d33c)

**Comment by damithc** [comment]
@Nid21cs Only the 2nd checkbox, not both. See https://se-education.org/guides/tutorials/savingPdf.html
