### ISSUE TITLE
Clarification if error handling is acceptable with regards to the code freeze

### ISSUE THREAD

**Issue by dhruvir29** [nus-cs2103-AY2324S1/forum#416]
Hi, I had a question regarding whether an error handling that I recently added would be acceptable with respect to the code freeze. 

Prior to the code freeze if someone typed in "delete -1", there would be an error stating that "There is no such recipe with that uuid". However, since it is an invalid uuid since uuid's have to be positive, this error message is technically not right and might be more appropriate for uuid's which are valid but don't exist currently. Hence I wanted to check if I could perform additional error handling at the parser stage for when the id is less than 0, which would then display an error message like "This is an invalid uuid".

**Comment by damithc** [comment]
@dhruvir29 yes, you can fix this during the ~~code freeze~~ feature freeze
