### ISSUE TITLE
Unsure if this is considered a bug that we can fix

### ISSUE THREAD

**Issue by flexibo** [nus-cs2103-AY2324S1/forum#417]
So at the moment, our app have very generic error messages, and we want to make them more specific to hit the UG requirements. 

In v1.3, our UG contains the specific error messages, but our app didn't have those specific error messages so will this count as a bug? Are we allowed to fix it?

**Comment by damithc** [comment]
@flexibo The following applies.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/fd9fdd1d-b21e-4570-81da-15443bd91f2f)

As generic doesn't mean incorrect, you should not tweak them any further. Instead, tweak the UG to fit the current behavior. Making error messages more specific can be listed as a planned enhancement.

**Comment by flexibo** [comment]
Noted, thanks!
