### ISSUE TITLE
Clarification regarding whether the following bug can be fixed

### ISSUE THREAD

**Issue by ryanozx** [nus-cs2103-AY2324S1/forum#418]
Hi Prof, our team discovered the following bug in our app:

1) Create a leave application (Leave Application 1) tagged to a person e.g. Person A. The leave application will indicate that it belongs to Person A.
2) Close the app.
3) Reopen the app.
4) Rename Person A to Person B.

This causes a bug as Leave Application 1 will not update to indicate it now belongs to Person B. This is an issue for the following reasons:
1) When trying to find leave applications belonging to Person B, Leave Application 1 will not appear even though it is supposed to belong to Person B.
2) If we close the app and reopen it again, Leave Application 1 will disappear since leaves are loaded only if they can be associated with an existing person in the address book. Since Leave Application 1 is associated with Person A and Person A no longer exists in the address book, Leave Application 1 will not be loaded and thus be lost.

We noted that the leave application does update if it was created in the current session i.e. the following sequence works:
1) Create Leave Application 2 tagged to Person A.
2) Rename Person A as Person B.

Leave Application 2 will update to indicate it belongs to Person B. As such, could we argue that there is a reasonable expectation that the person's name in the leave application should change when the person's name changes and thus be allowed to fix it? Our team has identified a fix that only requires changing one line of code, thus there is minimal code change. Thank you!

**Comment by damithc** [comment]
> could we argue that there is a reasonable expectation that the person's name in the leave application should change when the person's name changes and thus be allowed to fix it?

@ryanozx Yes, this is a bug. Can be fixed in v1.4

**Comment by ryanozx** [comment]
Thanks prof!
