### ISSUE TITLE
Clarification on whether error message is allowed to fix 

### ISSUE THREAD

**Issue by tayruxin** [nus-cs2103-AY2324S1/forum#419]
Hi! 

Our group has an error message stating that the user has entered an index greater than the number of entries they have. However, this error message seems incorrect after filtering and finding is performed. 

It should state that the user has entered an index greater than the number of entries in the list. Since they have more entries, just that they are not shown. 

I would like to ask if we are allowed to do a quick fix of this error message.

**Comment by damithc** [comment]
@tayruxin Yes, this is a case of giving incorrect information to the user, and can be fixed.

**Comment by tayruxin** [comment]
Thank you so much!
