### ISSUE TITLE
Unable to import Junit for testing.

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#42]
I am working on A-Junit and have faced the following issue:
After adding the folders accordingly, I could not import junit in my test file:
![Screenshot 2023-08-28 at 10 33 00 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/5423a0e9-5e60-407a-bd1e-2f924320100b)

I then thought that it might be due to gradle not recognising these files as test files, therefore I marked the src/test/java folder as a test source root:
![Screenshot 2023-08-28 at 10 33 30 PM](https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/47a5126b-d46a-4993-8c9c-f59a16e6f4c8)

However, it still does not work. I have also tried the following ways that I found on the web:
1. Removing .idea folder and reopening the project again
2. Invalidate Cache and Restart through "File" > "Invalidate Caches / Restart..." and choose "Invalidate and Restart."

**Comment by damithc** [comment]
@yucongkoo While waiting for inputs from others, you can also push the exact code to a branch in your fork and share here so that others can try to replicate the problem.

**Comment by yucongkoo** [comment]
@damithc Alright. I have pushed a dummy test file(src/test/java/duke/DukeTest.java) to a branch:
https://github.com/yucongkoo/ip/tree/branch-A-JUnit

**Comment by Chandan8186** [comment]
I had encountered the same problem, the following was able to fix it for me:

1. Go to build.gradle
2. Comment out/remove `useJUnitPlatform()` inside of `test{ ... }`
3. Click "Load Gradle changes"
4. Uncomment/add `useJUnitPlatform()` inside of `test{ ... }`

Perhaps you can try it out @yucongkoo

**Comment by KamJiaYue** [comment]
build.gradle seems correct. Maybe try load gradle changes and see whether it works.

**Comment by yucongkoo** [comment]
@Chandan8186 Will try these step afterwards, currently my laptop has some problems and is undergoing repairs. I will be leaving this issue open until I am able to test it.

**Comment by supermii2** [comment]
Hi! I had a similar issue and it was caused by my gradle-wrapper.jar and gradle-wrapper.properties files being corrupted! Please check if that is the case (Both files are found in /.gradle/wrapper/ and should have 62kb and 1kb each (Not 0kb as mine was)!

**Comment by Ken-Lai** [comment]
Not sure if you have found the solution, but I will share my approach to this issue here:

```java
// A simplified section from my code

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

public class CommandTest {

    @Test
    public void taskList_inputLessThanOne_exceptionThrown() {
        try {
            Command command = new MarkCommand("0");
            command.execute(taskList, ui, storage);
            Assertions.fail();
        } catch (Exception e) {
            Assertions.assertEquals("The task index cannot be less than 1", e.getMessage());
        }

    }

}
```

Since they are static functions, you can just call them from the Assertions class, e.g. Assertions.assertEquals() instead of assertEquals().

**Comment by yucongkoo** [comment]
Sorry for the delay, just got my laptop back.
The steps provided by @Chandan8186 indeed worked for me, thanks so much for the help.
