### ISSUE TITLE
Updating AddressBook icon during feature freeze

### ISSUE THREAD

**Issue by joeng03** [nus-cs2103-AY2324S1/forum#420]
Hi Prof, are we allowed to update the AddressBook icon with our own icon during feature freeze?
Saw [an issue](https://github.com/nus-cs2103-AY2324S1/forum/issues/378) about this but the circumstances might be a bit different as we have no copyright issues, so we are asking to double check :))

**Comment by damithc** [comment]
@joeng03 Updating the icon will be an enhancement (i.e., not allowed) unless there is some problem with the current one.
