### ISSUE TITLE
Adding missing `$` due to regression

### ISSUE THREAD

**Issue by woojiahao** [nus-cs2103-AY2324S1/forum#421]
Is it possible to re-add a missing `$` that was removed accidentally during a previous PR made by someone else? The screenshots of the command use shows that `$` was present so it's not a new change. Thanks!

**Comment by damithc** [comment]
@woojiahao can you point out the PR/commit that introduced the regression? A screenshot showing the relevant code is good enough (i.e., no need to identify the author).

**Comment by woojiahao** [comment]
This was the commit that added it in:
![Screenshot 2023-11-12 at 18 05 31](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/1e2521fb-00fd-4062-9c07-8f5a59219377) with the [commit here.](https://github.com/AY2324S1-CS2103-T16-3/tp/commit/e4885716727d3b495ef0671cf129a0955d22b0b0#diff-156555d7d9be8a35b0416469fd3a96b653ffcbdfe6cca964f131839e515a679f) This was dated on 2 November (before feature freeze).

This was the commit that removed it. After further inspection, it occurred as the previous iteration did not have the `$` and so when merging in the changes, it had used the previous iteration's version which was missing the `$`. The author of it was migrating the command messages and might have been using the previous version, thus introducing the accidental regression.

![Screenshot 2023-11-12 at 18 08 03](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/d897e0ee-8db7-48a7-b361-08c4af7a115e)

**Comment by damithc** [comment]
@woojiahao Go ahead.

**Comment by woojiahao** [comment]
Awesome, thank you @damithc
