### ISSUE TITLE
Is fixing spelling mistake in message shown allowed?

### ISSUE THREAD

**Issue by timetraveller-123** [nus-cs2103-AY2324S1/forum#422]
Hi prof,
Currently, in one of the messages being shown "short form" is spelt as "short from".
Can this be fixed?
Thanks.

**Comment by damithc** [comment]
@timetraveller-123 any spelling mistakes and grammar errors (in the UI or in docs) can be fixed during the feature freeze.

**Comment by timetraveller-123** [comment]
Thank you.
