### ISSUE TITLE
Clarifying whether changing search functionality would be a new feature

### ISSUE THREAD

**Issue by supermii2** [nus-cs2103-AY2324S1/forum#423]
Originally search command allowed for multiple names, but was changed to 1 name. Though it was not explicitly stated in v1.3 that you could search for multiple names, searching for multiple names always returned no users anyway.

For example, previously `search Alex Yeoh, Irfan Ibrahim` was a valid search, but would return nothing. 

Documentation states that if multiple conditions were given, then it would return users that would match all, i.e. have both names. Since this would always return nothing, would it violate the feature freeze to instead throw an error instead of return nothing?

**Comment by damithc** [comment]
@supermii2 Yes, the ability to search for multiple names may be removed (as removing a feature is allowed during the feature freeze).

**Comment by supermii2** [comment]
Thank you!
