### ISSUE TITLE
Advice regarding what to fix and procedure to revert enhancements

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#425]
Hi, sorry for the late question - my group and I were confused if we could make fixes to some of these bugs after checking the forums, so we wanted to clarify for these:

1. Our program does not show an error message if no fields have been modified during an `edit` command, and just tells the user that the field has been successfully modified. Would it be a bug fix if we made this case show an error message to reduce confusion?
2. Our program currently has a panel that retains a snapshot of the `Person` data on the UI. Currently, if the user tries to add a person with no changes that already exists on this panel, no error is thrown, and the program tells the user that the person has been successfully added. Would it be a bug fix if we made this case show an error message to reduce confusion?
3. For the panel that retains a snapshot, our intention was to have the snapshot update any existing persons to the latest version of the `Person` data if we add duplicates to this panel. However, it currently does not do this. Will we be allowed to modify this behavior to add this to the program?
4. Are we allowed to modify user input to force upper-case if we had previously specified that the item is unique? ie we want ID to be unique, but both 873B and 873b are allowed when they shouldn't.
5. We have an undo command - however, undo on delete currently returns the person back to the bottom of the list instead of their original location on the list. Will we be allowed to return the person back to their original location?

Finally, I want to ask - our group has made changes that we thought were bug fixes, but realized later that they were enhancements after checking the forums. Can we push new commits to revert these changes by removing them to fix this?

**Comment by damithc** [comment]
> 1. Our program does not show an error message if no fields have been modified during an `edit` command, and just tells the user that the field has been successfully modified. Would it be a bug fix if we made this case show an error message to reduce confusion?

@WZWren can you give an example command and the precise result message? Is it an empty edit command or editing previous value to the same value?

> 2. Our program currently has a panel that retains a snapshot of the `Person` data on the UI. Currently, if the user tries to add a person with no changes that already exists on this panel, no error is thrown, and the program tells the user that the person has been successfully added. Would it be a bug fix if we made this case show an error message to reduce confusion?

Do you mean the addition fails because there is already an existing entry with the same data? Yes, showing a success message when the operation failed is an error, and can be fixed.


> 3. For the panel that retains a snapshot, our intention was to have the snapshot update any existing persons to the latest version of the `Person` data if we add duplicates to this panel. However, it currently does not do this. Will we be allowed to modify this behavior to add this to the program?

I'm not very clear how this panel works, especially regarding this case of adding duplicates. Can explain more with screenshots and examples?
Was this feature stated in the UG?
Was the feature implemented but not working due to a bug, or not implemented at v1.3?


> 4. Are we allowed to modify user input to force upper-case if we had previously specified that the item is unique? ie we want ID to be unique, but both 873B and 873b are allowed when they shouldn't.

Yes, if adding both 873B and 873b somehow causes the application to misbehave and hence, should be prevented. Otherwise it is an enhancement.

> 5. We have an undo command - however, undo on delete currently returns the person back to the bottom of the list instead of their original location on the list. Will we be allowed to return the person back to their original location?

Yes.


> Finally, I want to ask - our group has made changes that we thought were bug fixes, but realized later that they were enhancements after checking the forums. Can we push new commits to revert these changes by removing them to fix this?

Yes, that should be fine.

**Comment by WZWren** [comment]
> can you give an example command and the precise result message? Is it an empty edit command or editing previous value to the same value?

It is editing previous value to the same value ie `edit p/12345` on a person with the phone number `12345`.

> I'm not very clear how this panel works, especially regarding this case of adding duplicates. Can explain more with screenshots and examples?
> Was this feature stated in the UG?
> Was the feature implemented but not working due to a bug, or not implemented at v1.3?

It is a panel that stores the results of our previous `find` command that serves as a sticky-note. On its own it is not meant to update its values even if we edit the original value in the list.

Before:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/115881359/c75159ec-7f39-4c55-9464-bb57f63051ae)

After:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/115881359/6d775df1-6bcc-4516-89d0-7476b349c6b3)

What we wanted was when the user tries to add the person to the panel after an `edit`, the value in the panel refreshes to the latest version of the value. However it does not do that right now.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/115881359/782b24da-099f-4885-86a4-163f3de414e6)
> _(bug fix for point 2 has already been implemented)_

This was intended at v1.3 of the panel - it is stated in the UG that the panel stores the last known values of the people to add to this panel at the time the command was called. However, the feature was not explicitly implemented as we had thought the implementation at v1.3 was sufficient.

**Comment by damithc** [comment]
> > can you give an example command and the precise result message? Is it an empty edit command or editing previous value to the same value?
> 
> It is editing previous value to the same value ie `edit p/12345` on a person with the phone number `12345`.

As the current behavior is not incorrect (in fact this could be argued as the default behavior of edit operations), any further changes will be considered as an enhancement.

> > I'm not very clear how this panel works, especially regarding this case of adding duplicates. Can explain more with screenshots and examples?
> > Was this feature stated in the UG?
> > Was the feature implemented but not working due to a bug, or not implemented at v1.3?

> It is a panel that stores the results of our previous `find` command that serves as a sticky-note. On its own it is not meant to update its values even if we edit the original value in the list.
> 
> Before: ![image](https://user-images.githubusercontent.com/115881359/282310929-c75159ec-7f39-4c55-9464-bb57f63051ae.png)
> 
> After: ![image](https://user-images.githubusercontent.com/115881359/282310978-6d775df1-6bcc-4516-89d0-7476b349c6b3.png)
> 
> What we wanted was when the user tries to add the person to the panel after an `edit`, the value in the panel refreshes to the latest version of the value. However it does not do that right now.
> 
> ![image](https://user-images.githubusercontent.com/115881359/282311205-782b24da-099f-4885-86a4-163f3de414e6.png)
> 
> > _(bug fix for point 2 has already been implemented)_
> 
> This was intended at v1.3 of the panel - it is stated in the UG that the panel stores the last known values of the people to add to this panel at the time the command was called. However, the feature was not explicitly implemented as we had thought the implementation at v1.3 was sufficient.

This looks like a bug. Can fix.

**Comment by WZWren** [comment]
Thank you for your prompt reply prof!
