### ISSUE TITLE
Clarification regarding long inputs

### ISSUE THREAD

**Issue by aslam341** [nus-cs2103-AY2324S1/forum#426]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65384645/f8d5622c-74f0-4c14-b6f0-e4f6c23272ce)

Our application does not limit the string length of the name of a person.

When a person's name exceeds more than 200 characters (which I think can be considered extreme input?), part of the name is truncated and can't be seen. So, how can I go about this? Is this a bug?

Possible solutions:
1. Limit the number of characters for the name of a person in code (lets say 100 characters), and mention this limit in the UG.
2. Don't do anything to the code. But, mention in the UG that it is best to limit the number of characters for a name to be 100.
3. Same as solution 2, but in addition, mention in the DG `Planned Enhancements` that we plan to forcefully limit the number of characters to 100.
4. Modify the UI slightly to show all the characters of the name without truncation.

I am unsure if the solution 4 is "accomodating 'extreme' inputs" and therefore it is not a bug fix but instead an enhancement. So, between 1, 2 and 3 what should be done? Or is there something else that should be done?

**Comment by damithc** [comment]
@aslam341 I recommend choosing 2 or 3 as it is reasonable, and also minimizes code changes.

**Comment by aslam341** [comment]
@damithc thank you for the reply at such a late hour. If I choose to go with 2 (since each team only has maximum 10 planned enhancements they can add), are testers allowed to point out the bug that: very long input causes UI to truncate the name; even though the UG has stated that it is best to limit to 100 characters?

**Comment by damithc** [comment]
> If I choose to go with 2 (since each team only has maximum 10 planned enhancements they can add), are testers allowed to point out the bug that: very long input causes UI to truncate the name; even though the UG has stated that it is best to limit to 100 characters?

@aslam341 Yes testers are allowed to report it. You can reduce the severity of the bug by explaining the limit in the UG. Also, if you can successfully argue that there is no real need to exceed this limit in normal usage (or the usage of the app is not really affected by this limit in normal usage), the bug can be categorized as `response.NotInScope` which doesn't carry a penalty.
