### ISSUE TITLE
UML Diagram XOR

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#427]
Hi all,

Suppose there is a class `A`, `B` and `C`, and `A` depends on 1 of `B` **or** 1 of `C` (but not both or none), how should this be represented on the UML diagram for the DG?

Some [sources](https://stackoverflow.com/questions/76431771/uml-constraint-xor-between-two-associations) online have recommended adding a constraint with text to highlight it is XOR, but I was wondering if it is legal for this module?

Alternatively, are there other ways to represent this?

Thank you!

**Comment by damithc** [comment]
@lihongguang00 Adding a UML note to mention the additional constraint should be enough.
