### ISSUE TITLE
Feature freeze clarification

### ISSUE THREAD

**Issue by zhanyang01** [nus-cs2103-AY2324S1/forum#428]
Is removing part of a feature to remove unnecessary details for the file a enhancement or a removal of feature?

<img width="403" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/22724d55-bb04-48e6-84ba-a8e0949604a9">

We are planning to remove the hashcode which is removing a part of a feature

**Comment by damithc** [comment]
@zhanyang01 Yes, you can remove it.

**Comment by zhanyang01** [comment]
Thank you prof
