### ISSUE TITLE
Will the format of the .txt file be considered in grading?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#43]
I am able to load the .txt file upon starting the chatbot, but since the .txt file stores the ArrayList itself instead of Task elements, its String representation is not readable. It was mentioned on the CS2103T website that the format is up to us, but the example given was readable, which now makes me doubt myself.

**Comment by damithc** [comment]
@JasonRay168 Yes, the iP file format is up to you. But in the tP, the file is required to be readable/editable by the user.

**Comment by JasonRay168** [comment]
Thank you very much Prof!
