### ISSUE TITLE
Clarification on whether bugs can be fixed

### ISSUE THREAD

**Issue by spatuly** [nus-cs2103-AY2324S1/forum#430]
1) In the delete command for our app, the user can indicate to delete all with an optional input tg/. When delete all is used without the optional input, errors are thrown correctly (does not allow extraneous inputs). All other commands with parameters also do not take in extraneous inputs. However, due to a bug in the code, when delete all is used with tg/, it allows commands such as "delete allocated tg/1" and "delete all pdsjfsk tg/1" to be parsed as a "delete all tg/1", and deletes all corresponding students. We believe that it is incorrect and should be fixed, but wanted to clarify if we can?

2) As mentioned in a previous issue, some commands in our app allows for duplicate inputs, such w/1 w/2 w/3, and takes the last one as the input to be parsed. It was mentioned in the response to that that the behaviour can be mentioned in the UG and that it is not incorrect. We would just like to know if this means that as long as we included this as intended behaviour in the UG, we would not be penalised for bug reports on it, or if we should add it to the DG under planned enhancements as well?

**Comment by damithc** [comment]
> 1. In the delete command for our app, the user can indicate to delete all with an optional input tg/. When delete all is used without the optional input, errors are thrown correctly (does not allow extraneous inputs). All other commands with parameters also do not take in extraneous inputs. However, due to a bug in the code, when delete all is used with tg/, it allows commands such as "delete allocated tg/1" and "delete all pdsjfsk tg/1" to be parsed as a "delete all tg/1", and deletes all corresponding students. We believe that it is incorrect and should be fixed, but wanted to clarify if we can?

Yes, this can be fixed. In particuar, `delete allocated tg/1` should not be interpreted as `delete all tg/1`

> 2\. As mentioned in a previous issue, some commands in our app allows for duplicate inputs, such w/1 w/2 w/3, and takes the last one as the input to be parsed. It was mentioned in the response to that that the behaviour can be mentioned in the UG and that it is not incorrect. We would just like to know if this means that as long as we included this as intended behaviour in the UG, we would not be penalised for bug reports on it, or if we should add it to the DG under planned enhancements as well?

Mentioning it in the UG will certainly make it a feature rather than a bug. Note that testers still can report FeatureFlaw type bugs against the current behavior of a feature. So, if you think there is a better behavior for this case, you can list it under planned enhancements.
