### ISSUE TITLE
Question on acceptable bug fix

### ISSUE THREAD

**Issue by LHeng1** [nus-cs2103-AY2324S1/forum#431]
Hi! Our team wanted to check if fixing the following issue would be acceptable as a bug fix:

>One of our commands does not function if a specific `Optional` variable is not present, even though it is promised in the UG.

Possible solutions that my team thought of as of now:
1. Add one line of code and the whole command works perfectly.
2. Delete some code to remove the `Optional` variable being needed for the command to run.
3. Delete the whole command.
4. Include it in the `planned enhancements` part in the DG.

Thank you!

**Comment by damithc** [comment]
@LHeng1 Do you mean a parameter that is specified as optional in the UG is behaving as if it is compulsory? If yes, you can fix it. Otherwise please post the relevant UG section and a screenshot of the actual behavior.

**Comment by LHeng1** [comment]
@damithc

>a parameter that is specified as optional in the UG is behaving as if it is compulsory

We did specify the parameter as an optional parameter in general in the UG, but it is and should be behaving as if it is compulsory through the specified command. I have added the relevant UG sections and actual behavior below:

Command description:
<img width="576" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/994cd107-9452-4737-b6ff-b5b346ad54c6">
<img width="590" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/8e6a6d54-bfd1-4694-bdef-e73bcb926c9c">

Actual expected behavior:
The parameter in question is `Interview Score`, where a "-" is used when user never added the parameter.

<img width="215" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/03957c01-6db1-44e3-9f5b-38dbe1936643">
<img width="212" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/0ac65926-28d7-4034-a9b7-9856aac3c51c">

General description of parameters in UG, where [ ] parameters are optional:
<img width="534" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/57ae64ce-25ab-4c68-b375-9539f486f255">

**Comment by damithc** [comment]
@LHeng1 Thanks for the explanation. Can you elaborate on the "doesn't work" part?

If the optional parameter is not present, how does the command behave now, and how should it behave (i.e., the proposed fix)?

**Comment by LHeng1** [comment]
@damithc 

As of now, If the optional parameter is not present (`Interview Score`), the command will not cause any changes to the main UI window, as shown below:
<img width="695" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/31c6576e-2dac-44fe-a6a7-8d0a93cc0470">

The expected behavior as stated in the UG excerpt, even if the optional parameter is not present (`Interview Score`), the command is supposed to generate a pop-up UI window, and still show the parameter as a dash as shown in the image below:
<img width="656" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110957690/76e1c526-1a0e-44b5-8fb8-a64ab44d59e4">

**Comment by damithc** [comment]
@LHeng1  Understood. Yes, you can fix this. It is not correct for the command to fail silently anyway.

**Comment by LHeng1** [comment]
Alright, thank you so much!
