### ISSUE TITLE
Is editing our User Guide past the 2103 deadline for 2101 alright?

### ISSUE THREAD

**Issue by dhruvir29** [nus-cs2103-AY2324S1/forum#432]
The deadline for our CS2101 User Guide is a 1.5 days after the deadline for CS2103. Since there are extra requirements for CS2101 regarding the UG, would we be able to edit the UG in our repo even after the CS2103 deadline?

**Comment by damithc** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/6f1c0b2d-ee8f-497f-8d7d-32f2f82c9410)

A gap of 0.5 is still recommended, but not required.
