### ISSUE TITLE
Clarification on allowing symbols in names

### ISSUE THREAD

**Issue by aslam341** [nus-cs2103-AY2324S1/forum#433]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65384645/baacac11-b32a-42fb-97af-4e77a0e3ac06)

Is it considered an enhancement if we were to now allow characters such as `/` and `-` in person names, when previously we didn't? Because some names can contain `/` and `-` but our application does not allow special characters, and we do not have any special reason for not allowing these special characters. Since valid names such as `Amelia-Rose` and `Vishnu S/O Prasath` are not allowed by the application when it should've, is this considered a functionality-bug and therefore can be fixed?

**Comment by damithc** [comment]
@aslam341 Yes, rejecting valid values can be considered a bug, and fixed.
