### ISSUE TITLE
Simplicity of a sequence diagram

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#434]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/7a120661-985d-4311-8ff8-a1c93f333495)

Hi Prof, 

Above is an example sequence diagram covered in the tutorial. I was confused as to how "simple" should the diagram be.

Say I have a sequence diagram which has 2 linear method calls. (For example, from `AddCommand`'s `execute` method, three method calls are propagated, of which 2 method calls are to two other classes in `Logic` component, and the last one to the `Model` component). The method calls to the 2 classes in `Logic` immediately return to `AddCommand`. I then proceed to show the low-level details within the `Model` component. 

Is this considered violating the "simplicity" of the diagram due to "showing low-level details for more than one component". The purpose of the diagram is to show the method call propagation, which covers the interaction between the `Logic` and `Model` components. 

I am having difficulty squaring this with making the diagram represent as close to implementation as possible and fitting the purpose. If you do think that the proposed diagram is too complex how do you suggest simplying it?

**Comment by damithc** [comment]
> Is this considered violating the "simplicity" of the diagram due to "showing low-level details for more than one component". The purpose of the diagram is to show the method call propagation, which covers the interaction between the `Logic` and `Model` components.

@AlagappanRa Yes, interaction _between_, not _inside_ both. So, if you are showing internal details of the Logic component, that means this diagram appears inside the section that explains the Logic component, and hence, the reader should not be forced to know details inside the Model component. So, the Model component should be shown as one lifeline only, showing only the API visible to the Logic component.

Relevant https://github.com/nus-cs2103-AY2324S1/forum/issues/398

**Comment by AlagappanRa** [comment]
@damithc But is this ok under the implementation section? The purpose was defined by me while writing documentation for the implementation. I understand that while explaning parts under `Logic`, `Model` should be listed as an API, however, the grey area is when the diagram is under implementation.

**Comment by damithc** [comment]
@AlagappanRa When writing documentation in a top-down fashion (which is what we recommend), any part of the documentation should not force the reader to know lower level details of more than one component. As a workaround, you can split it into multiple diagrams, each containing lower level details of no more one component. While this results in more diagrams, each diagram will be simpler on its own.

**Comment by AlagappanRa** [comment]
@damithc 
> @AlagappanRa As a workaround, you can split it into multiple diagrams, each containing lower level details of no more one component.

What is an example of this workaround.

Is it one diagram that shows `Model` as API and another that shows `Logic` as an API stacked one on top of each other? Or side-by-side? 

Or alternatively, it will just be ok to simplify it to a single diagram and making either component an API right?

**Comment by damithc** [comment]
> Is it one diagram that shows `Model` as API and another that shows `Logic` as an API stacked one on top of each other? Or side-by-side?

Diagrams exist in the context of an explanation, and those explanation should follow the top-down multi-level explanation style too. So, you can first explain how this feature is implemented in the Logic component (using diagram that do not show low level details of other components) and in another sub-section you can explain how it is implemented in the Model component (using diagrams that show low level details of Model only -- other components can appear but only as API only), and so on.

> Or alternatively, it will just be ok to simplify it to a single diagram and making either component an API right?

Yes, if you think there is no need to explain lower level details of _any_ component. Or, you could do this in addition to the other diagrams, at the start of the explanation, to give an overview first. Notice how AB3 uses that kind of sequence diagrams when explaining the architecture.

#### AB3 example:
When explaining the architecture:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/ae2feafe-a5bf-45ce-99c3-00a6fcf28150)

When explaining the Logic:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/b20186ad-5ece-400a-afc0-c9cd4378cece)

**Comment by AlagappanRa** [comment]
Ok thank you for the thorough explanation and your time!
