### ISSUE TITLE
Follow-up on #292

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#435]
#292.

Hi Prof,

You mentioned 3 branch nodes to represent this code.
```
if (a) {...)
if (b) {...}
if (c) {...}
```

But shouldn't you be needing a minimum of 7 branch nodes ? 

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/c0bd9bdd-c4f9-4c9c-9204-a64e1dd275ad)

**Comment by WZWren** [comment]
You can express it in 3 branches - notice that branch for `b` and `c` are done no matter the result of `a`, so you should place the check after the paths merge again. Something like:

```
   A?
  / \
 y   n
 |   |
 A   |
 |   |
 \   /
  < >
   |
   B
 ......

**Comment by AlagappanRa** [comment]
Oh i see. Just another clarification, is first diagram considered a wrong diagram or just not-optimal when talking about Activity Diagrams.

**Comment by damithc** [comment]
@AlagappanRa The original diagram has room for improvement (as it currently harder-than-necessary to follow), and not a natural visual match to how the code actually works.
