### ISSUE TITLE
Re-using an object's lifeline based on `alt` paths in sequence diagram

### ISSUE THREAD

**Issue by woojiahao** [nus-cs2103-AY2324S1/forum#436]
I was wondering but are we allowed to re-use the same object's lifeline when it is created during different `alt` paths, something like this where the `commandResult` differs based on the `alt` path taken:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/2ae55603-03ef-41e2-a31c-d141e5e7af5d)

Or do we have to create three separate lifelines for all three `alt` paths?

**Comment by damithc** [comment]
@woojiahao use the same lifeline.

**Comment by woojiahao** [comment]
So to confirm, the sequence diagram above does not violate any of the conventions?

**Comment by damithc** [comment]
> So to confirm, the sequence diagram above does not violate any of the conventions?

@woojiahao the use of the same lifeline across alt frames in the given diagram is fine.

**Comment by woojiahao** [comment]
Awesome, thank you for the clarification prof @damithc
