### ISSUE TITLE
PE bug testing

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#437]
Say a group that you are testing has minimal bugs (30 minutes into the testing phase) and you decide to request the TA/Prof for possibly another group. Will you be given the full one hour again to test on the backup product?

**Comment by damithc** [comment]
> Say a group that you are testing has minimal bugs (30 minutes into the testing phase) and you decide to request the TA/Prof for possibly another group.

@AlagappanRa This is not a valid reason to request for another team to test. A second team to test will be given only if a student run into technical problems with the first one (need to submit proof first) in the first few minutes of testing, and in those cases an extra time will be added to their PE time.

**Comment by AlagappanRa** [comment]
@damithc  Ok, thank you. I was confused by this, but after re-reading, your explanation makes sense.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/da2331e6-2841-4fb9-b146-d51b5facfd82)
