### ISSUE TITLE
Clarification of feature freeze rules and bugs that can be fixed

### ISSUE THREAD

**Issue by peasantbird** [nus-cs2103-AY2324S1/forum#438]
Hi prof, my team and I would like to be very sure we aren't violating any feature freeze rules. Could you help to verify if any of these are violations?

### 1. UG does not include default sort
Our sort command for v1.3 sorts the list of persons based on a prefix and sort order (included in the UG), but also sorts by the default input order when no prefix and sort order is given (not included in the UG). Is adding this already implemented feature into the UG considered a feature freeze violation or a bug? Should we remove this feature or is adding it to the UG okay?

### 2. Sort command takes in invalid parameters and does the default sort
Our sort command takes in invalid parameters like `sort qwerty` and invalid prefixes and sort orders like `sort qwerty/asdf` and does the default sort since there are no valid prefixes and sort orders. This behavior was not recorded down in our UG. Will implementing a check for invalid parameters and invalid prefixes and sort orders and showing an error message to the user be a feature freeze violation or a bug fix? Would recording this behavior into our UG be okay?

### 3. Sort command takes in extra valid prefixes
Our sort commands takes in extra valid prefixes like `sort prio/d n/d` and only does the first sort, i.e. `sort prio/d`. This behavior was not recorded down in our UG. Will implementing a check for extra prefixes and showing an error message to the user be a feature freeze violation or a bug fix? Would recording this behavior into our UG be okay?

### 4. Changes to sort command error message for invalid sort order
When the sort order is wrong, the sort command throws a general error message on how to use the sort command. Will changing the error message to tell the user that the sort order is wrong be a feature freeze violation or a bug fix? 

### 5. Changes to sort command help message
The current sort command has the help message `... Parameters: Choose one of...`. However, for the default sort, the sort command accepts zero parameters. Will changing the help message to `... Parameters: Choose zero or one of...` be a feature freeze violation or a bug fix? 

Thanks!

**Comment by damithc** [comment]
> ### 1. UG does not include default sort
> Our sort command for v1.3 sorts the list of persons based on a prefix and sort order (included in the UG), but also sorts by the default input order when no prefix and sort order is given (not included in the UG). Is adding this already implemented feature into the UG considered a feature freeze violation or a bug? Should we remove this feature or is adding it to the UG okay?

Sure, can update the UG to include it.  

> ### 2. Sort command takes in invalid parameters and does the default sort
> Our sort command takes in invalid parameters like `sort qwerty` and invalid prefixes and sort orders like `sort qwerty/asdf` and does the default sort since there are no valid prefixes and sort orders. Will implementing a check for invalid parameters and invalid prefixes and sort orders and showing an error message to the user be a feature freeze violation or a bug fix?

You can mention this behavior in the UG. Better error handling can be a planned enhancement.

> ### 3. Sort command takes in extra valid prefixes
> Our sort commands takes in extra valid prefixes like `sort prio/d n/d` and only does the first sort, i.e. `sort prio/d`. Will implementing a check for extra prefixes and showing an error message to the user be a feature freeze violation or a bug fix?
 
Same as above.

> ### 4. Changes to sort command error message for invalid sort order
> When the sort order is wrong, the sort command throws a general error message on how to use the sort command. Will changing the error message to tell the user that the sort order is wrong be a feature freeze violation or a bug fix?

This seems like an enhancement (as the current error message is not incorrect).
 
> ### 5. Changes to sort command help message
> The current sort command has the help message `... Parameters: Choose one of...`. However, for the default sort, the sort command accepts zero parameters. Will changing the help message to `... Parameters: Choose zero or one of...` be a feature freeze violation or a bug fix?

This should be fine, as the current message is inaccurate.

**Comment by peasantbird** [comment]
@damithc Thank you so much for the clarifications!
