### ISSUE TITLE
UI Bug on different platforms

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#439]
Hello prof @damithc ,

Our team is having a peculiar issue with our UI where on 1 of our groupmate's computer (as well as 1 PED tester's computer), the UI is inconsistent with the rest the team's UI (and rest of the PED testers' computers). 

When said group mate replicated the bug, we copied over the data files from his computer and ran it on our computers, but the UI looks fine on the rest of our computers. Since we all use windows, it dosen't seem like it is OS dependent. 

What would be the appropriate means to address this?

Thanks!

**Comment by damithc** [comment]
Perhaps share more details here so that others can help troubleshoot? 
Note that there are other things than can affect the UI even if the OS is same e.g., Locale setting (e.g., language, date/time format), Zoom level

**Comment by lihongguang00** [comment]
Hello prof,

We figured out that the zoom level was the problem from your reply, in this case, would it be appropriate to note in the UG that the zoom level causes a UI bug?

**Comment by glenngnng** [comment]
Hey just wanted to jump in.

I think it should be in the UG! You can add it in the known issues segment, and perhaps add a way to address the issue for the user.

**Comment by damithc** [comment]
@lihongguang00 Yes, you can inform users about this limitation and workaround in the UG.
