### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by larrywang0701** [nus-cs2103-AY2324S1/forum#44]
Hello professors and classmates
I'm curious about that are we allowed to make graphical user interface (e.g. a window) for Duke project rather than text user interface?

**Comment by damithc** [comment]
@larrywang0701 We'll be moving to a GUI when we reach Level-10 (in week 4).

**Comment by muhammadreyaaz** [comment]
Hi @larrywang0701 please close this issue if it is resolved. Thanks!
