### ISSUE TITLE
Feature Freeze: Are we allowed to freely modify the user feedback box

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#440]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/157763cd-3a01-4df5-843b-b3f9e5a94f05)

The box that outputs whether the command is a success or failure is the user feedback box, as indicated above.

Are we allowed to freely edit what is shown in this box?

For context, our app has Contacts and Meeting classes, and Meeting can contain contacts in a list. 
When we try to delete a contact from a meeting, there are two situations. The contact does not exist at all, and the contact does not exist in the meeting. The current feedback text is too general, and I want to make it specific that reflects which scenario it belongs to.

But my bigger question is whether we can change freely the output in this box regardless of the situation.

**Comment by damithc** [comment]
@s-peiran 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/4b1a1f6f-857c-4a78-89c0-2b7c19c9063f)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/34c97935-85e2-41b2-9723-fa8af2df91eb)

So, both not allowed.

**Comment by tanyyyming** [comment]
I think you can only do the edit if your UG have already specified the exact text in the feedback box but your application fails to comply with it. In this case, your text is considered an "incorrect" output and can be fixed.

Correct me if I am wrong!

**Comment by damithc** [comment]
> I think you can only do the edit if your UG have already specified the exact text in the feedback box but your application fails to comply with it. In this case, your text is considered an "incorrect" output and can be fixed.

@tanyyyming Close but not entirely. If the current output is not incorrect but differs from the UG, the UG should be updated (in the interest of minimizing code changes).

**Comment by s-peiran** [comment]
Thank you @tanyyyming  for chiming in.

@damithc Prof I have found another issue in my code.
1.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/e62c3788-7bde-4878-b6f9-1e36403da487)
There is a typo at line 39, it should be timeEnd instead of timeStart, but I wasn't very specific in my UG then, the UG states:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/0910bd80-4c98-4db7-9723-fb22f3265e27)
Am I allowed to correct the above-mentioned typo?

2. Currently we allow the user to filter the meeting by start time and end time. However, I have used the LocalDateTime isAfter(other) and isBefore(other) function, which is non-inclusive on the dateTime that the user has input. The filter should be inclusive of the user input so that the user can search for a meeting that falls under the exact dateTime by stipulating the same startTime and endTime. Am I allowed to make the time inclusive of the user input?

**Comment by damithc** [comment]
> Am I allowed to correct the above-mentioned typo?

Yes.


> 2\. Currently we allow the user to filter the meeting by start time and end time. However, I have used the LocalDateTime isAfter(other) and isBefore(other) function, which is non-inclusive on the dateTime that the user has input. The filter should be inclusive of the user input so that the user can search for a meeting that falls under the exact dateTime by stipulating the same startTime and endTime. Am I allowed to make the time inclusive of the user input?

Yes.

**Comment by s-peiran** [comment]
Thanks prof for your clarification
