### ISSUE TITLE
Checking if this is allowed to be fixed

### ISSUE THREAD

**Issue by techjay-c** [nus-cs2103-AY2324S1/forum#441]
Hi Prof

My team and I discovered a bug where out filter feature for our patient and dentist accepts extra attributes and the command is not what we had envisioned and expected.

For example, a proper command is filter-dentist / filter-patient a/ATTRIBUTE k/KEYWORDS but if the command is filter-dentist / filter-patient a/ATTRIBUTE k/KEYWORDS k/KEYWORDS, meaning more than one k/ happens, the filter feature will be conducted based on everything after the first k/, meaning filter will be on KEYWORDS k/KEYWORDS. 

We fixed this as we consider it to be a bug, as the expected behaviour when the command is not in the format filter-dentist / filter-patient a/ATTRIBUTE k/KEYWORDS  should be to throw an exception that it has to be in this format.

I would like to confirm with you if this is allowed or if we will be required to revert this change.

Thanks.

**Comment by damithc** [comment]
@techjay-c Treating the second `k/KEYWORDS` as part of the search string (when it clearly contains a known parameter prefix) can be considered a bug and can be fixed. But do apply a minimal fix and leave further improvements as a planned enhancement, in the interest of minimizing code changes.

**Comment by techjay-c** [comment]
Thank you prof. Yes only the regex was changed. I will close this issue now
