### ISSUE TITLE
Question on Sequence Diagram in DG

### ISSUE THREAD

**Issue by Carlintyj** [nus-cs2103-AY2324S1/forum#442]
Hi prof @damithc ,

Just 2 quick questions on the Sequence diagram. We are currently in the midst of simplifying the sequence diagram to show the internal details of at most one component but ran into a couple of roadblocks.

This is the add command sequence diagram:
![AddSequenceDiagram](https://github.com/nus-cs2103-AY2324S1/forum/assets/102083899/7a6b6be6-8ee7-4e9b-a278-d4254aee569e)

Questions:
1. In the above sequence diagram, we are simplifying them to the model containing only one model lifeline. However, the person and course object is being constructed during the process, do we include them in the model component as well? This means that there will be 3 lifelines in the model component? 

2. In AB3, the sequence diagram for the delete operation did not include ParserUtil, but after looking through the code we found out that it goes through ParserUtil, do we include it in the sequence diagram?

Thank you.

**Comment by damithc** [comment]
Good question @Carlintyj 
See if this issue thread answers your question https://github.com/nus-cs2103-AY2324S1/forum/issues/398
Short answer: show the Course/Person object creations inside the Logic component, as that is where they happen anyway.

**Comment by tanteckfang** [comment]
Hi Prof @damithc , do you mean that all the Model Component can be all refer as one single participant Model? 
for example, this is my original UML, 
<img width="1463" alt="Screenshot 2023-11-13 at 4 47 53 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110968724/06746714-cc1d-41ae-8458-b3cf814abacb">
to simplify, I will merge `:CourseContainsPredicate` and `Model` to be a single `Model`
<img width="1324" alt="Screenshot 2023-11-13 at 4 48 23 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110968724/e5c02c8b-e394-4234-a60a-0b9b3a388cd2">
is this correct?

**Comment by tanteckfang** [comment]
Hi Prof @damithc , regarding this question, I am trying to focus on how the tag feature works, am I allow to merge all the Logic components to one Logic participant,
for example, here my original UML diagram
<img width="1458" alt="Screenshot 2023-11-13 at 5 08 38 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110968724/cabaebc9-375a-4927-b472-d83609f30fd3">
and due to Objects in Logic being created before Model, am I allowed to do this way?
<img width="1086" alt="Screenshot 2023-11-13 at 5 08 12 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/110968724/6cb039d9-fc56-4a44-8e87-e9dedc3b1a6f">

**Comment by damithc** [comment]
@tanteckfang 

> and due to Objects in Logic being created before Model, am I allowed to do this way? <img alt="Screenshot 2023-11-13 at 5 08 12 PM" width="1086" src="https://user-images.githubusercontent.com/110968724/282414349-6cb039d9-fc56-4a44-8e87-e9dedc3b1a6f.png">

Yes, you can use a diagram like this to explain _tag-related interactions happening inside the Model component while adding a person_.

**Comment by tanteckfang** [comment]
Okay understand, thank you so much Prof for your clarification.

**Comment by Carlintyj** [comment]
Thank you prof @damithc for the reply. Can I check if including the ParserUtil will be considered showing too in-depth details? Or should it have been omitted similarly to how AB3 omitted it in the delete sequence diagram? Thank you

**Comment by damithc** [comment]
> Can I check if including the ParserUtil will be considered showing too in-depth details? Or should it have been omitted similarly to how AB3 omitted it in the delete sequence diagram? Thank you

@Carlintyj Some parts of the execution path can be omitted if they are not important to the purpose of the diagram. If parts are omitted, it may be good to mention the omissions in a UML note or in the accompanying explanations.

**Comment by Carlintyj** [comment]
Thank you prof! :)
