### ISSUE TITLE
Is duplicate considered a feature flaw or a bug?

### ISSUE THREAD

**Issue by Nid21cs** [nus-cs2103-AY2324S1/forum#443]
When we add tasks to our application, we do check for duplicates. But we realised if a user edits the json file, a duplicate task can be created. Would this be a feature flaw? The user would then be unable to distinguish between both tasks.

**Comment by damithc** [comment]
@Nid21cs As per the following, no need to handle such problems caused by edits to the data file, provided you caution the user about the appropriately in the UG.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/3d1e4fcb-f042-434b-b0a2-a5909ab712b0)

**Comment by Nid21cs** [comment]
Thank you prof.
