### ISSUE TITLE
Clarification if this bug is fixable

### ISSUE THREAD

**Issue by yanghengtang** [nus-cs2103-AY2324S1/forum#444]
Our application has the `Remark` command that is in the format: `remark_p INDEX r\REMARK`

When the following command is entered:
```
remark_p 1 r\Patient undergoing speech therapy r\Patient undergoing other therapy
```
The application successfully added the 2nd remark "Patient undergoing other therapy". However we intended for there to only be one Remark parameter supplied, and thus should throw an error of multiple parameters. Can we fix this bug?

**Comment by damithc** [comment]
@yanghengtang The following applies.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/fd81f26b-8133-4ca1-8b2d-3d867da15eb9)

**Comment by yanghengtang** [comment]
Noted Prof, thank you for the clarification.
