### ISSUE TITLE
Are we allowed to retake canvas survey on reuse declaration

### ISSUE THREAD

**Issue by aslam341** [nus-cs2103-AY2324S1/forum#445]
I took some inspiration from another team's UG, and I think I need to credit them. However, I had already submitted the survey titled: "tP code reuse declaration" and had said that I did not reuse anything. Am I allowed to retake this survey?

Also, how do I credit this reuse since this is in docs and not code.

**Comment by aslam341** [comment]
Also, how do I credit this reuse since this is docs and not code.

**Comment by damithc** [comment]
> I took some inspiration from another team's UG, and I think I need to credit them. However, I had already submitted the survey titled: "tP code reuse declaration" and had said that I did not reuse anything. Am I allowed to retake this survey?

@aslam341 yes, it is still open.



> Also, how do I credit this reuse since this is in docs and not code.

Use a comment. Markdown supports HTML comments syntax `<!-- your comment -->`
