### ISSUE TITLE
Clarification regarding feature freeze rules

### ISSUE THREAD

**Issue by mounilsankar** [nus-cs2103-AY2324S1/forum#446]
My team has clarifications over 2 issues that we aren't sure we are allowed to fix in v1.4

1. Editing a doctor's or patient's nric into an nric that does not exist in the system. 
Currently our app allows this to happen. However the expected behaviour is that there be shown an error message when there is an appointment where patient and doctor does not already exist in the system. Would fixing this issue be a violation of the feature freeze rules?

2. Pop up window does not pop up after minimising the pop up window. 
This is an issue where if the user types in a command view_a/view_d/view_p, a pop up window appears. However, when the window is minimised, and the same command is typed again, the window does not pop up.  Again, would fixing this issue be a violation of the feature freeze rules?

**Comment by damithc** [comment]
> 1. Editing a doctor's or patient's nric into an nric that does not exist in the system.
>    Currently our app allows this to happen. However the expected behaviour is that there be shown an error message when there is an appointment where patient and doctor does not already exist in the system. Would fixing this issue be a violation of the feature freeze rules?

@mounilsankar You can fix this, as this results in inconsistent data being stored.

> 2\. Pop up window does not pop up after minimising the pop up window.
>     This is an issue where if the user types in a command view_a/view_d/view_p, a pop up window appears. However, when the window is minimised, and the same command is typed again, the window does not pop up.  Again, would fixing this issue be a violation of the feature freeze rules?

You can fix this.

**Comment by mounilsankar** [comment]
Thank you prof!
