### ISSUE TITLE
Feature Freeze: Are we allowed to tweak a validity check to produce a 'correct' error message?

### ISSUE THREAD

**Issue by Eola-Z** [nus-cs2103-AY2324S1/forum#448]
Right now my team is planning to add a command validity check to our application.

The issue is: 
Our application already catches the invalid input, but it produces an incorrect error message (the invalid input is captured by another validity check).
Are we allowed to tweak the validity check so that the correct error message is returned to the user?

**Comment by Eola-Z** [comment]
Also clarifying because in either case, the software doesn't really misbehave, so we are not if the feature freeze applies.

**Comment by damithc** [comment]
@Eola-Z Can you give an example input, the current behavior from user POV, and the proposed new behavior?

**Comment by Eola-Z** [comment]
Got it, sorry about that, Prof!

**Current behavior:**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113225702/a099213a-a0dd-45cb-b581-e2f08fc20e33)
Currently, if the user types a filter command with "/taken" and "/with" in the wrong order ("/taken" should be after "/with"), this error message is produced. However, this error message is not very useful since the user has technically typed all the parameters correctly, just in the wrong order.

**Proposed behavior:**
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113225702/d2d92f04-2655-4d1a-a880-6c88261471d4)
This way, the user has a better idea of how they should rewrite the input.

**Comment by damithc** [comment]
@Eola-Z Yes, this can be fixed as the problem indicated by the error message is not the actual problem.

**Comment by Eola-Z** [comment]
Understood Prof, thank you very much!
