### ISSUE TITLE
Using merge without --no -ff

### ISSUE THREAD

**Issue by lsyurea** [nus-cs2103-AY2324S1/forum#45]
I was wondering if it is possible to use the normal merge with fast forwarding if there is no merge conflicts for the adding of increments as parallel branch (the one after level 8) ? 

I understand that level 7 and 8 had explicit mention for it, but not for the level 9, coding standards and javadocs. 
I was testing out the preview pull request feature and merging on github directly, but I realised the merge request from github default global configuration for merge request is with fast forward ):

**Comment by damithc** [comment]
@lsyurea yes, you can use fast-forward merge for cases don't specifically ask for a merge commit. No harm learning both ways.

**Comment by lsyurea** [comment]
Thank you :)
