### ISSUE TITLE
Question regarding sequence diagram illustrating UI component

### ISSUE THREAD

**Issue by mfjkri** [nus-cs2103-AY2324S1/forum#450]
Hi Prof @damithc, this is a sequence diagram for a change theme feature. 

Can I check if the leftmost component should be labelled as `Ui` or `MainWindow`?

Also is it permitted to show the internal `handleThemeChange` call?

Thanks!

![ChangeThemeSequenceDiagram](https://github.com/nus-cs2103-AY2324S1/forum/assets/32407747/96d9cc8c-f5bf-4005-ab54-2c3f4e1a7b76)

**Comment by damithc** [comment]
> Can I check if the leftmost component should be labelled as `Ui` or `MainWindow`?


If the lifeline represents the entire component, it should have the name of the component.


> Also is it permitted to show the internal `handleThemeChange` call?

Yes, if you think it is important enough to be shown.

**Comment by mfjkri** [comment]
# Inclusion of `handleChangeTheme`

In this case MainWindow has the method `handleChangeTheme` which I would like to highlight.

In https://github.com/nus-cs2103-AY2324S1/forum/issues/434#issuecomment-1807541514,

it was mentioned only

>  interaction between, not inside both

should be shown, in this case would `handleChangeTheme` be violating that?


# Naming of the `MainWindow` component

Here since all the interactions occur within the `MainWindow`, would it be alright to have the component named `MainWindow`? 

Or should it be since I am showing at most 1 component for the `Ui` side of things, then the component should be named `Ui`?

**Comment by damithc** [comment]
> # Inclusion of `handleChangeTheme`
> In this case MainWindow has the method `handleChangeTheme` which I would like to highlight.
> 
> In [#434 (comment)](https://github.com/nus-cs2103-AY2324S1/forum/issues/434#issuecomment-1807541514),
> 
> it was mentioned only
> 
> > interaction between, not inside both
> 
> should be shown, in this case would `handleChangeTheme` be violating that?

Good point. It is OK to show this step if it is a higher-level step shown at component level, not a lower-level interaction between two entities inside UI.



> # Naming of the `MainWindow` component
> Here since all the interactions occur within the `MainWindow`, would it be alright to have the component named `MainWindow`?
> 
> Or should it be since I am showing at most 1 component for the `Ui` side of things, then the component should be named `Ui`?

The second one.

**Comment by mfjkri** [comment]
I see thank you Prof!
