### ISSUE TITLE
Catching a previously uncaught exception considered violating feature freeze?

### ISSUE THREAD

**Issue by bkjwjason** [nus-cs2103-AY2324S1/forum#451]
Good evening Prof, wanted to ask if catching a previously uncaught exception to produce an error message is violating a feature freeze?

What is currently happening is that for some of our commands, edge cases are not producing any error messages or results.

For example, doing a `search n/` command where n/ is supposed to be followed by a name input does not return an error message. The application neither produces an error message nor accepts the command, there is no response after pressing the enter key.  This is because we did not catch an exception arising from this input.

Since it's a invalid command but there are no error messages produced, would this be counted as an incorrect behavior and hence allowed to be fixed?

**Comment by damithc** [comment]
@bkjwjason The following applies

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/603af303-44d9-4710-84d0-3e4b0b7df9d0)

**Comment by bkjwjason** [comment]
@damithc Understoof Prof! Much appreciated, thank you!
