### ISSUE TITLE
Questions about bug fixing during feature freeze

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#452]
Hi Prof, can we ask if the following issue is considered a bug and can be fixed during feature freeze:

The parameters `wl` and `tl` for `Add` command should be optional. All optional params are stated in UG, quoted with bracket in the app except the message for this command. Thus, we found the current message for `Add` incorrect and misleading.  

<img width="1060" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/112334419/7d3f2a04-6040-4ba7-9de5-00d091c01101">

Thank you!

**Comment by damithc** [comment]
@A1WAYSD If the message states an optional part as compulsory (or vice versa), it can be corrected.

**Comment by A1WAYSD** [comment]
Okay thanks Prof!
