### ISSUE TITLE
Using comments to indicate long parameters in sequence diagrams

### ISSUE THREAD

**Issue by woojiahao** [nus-cs2103-AY2324S1/forum#453]
Just wanted to check if it's alright to use comments in a sequence diagram to represent long parameters in a sequence diagram. The main reason is because long parameters cause the sequence diagrams to be a lot longer and that reduces the readability on the DG. Thanks!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/7a864aa0-81a2-4754-ab08-3c26b203b984)

**Comment by damithc** [comment]
@woojiahao Yes, that is fine.

**Comment by woojiahao** [comment]
Awesome, thanks prof @damithc
