### ISSUE TITLE
Changing sample data and error message mismatch. 

### ISSUE THREAD

**Issue by timetraveller-123** [nus-cs2103-AY2324S1/forum#454]
Hi prof, 
1) Is changing sample data in SampleDataUtil allowed. We intend to change the tags. 
For example, from "colleagues" to "elderly". 

2) One of our commands, `addp`, accepts `no/` as one of its parameters. However, the error message is displayed incorrectly as it doesn't show `no/` as one of the accepted parameters. However, in our User Guide, it is mentioned that the said parameter is accepted. Are we allowed to change error message to match the User Guide description?
Displayed error message
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111265952/fed2343f-876a-44ac-8317-04a20e7f0312)
Format in User guide

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111265952/1268e15b-a5b8-4651-b6fc-dbe6ea4bb509)

Thank you

**Comment by damithc** [comment]
> 1. Is changing sample data in SampleDataUtil allowed. We intend to change the tags.
>    For example, from "colleagues" to "elderly".

As that file controls the app behavior, it comes under the feature freeze as well. Only bugs can be fixed.

> 2. One of our commands, `addp`, accepts `no/` as one of its parameters. However, the error message is displayed incorrectly as it doesn't show `no/` as one of the accepted parameters. However, in our User Guide, it is mentioned that the said parameter is accepted. Are we allowed to change error message to match the User Guide description?
>    Displayed error message
>    ![image](https://user-images.githubusercontent.com/111265952/282482968-fed2343f-876a-44ac-8317-04a20e7f0312.png)
>    Format in User guide
> 
> ![image](https://user-images.githubusercontent.com/111265952/282483237-1268e15b-a5b8-4651-b6fc-dbe6ea4bb509.png)

Yes, this can be fixed.

**Comment by timetraveller-123** [comment]
Thanks prof. 
Just to clarify.
1) Not even just deleting the sample tags in SampleDataUtil is allowed?
2) But deleting the entire tag feature is allowed?
Thank you

**Comment by damithc** [comment]
> * Not even just deleting the sample tags in SampleDataUtil is allowed?

Yes, unless having that tag is incorrect or causes a bug. Otherwise it is an enhancement.

> * But deleting the entire tag feature is allowed?

Yes. If a feature is not yet ready for release, we have no choice but to remove it. This is not an enhancement but a necessary sacrifice.

**Comment by timetraveller-123** [comment]
ok Thank you prof
