### ISSUE TITLE
Clarification regarding sequence diagram

### ISSUE THREAD

**Issue by mounilsankar** [nus-cs2103-AY2324S1/forum#455]
May I clarify how objects that are parameters are represented in sequence diagrams? In particular, for example if there is a command that has an Index object as a parameter how should it be represented? Moreover, lets say there is a setPatient(Patient, Patient) method, how do we represent the two patient objects in a sequence diagram? Below is the example from AB3's DG where index is represented simply as an integer.

<img width="958" alt="Screenshot 2023-11-13 at 10 55 26 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/98753425/9d737a41-289c-4f74-89b7-5fd717355037">

For our own diagram below,  we are unsure how to represent the patient objects inside the setPatient method call.
<img width="976" alt="Screenshot 2023-11-13 at 11 00 37 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/98753425/24cde7fe-3ee1-4e25-a429-67a20116612c">

**Comment by damithc** [comment]
@mounilsankar In the diagram you see an object `d` being passed as a return value. If you want to pass it as a parameter, you can just use `foo(d)`. In this case the `d` was newly created, but instead it could have existed from the start too (i.e., the lifeline could have started from the top rather than in the middle).
So, to pass an object as a parameter, you just show it normally but give it a name, after which you can use the name to pass it as a parameter.

**Comment by mounilsankar** [comment]
@damithc In our case the setPatient(Patient, Patient) method, takes in parameters the patient to be edited and the edited patient. In our diagram above we have omitted the method call that returns the patient to be edited. In this case how do we represent the patient to be edited parameter? 

Also regarding the orginal AB3 diagram, where the index object containing 1, is written simply as the number 1. Is this the proper notation to represent the Index object?

**Comment by damithc** [comment]
@mounilsankar I think you are overthinking this :-) Just have two objects `p1:Patient`  and `p2:Patient` in the sequence diagram as per normal (lifelines starting at the top), and use `p1` and `p2` wherever you want to pass them as parameters or return values.

**Comment by mounilsankar** [comment]
@damithc Thank you for your reply! How about regarding the Index object in the AB3 diagram?

**Comment by damithc** [comment]
> Also regarding the orginal AB3 diagram, where the index object containing 1, is written simply as the number 1. Is this the proper notation to represent the Index object?

It's a simplification.  The diagram shows only `1` because it is the number `1` that is really being passed around, although in the code it is elevated to an object (in order to package some related behaviors with it).
