### ISSUE TITLE
Must all NFRs listed in DG be met?

### ISSUE THREAD

**Issue by nathanielcalimag** [nus-cs2103-AY2324S1/forum#456]
Hi Prof, this is related to #409 

Must all NFRs be met?

We have an NFR for non-laggy usage with X number of model1, and X number of model2 in our application but as we have had not had allocated time for optimisation in v1, we have not been able to meet this NFR.

Should we reduce the NFR to our current implemention?

**Comment by damithc** [comment]
@nathanielcalimag Not necessary to meet all NFRs in this version, @nathanielcalimag
