### ISSUE TITLE
Do I have to declare a reuse if I use a Github action template?

### ISSUE THREAD

**Issue by seewhyjay** [nus-cs2103-AY2324S1/forum#457]
I used [actions/upload-artifacts@v3](https://github.com/AY2324S1-CS2103T-T12-3/tp/blob/master/.github/workflows/gradle.yml#L60) in my team's workflow, do I need to declare this as reusing code?

**Comment by damithc** [comment]
@seewhyjay Not required

**Comment by seewhyjay** [comment]
thank you!
