### ISSUE TITLE
Clarification of feature freeze rules: Unsure if message edited is considered a bug

### ISSUE THREAD

**Issue by jamz903** [nus-cs2103-AY2324S1/forum#458]
Hi prof, just wanted to clarify if this would violate feature freeze! In each of my team's commands, when the command `help <command word>` is called, we also provide an example usage. I just discovered that our `Find` command (and only this one), it lists all command abbreviations instead of only the main command word

in `Find`:
```@java
Example: find, search, f n/Buying groceries ...
```

after the fix, it would become:
```@java
Example: find n/Buying groceries ...
```

other commands currently (e.g. add):
```@java
Example: add n/Buying groceries ...
```

Just wanted to double check that this would constitute a bug fix and not a violation of feature freeze! The reason why I think this constitutes a bug is because our team has intended the example command to allow users to directly copy & paste and for it to work without issues, however without this fix it will be flagged out as incorrect formatting if users copy it exactly (which it is, since it has multiple command keywords), making the example inaccurate.

**Comment by oeggy03** [comment]
I'm not prof Damith, but you can probably include a part in your User Guide under the find section that tells the user how to navigate and use this example, and specify that the user is only supposed to use it with one of the keywords (find, f or search). If the user guide is clear enough, then I think it's quite intuitive what this means

**Comment by damithc** [comment]
@jamz903 As the given example is incorrect, you may fix it.
