### ISSUE TITLE
Submit more than once Jar file in Canvas

### ISSUE THREAD

**Issue by brendanneojw** [nus-cs2103-AY2324S1/forum#459]
When i first submit the jar file, the jar file name follows the convention. However as we made some changes to the jar file, I reuploaded it into Canvas and it seems that they append a prefix such as `[CS2103T-XXX-X][PRODUCT_NAME]-1.jar` for the first resubmission and `[CS2103T-XXX-X][PRODUCT_NAME]-2.jar` for the second resubmission. Wondering if this is okay since it is stated in the email that deviations to the file name may cause the teaching team's processing script to miss the files

**Comment by AaronJT1** [comment]
Hi @brendanneojw , as mentioned on course website, it should be ok.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/134244836/5177c5e5-e29a-4aa8-ae77-e0591cbfedd7)

**Comment by brendanneojw** [comment]
Hi Aaron, Thanks for the help!
