### ISSUE TITLE
Level 8. Date & Time 

### ISSUE THREAD

**Issue by sheryew** [nus-cs2103-AY2324S1/forum#46]
For Level 8, are we supposed to assume that only deadline Task will have date / time inputs? I.E. Event Task can still accept strings for their /from /to.

**Comment by lsyurea** [comment]
I think this is the case and I also didnt change the Event Task :)

**Comment by sheryew** [comment]
Okay thanks! Can I also check whether you handled like erroneous test cases for deadline Task? Like for example, deadline return book /by tmw Are we supposed to give error by asking the user to input date? Thanks

**Comment by lsyurea** [comment]
I did not handle it, but i think its better to just do try catch when you do localDate.parse. Thanks for the heads up :)

**Comment by joeng03** [comment]
I did change the Event task though. The code is not that different from the Deadline code, but we could throw an additional exception for invalid date ranges. The Deadline constructor could throw a DukeException, which can be caught by the catch block in the Duke class

**Comment by damithc** [comment]
> For Level 8, are we supposed to assume that only deadline Task will have date / time inputs? I.E. Event Task can still accept strings for their /from /to.

@sheryew Using it in one place is enough to meet the minimal requirement. Doing more will give you more practice and will give you a better product in the iP, but it will not earn you more iP marks, and will take more of your time too. So, it's up to you how much more you want to do (e.g., depends on how much time you can spend on this course, based on your other courses).

> Can I also check whether you handled like erroneous test cases for deadline Task? Like for example, deadline return book /by tmw Are we supposed to give error by asking the user to input date? Thanks

Same for this one.

**Comment by KamJiaYue** [comment]
I basically only take in the date + hour + min input, as Assignment deadlines are all of that format, imma use my chat bot in the future for recording my task list i guess.
