### ISSUE TITLE
Final submission naming typo

### ISSUE THREAD

**Issue by Tim-Siu** [nus-cs2103-AY2324S1/forum#460]
Our group accidentally named the jar file `[GROUP_NUMBER][PRODUCT_NAME].jar.jar` with a duplicate `.jar` extention. Will this be penalized? Do we need to resubmit the jar file?

**Comment by damithc** [comment]
@Tim-Siu no need. This specific mistake is common and is auto-corrected (without penalty) by our submission processing script.

**Comment by Tim-Siu** [comment]
Thanks for your prompt reply!
