### ISSUE TITLE
Is team member count factored into project grading?

### ISSUE THREAD

**Issue by Cloud7050** [nus-cs2103-AY2324S1/forum#461]
[Part 2B of the TP grading page](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-grading.html#2-project-grading-implementation-15-marks) mentions that effort for the entire project gets evaluated by both testers (peers) and tutors.

On average, the percentage of total effort in comparison to AB3 that a team with less members would be able to put in would be lower than that of a team with more members, if all members are aiming to put in an IP's worth of effort. Therefore, a team with less members may get a lower effort score from testers and/or tutors, especially if the tester has a different frame of reference from being in a team with more members.

Will such a lower effort score get "re-weighted" to account for teams with less members? For reference, I am in a tutorial with only 4 people total, so we automatically formed a team of 4.

**Comment by damithc** [comment]
@Cloud7050 For relevant components, we do an adjustment based on team size. But it is not linear adjustment as there are other factors involved e.g., more members means more communication overhead, more merge conflicts, harder to find common ground, etc.

**Comment by Cloud7050** [comment]
I see, thank you.
