### ISSUE TITLE
Unable to see seat numbers for the PE

### ISSUE THREAD

**Issue by LordSaumya** [nus-cs2103-AY2324S1/forum#462]
The PE instructions say I can find the seat number in the given link (shown below)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/68504323/d22282d2-d454-464e-b7c2-70616ebbb3be)

However, if I follow that [link](https://docs.google.com/spreadsheets/d/e/2PACX-1vSUbcJpMC5OdJkr_K6VxDwAkkrwJsqAFSPwHmZq88EbOdAWIPMeYvDQDYOUEcsEYVwACmAz5hH0W0ZY/pubhtml?gid=0&single=true), I can only see a blank sheet (shown below)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/68504323/be51e5d9-f948-4586-9dd1-7f55403b4c6a)

How do I check my seat number?

**Comment by damithc** [comment]
@LordSaumya They are not available yet. Should be available by end of today.
