### ISSUE TITLE
Textbook on Course Website during PE

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#463]
Sorry for the silly question, but would we be allowed to access the textbook on the course website during the PE, our would we be required to convert the textbook to PDF format?

**Comment by damithc** [comment]
@WZWren yes, the course website is in the [allowed list](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-pe.html#:~:text=During%20the%20bug%20reporting%20periods)

BTW, the PDF version of the textbook is already in the Canvas/files/handouts. You don't need it for the PE but you'll need it for the final exam.
