### ISSUE TITLE
Question on Notes 

### ISSUE THREAD

**Issue by Gabriel4357** [nus-cs2103-AY2324S1/forum#465]
Hi just want to be very sure but we will be allowed to use digital notes so this would allow me to use my Notes app on Mac to see Notes that I have made correct? Thank you!

**Comment by damithc** [comment]
> Hi just want to be very sure but we will be allowed to use digital notes so this would allow me to use my Notes app on Mac to see Notes that I have made correct? Thank you!

@Gabriel4357 Yes, but it goes without saying that you should not be communicating with others using any such software.

**Comment by Gabriel4357** [comment]
Alright thank you!
