### ISSUE TITLE
Remote Zoom two devices 

### ISSUE THREAD

**Issue by Gabriel4357** [nus-cs2103-AY2324S1/forum#466]
Can we just mute both mics during the PE exam or must one mic be on at all times?

**Comment by damithc** [comment]
> Can we just mute both mics during the PE exam or must one mic be on at all times?

@Gabriel4357 Your mic must be kept mute. However, the invigilator will be able to unmute the mic if there is a need to do so.

**Comment by Gabriel4357** [comment]
Ohh yes ok thank you!
