### ISSUE TITLE
Classification of functionality or documentation bug. 

### ISSUE THREAD

**Issue by tayruxin** [nus-cs2103-AY2324S1/forum#467]
Hi prof, if the user guide provided a command that is incorrect, will that be considered a functionality or documentation bug?

**Comment by damithc** [comment]
@tayruxin If the feature behavior needs to be changed, it is either a type.FunctionalityBug or type.FeatureFlaw. But if it the UG that needs to be updated, it is a type.DocumentationBug. 
Usually, it is possible to see from the context if the error is in the document or the code. If it is a 50:50 case, it is up to the team to decide.

**Comment by tayruxin** [comment]
Thank you prof
