### ISSUE TITLE
PE Phase 1 Time Allocation

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2103-AY2324S1/forum#468]
The course website speficies the time durations for Product Testing, Evaluating Documents and Overall Evaluation respectively. Is the timing displayed just a suggustion or does it mean that we can only use the first 60 minutes to report bugs for the product and following 30 minutes to evaluate documents and etc?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/97677245/22463fd2-2aac-4497-b4a6-c36803ad67a8)

**Comment by damithc** [comment]
@mamayuan It is not just a suggestion. The invigilator will inform you when the PE moves from one segment to the other. In particular only documentation bugs will be accepted during part II. Any other bug reported during that time will be discarded later when we process the bug reports.

**Comment by mamayuan** [comment]
Noted. Thanks, prof!
