### ISSUE TITLE
Clarifications on a type of bug as Feature Flaw

### ISSUE THREAD

**Issue by RiyaMehta2211** [nus-cs2103-AY2324S1/forum#470]
Hi prof,

I understand that a feature flaw is reported if a feature exhibits incomplete behaviour.

But for instance, if it happens so that the UI does not display the data unless the user clicks on it. Would that be counted as a feature flaw (since the behaviour is deemed incomplete)?

Extension: If such a bug is declared in the Known Issues of a User Guide as well as the Planned Enhancements section of the DG, would that bug not be counted? Thank you.

**Comment by damithc** [comment]
> I understand that a feature flaw is reported if a feature exhibits incomplete behaviour.
> 
> But for instance, if it happens so that the UI does not display the data unless the user clicks on it. Would that be counted as a feature flaw (since the behaviour is deemed incomplete)?

@RiyaMehta2211 You can report a type.FeatureFlaw bug if you think the feature if you think the feature should have been designed better. But if the alternative you suggest would require a lot more effort than the current implementation, the team can argue that it is NotInScope for the current iteration. In this case the team will not be penalized, and the credit you earn will be quite small (but you still earn some credit). If the alternative you suggest is indeed better and could have been done with a similar effort, it cannot be categorized as NotInScope, and the bug will count for the receiving team (and you will earn more credit for reporting it).


> Extension: If such a bug is declared in the Known Issues of a User Guide as well as the Planned Enhancements section of the DG, would that bug not be counted? Thank you.

Planned enhancements are not counted as bugs.
Known issues are still counted as bugs, although mentioning it in the UG could lower its impact on users, and hence, justify a lower severity for it.

**Comment by RiyaMehta2211** [comment]
I see, thank you Prof. As a follow up, if the bug is most likely deemed not in scope due to a difficulty in its implementation, then could it be categorised as a documentation bug (either in UG/DG) instead? Since the users should be made aware of the current limitations?

Also, may I clarify, suppose the DG has planned enhancements on some extension. However, the UG does not contain that same information on current limitations, it can be categorised as a documentation bug of Medium intensity? Especially since the limitations can cause some unintended data loss?

**Comment by damithc** [comment]
> I see, thank you Prof. As a follow up, if the bug is most likely deemed not in scope due to a difficulty in its implementation, then could it be categorised as a documentation bug (either in UG/DG) instead? Since the users should be made aware of the current limitations?

It is unlikely the team will allow you to 'sneak in' feature flaws as documentation bugs this way :-) As they should be reported as feature flaws in the first place, there is no need to report them again as doc bugs. Not having it described in the UG can be used to increase the severity of the feature flaw (conversely, having it mentioned in the UG can be used to lower the severity).


> Also, may I clarify, suppose the DG has planned enhancements on some extension. However, the UG does not contain that same information on current limitations, it can be categorised as a documentation bug of Medium intensity? Especially since the limitations can cause some unintended data loss?

Same as above.

**Comment by RiyaMehta2211** [comment]
Yup thank you Prof
