### ISSUE TITLE
Would screen recording websites be allowed for providing visuals in bug reports?

### ISSUE THREAD

**Issue by nathanielcalimag** [nus-cs2103-AY2324S1/forum#471]
Hi Prof,

In the course website, it was stated that

> Software: CATcher, any text editor, any screen grab/recording software

could be used. However, it was not stated whether screen grab / recording software was meant for monitoring purposes should there be a need, or whether we can use such software to screen record the TP application. I wanted to explicitly ask if using screen recording websites like gifcap.dev for purposes of screen recording bugs in the TP would be allowed.

Thank you

**Comment by damithc** [comment]
@nathanielcalimag Screen recording (for monitoring purposes) is not required.  The software can be used if you want to record the app behavior, to submit together with a bug report.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/6200b19d-c862-4e24-8128-45194326eb47)
