### ISSUE TITLE
Unable to change Zoom display name

### ISSUE THREAD

**Issue by nknguyenhc** [nus-cs2103-AY2324S1/forum#472]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/87511888/fd776949-a0cf-4a0d-972d-b90aa86f085d)

It looks like I cannot change my display name under my zoom profile on web browser.

Any help on how to change Zoom display name would be appreciated! Thanks.

**Comment by yanghengtang** [comment]
@nknguyenhc you can rename your display name when you're in the Zoom call.

Go to the '**Participation**' panel and search for yourself. The click on '**More**' then '**Rename**'.

<img width="370" alt="Screenshot 2023-11-17 at 10 40 36 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/24840938/b843cd94-31db-478f-8e82-7934ca440848">

**Comment by nknguyenhc** [comment]
Ok that works, thanks!
