### ISSUE TITLE
PE Phase II

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#473]
Hi Prof @damithc, I would like to clarify whether for PE Phase II, will commenting on feature flaws of the app's implementation based solely on the UG be allowed? Or is it best to do so in Phase I? 

For example, if I realised that a field has a feature flaw based on the app's description in the UG, but did not manage to test it out in the app during Phase I, will I be given credit? 

Thank you!

**Comment by damithc** [comment]
@GlendaChong Phase II is to report bugs in the documents themselves. So, FeatureFlaws not allowed.

**Comment by GlendaChong** [comment]
Understood, thank you!
