### ISSUE TITLE
Where to get the code to check against DG diagrams

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#474]
Hi, I am wondering during phase II, if we want to check the code against the diagram drawn in DG, do we use the latest version of the code (i.e. directly clone the repo) or do we use the source code zip file in the newest release?

**Comment by damithc** [comment]
@yucongkoo Either should be fine, as the product code or the DG shouldn't have changed after the submission. But UG may have changed after the submission.

**Comment by yucongkoo** [comment]
@damithc okay thanks prof!

**Comment by sp4ce-cowboy** [comment]
@damithc @yucongkoo Hi just to clarify, does phase II here refer to the "Phase 2: Developer Response" or "Phase 1 part II: Evaluating Documents"? If it is the latter, then does that mean we are allowed to access the codebase of the team that we are testing i.e. clone and open locally?

**Comment by damithc** [comment]
@sp4ce-cowboy My answer applies to `Phase 1 Part II` (not Phase 2)

> If it is the latter, then does that mean we are allowed to access the codebase of the team that we are testing i.e. clone and open locally?

Yes.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/e8a9b58d-0daf-4a01-ae73-88c6c2a4ca8c)

**Comment by sp4ce-cowboy** [comment]
@damithc Thank you prof!
