### ISSUE TITLE
What to do if a team has more planned enhancements than allowed

### ISSUE THREAD

**Issue by aslam341** [nus-cs2103-AY2324S1/forum#475]
Hi prof @damithc,

If a team's planned enhancement section contains more than 10 specific feature flaws by doing it in a general manner like this:

`1.  general  description 1`
    - specific flaw 1
    - specific flaw 2
    - specific flaw 3

`2. general description 2`
    - specific flaw 1
    - specific flaw 2

...           

`10. general description 10`
    - specific flaw 1
    - specific flaw 2  

Does this mean we cannot report any of the specific feature flaws even though they exceeded the limit, since by right a team of 5 should only mention at most 10 specific planned enhancements addressing 10 specific feature flaws?

**Comment by damithc** [comment]
Good question @aslam341 
If the team has exceeded the allowed count in the _planned enhancements_, only the first N  items (where N is team size  x 2) in that list will have immunity. The rest can be reported as bugs. In addition, exceeding the count can be reported as a separate DG bug.
You can find the team size by going to the team list page in the course website https://nus-cs2103-ay2324s1.github.io/website/admin/teamList.html
