### ISSUE TITLE
Question regarding bug type when a feature can be used but not documented

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#476]
I came across this scenario when considering possible bugs in PE, that there is a feature that can be used but not documented and I am thinking what kind of bug is this. Consider the following cases:

**Case 1:** 
The team actually wanted the feature, but forgot to document about it. I would deem this to be a documentation bug.

**Case 2:**
The team did not want the feature to be included in their application, but they could possibly forgot to remove it and was inherited from AB3. Then this would be a functionality bug right? As the application is not functioning as it is supposed to be.

Then for both cases, would the severity of the bug be determined by what kind of consequences could arise from using that feature? For instance, clearing the whole data (the clear command from the AB3) could be quite a severe case as it is a destructive and non-recoverable operation, so maybe severity.Medium/severity.High?

On top of that, as it is fully up to the developer team to decide on whether they wanted to include such features, are there any guidelines on how we should determine which case it is? If it were to be case1, we might need to consider whether the feature has any flaws or not, but for case2, since the feature was not supposed to be there at the first place, any flaws in the feature should not be reported too.

**Comment by damithc** [comment]
> **Case 1:**
> The team actually wanted the feature, but forgot to document about it. I would deem this to be a documentation bug.

Yes, if the feature is visible and usable from the app.


> **Case 2:**
> The team did not want the feature to be included in their application, but they could possibly forgot to remove it and was inherited from AB3. Then this would be a functionality bug right? As the application is not functioning as it is supposed to be.

Yes, can't disown a feature if it is in the UG as well as in the app.


> Then for both cases, would the severity of the bug be determined by what kind of consequences could arise from using that feature? 

Yes, depends on the potential impact caused by the error.


> On top of that, as it is fully up to the developer team to decide on whether they wanted to include such features, are there any guidelines on how we should determine which case it is? If it were to be case1, we might need to consider whether the feature has any flaws or not, but for case2, since the feature was not supposed to be there at the first place, any flaws in the feature should not be reported too.

Should be based on costs (e.g., effort to adapt/maintain) and benefits (e.g., is it a good fit for with the rest of the features, is it useful to target users, etc.)

**Comment by yucongkoo** [comment]
@damithc Thanks for your prompt response, can I further clarify what the following sentence meant as response to case 2,

> Yes, can't disown a feature if it is in the UG as well as in the app.

As I was considering the case where the feature is not documented in the UG, but useable in the app, however the dev team might not intended that this feature to exist in the app. So since it is not documented in the UG/DG, the dev team are allowed to disown the feature right? But since it is still usable, hence considered a functionality bug.

**Comment by damithc** [comment]
> As I was considering the case where the feature is not documented in the UG, but useable in the app, however the dev team might not intended that this feature to exist in the app. So since it is not documented in the UG/DG, the dev team are allowed to disown the feature right? But since it is still usable, hence considered a functionality bug.

We need to treat it as any other feature. Whether the team intended to have it or not can't be a factor, as the team is responsible for the entire product they have released.

**Comment by yucongkoo** [comment]
Ouh I see, understood. Thank you prof!
