### ISSUE TITLE
Clarifications on bug severity for UG links

### ISSUE THREAD

**Issue by RiyaMehta2211** [nus-cs2103-AY2324S1/forum#477]
Hi Prof,

I understand low bugs are meant to be a minor inconvenience, so hyperlinks in UG (if broken) to the table of contents (for e.g.) would be of low severity?

In addition, if crucial links (e.g. to the jar file / java 11 Oracle page) are broken, which severity would be the most appropriate in this case? 

Thank you Prof.

**Comment by damithc** [comment]
@RiyaMehta2211 I'd rather not specify severity for specific cases (if I do, there'll be too many cases to do so). You can make a best judgement and if the team doesn't agree with it and you don't agree with their reasoning, the teaching team will make the final decision.

**Comment by RiyaMehta2211** [comment]
Thank you Prof
