### ISSUE TITLE
How to estimate effort for a team that has less than the typical 5 members

### ISSUE THREAD

**Issue by aslam341** [nus-cs2103-AY2324S1/forum#479]
Context: TEAMMATES overall evaluation

I was going to give a team I evaluated 7 for effort, even though typically teams should get 8-12. But before I submitted it, I wanted to check if they had 5 members, because the total implementation effort this team put felt quite less compared to the implementation effort required to create AB3 from scratch. Turns out, they had 4 members only.

Should I stick to my original score of 7, or re-evaluate knowing that there are 4 members in the team?

**Comment by damithc** [comment]
@aslam341 You should not consider the team size at all. You are simply estimating the effort compared to AB3. The team size doesn't play a role in that estimation.
