### ISSUE TITLE
Unexpected output when running runtest.sh

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#48]
After I modified my code for A-MoreOOP, the output of runtest.sh showed extra error messages: the loadingError and savingError.
This only happens for automated testing. The error messages never appear when I manually run the program, and other interactions all behave normally in the test.
Would appreciate some help on this. Is there anything I need to change, e.g. the test script, to ensure the test can read the txt file without error?

Here's my main function:
```java
    public Duke(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.load());
        } catch (FileNotFoundException e) {
            ui.showLoadingError();
            tasks = new TaskList();
        }
    }

    public void run() {
        ui.run(new Parser(tasks));
        try {
            storage.save(tasks);
        } catch (IOException e) {
            ui.showSavingError();
        }
    }

    public static void main(String[] args) {
        new Duke("data/duke.txt").run();
    }
```

**Comment by damithc** [comment]
@A1WAYSD perhaps push the full code to your fork and share the link here, so that others can try to reproduce the problem?

Also, for future reference, if you evolve the code in small steps while running tests after each step (and committing after each step), it is easy to figure out which specific code change introduced the problem.

**Comment by KamJiaYue** [comment]
what is the error message?

**Comment by A1WAYSD** [comment]
@damithc Thanks for the advice! Here's the link:
https://github.com/A1WAYSD/ip/tree/A-MoreOOP
The error occurred when I rewrote my code to the template main function mentioned above.

**Comment by A1WAYSD** [comment]
@KamJiaYue Sorry I may not deliver the issue clearly. During the test, FileNotFoundException and IOException were caught and ui showed the errors. But these 2 exceptions didn't appear when I manually ran the program.

**Comment by lamchenghou** [comment]
Hey, I think you should modify your ~`.sh` script~ code to also create `data/duke.txt` if it doesn't exist.

Edit: It should be done in the java code instead, you might also want to reset the file to blank state before each run of the test.

**Comment by A1WAYSD** [comment]
@lamchenghou Thanks!!! I changed my load/save method and it works now. The issue lies in my Writer.write() method, the input string cannot be null or else an exception will be thrown.
