### ISSUE TITLE
Severity handling of bugs

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#480]
Regarding the accuracy points,

In which scenarios do I get the points

1. Developer team successfully accepts the severity level at the first stage itself.
2. Developer team down-triages severity. The tester accepts the eventual down-triaged level. 
3. Developer team rejects, tester rejects the rejection, teaching team accepts

Accuracy also depends on the number of successfully accepted bugs correct?

Thanks!

**Comment by damithc** [comment]
@AlagappanRa Here are some examples:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/1765a9aa-5d5d-4c67-ab6b-96a33f08e44d)

**Comment by AlagappanRa** [comment]
@damithc  
How about those classfied by the dev team as rejects? Do they reduce accuracy or mantain accuracy?

**Comment by damithc** [comment]
> How about those classfied by the dev team as rejects? Do they reduce accuracy or mantain accuracy?

Similar to last 3 rows in the table. So, depends on tester's reaction and teaching team decision.
