### ISSUE TITLE
How do we handle the bug type and severity for bugs that we want to reject?

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#481]
As mentioned in the title, if we were to reject a bug, it implies that there should not be any bug type and severity, however, we are not provided with the option to set the bug type and severity to none. 

May I know how we should handle such cases? Do we just ignore the bug type and severity?

**Comment by damithc** [comment]
@yucongkoo 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/7ea71f64-dde1-4bd7-907b-aa7e4c031d5f)

If you are sure the bug will stay rejected through the next two phases, you can ignore type/severity as they don't matter if the bug is eventually rejected.

**Comment by yucongkoo** [comment]
@damithc okay.
