### ISSUE TITLE
Can inherited feature flaws be flagged for duplicate?

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#484]
We allowed case sensitive adding of contacts. In another operation that add this contact into group/meeting/events, the tester flagged that the user should not be required to remember the exact case of the contact name. Can these 2 bugs be flagged as duplicate?

**Comment by damithc** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/912f589e-3352-468e-a592-ae56c0004852)

@s-peiran does fixing one automatically fixes the other?

**Comment by s-peiran** [comment]
The issue for adding contacts #4037
The issue for adding contacts to meeting #5311
The issue for removing contact from meeting #5138

Fundamentally all these issues are saying that the contact name should be case in-sensitive.
We did not plan to make it case insensitive from the start and it is mentioned in the UG. 

If we were to convert the entire app into case in-sensitive, it will requires a 1 line change to how we check whether two contacts are the same in AddContactToMeeting class and DeleteContactFromMeeting class

**Comment by damithc** [comment]
@s-peiran case sensitivity of a field of an entity type can be implemented in one place, and if so, it can be changed one usage without automatically changing it for other usages as well. If this is the case, it qualifies as duplicates.

**Comment by s-peiran** [comment]
Thank you for your clarification prof
