### ISSUE TITLE
How will unassigned bug reports affect accuracy?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY2324S1/forum#485]
Our team has decided to not assign a couple of bug reports because we feel that all of us, or rather none or us, would be responsible for the bug but we still are arguing for a different severity.

How would this affect developer accuracy if the bug was not resolved in our favor? 

Would the accuracy penalty be evenly split according to the number of team members?

**Comment by damithc** [comment]
> Would the accuracy penalty be evenly split according to the number of team members?

@chiayunrong Yes, the impact will be divided among all team members.
