### ISSUE TITLE
Regarding content in Glossary for both UG and DG

### ISSUE THREAD

**Issue by inezkok** [nus-cs2103-AY2324S1/forum#486]
According to the course website, the definition of a glossary is the one shown below:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/4918784b-d635-46fa-ad4f-9fcb82b46ba2)

From the examples given, the terms are related to the project itself rather than general terminology. So is there a need to explain general terms that aren't specific to the project like for example what a command terminal is in the glossary (for the UG) or explicitly explaining what Object Oriented Programming is in the glossary (for the DG)?

**Comment by damithc** [comment]
@inezkok Only if a term is relevant to the project, and only if defining it in the Glossary adds value.
