### ISSUE TITLE
Reporting 4 low severity or 1 medium severity

### ISSUE THREAD

**Issue by bhnuka** [nus-cs2103-AY2324S1/forum#487]
For our product, we have 4 issues that are independently fixable yet have similar problems. Would the penalty be reduced if we were to combine them as one medium bug, rather than 4 separate low bugs (assuming that the current severity of low for each individual bugs is acceptable)? I understand that on the CS2103T website, it states that "If an independently-fixable yet similar problem appears in more than five distinct places, get our permission to combine them as one bug (in which case we'll require you to increase the severity to match the frequency of the bug).". As this is a borderline case, I was wondering if there was any input regarding which would be preferred. Thank you.

**Comment by damithc** [comment]
@bhnuka although we state 5 as the bar to be considered for this exception, we only allow it when there is an excessive number of of similar things being reported (e.g, the same word misspelled in many places, and can be fixed easily with a find-and-replace). So, this case is unlikely to qualify.

**Comment by bhnuka** [comment]
Ah I see. In this case, its 4 URL links that have not been updated from the addressbook repo to my teams repo (but reported as separate issues). Would that still be classified as inappropriate to condense into one issue?

**Comment by damithc** [comment]
@bhnuka 4 is too low. So, they'll have to remain as separate bugs.
