### ISSUE TITLE
Clarificaiton regarding some bugs recceived

### ISSUE THREAD

**Issue by mounilsankar** [nus-cs2103-AY2324S1/forum#488]
Hi prof, my team has some clarifications regarding some of the bugs we received. 

1.  Glossary lacking the term JSON [#2295](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/2295)
So for this issue we were wondering if this is considered a bug since JSON is a commonly used abbreviation that most developers would be aware of.

2. Allows appointment time with 0 minutes [#4772](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/4772)
For this issue, we allowed for users to have appointment start time and end time be the same so as to allow for appointments where a user may not know when the end time is or simply for very brief appointments. The only constraint our UG mentions is that the end time cannot be before the start time and even that the start and end time can be the same(as shown in the screenshot from our UG below). Hence we feel that this should not be a bug. 
<img width="917" alt="Screenshot 2023-11-19 at 12 05 12 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/98753425/105af5ee-3e48-4586-b548-e56d6f6ef926">

3. Lack of Parser for List commands [#4462](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/4462)
We feel that this is not an issue as we felt that the ListCommand relation with the MediConnectParser would be too trivial to show hence we only showed the more complicated commands which required the additional XYZCommandParser class.

4. Some remnants from address a book[#4142](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/4142)
Our package name is still addressbook, therefore we left the name of the log file unchanged as well.  Hence we feel that this is not a bug as well.

5. Able to add appointments whose date span across multiple days [#2676](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/2676)
We feel that this is not a bug. This is because our UG only states the constraint of the end time being after the start time as show n in the screenshot  under point 2.  Moreover where do we draw the line between an appointment being too long?

6. No warning of using PlantUML [#4460](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/4460)
We did provide a warning for the first instance of a sequence diagram in the dg but we failed to provide the reminder again for the subsequent diagrams. This was because we did not want to repeat the same information over and over. The below screenshot shows the warning message.
<img width="960" alt="Screenshot 2023-11-19 at 12 16 46 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/98753425/22941ada-4e69-49b3-a2f2-fd298ae7ccbc">

Also if this were to be a bug we would like to argue that it be a veryLow severity bug as it can be deemed a cosmetic bug as it does not change how the feature would be implemented by a developer as java makes use of a garbage collector and the developer does not have to dereference the object manually.

**Comment by damithc** [comment]
@mounilsankar In all cases you have listed, you have already provided your justification. Now we wait to see if the tester accepts it, which happens in the next phase. So, I don't normally give a decision on specific bugs at this phase. I can give some general comments only, or clarify PE policies/guidelines.

My general comment here: In addition to the "not a bug" option, there is also another option "yes it is an improvement we can do in a future version but we had to give a higher priority to other things we did in this version" (aka `response.NotInScope`). Both have no penalty for the team but the latter earns some small amount of credit for the tester.
