### ISSUE TITLE
Clarifications on reports of bugs and flaws inherent to AB3

### ISSUE THREAD

**Issue by CJ-Lee01** [nus-cs2103-AY2324S1/forum#489]
[One of the reports](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/4266) we received is related to a flaw in AB3 that we were not aware of until much later. This flaw was also not mentioned in the documentation for the AB3

The flaw is that the user cannot use the help command to open the help window if the help window was previously opened and minimised without closing.

Since this is a bug inherent to AB3 and it is separate from the features that we have implemented, would this count as `response.NotInScope`?

**Comment by damithc** [comment]
> Since this is a bug inherent to AB3 and it is separate from the features that we have implemented, would this count as `response.NotInScope`?

@CJ-Lee01 Bugs inherited from AB3 are not immune from the PE. However, any bug (inherited or not) can be argued as `NotInScope` if the effort required for fixing it is better spent on higher priority things that was done in the current version. More info [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-pe.html#:~:text=How%20to%20prove%20that%20something%20is%20response.NotInScope).

**Comment by CJ-Lee01** [comment]
Thank you for the clarification. I will close the issue.
