### ISSUE TITLE
Consequence of more than 10 enhancements 

### ISSUE THREAD

**Issue by sk2001git** [nus-cs2103-AY2324S1/forum#492]
Issue #3642 in catcher
original: nus-cs2103-AY2324S1/pe-interim#5049

Claims: Since one of our planned enhancement could be considered as 2 enhancements, the claim is that we have violated the maximum of 10 enhancements and thus our last enhancement is considered nullified and is a valid bug that he can pick out.

The question is if this is an appropriate bug because all the tester did in this case is literally copy the problem we mentioned with our last enhancement and say this is now a bug.

Or rather is there an appropriate ground for a rejection since the bug actually lies in the fact that 1 enhancement could be broken down into 2 and thus on this ground, we are able to reject it since its a invalid bug

**Comment by damithc** [comment]
@sk2001git the following was announced earlier.

>Some additional info that are not in the course website:
>
>If a If the team has exceeded the allowed count in the planned enhancements section, only the first N items (where N is team_size x 2) in that list will have immunity from being reported as feature flaws. The rest can be reported. In addition, exceeding the count can be reported as a separate DG bug. You can find the team size by going to the [team list page in the course website](https://nus-cs2103-ay2324s1.github.io/website/admin/teamList.html)

So, it is not possible to reject but you can avoid a penalty if you can justify the defect being reported is `NotInScope`. More info [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-pe.html#:~:text=How%20to%20prove%20that%20something%20is%20response.NotInScope).
