### ISSUE TITLE
Some questions regarding documentation bugs

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#494]
I have the following two questions regarding documentation bugs:

1. We have a bug report related to naming of our target users, so basically the majority of the documentation, we used `Customers` to name our target users, but in our class diagram (which was inherited from the AB3, the classes are called `Person` and some other related namings such as `PersonListPanel`, `PersonCard` etc). So we received a bug stating that our naming in diagrams should also be kept consistent with other sections of the documentation so that the reader can understand it more easily. Our interpretation is that, our class diagram is actually not wrong, as it shows the correct class names, but we also agreed that if we were to change the namings in our implementation it would make the reader understand the context easier. So we were planning to classify this as not in scope (as we think that rectifying the naming is not as important as other features we implemented), but we are not very sure whether is this actually a documentation bug or not, since our documentation is technically correct, and if it is, are we allowed to classify documentation bugs as not in scope?

2. How detailed does the manual testing part need to be? As we thought that we were just required to provide certain test cases for the tester to begin with, we did not include much detail in it, which ended up being reported as bugs(i.e. we did not include prerequisites for a test case). So for example, we provided a test case `delete 1` with the expected output being successful deletion of customer at index 1, however, the tester stated that we should include a prerequisite of the displayed list having at least 1 customer, or else the test case will have a different output. We think that this is valid too, but since we though that the manual testing section was more of just a few examples provided for the testers to test, we think that this bug is kind of not in scope, as we think that this is a good to have, but without it the tester can still use our test cases to test the product. 

3. As for the other dev docs linked in the DG, since they are not graded, if the links were broken (i.e. the Setting up, getting started and Documentation, logging, testing, configuration, dev-ops), can be it reported as a bug? As we understood that it is not graded, we did not actually went to test these links, but it ended up to be broken (as we generated our pdf using local host).<img width="748" alt="Screenshot 2023-11-19 at 3 14 59 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/3a0e9398-488c-43ff-a5f5-f72f1200fea1">

**Comment by damithc** [comment]
> 1. We have a bug report related to naming of our target users, so basically the majority of the documentation, we used `Customers` to name our target users, but in our class diagram (which was inherited from the AB3, the classes are called `Person` and some other related namings such as `PersonListPanel`, `PersonCard` etc). So we received a bug stating that our naming in diagrams should also be kept consistent with other sections of the documentation so that the reader can understand it more easily. Our interpretation is that, our class diagram is actually not wrong, as it shows the correct class names, but we also agreed that if we were to change the namings in our implementation it would make the reader understand the context easier. So we were planning to classify this as not in scope (as we think that rectifying the naming is not as important as other features we implemented), but we are not very sure whether is this actually a documentation bug or not, since our documentation is technically correct, and if it is, are we allowed to classify documentation bugs as not in scope?

In v1.4, we did not allow fixing anything that is not _strictly incorrect_, in order to minimize changes to the code during the feature freeze. There is no such restriction in the PE. Anything that can be improved further can be reported. As you suggested, some can be categorized as `NotInScope` i.e., things suitable to be improved in future


> 2\. How detailed does the manual testing part need to be? As we thought that we were just required to provide certain test cases for the tester to begin with, we did not include much detail in it, which ended up being reported as bugs(i.e. we did not include prerequisites for a test case). So for example, we provided a test case `delete 1` with the expected output being successful deletion of customer at index 1, however, the tester stated that we should include a prerequisite of the displayed list having at least 1 customer, or else the test case will have a different output. We think that this is valid too, but since we though that the manual testing section was more of just a few examples provided for the testers to test, we think that this bug is kind of not in scope, as we think that this is a good to have, but without it the tester can still use our test cases to test the product.

Official requirement for that appendix is given below:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/6b9c1762-3917-4671-afcb-a29d2ad0bf6f)

It was not meant to be comprehensive test script for testers to follow, just something to get them started. Note that dev docs normally aim for _minimal yet sufficient_, not _comprehensive_. So, some details may be omitted if you expect the omission will not mislead the tester or put them at a disadvantage. Is that's the case for this specific omission, is something your team will have to decide and justify to the tester.

**Comment by yucongkoo** [comment]
@damithc Thanks for your response.

For the first question, just to confirm, documentation bugs can be classified as not in scope too right?

On top of that, I added a third question after posting this issue and I think you might have missed it maybe due to the interface not refreshing, could you provide advice on that question too? Sorry for the inconvenience cause.

**Comment by damithc** [comment]
> For the first question, just to confirm, documentation bugs can be classified as not in scope too right?

@yucongkoo Yes.

> 3\. As for the other dev docs linked in the DG, since they are not graded, if the links were broken (i.e. the Setting up, getting started and Documentation, logging, testing, configuration, dev-ops), can be it reported as a bug? As we understood that it is not graded, we did not actually went to test these links, but it ended up to be broken (as we generated our pdf using local host).<img alt="Screenshot 2023-11-19 at 3 14 59 PM" width="748" src="https://user-images.githubusercontent.com/122191710/284042852-3a0e9398-488c-43ff-a5f5-f72f1200fea1.png">

As implied by the last bullet point above, broken links in the DG are considered DG bugs, even if the content of those destination pages are not graded.

**Comment by yucongkoo** [comment]
@damithc

> As implied by the last bullet point above, broken links in the DG are considered DG bugs, even if the content of those destination pages are not graded.

I see, but one of the teams reported this bug to be a severity.High, can we use the fact that these sections are not actually graded to counter this, since the content of the destination pages are not graded, having a broken link to those pages are not as of high severity in our course?

**Comment by damithc** [comment]
> I see, but one of the teams reported this bug to be a severity.High, can we use the fact that these sections are not actually graded to counter this, since the content of the destination pages are not graded, having a broken link to those pages are not as of high severity in our course?

hmm... Severity is determined from the target reader's POV. 'Not graded' is a course admin matter; it doesn't mean the link is less important to the DG target reader (i.e., another developer).

**Comment by yucongkoo** [comment]
Hmm, but from another point of view, as we are still being graded under the context of the course, the fact that the destination page is not graded is one of the factors that caused us to miss this during our developer testing stage, as we would subconsciously ignore these sections. On top of that, the broken link issue only arises when the reader is using the pdf version (which is also another restriction enforced by the course, if we were putting ourselves in the shoes of the developer, using the website version could also be an easy workaround).

As a side note, the tester did not actually provide any justification on why they think this broken link is a very severe issue (they only stated that the link is broken), hence it is even more harder for us to state our stance and arguments on why we do not agree that it is a severity.High bug.

**Comment by damithc** [comment]
> As a side note, the tester did not actually provide any justification on why they think this broken link is a very severe issue (they only stated that the link is broken), hence it is even more harder for us to state our stance and arguments on why we do not agree that it is a severity.High bug.

You can choose what you think is the correct severity and justify that rating. 

> Hmm, but from another point of view, as we are still being graded under the context of the course, the fact that the destination page is not graded is one of the factors that caused us to miss this during our developer testing stage, as we would subconsciously ignore these sections. On top of that, the broken link issue only arises when the reader is using the pdf version (which is also another restriction enforced by the course, if we were putting ourselves in the shoes of the developer, using the website version could also be an easy workaround).

You can use these reasons when you write the justification.  If the tester agrees with you, no problem. If the tester doesn't agree, the teaching team will decide after considering reasons given by both your team and the tester.

**Comment by yucongkoo** [comment]
Okay, thanks for clarifying all the questions!

**Comment by yucongkoo** [comment]
@damithc 

Sorry but I have one more question, since all these broken links are caused by the fact that we used the local host to generate the pdf, they could not be fixed independently, hence flagged as a duplicate by us. However, are we required to provide a response to each bug(after flagging them as a duplicate of the "original" bug)? As there is one report on broken images links (also because of the local host), and the reporter might not find the explanation and response we provided to the "orginal" bug useful as it was mainly explaining based on the `getting started` broken links case. Do we add an additional response to the specific bug? As the severity and bug type reported in that specific bug matches our decision.

**Comment by damithc** [comment]
> Sorry but I have one more question, since all these broken links are caused by the fact that we used the local host to generate the pdf, they could not be fixed independently, hence flagged as a duplicate by us. However, are we required to provide a response to each bug(after flagging them as a duplicate of the "original" bug)? As there is one report on broken images links (also because of the local host), and the reporter might not find the explanation and response we provided to the "orginal" bug useful as it was mainly explaining based on the `getting started` broken links case. Do we add an additional response to the specific bug? As the severity and bug type reported in that specific bug matches our decision.

@yucongkoo If the justification in the 'original' doesn't fit a duplicate, it's best to give further explanations in the duplicate as well. Furthermore, explain the justification for flagging it as a duplicate if it is not obvious.

**Comment by yucongkoo** [comment]
@damithc okay thank you prof.
