### ISSUE TITLE
Query on missing extension in use case 

### ISSUE THREAD

**Issue by seanpzk** [nus-cs2103-AY2324S1/forum#495]
Hello, 

This is regarding catcher issue #3653([link to github issue](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/3653)). May I ask if missing an extension in use case that may be deemed as "important" to be considered as a bug? The tester suggested that the below use case should have an extension "for when the class name given is invalid." Our team agreed with his point but wasn't sure if this is actually considered a bug. Thank you!

```
Use case: Remove a student

MSS

    User chooses to remove a student from a class.

    User requests to delete a specific student in a class.

    EduTrack removes the student from that class.

    Use case ends.

Extensions

    2a. EduTrack detects that class name is not specified.

        2a1. EduTrack informs user that class name is empty.

        2a2. EduTrack terminates the request.

        Use case ends.

    2b. EduTrack detects that student index is not specified.

        2b1. EduTrack informs user that student index is empty.

        2b2. EduTrack terminates the request.

        Use case ends.

    2c. EduTrack detects that student index is not valid.

        2c1. EduTrack inform user that student index is invalid.

        2c2. EduTrack terminates the request.

        Use case ends.
```

**Comment by damithc** [comment]
@seanpzk Yes, missing extensions is one of the example DG bugs given:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/fc07c7ef-966f-4eb2-b359-b9e82c7ad624)

**Comment by seanpzk** [comment]
Okay thank you! Sorry I missed out on that part
