### ISSUE TITLE
Logger messages

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#496]
Hi Prof,

If the Logger messages generated while the app is being used are not contexualised to the application, aka, still follows the name `addressbook` within the message, is this considered a valid bug? 

Thanks!

**Comment by damithc** [comment]
@AlagappanRa log messages visible in the terminal are seen by the user and can be considered as part of the app UI. However, they are less important than the content on the GUI, which matters when categorizing bugs as NotInScope

**Comment by AlagappanRa** [comment]
Ok thank you!
