### ISSUE TITLE
What is an invalid year?

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#497]
According to the [gregorian calendar](https://en.wikipedia.org/wiki/Gregorian_calendar), there is no year 0000. 

But according to the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), there is a year 0000.

Is there a consensus on whether 0000 is an "invalid" year that shouldn't be allowed in our applications?

**Comment by damithc** [comment]
@papataco14 Other things to consider:
* Does the user needs to enter such a value during normal usage of the app?
* What's the problem if the user entered such a value, on purpose or by mistake?
* How important is it to handle this corner case? If not very important, it can be `NotInScope`.

**Comment by papataco14** [comment]
>     * Does the user needs to enter such a value during normal usage of the app?

The field is for keeping track of internship application deadlines. But we do allow for entries in the past for record keeping. So realistically, the user won't ever have to enter the year 0000, unless they were interning under [Augustus](https://en.wikipedia.org/wiki/Augustus).

>     * What's the problem if the user entered such a value, on purpose or by mistake?

The app allows it as a valid application deadline. But in our planned enhancements we mentioned that we will warn users if they enter a deadline in the past. 

>     * How important is it to handle this corner case? If not very important, it can be `NotInScope`.

Not very important.

**Comment by damithc** [comment]
> Other things to consider:
> 
> * Does the user needs to enter such a value during normal usage of the app?
> * What's the problem if the user entered such a value, on purpose or by mistake?
> * How important is it to handle this corner case? If not very important, it can be `NotInScope`.

@papataco14 To be clear, I wasn't asking for the answers to the above questions. I was merely suggesting that you consider those questions when you decide how to respond to this bug report, but it still needs to be your decision.

**Comment by papataco14** [comment]
Oh I see, thank you for the suggestions! We will consider them when responding.
