### ISSUE TITLE
Outgoing actors in sequence diagram

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#498]
Two questions.

1. Is an outgoing actor required in every sequence diagram
2. If the answer to question 1 is yes, can `EditCommand` here be considered the "outgoing actor"

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/56ca7f68-3639-437d-9064-67f2b4353356)

**Comment by damithc** [comment]
@AlagappanRa What's an 'outgoing actor'? We didn't use such a term in the course.

**Comment by AlagappanRa** [comment]
@damithc  I am also not sure actually. This was a term used by the tester. In this case are we allowed to reject the bug on that basis? 

Thanks!

**Comment by damithc** [comment]
@AlagappanRa When you respond, you can explain what your 'educated guess' the term is supposed to mean, and formulate your response based on that.

**Comment by AlagappanRa** [comment]
Ok thank you
