### ISSUE TITLE
Queries on duplicate

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#499]
Hi Prof @damithc, could I clarify what exactly constitutes duplicates? 

According to the website, it is mentioned that if the bugs can't be fixed independently, then it is not considered a duplicate. 
<img width="578" alt="Screenshot 2023-11-19 at 6 17 53 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/47603827/e2970703-560d-41ef-81c2-025268713193">

Does that mean that for documentation bugs, like UG and DG, if the same formatting issues appear in multiple places, but are reported as individual bugs (e.g. there are 3 individual incorrect format issues), they should not be considered as duplicates, since fixing the issue at one paragraph, does not fix the issue at the next paragraph? 

Thank you!

**Comment by damithc** [comment]
> they should not be considered as duplicates, since fixing the issue at one paragraph, does not fix the issue at the next paragraph?

@GlendaChong Yes, that's right.

**Comment by GlendaChong** [comment]
Okay, thank you!
