### ISSUE TITLE
Cant delete openjdk version 13.0.14

### ISSUE THREAD

**Issue by Nid21cs** [nus-cs2103-AY2324S1/forum#5]
Im trying to Delete my version 13 java so that i can install my version 11. I followed the instructions in the steps as well as the videos and i cant seem to figure it out. 
<img width="682" alt="Screenshot 2023-08-21 at 7 16 24 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/4891edd6-081a-4264-8775-03a3a326d013">

**Comment by flexibo** [comment]
maybe you can take a look at this link

https://medium.com/@devkosal/switching-java-jdk-versions-on-macos-80bc868e686a

you don't have to delete the JDK version that you have, you can just switch versions.

**Comment by sp4ce-cowboy** [comment]
On macOS, JDK versions are permanently installed in /Library/Java/JavaVirtualMachines. You need to `cd` into that directory and `sudo rm -rf` that particular version of Java. The Application Support directory contains Java itself (the Application to support the running of Java apps on macOS), which (iirc) is different from JDK (the Java Development Kit used to compile and run Java code).

The instructions [here](https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jdk.html) are clearer.

**Comment by Nid21cs** [comment]
> maybe you can take a look at this link
> 
> https://medium.com/@devkosal/switching-java-jdk-versions-on-macos-80bc868e686a
> 
> you don't have to delete the JDK version that you have, you can just switch versions.

Thank you this worked!
