### ISSUE TITLE
FileNotFound error when I run runtest.bat for Level-7

### ISSUE THREAD

**Issue by zacwong2151** [nus-cs2103-AY2324S1/forum#50]
When I manually test my code, the "data/duke.txt" relative path is recognised and I am able to write inputs to the duke.txt file. However, when I run runtest.bat, it shows the FileNotFound error, data\duke.txt (The system cannot find the path specified).

Any ideas why?

**Comment by Respirayson** [comment]
It could be because your code doesn't handle the case where the folder and the file does not exist at the start, since the data folder used when you run runtest.bat is different from the data folder used when you manually test your code. Hope this helps!

**Comment by KamJiaYue** [comment]
Did you close your scanner? u may wanna include 'bye' into ur input.txt file as I have a friend who also has this issue and is solved by adding 'bye' to the tail of the input.txt file. Hope this helps.

**Comment by zacwong2151** [comment]
Thanks all for replies! The issue was that the working directory where my main method was run from was different from where my runtest.bat was run from, so when I tried to run runtest.bat there were issues due to the wrong relative pathing. Fixed it by running runtest.bat from the IP directory instead of the text-ui-test directory, but because of this had to change certain parts of runtest.bat to point to the correct ACTUAL.TXT and EXPECTED.TXT
