### ISSUE TITLE
Clarification on the "You may reject this bug if it is not related to the quality of documentation."

### ISSUE THREAD

**Issue by nathanielcalimag** [nus-cs2103-AY2324S1/forum#500]
Hi prof,

I understand that functionality bugs can be rejected if reported during the "evaluating documentation" phase, but can feature flaws reported in this phase be rejected as well? (e.g. Some bugs are may have slight overlap with documentation bugs but most likely count as feature flaw)

Thank you!

**Comment by damithc** [comment]
@nathanielcalimag Yes, you can reject them if they are not documentation bugs. You should select the type that matches the most, but note the following:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/3a2ff0a8-d3a0-4675-a719-2abc0b10cca6)
