### ISSUE TITLE
Handling tester misunderstanding/potential grammar issue

### ISSUE THREAD

**Issue by cbj252** [nus-cs2103-AY2324S1/forum#503]
Hello, this is regarding issue [#1931](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/1931). The tester suggested that the below explanation should include the "Telegram" class as the "Telegram" class is part of Person_fields.

![image](https://raw.githubusercontent.com/nus-cs2103-AY2324S1/pe/master/files/57983e98-0c44-4337-9bad-3d221453a22f.png)

Our team was conflicted because the list of fields given (Name, Phone and Email in the DG) was not intended to be an exhaustive list, hence the use of "such as" behind fields. 

The tester put this bug as severity Low. Does this count as a minor grammatical bug (hence VeryLow)? In general, how should we deal with the tester's misunderstanding? I see that there's a paragraph on tester misunderstandings: "Some bug reports that arose from a tester misunderstanding something could be due to a flaw in the documentation e.g., something was not explained clearly enough in the document." but am not sure how to proceed.

UML diagram involving Person_fields if needed:
![image](https://raw.githubusercontent.com/nus-cs2103-AY2324S1/pe/master/files/274a3189-2be7-44ef-9a13-b667889a6e5f.png)

**Comment by damithc** [comment]
> "Some bug reports that arose from a tester misunderstanding something could be due to a flaw in the documentation e.g., something was not explained clearly enough in the document."

@cbj252 Glad to see you guys are trying to follow this guideline. But note that it can lead you to identify a problem area in _some_ cases, it might not in other cases. If you think the current version of the DG text in concern has no error and there is no need to improve further, it is fine to reject the bug report.
