### ISSUE TITLE
Question on user stories

### ISSUE THREAD

**Issue by lambraydon** [nus-cs2103-AY2324S1/forum#504]
<img width="1184" alt="Untitled" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105839384/92b435a5-3696-4ebc-a04b-42a09f56b9aa">

It was raised during the PE that the {function} "find a tutee" and the {benefit} "search for a specific tutee that I teach" is a bug because it adds no value.

However, our team is not sure whether this is a documentation bug of a severity.low because it doesn't hinder the reader and should be a severity.verylow instead.

**Comment by damithc** [comment]
> However, our team is not sure whether this is a documentation bug of a severity.low because it doesn't hinder the reader and should be a severity.verylow instead.


@lambraydon it's fine to discuss this in the forum but the teaching team can't make this choice for you at this point.  The teaching team will make a decision only if the tester and the dev team can't agree on a severity.

**Comment by papataco14** [comment]
IMO, this cannot be a `severity.VeryLow` as the requirements for that are "purely cosmetic issues" **and** "doesn't affect usage". 

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/108869153/36988339-d950-4b6d-a10d-5df03227aa6c)

This doesn't seem to be a purely cosmetic issue.

**Comment by lambraydon** [comment]
Thanks for the clarification!
