### ISSUE TITLE
Question on different view of severity in bug

### ISSUE THREAD

**Issue by Gabriel4357** [nus-cs2103-AY2324S1/forum#505]
For Phase 2 of the PE, may I know which label of Response it falls under, "Accept" or "Reject" if we were to agree with someone's bug but disagree on the severity of they proposed. Thank you!

**Comment by damithc** [comment]
@Gabriel4357 Similar to the below, you should accept the bug and change type/severity to the ones you think are more appropriate.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/c7898511-7fc4-4154-b006-d67029806f72)

**Comment by Gabriel4357** [comment]
Alright thank you!
