### ISSUE TITLE
Unfulfilled value proposition and user story

### ISSUE THREAD

**Issue by mfjkri** [nus-cs2103-AY2324S1/forum#506]
## Q1: Value proposition fulfilment

Is it considered a bug if a product does not fulfill its value proposition?

The website mentions that the DG can include requirements not implemented by the end of the semester.

<img width="712" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/32407747/b193fb6d-be2f-4098-a761-dd8fef1b8438">

However, does this also include a value proposition that has not been fully fulfilled and is left for future implementations?

The website mentions that a feature not solving the stated problem for the intended user is considered a feature flaw.

![telegram-cloud-photo-size-5-6258292934466189006-y](https://github.com/nus-cs2103-AY2324S1/forum/assets/32407747/4e25eff6-5ebd-4a13-9376-34a97dca4a66)

Similarly, an unfulfilled value proposition would mean the product does not address the problem it is designed for.

## Q2: User story with high importance fulfilment

Is it considered a bug if a user story marked as high priority (`***`) has not been fulfilled?

The website states that essential requirements must be met to achieve user acceptance.

<img width="715" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/32407747/39a684a4-818e-4637-a443-15bfe93540e2">

**Comment by damithc** [comment]
> ## Q1: Value proposition fulfilment
> Is it considered a bug if a product does not fulfill its value proposition?
> 
> The website mentions that the DG can include requirements not implemented by the end of the semester.
> 
> <img alt="image" width="712" src="https://user-images.githubusercontent.com/32407747/284068540-b193fb6d-be2f-4098-a761-dd8fef1b8438.png">
> However, does this also include a value proposition that has not been fully fulfilled and is left for future implementations?
> 
> The website mentions that a feature not solving the stated problem for the intended user is considered a feature flaw.
> 
> ![telegram-cloud-photo-size-5-6258292934466189006-y](https://user-images.githubusercontent.com/32407747/284068791-4e25eff6-5ebd-4a13-9376-34a97dca4a66.jpg)
> 
> Similarly, an unfulfilled value proposition would mean the product does not address the problem it is designed for.

@mfjkri  It is fine if some of the less important part of the value proposition is not delivered yet, if the work delivered already is more important than the work not yet delivered.  In such cases, the shortfall can be categorized as `NotInScope`



> ## Q2: User story with high importance fulfilment
> Is it considered a bug if a user story marked as high priority (`***`) has not been fulfilled?
> 
> The website states that essential requirements must be met to achieve user acceptance.
> 
> <img alt="image" width="715" src="https://user-images.githubusercontent.com/32407747/284069392-39a684a4-818e-4637-a443-15bfe93540e2.png">

Yes, delivering less important user stories while not delivering more important user stories can be a feature flaw, or a documentation bug (if the user story was given the wrong priority).
