### ISSUE TITLE
Questions on planned enhancement

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#507]
1. Our team received bug of [one planned enhancement containing multiple distinct enhancements](https://catcher-org.github.io/CATcher/phaseTeamResponse/issues/339). It quotes the requirement on website:

`FAQ: Enhancement X and Y are very similar. Can we count them as one? Answer: Only if adding one automatically adds the other. If one can be added without the other, they are counted as two enhancements.`

And stated that **changing font sizes at two different parts in UI** should be considered as 2 separate enhancements. We think it over-interpretting what's stated in FAQ, as it would lead to situation like adding or modifying a whole feature can be considered as 1 enhancement but the tiny change here is considered as 2 enhancements, which doesn't make sense.

Thus, may I clarify that as long as the enhancement is aimed to achievement the same purpose, even if it changes multiple lines of code in one Java file, **such as changing styles in CSS file, or fixing all grammar and inconsistent error messages in one file `Message.java`**,  it could be considered as 1 enhancement?

2. It is [previously answered in forum](https://github.com/nus-cs2103-AY2324S1/forum/issues/475) that 

`If the team has exceeded the allowed count in the planned enhancements, only the first N items (where N is team size x 2) in that list will have immunity. The rest can be reported as bugs. In addition, exceeding the count can be reported as a separate DG bug.`

If there are still vacancies in our planned enhancement, could we reject the issue regarding issues like [one planned enhancement containing multiple distinct enhancements](https://catcher-org.github.io/CATcher/phaseTeamResponse/issues/339)? Because it should not be considered as a bug since we don't exceed the allowed count.

Thank you!

**Comment by damithc** [comment]
> 1. Our team received bug of [one planned enhancement containing multiple distinct enhancements](https://catcher-org.github.io/CATcher/phaseTeamResponse/issues/339). It quotes the requirement on website:
> 
> `FAQ: Enhancement X and Y are very similar. Can we count them as one? Answer: Only if adding one automatically adds the other. If one can be added without the other, they are counted as two enhancements.`
> 
> And stated that **changing font sizes at two different parts in UI** should be considered as 2 separate enhancements. We think it over-interpretting what's stated in FAQ, as it would lead to situation like adding or modifying a whole feature can be considered as 1 enhancement but the tiny change here is considered as 2 enhancements, which doesn't make sense.
> 
> Thus, may I clarify that as long as the enhancement is aimed to achievement the same purpose, even if it changes multiple lines of code in one Java file, **such as changing styles in CSS file, or fixing all grammar and inconsistent error messages in one file `Message.java`**, it could be considered as 1 enhancement?

@A1WAYSD We follow a similar rule when differentiating bugs, so we'll have to stick with this rule. I agree it doesn't always give a fair result, as it only counts the number but does not account for the size or similarity. Still, we need to keep it simple/objective as much as possible too. 
Yes, if we count this way, the planned enhancements list may not have room to include all cases found, in which case it should be used to cover bigger cases. Some minor things such as font size changes might not have room in the list. Hence, if there are many cases, the list can only reduce damage, not avoid damage entirely.

> 3\. It is [previously answered in forum](https://github.com/nus-cs2103-AY2324S1/forum/issues/475) that
> 
> `If the team has exceeded the allowed count in the planned enhancements, only the first N items (where N is team size x 2) in that list will have immunity. The rest can be reported as bugs. In addition, exceeding the count can be reported as a separate DG bug.`
> 
> If there are still vacancies in our planned enhancement, could we reject the issue regarding issues like [one planned enhancement containing multiple distinct enhancements](https://catcher-org.github.io/CATcher/phaseTeamResponse/issues/339)? Because it should not be considered as a bug since we don't exceed the allowed count.

Yes, if the correct count is still below the limit, the said bug can be rejected.

**Comment by A1WAYSD** [comment]
Thank you Prof for the clarification!

**Comment by damithc** [comment]
@A1WAYSD Sorry, a correction.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/52853e04-bb0f-4ba0-8953-509ace0d6eb4)

As per the above, you can reject a bug that says you exceeded the enhancement count when you didn't. However, a bug can be reported if multiple enhancements are listed as one enhancement. That said, the severity can vary based on if the total is exceeded or not. If the total is not exceeded, the impact can be considered 'cosmetic'.
