### ISSUE TITLE
Response for bug

### ISSUE THREAD

**Issue by techjay-c** [nus-cs2103-AY2324S1/forum#508]
Hi Prof, our team has received a bug depicting a program crash using our application. To clarify, in the terminal, there seems to be null exceptions thrown. However, there is no program crash as stated in the description. We would like to check what response we should give for this issue,  as we cant explicitly reject it because it is still valid but at the same time the issue is unclear.

Thanks.

**Comment by damithc** [comment]
@techjay-c Are you able to reproduce it? Perhaps you can share the bug report number here?

**Comment by techjay-c** [comment]
Bug report number is 395. We were not able to reproduce the program crash which was stated in the bug description. However, the screenshot also showed null exceptions thrown in the terminal which we were able to reproduce. But the null exceptions had no impact on the program crash. Hence, we believe that the tester might have misunderstood that his app crashed when he saw the null exception warnings.

**Comment by damithc** [comment]
@techjay-c When the but report is not 100% correct, the dev team should try to figure out the actual situation based on the given data and respond to that actual situation. So, you can respond to this bug report on the basis that the application doesn't crash but the NPE appears in the terminal.
