### ISSUE TITLE
Forum participation dashboard not displaying my participation record

### ISSUE THREAD

**Issue by newway1814** [nus-cs2103-AY2324S1/forum#509]
Dear Teaching Team,
I can not find my record of forum participation even though I have contributed in forum discussions. Requesting if you can provide some advice for the same.
Thanks

**Comment by damithc** [comment]
@newway1814 2 entries missing here (you are one of them) due to a UI issue in the page. Will fix in due course.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/d0544463-c021-429b-a480-11917e826801)

**Comment by newway1814** [comment]
Thank you so much prof for the response!

**Comment by damithc** [comment]
Fixed.
