### ISSUE TITLE
How to respond to illegal modification of JSON files

### ISSUE THREAD

**Issue by zekone** [nus-cs2103-AY2324S1/forum#510]
During PE-D, a few testers have reported issues when they changed parts of the data JSON file manually. For example, changing the format which causes parsing error, adding duplicate entries when our app does not allow through the add command in the CLI, making the file unreadable, etc. 

To "defend" against this, our team has decided to warn against manually editing of the data files in the FAQ section of the UG as we believe that there is too many ways that the file can be modified for us to effectively defend against every case. Even if we were to do so, it seems like it was out of the scope of 1.4.

However, in the actual PE, one tester (#4275) have pointed out, with a high severity, that doing so is a violation of the project requirements. Can we check if this is indeed the case?

Despite the warning in the UG, another tester have edited the the data file (#4402) by inserting a `null` in the first line. How do we respond to this? Would referring them to the FAQ section in the UG section suffice?

Lastly, while we did not warn against modifying the userpref file as it was meant to be modified, the same tester (we believe) has added `null` in the userpref file (#768) which crashed the program. This brings us to the same question on whether such an illegal modification is within the scope of 1.4.

**Comment by damithc** [comment]
> To "defend" against this, our team has decided to warn against manually editing of the data files in the FAQ section of the UG as we believe that there is too many ways that the file can be modified for us to effectively defend against every case. Even if we were to do so, it seems like it was out of the scope of 1.4.
>However, in the actual PE, one tester (#4275) have pointed out, with a high severity, that doing so is violation of the project requirements. Can we check if this is indeed the case?

@zekone The following applies. So, the support for editing the data file cannot be less than AB3, but need not be more than AB3. 

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/c1b8832a-fd02-44e7-917a-d5652a3a2e8d)

For reference, AB3 UG says:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/e52b22ef-dcae-440f-bc98-167dcf6a4a2c)


> Despite the warning in the UG, another tester have edited the the data file (#4402) by inserting a `null` in the first line. How do we respond to this? Would referring them to the FAQ section in the UG section suffice?
> 
> Lastly, while we did not warn against modifying the userpref file as it was meant to be modified, the same tester (we believe) has added `null` in the userpref file (#768) which crashed the program. This brings us to the same question on whether such an illegal modification is within the scope of 1.4.

Recovering from improper edits to the data file (or other config files) was not an expectations at v1.4, unless you specifically stated such a feature in the UG.

**Comment by zekone** [comment]
Thank you for the clarification.
