### ISSUE TITLE
Evidence of tester accessing and downloading from website not included in the PE restrictions.

### ISSUE THREAD

**Issue by CJ-Lee01** [nus-cs2103-AY2324S1/forum#511]
With regards to [issue 5903](https://github.com/nus-cs2103-AY2324S1/pe-dev-response/issues/5903), it would appear that the tester would have to navigate the Oracle website and download the Java 11 JDK and reinstall it during the PE.

I would like to verify if this was allowed during the PE, and if it was not allowed, could it be grounds for rejecting the report?

**Comment by damithc** [comment]
@CJ-Lee01 testers were allowed to access (with permission) websites mentioned by the UG/DG. So, that's not a valid reason for rejection.

**Comment by CJ-Lee01** [comment]
Thank you for the clarification. I will close this issue now.
