### ISSUE TITLE
Severity level of data file bugs

### ISSUE THREAD

**Issue by jflam1301** [nus-cs2103-AY2324S1/forum#513]
Hi Prof, should data file bugs be considered as Medium or Low? The system doesnt crash but the addressbook is cleared, users can still retrieve the data from the JSON file by simply changing the part that causes bugs.
Additionally, I would like to ask if this is a valid consideration/justification to say that the issue is unlikely to happen since the target users most likely wouldn't do that because it is more troublesome?

**Comment by damithc** [comment]
@LamJiuFong See if https://github.com/nus-cs2103-AY2324S1/forum/issues/510#issuecomment-1817931677 answers your question. I should not specify a severity level for specific cases though, as that needs to be your decision.

**Comment by jflam1301** [comment]
Ok thank you!
