### ISSUE TITLE
Will "NotInScope" still benefit the tester's accuracy

### ISSUE THREAD

**Issue by nathanielcalimag** [nus-cs2103-AY2324S1/forum#514]
<img width="701" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/89729098/0b4ade85-c2b7-409e-b49d-c54478d55df7">

Hi prof,
I understand that "NotInScope" will not hurt the dev team's accuracy, but I am wondering if "NotInScope" will have any benefit to tester's accuracy.
Thank you

**Comment by damithc** [comment]
@nathanielcalimag `NotInScope` will not hurt the accuracy of the dev team or the tester.

**Comment by nathanielcalimag** [comment]
Hi prof, I understand that it won't hurt the accuracy of the dev team or tester, but will the tester still get any increase in accuracy?
