### ISSUE TITLE
Is omitting the operation description for a Constructor ok in a sequence diagram?

### ISSUE THREAD

**Issue by seraphimstreets** [nus-cs2103-AY2324S1/forum#515]
As in image shown:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/51947676/5feea3f7-55f6-4796-a654-3a46c1cf3a0d)

The majority of sequence diagrams in this course are shown with the constructor method call. Is it considered non-standard to omit it?

**Comment by damithc** [comment]
@seraphimstreets It is OK to omit it if omitting it doesn't introduce any ambiguity (w.r.t. the purpose of the diagram)

**Comment by seraphimstreets** [comment]
Ok thanks Prof!
