### ISSUE TITLE
Clarification on "cannot be fixed independently"

### ISSUE THREAD

**Issue by nknguyenhc** [nus-cs2103-AY2324S1/forum#516]
Hi prof, according to the course website,

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/87511888/05397a4b-7d76-47c7-84bc-f46c3a2b1859)

two bug reports can be flagged duplicates if they are not obvious duplicates but "cannot be fixed independently". I want to clarify if it qualifies if the solutions to the two bugs have a high degree of overlap. In particular, does it qualify if:

1. The problems are with `ACommand` and `BCommand`. The problem can be resolved by declaring a new method `example` in `Model`, but the two command classes `ACommand` and `BCommand` still needs to make independent calls to the method `Model::example`.
2. Both problems are associated with the generic method `X::<T>method`, which depends on a generic class `G<T>`. Here `X` is a class declared in the programme, and `G<T>` is a generic class imported from a java default package. `T` binds to class `A` in problem 1 and `T` binds to class `B` in problem 2. Both problems can be resolved by declaring `T` in the generic method `X::<T>method` to extend a new interface `I` that has method `example`, i.e. `<T extends I>`, so that `I::example` can be called in the method. The code now will only compile if classes `A` and `B` implements `I`, however, the implementation of `I::example` must be correct in `A` and `B` in order for each problem to be resolved.

Also, can I ask if I can use the team's code base to prove that the two problems cannot be fixed independently?

**Comment by yucongkoo** [comment]
Hi prof, jumping in to also seek clarification regarding wrong duplicate flagging, so if the tester flagged multiple bugs as duplicate, but in fact they aren't (they are similar bugs but not individually fixable), how would the severity, type and respond be determined for the non-duplicate bug(do we need to decide on whether or not to disagree with their respond to the "original" bug)?

**Comment by damithc** [comment]
@nknguyenhc both these conditions must be true for the bug to be declared as duplicates
1. Cannot be fixed independently
2. Fixing one fixes the others automatically

Significant overlap is not enough.

The two examples given don't seem to satisfy both conditions, going strictly by the rule, as fixing the 'supposed copies' of the bug requires some additional work.

**Comment by damithc** [comment]
> Hi prof, jumping in to also seek clarification regarding wrong duplicate flagging, so if the tester flagged multiple bugs as duplicate, but in fact they aren't (they are similar bugs but not individually fixable), how would the severity, type and respond be determined for the non-duplicate bug(do we need to decide on whether or not to disagree with their respond to the "original" bug)?

@yucongkoo Yes, you need to respond to the type/severity currently selected by the dev team, independent of your response to the duplicate status.

**Comment by nknguyenhc** [comment]
Thanks, prof!

**Comment by yucongkoo** [comment]
> > Hi prof, jumping in to also seek clarification regarding wrong duplicate flagging, so if the tester flagged multiple bugs as duplicate, but in fact they aren't (they are similar bugs but not individually fixable), how would the severity, type and respond be determined for the non-duplicate bug(do we need to decide on whether or not to disagree with their respond to the "original" bug)?
> 
> @yucongkoo Yes, you need to respond to the type/severity currently selected by the dev team, independent of your response to the duplicate status.

Okay understood. Thanks prof
