### ISSUE TITLE
Clarification on how PE tester accuracy is graded

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#517]
From the website:
```
If the dev team disagreed with an aspect (i.e., type/severity/validity
) and you now agree with the dev team's position, it will not hurt your accuracy rating. 
```

I wanted to ask why having your bug rejected would not negatively effect your accuracy rating. Wouldn't rejecting a bug mean that you aren't finding issues with their design? I'm not very certain of the reasoning here.

**Comment by damithc** [comment]
@WZWren in phase 1, testers operate under time pressure, and possibly, with partial information. So, it is possible to make mistakes. We can't expect perfection under such conditions. When presented with additional information and given more time, it is fine to admit your mistake and change your position, and it is a behavior we want to encourage. 
Sticking to the original mistaken position even in the face of opposing facts is not a behavior we want to encourage.

**Comment by WZWren** [comment]
Oh OK, thank you for clarifying prof!
