### ISSUE TITLE
Clarification of 'Known Issues' section

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#518]
Can I ask if teams can reject functionality bugs/feature flaws if it was included in a known issues section? I know there is a rule for this for feature flaws in the DG ("Planned Enhancements"), but I do not remember if there was such a rule for known issues.

**Comment by damithc** [comment]
@WZWren Only the `Planned enhancements` section is immune from being reported as bugs. However, being mentioned in other ways (e.g., as a known issue) can reduce the severity of a bug (as keeping users informed can help reduce the impact of the bug on users).
