### ISSUE TITLE
Omitting parameters of method calls in sequence diagrams

### ISSUE THREAD

**Issue by craigtonlian** [nus-cs2103-AY2324S1/forum#519]
Suppose in a sequence diagram, a call was made on a method `foo(int a, int b)` that takes in two parameters. But the sequence diagram labels it as a call to `foo()`. Can we justify the omission of the parameters as a means of simplifying the diagram? Or is it just wrong?

**Comment by damithc** [comment]
@craigtonlian depends on how relevant to the purpose of the diagram and how much it hinders the reader. Ideally, such simplifications should be indicated (e.g., `foo(...)` or mention in the accompanying explanations/note)
