### ISSUE TITLE
Clarification regarding wrong examples used in bug reports

### ISSUE THREAD

**Issue by mounilsankar** [nus-cs2103-AY2324S1/forum#520]
Hi prof, lets say the issue pointed out in my original bug report is valid, however the example i had given in the original bug report is invalid and the team responded CannotReproduce. Am i allowed to provide the corrected example?

**Comment by damithc** [comment]
@mounilsankar note the following instruction from the dev response phase:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/fc50ee01-0383-49c8-840b-65039e7d4e34)

If you think the dev team should have been able to reproduce the error even if the example given was wrong, you can disagree with their response and also provide the correct example.  Based on that info, the teaching team will decide if the dev team is justified in their earlier response.
