### ISSUE TITLE
No team response given for duplicate bug

### ISSUE THREAD

**Issue by LoMaply** [nus-cs2103-AY2324S1/forum#522]
Hi prof, currently one of my bugs was marked by the developer team as a duplicate (which I agree with), however no response was given by the developer team to the Original bug that is referenced (no indication of whether the Original bug is accepted or rejected etc.).

As I only have the option to select Agree/Disagree for the duplicate status, do I just leave it as Agree and move on?

**Comment by damithc** [comment]
@LoMaply What's the issue number?

**Comment by LoMaply** [comment]
> @LoMaply What's the issue number?

It is issue [9](https://github.com/LoMaply/pe/issues/9) for me
Issue [8](https://github.com/LoMaply/pe/issues/8) is similar in that the dev team gave a written response, but no issue label

**Comment by damithc** [comment]
@LoMaply If there is no option for you to disagree on response/severity/type, that means there is nothing for you to disagree with (i.e., the issue was accepted and there was no change to type/severity).

**Comment by LoMaply** [comment]
Got it, thanks prof
