### ISSUE TITLE
UML diagram issues in bug reporting

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#523]
The team I tested uses some UML diagrams with excessive infomation and unreadable font sizes in different places. As the course website suggests, I report the different UML diagrams in separate issues with severity.VeryLow, since fixing one of them does not fix the others.

However, in the response session, they mark these as duplicate of an overarching issue, which contains all the problems and with severity.VeryLow. I don't think this follows the description on course website. Duplicate similar problems in different places should be reported separately. If they want to combine the problems, they should increase the severity. Not to mention the total number of problems does not reach the bar of 5.

In this case, for the separate issues I submit, should I reject the marking as duplicate or should I increase the severity?

(I am not posting pictures to avoid reflecting which team I am testing.)

**Comment by damithc** [comment]
@ChangruHenryQian As mentioned in https://github.com/nus-cs2103-AY2324S1/forum/issues/516, we are strict on what is allowed as duplicates. If you think the cases you reported don't qualify, you can disagree with the duplicated status and give your reasons.

FYI, this time we did not approve _any_ case of merging >5 similar bugs as one. So, this is definitely not such a case.

**Comment by ChangruHenryQian** [comment]
> @ChangruHenryQian As mentioned in #516, we are strict on what is allowed as duplicates. If you think the cases you reported don't qualify, you can disagree with the duplicated status and give your reasons.
> 
> FYI, this time we did not approve _any_ case of merging >5 similar bugs as one. So, this is definitely not such a case.

@damithc Thank you for replying. In this case, the overarching issue consists of the issues which should have been separate. Solving the overarching issue solves the separate issues, because that tester simply combine all the problems into one. But it has the wrong severity type and it is not submitted by me. In fact, it should not be submitted at all. May I confirm is it still allowed to reject the duplicate?

**Comment by damithc** [comment]
@ChangruHenryQian you can disagree with the duplicate status and write in the comment that if it is treated as a duplicate the severity should be higher. Note that I'm suggesting a possible action available to you, not confirming that is the correct choice (the choice should be your decision).
