### ISSUE TITLE
Which testers are responsible for defending duplicate issues?

### ISSUE THREAD

**Issue by nathanielcalimag** [nus-cs2103-AY2324S1/forum#525]
Hi prof,

Suppose we have this scenario.

Issue A: Medium, all other issues are duplicates of this
Issue B: High
Issue C: Low
Issue D: Very Low

Suppose the dev team wants to mark issue A as Low, and all testers want to keep their original severity (but agree that their issue is a duplicate). The dev team only responded to issue A, reasoning why it is not medium and it should be low.

1. Would the same teaching team member be handling the dispute for all 4 issues to remain completely objective, or will the teaching team only consider the argument laid by Issue A, the main issue? How would the teaching team handle 4 different "disagree" arguments from 4 different issues?
2. Would issue C's only option be to accept the dev team's feedback since they want to downgrade from medium to low, which is the issue's current status anyway? How does it affect Tester C's accuracy if the dev team's argument gets accepted or rejected?
3. Would issue D's minimum severity automatically be increased from Very Low to Low? How does it affect Tester C's accuracy if the dev team's argument gets accepted or reject? 
4. Should Tester B be arguing that the issue is severity medium or high?

Thank you

**Comment by damithc** [comment]
@nathanielcalimag the moment the team mark B, C, D as duplicates of A and gives it Low severity, it is as if they changed B, C, D severity to Low as well (duplicates inherit severity from the original). For example, the tester B will be told that the team chose `Low` for the bug, and the tester can respond accordingly. 

All 4 tester responses will be evaluated by the same teaching team member, but independently, based on justifications provided by each tester.

If any of the testers managed to successfully argue that the bug should be `High`, it will be considered `High` for all testers involved (i.e., when dealing with a cluster of duplicates, we take the highest severity and apply it to all).

A tester's accuracy is lowered only if the tester disagreed and the teaching team sided with the dev team.

**Comment by nathanielcalimag** [comment]
Hi Prof @damithc, thanks for your reply. I still need some clarification on accuracy as I'm in this particular situation:

Issue A: Severity `Medium`
Issue B: Severity `Low`, marked as duplicate of A and is my current issue

The dev team is arguing for Issue A to be lowered to `Low`, and I suppose all I need to do is agree.

I'm under the impression that if the teaching team agrees with the developer and chooses `Low`, the severity will match mine and will result in my accuracy increasing.

However, if the dev team sides with Tester A and keeps the severity at `Medium`, will this negatively impact me in the sense that I will no longer receive my accuracy increase? In this case, is there anyway to defend my bonus accuracy to keep the severity as `Low`?

Thank you!

**Comment by damithc** [comment]
> Issue A: Severity `Medium` Issue B: Severity `Low`, marked as duplicate of A and is my current issue
> 
> The dev team is arguing for Issue A to be lowered to `Low`, and I suppose all I need to do is agree.

@nathanielcalimag Yes.

> I'm under the impression that if the teaching team agrees with the developer and chooses `Low`, the severity will match mine and will result in my accuracy increasing.

Yes
 
> However, if the dev team sides with Tester A and keeps the severity at `Medium`, will this negatively impact me in the sense that I will no longer receive my accuracy increase? In this case, is there anyway to defend my bonus accuracy to keep the severity as `Low`?

Yes, it will decrease but you will receive the credit for a `Medium` bug. Hence, you are likely to end up with a net gain.
