### ISSUE TITLE
Disagreeing with NotInScope Feature Flaw in consideration of Planned Enhancements

### ISSUE THREAD

**Issue by HEEaZ** [nus-cs2103-AY2324S1/forum#526]
Hi Prof, currently teams can classify a feature flaw under notInScope if it is deemed that the feature is of lower priority than the work done in v1.4. Are we allowed to point out that certain features which are in their planned enhancements are in fact of lower priority than rectifying this feature flaw, and hence disagree with their characterization of the FF as notInScope?

This question was inspired by your reply to #521

**Comment by s-peiran** [comment]
While waiting for prof to reply let me offer my 2 cents. Firstly, this feature flaw you pointed out must not be under their planned enhancements. Personally, I don't think that arguing the stuff in their planned enhancements are of lower priority than this feature flaw you pointed out is a strong argument. I suggest you argue from the fundamental of this feature flaw and why it is not suitable.

**Comment by damithc** [comment]
@HEEaZ you can do that with their current features. As we did not specifically require that _planned enhancements_ should be next highest priority changes (although it was kind of implied), I think best not to compare priority of _planned enhancements_ with that of feature flaws you reported.

**Comment by HEEaZ** [comment]
Got it, thank you!
