### ISSUE TITLE
NotInScope and severity level

### ISSUE THREAD

**Issue by zsh-eng** [nus-cs2103-AY2324S1/forum#528]
Does the severity level of a bug that is flagged as `NotInScope` matter?

> Note that response.NotInScope bugs earn a small amount of credit for the tester without any penalty for the dev team, unless there is a high number of such issues for a team.

For example, if a team flags the bug report as `NotInScope` and reduces the severity level from `Medium` to `VeryLow`, does "agreeing" for the `NotInScope` and "disagreeing" for the severity level make any difference?

Thank you!

**Comment by s-peiran** [comment]
If you agree to `NotInScope` the severity level will be discarded and the issue will be settled as `NoteInScope`.

Correct me if I'm wrong.

**Comment by damithc** [comment]
@zsh-eng When giving testers credit for NotInScope bugs, the severity doesn't matter.

**Comment by zsh-eng** [comment]
Noted thank you!
