### ISSUE TITLE
What to do with severity downgrade without any justifications

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#529]
If the dev team rejected and downgraded severity of a bug report without any justifications(the bug was reported as a FeatureFlaw of medium severity, the dev team just stated that this behaviour is stated in UG and rejected the bug and downgraded it to severity.VeryLow). As stated in the website: 
<img width="718" alt="Screenshot 2023-11-21 at 4 04 47 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122191710/470c7511-9f27-4596-b389-a0fad62da60a">

Do I need to provide additional reasoning of disagreeing with the rejection(and downgrade)?

**Comment by s-peiran** [comment]
The dev team did not leave the justifications blank and said refer to their UG. You should review the UG and propose a stronger reasoning than what they stated in order for you to have a greater chance of winning the case.

**Comment by damithc** [comment]
@yucongkoo the team not giving sufficient reasons for the downgrade tilts the case in your favor. Nevertheless, you can provide a justification why you chose that severity/type to further increase your chance of a favorable decision in the next phase.

**Comment by yucongkoo** [comment]
> The dev team did not leave the justifications blank and said refer to their UG. You should review the UG and propose a stronger reasoning than what they stated in order for you to have a greater chance of winning the case.

Hi @s-peiran , thanks for pitching in, the case was that the dev team just said that the feature is functioning as it is supposed to be, but I did not report is as a functionality bug, rather a feature flaw with my reasoning on why I think this feature has a flaw. Hence, his response on saying that it is stated in the UG is basically not responding to the bug report(his respond just shows that it is not a functionality bug).

**Comment by yucongkoo** [comment]
> @yucongkoo the team not giving sufficient reasons for the downgrade tilts the case in your favor. Nevertheless, you can provide a justification why you chose that severity/type to further increase your chance of a favorable decision in the next phase.

Ahh okay, because what I did was that I provided explanations on why I think that the current behaviour might be flawed and problematic, but the team totally did not respond to any of my stance, so I am not sure what they do not agree with me( nor why they think that it is not a bug) 

But anyways, I will still provide my justifications in the response to further elaborate why I initially think that it is flawed. Thank you prof.
