### ISSUE TITLE
Missing CS2101 context when testing documentation

### ISSUE THREAD

**Issue by Cloud7050** [nus-cs2103-AY2324S1/forum#530]
I am exempted from CS2101, and thus am taking CS2103 standalone. My tutorial mates and I have never taken the former course and do not have access to its materials. Thus I have not heard about the goings-on in that course; I have no context as to the additional requirements that it turns out CS2101 places on this course's documentation, such as the UG.

Still, I was assigned to test the product of a team whose documentation has to fulfill both courses' rubrics. I was thus missing important context under which some of that team's documentation was written and _phrased_ (e.g. tone), and the reasons behind why they may have made certain decisions that differ from that of the teams I have seen so far.

It is only now that my assigned team has responded, including content such as screenshots, files, and keywords that I am finding out/hearing about for the first time, that I am learning of this difference. This has negatively impacted my report accuracy, especially since I was only able to make mainly documentation-related reports for their product for lack of other types of issues found. Had I known some of this information beforehand, I would have made my reports differently/made different reports altogether.

Will any of this be taken into account when it comes to grading for accuracy? I feel like this would not have been a concern had the team assignment been done amongst teams who are also not taking CS2101.

**Comment by damithc** [comment]
@Cloud7050 can you email me the issue numbers that are affected by this?

**Comment by Cloud7050** [comment]
> @Cloud7050 can you email me the issue numbers that are affected by this?

Yes, I have sent you an email as a follow up. Thank you.

**Comment by damithc** [comment]
In case any other CS2103 student with similar concerns is reading this thread, here is the relevant part from my email reply to @Cloud7050 

>I can understand that you are worried about being disadvantaged because CS2101 covers communications topics closer to CS2103/T compared to the equivalent communications course you have taken (CS2101 fulfils a university level communication course requirement, which means you must have taken a similar course too). But the effect of CS2101 on the CS2103 grade is minimal (i.e., things taught in CS2101 are graded on CS2101 side rather than CS2103 side -- e.g., CS2101 focuses on the language aspect while CS2103 focuses on the technical content). In addition, CS2103 grading and CS2103T grading is done as two separate courses.
