### ISSUE TITLE
Referencing separate bug reports

### ISSUE THREAD

**Issue by LHeng1** [nus-cs2103-AY2324S1/forum#531]
Say my bug report `a` was rejected by the dev team. However, some information provided in the response of the dev team in my bug report `b` contradicts the rejection of `a`. Is it possible to quote their response in `b` to respond to their rejection of `a`?

**Comment by damithc** [comment]
@LHeng1 yes, you may do so. Give the full link to the other issue as well as repeat the relevant content.

**Comment by LHeng1** [comment]
Alright, thank you!
