### ISSUE TITLE
Follow up on #535

### ISSUE THREAD

**Issue by nknguyenhc** [nus-cs2103-AY2324S1/forum#536]
Hi prof, following up on your reply in [#535](https://github.com/nus-cs2103-AY2324S1/forum/issues/535#issuecomment-1822163664), can I clarify that this is also applicable to other json files (i.e. `preferences.json` and `config.json`), that is, the minimum requirement for v1.4 is that the app should still be able to start upon any edits to those json files?

**Comment by damithc** [comment]
@nknguyenhc Currently, other data files are not covered in the minimum requirement as they are not mentioned in the AB3 UG. So, it is up to the team to support or not support editing them, and to what extent.

**Comment by nknguyenhc** [comment]
Thanks prof!
