### ISSUE TITLE
Details of response

### ISSUE THREAD

**Issue by AlagappanRa** [nus-cs2103-AY2324S1/forum#537]
Hello Prof,

I strongly believe the tester should not be allowed to stray away from the initial report by adding details not relevant to the initial report within their phase 3 appeal - as they would have had more time to critique the team. Does the teaching team take this same stance when evaluating tester appeals?

Thanks!

**Comment by damithc** [comment]
@AlagappanRa Any additional info provided by the tester in phase 3 is considered only if the dev team should know that information already (even if not mentioned in the original bug report) or should be able to discover that information by themselves (based on the partial info provided by the bug report).

Relevant point:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/e97cd88a-20f5-45bf-a03d-817eed4d1a2c)
