### ISSUE TITLE
Question on tester accuracy

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#538]
May I ask in case where original tester choice is `VeryLow` and Dev choice is `Low`, will tester's reaction to accepting this change hurt tester accuracy? Thank you!

**Comment by damithc** [comment]
@A1WAYSD Yes, the the net gain will likely be positive (i.e., the extra marks gained by higher severity will be more than the bonus marks lost by lower accuracy)

**Comment by A1WAYSD** [comment]
@damithc Okay got it. Thank you Prof!
