### ISSUE TITLE
Changing from Rejected to NotInScope

### ISSUE THREAD

**Issue by geraldngjx** [nus-cs2103-AY2324S1/forum#539]
Hello! May I ask if the objection to the dev team not accepting a bug can be a proposal to change the Response from Rejected to NotInScope? Based on the CS2103T website (from the screenshot), the usual assumption would be that an objection to the bug report "not accepted" would be to propose that it be accepted at the said level of severity, hence I would like to reconfirm if I could object to change it to NotInScope (or would there be little to no value in that). Thank you!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/102348985/51466e19-62b9-42b3-b12b-677eae760307)

**Comment by damithc** [comment]
@geraldngjx Yes, if the current response is `Rejected`, you can disagree with it and request it to be `NotInScope` (which can earn you some credit).

**Comment by geraldngjx** [comment]
Thank you for the prompt response, Prof Damith!
