### ISSUE TITLE
NotInScope marking

### ISSUE THREAD

**Issue by InfiBeyond** [nus-cs2103-AY2324S1/forum#540]
How does `NotInScope` affect the mark for the testers and developers?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/67530014/15a0a58b-fe3d-42ca-9c65-e44e298498ba)

On the website, it says that the dev team will not be penalized, but the bug reporter will earn a small amount of credit for reporting it.

Specifically, how much does the "small amount of credit" account for?

**Comment by damithc** [comment]
@InfiBeyond we don not specify exact marks for bug type/severity/response, in order to avoid bug type/severity/response decisions being too 'calculative'. So, the decision should be based on whether the bug is really NotInScope or not.
