### ISSUE TITLE
Invalid bugs accepted as a duplicate bug

### ISSUE THREAD

**Issue by jflam1301** [nus-cs2103-AY2324S1/forum#542]
Hi Prof,

I reported an invalid bug (I misunderstood the app) and the developer team agreed that it is not a bug in their response too. However, they did not reject it but accepted it as a duplicate bug to another bug report which is also reported by me (but I think they are totally different)

I disagree with it being a duplicate to another bug report, but I am curious do I still get a +1 for bugs accepted by developer team? I admit that it is an invalid bug but the dev team did not reject it though (despite rejecting it in their response).

**Comment by damithc** [comment]
@LamJiuFong what's the corresponding issue number?

**Comment by jflam1301** [comment]
@damithc It is issue 5 
[https://github.com/LamJiuFong/pe/issues/5](url)

**Comment by damithc** [comment]
@LamJiuFong as per our rules, you can disagree with the duplicate status and if the teaching team agrees with you, this will be treated as a separate issue. Note that the team has explicitly accepted both this bug and the original bug. So, if they are counted as separate bugs, you'll get credit for both.

**Comment by jflam1301** [comment]
Thank you for your clarification!
