### ISSUE TITLE
Syllabus for Final Exam

### ISSUE THREAD

**Issue by eyelessrhyme7** [nus-cs2103-AY2324S1/forum#543]
Hi, could the teaching team clarify roughly what all to study and focus on for the final exams, given the abundance of content in the textbook and otherwise. UML is one of the main portions. Along with that, what else is heavily examinable?

**Comment by damithc** [comment]
@eyelessrhyme7 All topics in the [textbook](https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/index.html) are examinable except level-4 topics.

The [printable version of the textbook](https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/print.html) has only the examinable topics, and is in one page. The PDF version of the textbook (in Canvas) also has examinable topics only, and also has a ToC and an index at the end.

**Comment by eyelessrhyme7** [comment]
Thank you so much Prof! I've gone through the textbook pdf and it really helps consolidate everything that's examinable.
