### ISSUE TITLE
Luminus API for Canvas Quizzes Dead

### ISSUE THREAD

**Issue by KamiliArsyad** [nus-cs2103-AY2324S1/forum#546]
I noticed that all the images in every quiz are now gone as it seems like the images were uploaded to Luminus (which is now dead).

Any ideas how I can still practice on the quizzes? I use them a lot.

**Comment by damithc** [comment]
@KamiliArsyad which quiz exactly? I checked quiz 5 and the images are still there.
Are others facing the same problem?
In the meantime, I'll check with NUS IT if access to images were blocked recently.

**Comment by KamiliArsyad** [comment]
It seems like it was only a momentary issue. Just now I tried doing Quiz 4, 5, 6, and 7 but the pictures weren't there. Sorry for the trouble, I'll close this issue for now!

**Comment by damithc** [comment]
@KamiliArsyad Noted. Another student mentioned about a similar case y'day. I also informed NUS IT as well.
