### ISSUE TITLE
Difference between association and navigation

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#548]
`Definition of Navigation from the textbook:`
<img width="604" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/80821e4f-22d5-47f6-88e1-c7b2ef758946">

`Definition of Association from the textbook:`
<img width="672" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/13dafcc8-2bfc-48e2-a556-1fdad8bb050c">

If both association and navigation requires one class to keep a reference to another class, then what differentiates them?

**Comment by TeeRenJing** [comment]
I think every association between two objects/classes has a navigability (Unidirectional or Bidirectional), and you can choose to include this information by adding arrowheads in the UML diagram. So I think navigability is a trait of the association, not something different from an association.

Much like how a road can be one way or two way.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/62975067/29217172-e11a-480c-a72a-3bbf085f1483)

**Comment by damithc** [comment]
> Much like how a road can be one way or two way.

Good analogy @TeeRenJing 👍

**Comment by s-peiran** [comment]
@TeeRenJing thanks for chiming in.

**Comment by s-peiran** [comment]
I want to follow-up this qn that whether navigability and association arrows can be used interchangeably.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/e14aae99-e18f-4c72-a895-a5906b1afa30)
Taking the practice exam for instance, can all the navigability arrows (such as that from activity to watcher) be replaced with association arrows?

**Comment by damithc** [comment]
> Taking the practice exam for instance, can all the navigability arrows (such as that from activity to watcher) be replaced with association arrows?

@s-peiran There is no such thing as an _association arrow_. Association is the line `____`, navigability is the arrowhead `>`

**Comment by s-peiran** [comment]
I meant whether it is technically correct to show navigability as association line? The navigability arrow is just a more specific representation of association that shows the direction of reference.

**Comment by damithc** [comment]
> I meant whether it is technically correct to show navigability as association line? The navigability arrow is just a more specific representation of association that shows the direction of reference.

Think of navigability, multiplicity, association label, and association role as additional information you add onto an association. They don't exist without an association.

**Comment by s-peiran** [comment]
thank you for the clarification prof.
