### ISSUE TITLE
Question on practice exam part 2

### ISSUE THREAD

**Issue by Elijah5399** [nus-cs2103-AY2324S1/forum#549]
Hi, I would like to ask why the two update methods are shown as public in the class diagram when no access modifiers were specified in the code.![telegram-cloud-photo-size-5-6280732257392113360-y](https://github.com/nus-cs2103-AY2324S1/forum/assets/22656175/1b96e236-06b3-4b2b-b60f-65aedb4ee432)![telegram-cloud-photo-size-5-6280732257392113362-y](https://github.com/nus-cs2103-AY2324S1/forum/assets/22656175/88db2476-d468-47ea-bf07-03ec22afa55e)

**Comment by TeeRenJing** [comment]
https://docs.oracle.com/javase/tutorial/java/IandI/interfaceDef.html#:~:text=All%20abstract%2C%20default%2C%20and%20static,you%20can%20omit%20these%20modifiers.

It seems that "All abstract, default, and static methods in an interface are implicitly public, so you can omit the public modifier." 

Hence the plus symbol for the visibility of public.
