### ISSUE TITLE
Question about class diagram's operation

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#551]
May I confirm whether the minimal representation of methods in class diagram is `method_name(param_type)` or can be simply `method_name()` in case it's enough to only know the method name? Thank you!

**Comment by damithc** [comment]
@A1WAYSD Even just `method_name()` is OK, but to avoid ambiguity, it is better to use `method_name(...)` to show that you are omitting the parameters.

**Comment by A1WAYSD** [comment]
@damithc Okay I see! Thank you prof for reminding the use of `...`!
