### ISSUE TITLE
Slides Quiz Question

### ISSUE THREAD

**Issue by Vanessamae23** [nus-cs2103-AY2324S1/forum#554]
Can i ask why ACBDEF is not possible here?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/60029664/660d7e97-d225-45d2-85df-1abbf79d50ac)

**Comment by damithc** [comment]
@Vanessamae23 thanks for raising this. `Yes` is correct, as was explained in the lecture. However, it was configured incorrectly in the Canvas quiz. I've corrected it just now.

**Comment by Vanessamae23** [comment]
Okay thank you prof
