### ISSUE TITLE
Can multiplicity be a variable in class diagrams? (Practice exam part 2)

### ISSUE THREAD

**Issue by matochichap** [nus-cs2103-AY2324S1/forum#555]
<img width="572" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/89329616/5f44fce6-924c-4811-b5d9-90531856dadd">

<img width="458" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/89329616/7710c2c4-5959-41f3-b3e4-2598ee7213a1">

In the image above, the multiplicity for watchers is 0...10 because MAX is 10 from ProgressWatcher. 

Is writing multiplicity as 0...ProgressWatcher.MAX allowed since it makes it clearer that the max number of watchers depends on that variable. Also the MAX variable is not defined as a final variable so that value can be changed and it would be misleading to state that the multiplicity is 0...10

Alternatively, is it better to replace the navigability with a field under the Activity class as shown in the image below? It would be able to capture more information too since it can indicate that the field is private as well.

<img width="500" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/89329616/140131b7-9b51-43bb-9920-e879d851c85e">

**Comment by damithc** [comment]
> Is writing multiplicity as 0...ProgressWatcher.MAX allowed since it makes it clearer that the max number of watchers depends on that variable. Also the MAX variable is not defined as a final variable so that value can be changed and it would be misleading to state that the multiplicity is 0...10

Yes, it is allowed @matochichap
