### ISSUE TITLE
Is +update(int) necessary in the UI Widget class?

### ISSUE THREAD

**Issue by MagnificentCreature** [nus-cs2103-AY2324S1/forum#556]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/61371541/fac88829-71f7-4787-921d-f87ea564982d)
We already know it inherits from the abstract interface

**Comment by TeeRenJing** [comment]
Another hypothetical scenario I can think of: abstract class ProgressWatcher could have provided an implementation of the +update(int) method, while the UiWidget just extends the abstract class ProgressWatcher without overriding the +update(int) method in ProgressWatcher.

Now the +update(int) method will be written in ProgressWatcher instead. Hence I think it is necessary to show where there has been an implementation of the +update(int) method.

Extending from my scenario, if the UiWidget overrides the +update(int) method in ProgressWatcher. I think +update(int) method will have to be written in both ProgressWatcher and UiWidget.

**Comment by MagnificentCreature** [comment]
Thanks, but without knowing that, would we be penalised if we don't write it for either, or write it for both?

Likewise actually, will we be penalised if we do not write the fields for the classes? Since they are optional also right?

**Comment by damithc** [comment]
> Thanks, but without knowing that, would we be penalised if we don't write it for either, or write it for both?

@MagnificentCreature The code of Activity, Watcher, ProgressWatcher are given in the question. So, some things are _known_ already.

**Comment by MagnificentCreature** [comment]
I see, because we know that ProgressWatcher DID NOT override it, so we know UiWidget must override it?

**Comment by damithc** [comment]
> I see, because we know that ProgressWatcher DID NOT override it, so we know UiWidget must override it?

@MagnificentCreature Yes, that's the idea.

**Comment by MagnificentCreature** [comment]
Thank you
