### ISSUE TITLE
Practice Exam Part 1 Q5

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#557]
Hello, may I know what's the reasoning behind why the options 2 and 3 are correct? 

My understanding is that removing the store() method will cause a compile error because Bar is not an abstract class, which makes the option correct. 

However, by the same logic, will removing process() method not also cause a compile error? 

Could someone help to clarify any misunderstandings I have, as well as to provide an explanation for the 2 options? 

Thank you!

<img width="802" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/47603827/ef78b3d4-96fb-405c-ab9f-56e85dce9399">

**Comment by TeeRenJing** [comment]
Question stated that "the Goo interface doesn't have any default method implementation", for Bar to be a concrete class it has to provide an implementation for store().

On the other hand the process() method is not italicized and there is no {abstract} keyword. Hence it is not an abstract method and has a default implementation in the abstract class Foo.

I think Java allows definition of abstract classes without any abstract methods https://stackoverflow.com/questions/4811678/defining-an-abstract-class-without-any-abstract-methods

**Comment by damithc** [comment]
> Question stated that "the Goo interface doesn't have any default method implementation", for Bar to be a concrete class it has to provide an implementation for store().
> 
> On the other hand the process() method is not italicized and there is no {abstract} keyword. Hence it is not an abstract method and has a default implementation in the abstract class Foo.
> 
> I think Java allows definition of abstract classes without any abstract methods https://stackoverflow.com/questions/4811678/defining-an-abstract-class-without-any-abstract-methods

@GlendaChong this answer given by @TeeRenJing is correct.

**Comment by GlendaChong** [comment]
Thank you!
