### ISSUE TITLE
Cannot find Java coding standards in handouts

### ISSUE THREAD

**Issue by ChangruHenryQian** [nus-cs2103-AY2324S1/forum#558]
<img width="664" alt="d8dc70ba21d620be439e8bfddbfa094" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/115453805/0ead02e1-b34c-4e9f-b66b-24dd06647ae7">

For the email, may I ask where can I find the Java coding standard pdf on Canvas? I find the other three in handouts but not this one.

**Comment by damithc** [comment]
@ChangruHenryQian Sorry, added it to Canvas/files/handouts just now.
