### ISSUE TITLE
Question on default branch

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#559]
Hi, may I ask if missing default branch in switch can be considered as coding standard violation? Since in coding standard it does state the format with default but doesn't explicitly mention.. Or shall we identify it as only coding quality problem? Thank you!
<img width="984" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/112334419/c212f5b4-f6a8-46c7-821c-cd401ed856cf">

**Comment by damithc** [comment]
@A1WAYSD No, the coding standard does not enforce a `default` branch for `switch` statements.

**Comment by A1WAYSD** [comment]
@damithc Okay Thanks prof!
