### ISSUE TITLE
Textbook in Canvas does not have expanded sections for Class Diagrams, Sequence Diagrams

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#561]
The Class Diagrams and Sequence Diagrams section of the textbook is currently not expanded on the Canvas copy of the textbook, so we can't refer to the details inside of that section.

**Comment by damithc** [comment]
@WZWren UML notation appears as a separate chapter. Those sections are collapsed to prevent duplication.

**Comment by WZWren** [comment]
Ah I see, thanks for clarifying!

**Comment by JCSnap** [comment]
> @WZWren UML notation appears as a separate chapter. Those sections are collapsed to prevent duplication.

Oh I was intending to print the website content manually as I thought the collapsed sections are a mistake. Can we assume that all the required content are present in the textbook?

**Comment by damithc** [comment]
> Oh I was intending to print the website content manually as I thought the collapsed sections are a mistake. Can we assume that all the required content are present in the textbook?

@JCSnap Yes, the textbook PDF contains all examinable topics, and omits non-examinable topics.
