### ISSUE TITLE
Clarification on test coverage

### ISSUE THREAD

**Issue by GlendaChong** [nus-cs2103-AY2324S1/forum#562]
Hi everyone and Prof @damithc, for a similar question like this, but for testing 100% branch and condition coverage respectively, how will one actually go about doing it? 

For `for` loops, there is a condition of `i < s.length()`, do we consider that as a branch/condition? If yes, will that mean a varying number of times of test, and hence cannot be determined? 

<img width="846" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/47603827/8ab3e5f4-08da-45db-86d9-7086d27bfd9b">

**Comment by damithc** [comment]
> For `for` loops, there is a condition of `i < s.length()`, do we consider that as a branch/condition?

@GlendaChong Yes, it is a branch, with one condition. To achive branch or condition coverage, it must be true at least once, and false at least once.

**Comment by GlendaChong** [comment]
Okay, thank you!
