### ISSUE TITLE
Is the main class (Duke.java) required to also be inside a package?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#57]
I currently have 1 duke package with subpackages inside
Should I leave my Duke.java file outside the duke package, inside the duke package but outside these subpackages, or inside these subpackages?

**Comment by damithc** [comment]
Good question @JasonRay168 More generally, this is about _best practices for organizing Java packages_ (but also connected to the coding standard, in our case).
Let's see what others think about this...

**Comment by woojiahao** [comment]
Usually, I would always put my entry point class outside of all other subpackages at the root of my folder so the structure is like this:

```
src/main/java/duke
    utility/
    commands/
    Duke.java
```

To me this makes the most sense since the entry point does not belong in any subpackage

**Comment by StevenLiudw** [comment]
You should put Duke.java into duke package but not inside other sub packages.
For me I have: duke.command(Command-related classes), duke.task(Task-related classes, including the various types of tasks), duke.storage(Classes related to file storage), duke.ui( User interface classes), duke(Core classes and exceptions).

**Comment by JasonRay168** [comment]
thank you very much! I'll put Duke.java into the package then.
