### ISSUE TITLE
Git Commit Subject violation

### ISSUE THREAD

**Issue by Bryan-Goh** [nus-cs2103-AY2324S1/forum#59]
I realize that during my first few levels of commits during the first ip tasks my commit message violated this course's git commit conventions do i need to change the commit message and force push it to my fork? or does it not effect my grading as long as i dont make the same mistake again

**Comment by imkwokyong** [comment]
Hi Bryan, the prof said in the last lecture that as long as you adhere to the conventions in future commits, you should be fine.

**Comment by damithc** [comment]
@imkwokyong is correct.

Editing past commits will change their timestamp, which can affect tracking of your progress by our dashboards (e.g., commits previously counted under week 2 will now be counted as done in week 3). So, that's one more reason not to edit past commits.
