### ISSUE TITLE
A-TextUiTesting: How to test multiple inputs using one input.txt?

### ISSUE THREAD

**Issue by KamJiaYue** [nus-cs2103-AY2324S1/forum#6]
Is it possible to put multiple inputs in the input.txt file and get multiple outputs? I'm not sure whether I'm doing it right or not as I can only manage to put one user input at a time, is that why it is called SEMI-AUTOMATED TESTING instead of AUTOMATED TESTING? If it is only one input at a time, which test case do I push to GitHub? else, how exactly should I conduct this SEMI-AUTOMATED TESTING? Thanks.

**Comment by damithc** [comment]
@KamJiaYue can you also share the content of your current input.txt?

**Comment by KamJiaYue** [comment]
input.txt:
todo read book

ACTUAL.txt:
    ————————————————————————————————————————————————————
     Hello! I'm BOT
     What can I do for you?
    ————————————————————————————————————————————————————
    ————————————————————————————————————————————————————
     Got it. I've added this task:
       [T][ ] read book
     Now you have 1 tasks in the list.
    ————————————————————————————————————————————————————

**Comment by KamJiaYue** [comment]
This test case passed, but I'd like to add more test cases on input.text though

**Comment by joeng03** [comment]
You can add more lines in the input.text, like this:
```
todo read book
list
deadline return book /by Sunday
event project meeting /from Mon 2pm /to 4pm
mark 2
...
```
Then add the corresponding expected outputs in EXPECTED.TXT, one after another. Do note that all inputs will be executed sequentially in the same session.

**Comment by damithc** [comment]
@KamJiaYue I've updated the issue title to be more descriptive.

**Comment by KamJiaYue** [comment]
It seems that my input.txt only reads the first line of the file

**Comment by KamJiaYue** [comment]
@joeng03 I tried but my actual output is always the first input only

**Comment by joeng03** [comment]
How do you read input from the user? If there is a while loop in the control flow, what is the condition for termination?

**Comment by m1oojv** [comment]
@KamJiaYue  Does the terminal after running  the runtest.sh show anything ?

**Comment by KamJiaYue** [comment]
> How do you read input from the user? If there is a while loop in the control flow, what is the condition for termination?

This is key to the solution. I solved it hahahaa thanks guys

I did one BIG MISTAKE. I create an instance of Scanner for every iteration. I solved it now using scanner.nextLine() for every iteration and have my Scanner as an instance of Duke instead.

**Comment by damithc** [comment]
@KamJiaYue Glad to hear you managed to solve it 👍 
Thanks to everyone who pitched in 💯

**Comment by cheeheng** [comment]
Hi. I am a student from a previous batch. Another way to solve this problem would be to use multiple input files instead of constraining yourself to just one file. I find that this solution is neater because it does not involve changes in the software code. The runtest.bat or runtest.sh file would have to be changed accordingly.

Here is one example of runtest.bat file which supports two input and two output files (slightly edited from my iP submission to support multiple input and multiple output). The input files are ACTUAL.TXT and ACTUAL2.TXT (file name convention is not ideal, just for demonstration purposes), and the corresponding output files are EXPECTED.TXT and EXPECTED2.TXT respectively.
```
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT
if exist ACTUAL2.TXT del ACTUAL2.TXT
if exist data\tasks.txt del data\tasks.txt

REM compile the code
call "..\gradlew.bat" build
IF ERRORLEVEL 1 (
   echo ********** BUILD FAILURE **********
   exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
REM idea adapted from https://github.com/nus-cs2103-AY2223S1/forum/issues/36
REM idea also adapted from https://github.com/nus-cs2103-AY2223S1/forum/issues/129
REM idea also adapted from https://stackoverflow.com/questions/24722757/how-to-call-a-batch-file-that-is-one-level-up-from-the-current-directory
call "..\gradlew.bat" run -p .. --args console-test -q < input.txt > ACTUAL.TXT
call "..\gradlew.bat" run -p .. --args console-test -q < input2.txt >> ACTUAL2.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT
FC ACTUAL2.TXT EXPECTED2.TXT
```
