### ISSUE TITLE
Does the disk need to be synced every time the tasks are updated, or just before the bot exits?

### ISSUE THREAD

**Issue by joeng03** [nus-cs2103-AY2324S1/forum#61]

**Comment by WangCheng0116** [comment]
Personally speaking, I think it would be a better idea to sync to disk every time the user writes something to it. Imagine a scenario where a user accidentally terminates your program, and the expected behavior of your program should memorize everything. Please correct me if I am wrong :)

**Comment by oeggy03** [comment]
I agree with WangCheng. Would also like to add on that this is good just in case there are erroneous inputs that you forget to handle (e.g. user typing in mark 9 when there are less than 9 tasks, can result in the program breaking due to IndexOutOfBounds error)

**Comment by lamchenghou** [comment]
I agree with the above 2 commenters too, I think the task description for `Save` wishes us to "save the tasks in the hard disk automatically whenever the task list changes".
