### ISSUE TITLE
Removing the --scan and --info flags out of build task

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#62]
When I was execute the 'build' gradle task, I was greeted with  errors regarding the checkstyle, which prompted me to click on these blue links
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/4f2c2aad-221c-4653-8e61-8b46c1cfd9dd)

I clicked on scan and info just to see what they are, but when I try to execute the build task again, the flags are still there:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/f0acc715-4533-499f-8d63-92c18044d282)

Is there any way so that executing build will not use these flags?

**Comment by iyioon** [comment]
Seems like there is checkstyle violation in your code. If you don't want the checkstyle to run, you can remove the checkstyle in the plugins section in the build.gradle file.

**Comment by JasonRay168** [comment]
Thank you, but that wasn't really my concern
My problem is how to remove the --scan and --info flags from the command, since everytime i click on build task in gradle toolbox, those two flags will be activated

I got a checkstyle violation before but without those two flags, so the text was shorter and easier to read. I'm trying to revert it back to before (I don't have the screenshot since I can't revert it back yet)

**Comment by damithc** [comment]
@JasonRay168 While we look for a solution, a workaround is to type the command `./gradlew build` in the terminal (i.e., run task using the command line), instead of using the Gradle toolbar.

**Comment by JasonRay168** [comment]
Alright, thanks Prof!
As of now, this is not a major concern, but certainly inconvenient for running a checkstyle. I really appreciate the answers.

**Comment by IsabelChong** [comment]
Hi @JasonRay168 just a senior dropping in from the previous batch, using Mac.

I understand that you want to remove the flags from the gradle build. I am trying to recreate the problem, and even after clicking on the links, I am still able to customise the build command when  i click on `Execute Gradle Task`. As such, I can run it without the flags.

<img width="668" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/71481877/4baa4589-0f99-445f-8e24-d315b759a335" align="centre">


One way it could have ran the command with the flags is if i clicked on the `Rerun` button, after having the flags added in already. (Clicking `Rerun` after running `Execute Gradle Task` > `gradle build` will run `gradle build` as usual.)

<img width="297" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/71481877/0bc562be-6580-4e1e-8584-6c0927ebfa6f">


- Can I check if you are clicking on the "Execute Gradle Task" or the "Rerun" button?

**Comment by hansstanley** [comment]
Hi @JasonRay168, senior here also.

With reference to [this stackoverflow question](https://stackoverflow.com/questions/21674091/how-to-add-stacktrace-or-debug-option-when-building-android-studio-project), perhaps the flags have been added to IntelliJ IDEA's `Settings` > `Build, Execution Deployment` > `Compiler` > `Command-line Options`. Removing them should revert the behaviour to what you had before.

**Comment by jefrai** [comment]
Hi @JasonRay168, yet another senior dropping in (Windows). I managed to revert this Gradle behaviour for your scenario as follows:

1. After running `build` from the Gradle toolbar, click `Modify Run Configuration...`, indicated by the wrench under the `Rerun` button.

![IP1](https://github.com/nus-cs2103-AY2324S1/forum/assets/30693850/0dec156f-a5ec-4d94-a9d5-1c930384b4f3)

2. The following window should open:

![IP2](https://github.com/nus-cs2103-AY2324S1/forum/assets/30693850/7cae93c1-28f7-463b-98c4-6ce7bea4d516)

3. Delete the extraneous flags from your `build` command configuration, and select `OK`/`Apply`.

![IP3](https://github.com/nus-cs2103-AY2324S1/forum/assets/30693850/3d6348e5-4cf8-425f-88f3-ad94fcd93dd6)

**Comment by SPWwj** [comment]
@JasonRay168, I'm a senior from the previous batch.

The flag helps you identify build failures. To remove the hint:

```
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
```

Fix the following errors:
![Error Screenshot](https://github.com/nus-cs2103-AY2324S1/forum/assets/30100720/1a0d6848-8c6f-4b80-b195-fd0e9a768b64)

**Comment by JasonRay168** [comment]
Oh sorry for the late reply, thanks very much Seniors and Prof! I appreciate all the help.
