### ISSUE TITLE
Why does runtest.bat not work once Gradle support is enabled?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#63]
I finished my Gradle setup, and can now execute run and build in IntelliJ, but now runtest.bat cannot work on Command Prompt, saying that there was a Build Failure because some of the classes (Storage, Ui, TaskList, Parser) doesn't exist

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/550ba80a-312c-4ff3-8f76-9f8568782a89)

t is running well on Gradle, so i don't know what happened.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/d3fa8d8e-6bdf-4170-b37c-f87e99f83c41)

Would somebody please explain whether this is normal? If not, what should i do? Thanks

**Comment by damithc** [comment]
@JasonRay168 push the problematic code to your fork and share the link here so that others can try to reproduce the error on their end.

**Comment by JasonRay168** [comment]
https://github.com/JasonRay168/ip

**Comment by damithc** [comment]
@JasonRay168 it's also possible this broke _before_ you added Gradle support (e.g., at the time you added the sub packages) but you didn't notice it then because you forgot to run the tests after every change.

**Comment by woojiahao** [comment]
It's not really a Gradle issue, just the way the test script compiles your Java files. Might want to dig around with compiling multiple Java files at once (including any external libraries).

**Comment by JasonRay168** [comment]
Edit: this is not just runtest.bat it seems, I tried running it on VSCode, and it doesn't work
However, running it in IntelliJ works, even though I have made sure that the file being run is the original file, not Gradle's run

I will try to fix this, thank you for the help

**Comment by JasonRay168** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/c444f6e3-ae51-4ad5-aff0-825fab9d2bf8)
When I tried running the current file, which is Duke.java, in IntelliJ, it was able to output correctly

However, if I try to compile it in terminal, it would tell me that the packages doesn't exist, even though it is there
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/1fcf8cc3-c5e8-4f3b-aa7d-f3555e9c1f82)

**Comment by damithc** [comment]
@JasonRay168 Run `javac` from outside of the package tree. Currently you are running it in `duke` folder which is already inside the package tree.

**Comment by JasonRay168** [comment]
Thank You Prof, it works perfectly..
However, now I don't know how to fix the runtest.bat, given this information

@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp ..\src\main\java\duke -Xlint:none -d ..\bin ..\src\main\java\duke\*.java
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin Duke < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT


That is my current runtest.bat, which cannot compile and shows the 'package does not exist' error shown previously. Which part of the file do I change so that it can compile? Thanks very much.

**Comment by woojiahao** [comment]
The way I resolved it was to build the jar using Gradle and run the built jar instead of compiling the code (because I'm using GSON)

**Comment by damithc** [comment]
~~@woojiahao~~ @JasonRay168  You can go to the [iP code dashboard](https://nus-cs2103-ay2324s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt) and compare your .bat files with that of a few others to see if you can spot what they are doing differently, and therefore, a potential solution.

**Comment by woojiahao** [comment]
Seconded! Mine was written for bash since I'm using a Mac but I believe it wouldn't be a challenge to translate the code to batch code

**Comment by JasonRay168** [comment]
Thanks you everyone, now I'm able to run the runtest.bat without problems. I ended up looking at the iP code dashboard, something I have forgotten about, so thanks very much Prof!
