### ISSUE TITLE
gradlew clean test gives an error

### ISSUE THREAD

**Issue by ScarletBlanks** [nus-cs2103-AY2324S1/forum#64]
Project directory 'C:\Users\pengt\OneDrive - National University of Singapore\Documents\Uni\Sem5\CS2103T\Project\Week 2\ip' is not part of the build defined by settings file 'C:\Users\user\settings.gradle.kts'. If this is an unrelated build, it must have its own settings file.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 58ms

**Comment by damithc** [comment]
@ScarletBlanks May be unrelated but I remember someone (in a previous semester) reporting that having  a project inside a folder controlled by OneDrive can cause problems as OneDrive software tend to interfere with our tools (due to periodic syncing etc.)

**Comment by ScarletBlanks** [comment]
Solved the issue, it was because I had a previous gradle installation, made sure to delete all referenced files and rebuild gradle, rerun and worked.
