### ISSUE TITLE
A pedantic gradle guide query

### ISSUE THREAD

**Issue by LicongHuang** [nus-cs2103-AY2324S1/forum#65]
![Screenshot from 2023-09-01 01-24-50](https://github.com/nus-cs2103-AY2324S1/forum/assets/29672264/b94308f0-29c9-47dd-a155-f717f23870c8)

The guide for Gradle states that within `build.gradle` it states that `archiveBaseName = <botname>.jar`, as seen at the bottom of the first image, but after running `./gradlew shadowJar`, I got the below result, notably `cheese.jar.jar`

![Screenshot from 2023-09-01 01-31-19](https://github.com/nus-cs2103-AY2324S1/forum/assets/29672264/84b7aa39-9765-47aa-b335-85a5b3f4347e)

I understand that I could just change `archiveBaseName = <botname>.jar` to `archiveBaseName = <botname>` to get `<botname>.jar`, that is why it is a pedantic question. My question is do I follow the guide here? Or should I not  follow the guide and edit the archiveBaseName?

Thanks for taking the time to read this.

**Comment by damithc** [comment]
@LicongHuang 
hmm... 🤔  Not sure if Grade changed the behavior recently; Previously, the name of the file produced was exactly as specified in the build file (i.e., it did not add another `.jar` at the end).
Let's wait to see if others are seeing a similar behavior. But thanks for bringing it up. If confirmed, we can update the guide accordingly.

**Comment by woojiahao** [comment]
It says `archiveFileName` actually, not `archiveBaseName`, this is intended behavior. `archiveFileName` would include the extension but `archiveBaseName` would rely on the `extension` value or it defaults to `.jar` (I believe)

**Comment by woojiahao** [comment]
To follow up on this, this section of ShadowJar's docs is probably relevant: https://imperceptiblethoughts.com/shadow/configuration/#configuring-output-name

For `archiveJarName`, it's a Gradle attribute so you can refer to [the website](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html):
![Screenshot 2023-09-01 at 07 55 17](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/2635deab-7d17-4560-9b1d-b9a8cceea7c0)

Hopefully this clears up the confusion!

**Comment by LicongHuang** [comment]
Oh ok, thank you, I have mistaken the 2 variable names.

**Comment by LicongHuang** [comment]
Oh ok, thank you, I have mistaken the 2 variable names.

**Comment by damithc** [comment]
> It says `archiveFileName` actually, not `archiveBaseName`, this is intended behavior.

Good catch @woojiahao 💯
