### ISSUE TITLE
No tests found for Gradle

### ISSUE THREAD

**Issue by lululwtv** [nus-cs2103-AY2324S1/forum#67]
<img width="523" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/85116693/a58c250d-d63d-4625-b8ed-95be3f4db037">

I am receiving this error here. I have uploaded my code into [a branch called branch-A-JUnit](https://github.com/lululwtv/ip/tree/branch-A-JUnit). Anyone able to help with this please?

**Comment by damithc** [comment]
@lululwtv Were you able to run JUnit tests using Gradle before, or is this the first attempt?

**Comment by nixonwidjaja** [comment]
@lululwtv Perhaps you need to change your packages name to lowercase. 
https://stackoverflow.com/questions/30474767/no-tests-found-for-given-includes-error-when-running-parameterized-unit-test-in
https://github.com/gradle/gradle/issues/20350

**Comment by lululwtv** [comment]
> @lululwtv Were you able to run JUnit tests using Gradle before, or is this the first attempt?
@damithc it works with Gradle, but not if i try to run the test file individually through intellij

**Comment by lululwtv** [comment]
> @lululwtv Perhaps you need to change your packages name to lowercase. 
> https://stackoverflow.com/questions/30474767/no-tests-found-for-given-includes-error-when-running-parameterized-unit-test-in
> https://github.com/gradle/gradle/issues/20350

@nixonwidjaja ah okay, i will try that. thanks!

**Comment by damithc** [comment]
> @damithc it works with Gradle, but not if i try to run the test file individually through intellij

So you are able to run all tests (using `./gradlew test`) but cannot run them individually?

While waiting for inputs from others, here are some things you can try (one at a time):
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project into InteliJ
