### ISSUE TITLE
Changing pushed tag names

### ISSUE THREAD

**Issue by WeeeHung** [nus-cs2103-AY2324S1/forum#68]
For week 2 iP, I was unclear of the tag naming convention, hence I just did v1.0, v1.1, etc and added the level as comments as shown in the screenshot. Hence, those progress weren't shown in ip tracking dashboard.

How can I change the tag names that are already pushed using either windows terminal or github.
Thank you in advance!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96626287/9bcace22-7629-4200-89a7-02b58b0337b6)

**Comment by damithc** [comment]
@WeeeHung from an admin perspective, yes, you can create the correct tags now and push to your fork. The dashboard script will detect them and turn them green at the next update.
As to _how_ to do it, I'll leave it as an opportunity for others to pitch in with their answers.

**Comment by Respirayson** [comment]
You can try running the following commands to rename the tag and update your remote repository

###  Step 1: Rename the tag
```
git tag [new_tag_name] [old_tag_name]
```

### Step 2: Delete the old tag
```
git tag -d [old_tag_name]
```

### Step 3: Update Remote Repository
```
git push origin [new_tag_name] :[old_tag_name]
```

**Comment by jx124** [comment]
In addition, if you want to tag a specific commit without a tag that is not the most recent one (and hence renaming is impossible), you can do the following
### Step 1: Find the commit
Run `git log` and use the vim motion keys `j` and `k` to find the specific commit. Copy the commit's hash (the long string of hexadecimal after the word `commit`) and press `q` to quit.
### Step 2: Add the tag
```
git tag [tag_name] [commit_hash]
```
Confusingly, this has the same syntax as renaming the tag as mentioned above.
### Step 3: Update the remote repository
```
git push origin --tags
```

**Comment by WeeeHung** [comment]
Thank you so much! I managed to change my existing tagging to the correct tag naming convention.
