### ISSUE TITLE
Bugs in previous commits

### ISSUE THREAD

**Issue by Gabriel4357** [nus-cs2103-AY2324S1/forum#69]
Hi may I know if I did not discover a relatively big bug in my previous commits, could I just fix this bug and commit it ? Or must I fix this bug in the previous Tags as well?

**Comment by damithc** [comment]
@Gabriel4357 You can fix it in a subsequent commit. See [this FAQ](https://nus-cs2103-ay2324s1.github.io/website/schedule/week2/project.html#:~:text=Q.%20What%20if%20I%20discovered%20a%20bug%20after%20I%20finished%20an%20increment%3F) for more info.

**Comment by muhammadreyaaz** [comment]
Hi @Gabriel4357 please close this issue if prof has clarified your queries. Thanks a lot!!

**Comment by Gabriel4357** [comment]
Thanks!
