### ISSUE TITLE
Error when running runtest.bat file for IP

### ISSUE THREAD

**Issue by zacwong2151** [nus-cs2103-AY2324S1/forum#7]
Got the below error when trying to run the runtest.bat file for the automated text UI testing portion for IP. Any idea how to resolve this?

![Screenshot 2023-08-22 201719](https://github.com/nus-cs2103-AY2324S1/forum/assets/111118549/7141ac00-c588-49db-99e2-585a0ffc6873)

**Comment by joeng03** [comment]
Can you compile .java files successfully in the same directory?

**Comment by zacwong2151** [comment]
Thanks, I realised I cant compile those files either. Googled some more and realised that there's some error with PATH and environmental variable. Solved it using the link below

https://www.javatpoint.com/javac-is-not-recognized
