### ISSUE TITLE
Level 7: cache file instead of .txt

### ISSUE THREAD

**Issue by suryanshkushwaha** [nus-cs2103-AY2324S1/forum#70]
Hi! I created a cache file instead of using .txt file to store and load data. May I ask if that is okay? or am I supposed to only stick to .txt files to store/load data?
Thanks

**Comment by damithc** [comment]
@suryanshkushwaha any format is fine. Also see https://github.com/nus-cs2103-AY2324S1/forum/issues/43

**Comment by muhammadreyaaz** [comment]
Hi @suryanshkushwaha please close this issue if prof has clarified your doubts. Thanks!!

**Comment by suryanshkushwaha** [comment]
Thanks for the clarification Prof. 
I had went through #43, just wanted to make sure since the website mentioned .txt example. :)
