### ISSUE TITLE
Does Role imply Navigation in UML diagram

### ISSUE THREAD

**Issue by DonovanJJ** [nus-cs2103-AY2324S1/forum#71]
# Does Role imply Navigation in UML diagram
<img width="853" alt="Screenshot 2023-09-01 at 6 55 09 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/58603123/f25ff286-9a17-4ab5-ae8c-17cb04c53a24">

With reference to the image above, it seems that Person has a role "app" containing an object Main, wouldn't this imply that we are able to access that attribute to Main within a Person object. Hence navigate from Person to Main? 
Thanks in advance!

**Comment by damithc** [comment]
@DonovanJJ In the diagram `app` role says _in the association between `Main` and `Person`, the role played by the `Main` is `app`_. It doesn't necessarily mean the Person object has a variable named `app` pointing to a `Main` object. IF the association is navigable in that direction (as per this diagram, it is not), then there will be a variable in `Person` pointing to a `Main` object, and the variable name is likely to be `app` (although it can be something else too -- depends on whether the programmer chose to name the variable based on the role it plays or something else).
