### ISSUE TITLE
Unable to run Duke class after packaging

### ISSUE THREAD

**Issue by LordSaumya** [nus-cs2103-AY2324S1/forum#75]
My directory structure is as follows:

src/main/java/duke/
  - Duke.java (main class, has `package duke`)
  - /command
      - all of the command classes (they all have `package duke.command` )
  - /task
      - all of the task classes (they all have `package duke.task`)
  - /parser
      - Parser.java (has `package duke.parser`)
  - /ui
      - Ui.java (has package `duke.ui`)
  - /storage
      - Storage.java (has `package duke.storage`)

I compiled everything with `javac *.java task/*.java ui/*.java command/*.java storage/*.java parser/*.java`, and it compiled without errors. All of the class files are in their respective directories (the same directory as their source file). However, I can't seem to be able to run the Duke class (using both `java duke.Duke` and `java -cp . duke.Duke`. It keeps giving me `Error: Could not find or load main class duke.Duke Caused by: java.lang.ClassNotFoundException: duke.Duke` (please see below image)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/68504323/f3a90a71-97f3-4da6-9c7a-0a46344ba8af)

Does anyone know why I'm unable to run my code?

**Comment by Bombbird2001** [comment]
Try running the same command from the folder one level up (/java instead of /java/duke) since that is considered the root folder.

**Comment by LordSaumya** [comment]
That worked, thanks!
