### ISSUE TITLE
Using checkstyle with gradle 

### ISSUE THREAD

**Issue by tayruxin** [nus-cs2103-AY2324S1/forum#76]
Hi all, 

I have followed the instructions given on the [website](https://se-education.org/guides/tutorials/checkstyle.html#configuring-checkstyle), added the config files from address book and added the necessary changes to my build.gradle file. However, when running gradlew checkstyleMain, it failed with the following error message: 

<img width="1091" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/106758300/0957e7c2-a016-4248-a0cb-e615d6fad54f">

I have added this into my build.gradle file: 
  
```
plugins {
    id 'checkstyle'
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

checkstyle {
    toolVersion = '10.2'
}
```

May I ask what could possibly go wrong?

**Comment by ghost** [comment]
Did you create all the directories and files for /config/checkstyle/checkstyle.xml and /config/checkstyle/suppressions.xml?

**Comment by tayruxin** [comment]
> Did you create all the directories and files for /config/checkstyle/checkstyle.xml and /config/checkstyle/suppressions.xml?

Yes, I created /config/checkstyle/checkstyle.xml and /config/checkstyle/suppressions.xml, I copied the file from the address book code given

**Comment by tayruxin** [comment]
Realised that the spelling of my files was wrong
