### ISSUE TITLE
Queries pertaining to Level-8 Date Time

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2103-AY2324S1/forum#77]
I am aware that the `Deadline` dates should be in the format`java.time.LocalDate`. Could I use `java.time.LocalDateTime` instead?
Also, is the storing of timing as dates only supposed to be for the `Deadline` class or should I do so as well for the `Event` class as well?

**Comment by HugeNoob** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/65714641/985c8192-75a4-4ce5-9997-4f35e0977dd0)

Yes, it is mentioned that you can use `java.time.LocalDateTime`. 

Regarding your second question, you can refer to this thread: https://github.com/nus-cs2103-AY2324S1/forum/issues/46
