### ISSUE TITLE
Refactoring for GUI

### ISSUE THREAD

**Issue by javinchua** [nus-cs2103-AY2324S1/forum#79]
Hi, can i check that after we have implemented the GUI, do we have to refactor all existing code so that duke replies the messages on the GUI instead of the terminal?

**Comment by damithc** [comment]
@javinchua Given below is some relevant info:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/cf305306-d5dc-47bb-b97a-b34c34882abe)

The GUI will be the main UI after Level-10. You are welcome to maintain the text UI as well, but it's not a requirement.
