### ISSUE TITLE
Are we allowed to remove tags?

### ISSUE THREAD

**Issue by supermii2** [nus-cs2103-AY2324S1/forum#8]
For example, if we tag a commit as level-5 and pushed it, and then realised we missed out some exceptions and want to move the tag to a different commit. Would we be allowed to remove the tag and add it to the newer commit? or would it cause an issue with the grading software

**Comment by damithc** [comment]
@supermii2 Yes, you can remove tags.

**Comment by Merrickneo** [comment]
Hi @supermii2, yeap there is no issue with that. 

Remember to close the issue if there is no other questions regarding this!
