### ISSUE TITLE
Forget to branch after finishing implementation

### ISSUE THREAD

**Issue by WangCheng0116** [nus-cs2103-AY2324S1/forum#80]
Hi folks,
For branch-level-8, I should have branched it, but instead, I have finished all the implementation already.
<img width="932" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/111694270/b5c874d6-8937-4afb-a5c9-c80e0fdcc924">

So the dashboard could not keep track of my work. Sadly.

Does anyone know how to fix it? Thanks in advance.

**Comment by damithc** [comment]
@WangCheng0116 somewhat related https://github.com/nus-cs2103-AY2324S1/forum/issues/27

**Comment by WangCheng0116** [comment]
Thank you so much :)
