### ISSUE TITLE
What should the format of this method in Ui class be?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#81]
I have a method handleInput() that takes in the parsed user input to output corresponding text, based on the first word of the input (commands). But there's a lot of commands possible, so my handleInput() function spans around 100 lines of code (due to all the if else conditions)

Is this still within the limits? if not, then where should the helper methods be created? in the Ui class or the Parser class?

**Comment by damithc** [comment]
@JasonRay168 You can also post a link to the said class or post an extract of the code here, for the convenience of readers.

**Comment by JasonRay168** [comment]
https://github.com/JasonRay168/ip/blob/master/src/main/java/duke/utilities/Ui.java

Is this how to link the file?

**Comment by damithc** [comment]
> https://github.com/JasonRay168/ip/blob/master/src/main/java/duke/utilities/Ui.java
> 
> Is this how to link the file?

@JasonRay168 Yes. While waiting for inputs from others, you can also use the iP code dashboard to see how a few others have done this part of the code, as described [here](https://nus-cs2103-ay2324s1.github.io/website/schedule/week4/project.html#3-learn-from-others-optional:~:text=3-,Learn%20from%20others,-(optional)).

**Comment by ong-wei-hong** [comment]
hi Jason,
I noticed some changes in the way you wrote your handleInput function. I agree that the splitting of commands into functions would help with structure. 
While the code is much better now, I have a few nits. Given that a majority of code deals with TaskList, perhaps it should be a member variable instead of a function argument?
Overall, good work so far.

**Comment by tanshiyu1999** [comment]
Hi Jason, honestly I think you can consider using regular expression to parse some of your things. As they can be quite flexible in reducing some of the checks that you might need compared to if you are parsing the entire String by itself. Hope this helps.

**Comment by nixonwidjaja** [comment]
I think handleInput() parses user input, so it should be in Parser class
