### ISSUE TITLE
I accidentally merged all three of A-JavaDoc, A-CodingStandard, and Level-9 increments without tagging them in-between, what should I do?

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#82]
During the merging process, I believe I should have tagged and pushed the commit after every successfuly merge conflict handling. However, I have just finished everything and then pushed the master branch and the three parallel branches when I realised this problem.

How should I approach this? Is it okay to tag this current commit (done with all the merge) three times with three different tags?

**Comment by damithc** [comment]
> Is it okay to tag this current commit (done with all the merge) three times with three different tags?

@JasonRay168 Yes. Also, Git allows you to tag past commits.

**Comment by JasonRay168** [comment]
> > Is it okay to tag this current commit (done with all the merge) three times with three different tags?
> 
> @JasonRay168 Yes. Also, Git allows you to tag past commits.

I think I'll go with tagging the last commit with all 3 tags, as there were some mistakes I missed during the merging process
Thank you very much Prof! I just knew that I can tag past commits :)
