### ISSUE TITLE
Warning on Unsupport JavaFX configuration

### ISSUE THREAD

**Issue by seanpzk** [nus-cs2103-AY2324S1/forum#83]
Hello,
I am currently working on GUI and everything is working fine. However, I see this warning after I run Launcher.main() in IntelliJ.
Although, my GUI's functionality is not affected, I am afraid it might cause some issues later in the semester. I would like to know how I can go about solving this issue as from what I have search online, there are a lot of unfamiliar terms on modules 😥  (or should I just leave it?) 
Thanks for helping!
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122248828/b302dc93-cd93-4672-8682-f72616fcd93c)

**Comment by TiwKangXu** [comment]
Hi @seanpzk . Please refer to issue #72 posed by TiwKangXu (me), in closed issue.

**Comment by lunaflight** [comment]
Related StackOverflow thread: https://stackoverflow.com/questions/67854139/javafx-warning-unsupported-javafx-configuration-classes-were-loaded-from-unna

You can ignore the warning if you'd like - nothing should break due to it.

**Comment by tanyyyming** [comment]
As pointed out by @et-irl, the functionality of JavaFX will not be affected, and you can safely ignore this warning.

**Comment by seanpzk** [comment]
Thank you all for your replies @TiwKangXu @tanyyyming @et-irl.
I have resolved after reading issue #72. 
Happy coding :)
