### ISSUE TITLE
Error running runtest.bat

### ISSUE THREAD

**Issue by lunaroddity** [nus-cs2103-AY2324S1/forum#84]
When running runtest.bat in my terminal, I get this error: 
```
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at Ui.getUserInput(Ui.java:10)
        at Bareum.run(Bareum.java:16)
        at Bareum.main(Bareum.java:27)
Comparing files ACTUAL.TXT and EXPECTED.TXT
***** ACTUAL.TXT
________________________
***** EXPECTED.TXT
*****

```

The correct output is saved in the file the data is stored in. Furthermore, when testing manually using the same commands I have in my input.txt file, it works fine.

Here's my input.txt:
```
todo borrow book
deadline return book /by 2023-09-02
event project meeting /from Mon 2pm /to 4pm
list
mark 1
list
mark 3
list
unmark 1
list
delete 2
list
todo
deadline
event
blah
bye
```

Here's my code for Bareum:
```java
public class Bareum {
    static TaskList taskList = new TaskList();

    public void run() {
        Ui ui = new Ui();
        Parser parser = new Parser();
        Storage storage = new Storage();
        boolean isExit = false;

        storage.loadSavedTaskList(taskList);
        ui.showWelcomeMessage();

        while (!isExit) {
            try {
                ui.showLine();
                String input = ui.getUserInput();
                Command cmd = parser.parse(input);
                cmd.execute(ui, storage, taskList);
                isExit = cmd.isExit();
            } catch (BareumException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public static void main(String[] args) {
        new Bareum().run();
    }
}
```
Here's my code for Ui:
```java
import java.util.Scanner;

public class Ui {
    private static Scanner sc = new Scanner(System.in);

    public Ui() {
    }

    String getUserInput() {
        return sc.nextLine();
    }

    static void reply(String reply) {
        String botName = "Bareum: ";
        String fullReply = botName + reply;
        System.out.println(fullReply);
    }
    void showWelcomeMessage() {
        reply("Hello! I'm Bareum! What can I do for you? ^^");
    }

    void showGoodbyeMessage() {
        reply("Bye! Hope to see you again soon ^^");
    }

    void showLine() {
        System.out.println("________________________");
    }
}
```
Referring to these issues (https://github.com/nus-cs2103-AY2021S1/forum/issues/49, https://github.com/nusCS2113-AY1920S1/forum/issues/35), I tried doing this for GetUserInput() instead:
```java
    String getUserInput() {
        if (sc.hasNextLine()) {
           return sc.nextLine();
        }
        return "\n";
    }
```
but when I run my runtest.bat file, there's no output and the indicator below ./runtest.bat keeps blinking and I have to terminate the batch job.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/101786124/4edd6e2a-bd1d-4a9e-ba61-bbac6580d067)

I also tried deleting all the files in the ./bin directory but I ended up with the same error. Anyone know how to fix this? Thanks :")

**Comment by damithc** [comment]
@lunaroddity Perhaps you can push the code to your fork (to the master branch or a separate branch) and share the link here so that that someone else can try to reproduce the error easily?

**Comment by lunaroddity** [comment]
Please find the code here!
https://github.com/lunaroddity/ip/tree/issue-reproduction

**Comment by zekone** [comment]
@lunaroddity The reason is because your program is not exiting properly and the scanner is still trying to get input. Try giving the bye command and you will notice that the program does not actually exit. Try using `instanceof` to check for exit condition in your `run` loop:
```java
if (cmd instanceof ByeCommand) {
    isExit = true;
 }
```

**Comment by lunaroddity** [comment]
That fixed it for me! Thank you so much!!
