### ISSUE TITLE
Need help with Git Branching (Master frozen before Level-7, Ip progress does not turn green)

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#85]
Intellij Community Edition 2022.1.2, Java 11, Windows
<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/5a399964-9540-42ae-8493-243a5b8c8be7">

<img width="582" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/3800fd64-2aaf-4f24-9bbc-81be7bd10a91">

<img width="686" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/40020029-7c49-4592-93d6-58fd0675a462">

The only mishap is at the last step on the screenshot above, I only pushed master but not branch Level-7. I have pushed the tag Level-8 to git, but it seems that only tags pushed to master will be detected by the progress dashboard? Can someone explain why does the master branch does not follow up to the most updated commit? And at this point how do I make the progress dashboard detect branch-Level 7 and branch Level 8, such that I will be following the objective of the course. 

Thank you.

**Comment by TiwKangXu** [comment]
Hi @s-peiran. 
My steps are:
1. Create a branch base on the content of master.
2. Make edits on branch.
3. Commit changes to branch.
4. Merge branch into master. (I guess you've missed this and hence your master is not up to date with branch 7?)
5. Make tag for this comit.
6. Push master, new branch, and all tags. (When you click the Push in Sourcetree, you need to check the checkboxes of master and the branch, and also  the push all tags.
7. Repeat the steps for next task.

I spotted that you've merge master into branch 7 which might cause a bit problem -- you're updating branch 7 but not master.

**Comment by s-peiran** [comment]
Thank you Kang Xu. I actually need to reset current branch to the commit before the merge to break the link on the graph for both master and branch-Level-7, before doing the steps detailed by Kang Xu.
