### ISSUE TITLE
Branch Not Detected

### ISSUE THREAD

**Issue by ryamgoh** [nus-cs2103-AY2324S1/forum#87]
Hi all,

Might need some help for this one. I am unsure why my branch-Level-9 is not detected by the progress tracker even though I pushed it 3 days ago.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122634188/8a3199b7-4bd1-4ec8-b5f8-4274e7c1dd18) 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122634188/721f7541-91bb-4755-95a4-ce2429eb18bd)

Any help would be appreciated! Thank you!

**Comment by damithc** [comment]
@ryamgoh Can you post the full width of the table in your screenshot, showing the rest of the information of the branches?

**Comment by ryamgoh** [comment]
@damithc Hi Prof, this is the ss of my branch list. Thank you
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/122634188/91cdc85d-7dd0-451d-89d5-41d8b412bd9f)

**Comment by damithc** [comment]
Let's wait a bit to give others a chance to find the reason (and practice their Git/GitHub troubleshooting skills while doing so) ...

**Comment by woojiahao** [comment]
I don't see a merge commit where you're merging `branch-Level-9` into `master`, perhaps that's a reason why this occurs. I'm not sure how the iP tracker works but this is my best guess

**Comment by damithc** [comment]
> I'm not sure how the iP tracker works but this is my best guess

@woojiahao Yup, only merged branches (i.e., the work is completed) are detected by the dashboard.

**Comment by ryamgoh** [comment]
@woojiahao @damithc Thank you for helping. It has been solved by performing the merge commit :)
