### ISSUE TITLE
Use GFMD in PR description

### ISSUE THREAD

**Issue by sheryew** [nus-cs2103-AY2324S1/forum#88]
Hi, I would like to check on this particular task.

Do we have to create a new PR with our week 3 commits and use GFMD on the commits or do we perform GFMD on week 2 commits? This is because I only remember doing PR in week 2. Thanks

**Comment by damithc** [comment]
@sheryew Update the previous PR. No need to create a new PR. 
Note: If you were to create a new PR, both the old and the new PR will contain the same commits, as PRs update automatically when you push to the same branch.

**Comment by sheryew** [comment]
Okay. I didn't realise that my commits are automatically updated in my PR. Thank you very much!
