### ISSUE TITLE
Forgot to create new branches for A-JavaDoc and A-CodingStandard

### ISSUE THREAD

**Issue by yyyaohhh** [nus-cs2103-AY2324S1/forum#89]
Hi, I have accidentally pushed my latest commits into my main branch and forgot to create the A-JavaDoc and A-CodingStandard branches. May I know a solution to this problem?

**Comment by damithc** [comment]
@yyyaohhh related https://github.com/nus-cs2103-AY2324S1/forum/issues/27#issuecomment-1694235597

**Comment by yyyaohhh** [comment]
Thank you very much!
