### ISSUE TITLE
Error when running ./gradlew run

### ISSUE THREAD

**Issue by lunaroddity** [nus-cs2103-AY2324S1/forum#91]
When I try to run ./gradlew run in the terminal, I received an error. Upon checking other people's code, I realised that my build.gradle file was in a directory called plugin instead of the root directory so I moved my build.gradle file to the root directory. I then got this error instead:
```
PS C:\Users\limyx\Documents\school\Y2S1\CS2103T\Individual Project> ./gradlew run

> Task :run FAILED
bareum.Bareum: Hello! I'm bareum.Bareum! What can I do for you? ^^
________________________
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at bareum.Ui.getUserInput(Ui.java:12)
        at bareum.Bareum.run(Bareum.java:20)
        at bareum.Bareum.main(Bareum.java:33)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.16.1\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
4 actionable tasks: 1 executed, 3 up-to-date

```
My SDK version and language level match in the Project Structure and I have tried invalidating my caches and restarting Intellij to no avail. Please find the code here (https://github.com/lunaroddity/ip/tree/31b7517c6488195f91689a69b657e6b5e23224f8) Does anyone know how to fix this? Thank you!

**Comment by damithc** [comment]
@lunaroddity How exactly did you add gradle support to your project? The expectation was that you'll merge the `add-gradle-support` branch that we have provided, which contains all the necessary files.

**Comment by lunaroddity** [comment]
Hi Prof, I created a new gradle wrapper following this tutorial (https://docs.gradle.org/current/userguide/gradle_wrapper.html). Would it be possible to delete the files created upon running gradle wrapper and merging the `add-gradle-support` branch to the existing code in my master branch instead?

**Comment by damithc** [comment]
> Would it be possible to delete the files created upon running gradle wrapper and merging the `add-gradle-support` branch to the existing code in my master branch instead?

Yes, that might be better.

**Comment by lunaroddity** [comment]
Hi ~~Prof~~, just to check if I did this correctly, is this the expected output when running ./gradlew run?
```
 PS C:\Users\limyx\Documents\school\Y2S1\CS2103T\Individual Project> ./gradlew run

> Task :run
bareum.Bareum: Hello! I'm bareum.Bareum! What can I do for you? ^^
________________________
<==<=========----> 75% EXECUTING [5s]
bareum.Bareum: Bye! Hope to see you again soon ^^

BUILD SUCCESSFUL in 6s
2 actionable tasks: 1 executed, 1 up-to-date

```

**Comment by damithc** [comment]
> Hi ~Prof~, just to check if I did this correctly, is this the expected output when running ./gradlew run?
> 
> ```
>  PS C:\Users\limyx\Documents\school\Y2S1\CS2103T\Individual Project> ./gradlew run
> 
> > Task :run
> bareum.Bareum: Hello! I'm bareum.Bareum! What can I do for you? ^^
> ________________________
> <==<=========----> 75% EXECUTING [5s]
> bareum.Bareum: Bye! Hope to see you again soon ^^
> 
> BUILD SUCCESSFUL in 6s
> 2 actionable tasks: 1 executed, 1 up-to-date
> ```

Others, does this look similar to what you see when you run your code via Gradle?

**Comment by sp4ce-cowboy** [comment]
> Hi ~Prof~, just to check if I did this correctly, is this the expected output when running ./gradlew run?
> 
> ```
>  PS C:\Users\limyx\Documents\school\Y2S1\CS2103T\Individual Project> ./gradlew run
> 
> > Task :run
> bareum.Bareum: Hello! I'm bareum.Bareum! What can I do for you? ^^
> ________________________
> <==<=========----> 75% EXECUTING [5s]
> bareum.Bareum: Bye! Hope to see you again soon ^^
> 
> BUILD SUCCESSFUL in 6s
> 2 actionable tasks: 1 executed, 1 up-to-date
> ```

@lunaroddity I can't tell from your screenshots, but if you entered the command "bye", and only then received the build success message, then that means the gradle run was successful. However, if the program exited immediately, then that might be an issue, as in my case the program only indicated the success message after I input the "bye" command. In fact, the program ran normally for every command until I input the "bye" command.

**Comment by lunaroddity** [comment]
There were some mistakes when IntelliJ refactored my code after packaging. After making sure that my import statements were correct and nothing else in my code changed, I got the success message after the bye command. Thank you for your help!
