### ISSUE TITLE
My Launcher will not run

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#92]
I have copied the javaFX dependencies to the build.gradle file, as shown here:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/fecab8d9-1bca-42da-b565-2fc088a60604)

I have also imported the package names, make Duke extend from Application, and added a start method under my main method. I did not change anything other than that

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/1c1e6def-cc43-4dda-ac90-b61a7c72b8ef)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/7dc127de-d2f0-4623-9b85-2f0a9dc1161a)

Finally, I added the Launcher class. When I try to run it, I get this error:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/fa5f5dbc-785e-4606-b5ca-943d9d94f96c)

This error happens regardless of where I put my Launcher.java, either inside duke package or outside it. Is there anything wrong with downloading the package?

**Comment by woojiahao** [comment]
Pretty sure you need to set your `mainClass` in `build.gradle` to be `Launcher`

**Comment by JasonRay168** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/eb5cc84f-9d21-4c3f-a759-66e044735ed0)
Thanks for your advice, but it seems the problem is that there's an unnamed module
I tried, but it still didn't work
Is the javafx package not detected?

**Comment by woojiahao** [comment]
Could you push your branch to the main repository please, that makes it easier for others to check it, thanks

**Comment by JasonRay168** [comment]
Alright wait a moment

**Comment by JasonRay168** [comment]
https://github.com/JasonRay168/ip/tree/branch-Level-10

Edit: I found this error when using VSCode:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/d7b4d8c7-e723-42f6-ab97-c239670eacab)

**Comment by jianrong7** [comment]
Try modifying your `Duke` class such that it has an empty constructor. Perhaps your filePath string can be a constant.

**Comment by JasonRay168** [comment]
Wow somehow that works
Thanks very much! If it is possible, could you explain why simply changing the filpath to a constant solves the problem? And also, is it only possible to run the launcher using gradle? I tried javac Launcher.java but it doesn't work, while running using gradle does

**Comment by jianrong7** [comment]
You added the dependencies to Gradle, so it will only work when you run with Gradle.

It works because Duke works with an empty constructor not so much because the filepath is a constant. The `Application.launch` takes in a class which extends the `Application` class. The `Application` class should have an empty constructor.

Hope it helps! 😸 

Docs: https://docs.oracle.com/javase/8/javafx/api/javafx/application/Application.html

**Comment by JasonRay168** [comment]
Thanks very much for the info! I'll make sure to read through the docs.
