### ISSUE TITLE
Issue with merging branch-level-8

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2103-AY2324S1/forum#93]
Hi, I was looking at the iP progress dashboard and realized that my branch-level-8 was not registered by the script:

<img width="883" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/e3cbea51-ed14-47d0-851c-8e9e8f82760c">

I suspect that the reason is because I made a mistake in merging that branch to my master branch earlier on, and didn't actually merge that branch to my master branch but instead I accidentally copied those changes over. (i.e. I have completed Level-8 but I did so on the master branch, so all my relevant code is on the master branch).

<img width="342" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/5d68902f-e47f-4882-943f-ca331cae7b40">

Is there any way I can rectify this? I'm hesitant to merge the old branch-level-8 with my current master branch as I don't want my code to be messed up, is there any safe way to do so without the merge commit affecting my current code base?

**Comment by damithc** [comment]
@sp4ce-cowboy From a dashboard perspective, as long as there is a merged branch with the expected name, it will turn green. It doesn't matter what the branch contains.

Also see #27

**Comment by sp4ce-cowboy** [comment]
Alright, thank you Prof. @damithc
