### ISSUE TITLE
How to fix this import assertEquals issue

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#94]
My import order for the JUnit tests are like this:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/9398308f-a9ee-4d5b-8b9c-b26ca4f9d9a4)

When I ran checkstyle on the files, this is what appeared:
Import statement for 'org.junit.jupiter.api.Assertions.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.

What does this mean, and how do I fix this? thanks

**Comment by woojiahao** [comment]
Under `Settings > Code Style > Java > Imports`, there is a section for import layout. Tweak that so Intellij's auto import system will organise your imports without any errors. Will need to play around with the ordering but that's what I use

**Comment by damithc** [comment]
@JasonRay168 The checkstyle rules file you are using dictate a specific order import statements should appear. 
As @woojiahao mentioned, you can tweak your IDE settings to follow the same order. This may be useful https://se-education.org/guides/tutorials/intellijCodeStyle.html

**Comment by JasonRay168** [comment]
It seems I found the correct arrangements
Thank you very much for the info!
