### ISSUE TITLE
Branch/Merge/Tag error?

### ISSUE THREAD

**Issue by raydenlim** [nus-cs2103-AY2324S1/forum#95]
Hi, can I check if im doing something wrong here?

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/109991591/ba33090d-fe85-40ac-b07b-aecf02012332)

My ip repo isit updating on github, and some of the tags are also not showing.
Send help ;(

**Comment by woojiahao** [comment]
Did you do `git push --tags`?

**Comment by damithc** [comment]
@raydenlim looks like you have a 'detached HEAD' too (i.e., on a commit that is not on any branch). https://circleci.com/blog/git-detached-head-state/

**Comment by raydenlim** [comment]
> Did you do `git push --tags`?

@woojiahao Oh right! That solves the tag issue, thanks!

**Comment by raydenlim** [comment]
@damithc 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/109991591/8d6e0990-1295-472d-808a-ba26c03dc477)

am I on the right track? 😢

**Comment by damithc** [comment]
@raydenlim My initial thinking was you would do this:
1. Create a branch `branch-A-JUnit` on the detached HEAD.
2. switch to `master`
3. merge  `branch-A-JUnit` onto `master`

You have taken a different route, but at least you got rid of the detached HEAD.
You also reverted the JUnit commit you did earlier, so you might have to do that work again and commit again.

Also, judging from the screenshot, I think you are merging `master` onto other branches when you should be merging in the other direction.
