### ISSUE TITLE
[A-Gradle] [J-Unit] no gradle icon after merging add-gradle-support. Add gradle plugin via intellij?

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2103-AY2324S1/forum#96]
IntelliJ 2022.1.2, Java 11, Windows
<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/2bbb7a5d-9abb-44c4-873c-736f4f9ab40b">
Currently I installed gradle by merging the add-gradle-support branch with my master branch, and deleting the .idea file. However I do not have the gradle icon in my Intellij. I can do all the gradle operation ./gradle run etc in command line regardless. 

But because of this I cannot do "Load Gradle changes" as outlined in #42 because I am facing the same issue of unable to import JUnit for testing. So do I go and import the gradle plugin from intellij to circumvent the issue?
<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/6bf340a4-06d0-429a-a7f6-7b03e6f513bd">

Thank you.

**Comment by damithc** [comment]
Try View -> Tool Windows -> Gradle

Also try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij, delete `.idea` folder, and open the project again
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by s-peiran** [comment]
<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/7ecea9ba-7c15-41e5-a2de-8865af15be0f">

The issue persists after doing each of the 3 points. I also tried to clone to a location outside of onedrive. 

<img width="960" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/96849432/99f4dd96-325b-4aa6-83f5-f899e35606e5">

maybe there is a way to resolve **java: package org.junit.jupiter.api does not exist** instead?

**Comment by damithc** [comment]
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/96849432/265440944-6bf340a4-06d0-429a-a7f6-7b03e6f513bd.png">

@s-peiran Wait, as per this screenshot, your Gradle plugin is not enabled.

**Comment by s-peiran** [comment]
Yes my question was whether to enable the gradle plugin directly as the tutorial/guide did not stipulate doing so.

**Comment by damithc** [comment]
Ah, I missed that question. Yes, you should. IIRC, it is in fact enabled by default. Perhaps you accidentally disabled at some point earlier. It is mentioned in the tutorial, in scenario 1, which scenario 2 refers to.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/a7e0281e-aed0-48d3-8633-1d56999066cd)

**Comment by s-peiran** [comment]
thanks prof for your clarification and prompt reply.
