### ISSUE TITLE
Where should I put these 2 image files

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#97]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/26b84b7c-b1ec-4f0a-ba93-59b4817ae8b6)

I downloaded images and renamed them, put them inside images folder. But I don't know where I should put this folder. I tried inside src/main, src/main/java, and even inside the duke package, but running the launcher will output an "InvocationTargetException" because the target image is null.

**Comment by cxo05** [comment]
Put it in `src/main/resources/`

**Comment by JasonRay168** [comment]
Thanks!
